/* global __dirname */
/**
 * earthbot / european-wilderness / subject — European INLAND wilderness, THE LAND IS THE HERO.
 * Recipe: scripts/gen-earthbot-pool.js `european_wilderness_subject` (toponym first; a camera-angle
 * phrase; ALL INLAND: peaks, cirque tarns, lakes, gorges, waterfalls, forests, sandstone towers, moor;
 * bans coast / sea / fjord, castles, ruins, monasteries, villages, standing stones, farm animals and
 * pasture, huts, roads and cable cars, Iceland, analogues, negation). Pool 2026-09-23: 200 entries,
 * 104 openers, the big names 5-7 times each. Same idea = same place + same light moment.
 */
const path = require('path');
const { landmarkPool } = require('../lib/landmarkPool');

const GROUPS = {
  'alpine-peaks': 6,
  'cirque-tarns': 5,
  gorges: 4,
  waterfalls: 3,
  forests: 2,
  'sandstone-towers': 2,
  'highland-moor': 3,
  glaciers: 2,
};
const PLACES = [
  ['Tre Cime di Lavaredo', 'three limestone peaks', 'alpine-peaks'],
  ['Seceda', 'tilted ridgeline', 'alpine-peaks'],
  ['Sassolungo', 'dolomite massif', 'alpine-peaks'],
  ['Marmolada', 'glacier-topped wall', 'alpine-peaks'],
  ['Cadini di Misurina', 'dolomite spires', 'alpine-peaks'],
  ['Cinque Torri', 'five rock towers', 'alpine-peaks'],
  ['Passo Giau', 'pass under Ra Gusela', 'alpine-peaks'],
  ['Matterhorn', 'pyramidal peak', 'alpine-peaks'],
  ['Eiger', 'north face', 'alpine-peaks'],
  ['Mont Blanc', 'summit dome', 'alpine-peaks'],
  ['Aiguille du Midi', 'granite needle', 'alpine-peaks'],
  ['Grossglockner', 'summit pyramid', 'alpine-peaks'],
  ['Zugspitze', 'limestone summit', 'alpine-peaks'],
  ['Watzmann', 'east face', 'alpine-peaks'],
  ['Dachstein', 'limestone massif', 'alpine-peaks'],
  ['Triglav', 'limestone summit', 'alpine-peaks'],
  ['Mangart', 'saddle under the north face', 'alpine-peaks'],
  ['Naranjo de Bulnes', 'limestone tower', 'alpine-peaks'],
  ['Pic du Midi d Ossau', 'twin-horned peak', 'alpine-peaks'],
  ['Kebnekaise', 'arctic summit', 'alpine-peaks'],
  ['Galdhøpiggen', 'summit', 'alpine-peaks'],
  ['Rysy', 'granite summit', 'alpine-peaks'],
  ['Mount Olympus', 'Mytikas summit', 'alpine-peaks'],
  ['Vihren', 'marble summit', 'alpine-peaks'],
  ['Buachaille Etive Mòr', 'pyramid peak', 'alpine-peaks'],
  ['Suilven', 'inselberg ridge', 'alpine-peaks'],
  ['Liathach', 'terraced sandstone ridge', 'alpine-peaks'],
  ['Crib Goch', 'knife-edge ridge', 'alpine-peaks'],
  ['Besseggen', 'ridge between two lakes', 'alpine-peaks'],
  ['Lago di Braies', 'turquoise alpine lake', 'cirque-tarns'],
  ['Lago di Carezza', 'mirror lake under spires', 'cirque-tarns'],
  ['Lago di Sorapis', 'milky-blue tarn', 'cirque-tarns'],
  ['Riffelsee', 'mirror tarn under the Matterhorn', 'cirque-tarns'],
  ['Oeschinensee', 'turquoise lake under cliffs', 'cirque-tarns'],
  ['Blausee', 'clear blue forest lake', 'cirque-tarns'],
  ['Bachalpsee', 'tarn reflecting the Wetterhorn', 'cirque-tarns'],
  ['Eibsee', 'mirror lake under the Zugspitze', 'cirque-tarns'],
  ['Königssee', 'fjord-shaped alpine lake', 'cirque-tarns'],
  ['Gosausee', 'lake under the Dachstein', 'cirque-tarns'],
  ['Lake Bohinj', 'glacial lake', 'cirque-tarns'],
  ['Lac Blanc', 'granite tarn facing Mont Blanc', 'cirque-tarns'],
  ['Lac d Oô', 'cirque lake with waterfall', 'cirque-tarns'],
  ['Morskie Oko', 'tarn under granite walls', 'cirque-tarns'],
  ['Rila Seven Lakes', 'glacial lake chain', 'cirque-tarns'],
  ['Durmitor Black Lake', 'pine-ringed lake', 'cirque-tarns'],
  ['Loch Coruisk', 'cirque loch under the Cuillin', 'cirque-tarns'],
  ['Llyn Idwal', 'cwm lake', 'cirque-tarns'],
  ['Wastwater', 'screes lake', 'cirque-tarns'],
  ['Buttermere', 'valley lake', 'cirque-tarns'],
  ['Loch Maree', 'island-dotted loch', 'cirque-tarns'],
  ['Abisko Lapporten', 'U-shaped valley gate', 'cirque-tarns'],
  ['Gorges du Verdon', 'limestone canyon', 'gorges'],
  ['Cirque de Gavarnie', 'glacial amphitheatre', 'gorges'],
  ['Ordesa Canyon', 'terraced canyon', 'gorges'],
  ['Congost de Mont-rebei', 'river gorge', 'gorges'],
  ['Vintgar Gorge', 'emerald river gorge', 'gorges'],
  ['Soča River', 'emerald river', 'gorges'],
  ['Tara Canyon', 'deep river canyon', 'gorges'],
  ['Vikos Gorge', 'limestone gorge', 'gorges'],
  ['Samaria Gorge', 'narrow gorge', 'gorges'],
  ['Partnach Gorge', 'slot gorge', 'gorges'],
  ['Cheddar Gorge', 'limestone gorge', 'gorges'],
  ['Glen Coe', 'glen', 'gorges'],
  ['Glen Etive', 'river glen', 'gorges'],
  ['Plitvice Lakes', 'terraced travertine cascades', 'waterfalls'],
  ['Krka', 'travertine waterfalls', 'waterfalls'],
  ['Krimml Falls', 'three-tier waterfall', 'waterfalls'],
  ['Vøringsfossen', 'plunge waterfall', 'waterfalls'],
  ['Mardalsfossen', 'ribbon waterfall', 'waterfalls'],
  ['Staubbach Falls', 'valley-wall waterfall', 'waterfalls'],
  ['Triberg Falls', 'forest cascade', 'waterfalls'],
  ['Kravica', 'tufa waterfalls', 'waterfalls'],
  ['Black Forest', 'fir forest', 'forests'],
  ['Białowieża', 'primeval forest', 'forests'],
  ['Biogradska Gora', 'old-growth forest', 'forests'],
  ['Oulanka', 'taiga river forest', 'forests'],
  ['Peneda-Gerês', 'oak and granite forest', 'forests'],
  ['Bastei', 'Elbe-sandstone pillar towers', 'sandstone-towers'],
  ['Adršpach', 'sandstone rock city', 'sandstone-towers'],
  ['Pravčická brána', 'sandstone arch', 'sandstone-towers'],
  ['Bardenas Reales', 'clay badlands', 'sandstone-towers'],
  ['Meteora', 'sandstone pillars', 'sandstone-towers'],
  ['Quiraing', 'landslip escarpment', 'highland-moor'],
  ['Old Man of Storr', 'rock pinnacle', 'highland-moor'],
  ['Rannoch Moor', 'blanket bog moor', 'highland-moor'],
  ['Cairngorms', 'granite plateau', 'highland-moor'],
  ['Dartmoor Haytor', 'granite tor', 'highland-moor'],
  ['Malham Cove', 'limestone pavement', 'highland-moor'],
  ['Kinder Scout', 'gritstone plateau edge', 'highland-moor'],
  ['Connemara Twelve Bens', 'quartzite peaks over bog', 'highland-moor'],
  ['Burren', 'limestone pavement', 'highland-moor'],
  ['Hardangervidda', 'mountain plateau', 'highland-moor'],
  ['Aletsch Glacier', 'glacier', 'glaciers'],
  ['Mer de Glace', 'glacier', 'glaciers'],
  ['Rhône Glacier', 'glacier tongue', 'glaciers'],
  ['Pasterze Glacier', 'glacier under the Grossglockner', 'glaciers'],
];
const LIGHT = [
  'dawn',
  'sunrise',
  'sunset',
  'alpenglow',
  'blue-hour',
  'golden hour',
  'misty dawn',
  'storm-break',
  'midday',
];
const LIGHT_RULES = [
  ['misty dawn', /misty dawn|mist-shrouded|mist/i],
  ['storm-break', /storm/i],
  ['alpenglow', /alpenglow/i],
  ['blue-hour', /blue[- ]hour/i],
  ['golden hour', /golden[- ]hour/i],
  ['sunrise', /sunrise|first light/i],
  ['sunset', /sunset|dusk/i],
  ['dawn', /dawn/i],
  ['midday', /midday|noon/i],
];

module.exports = landmarkPool({
  name: 'earthbot/european_wilderness/subject',
  poolFile: path.join(__dirname, '../../bots/earthbot/seeds/european_wilderness_subject.json'),
  intro:
    'European INLAND wilderness, one real place per entry, THE LAND IS THE HERO: alpine peaks, cirque tarns and lakes, gorges, waterfalls, old forests, sandstone towers, highland moor and glaciers.',
  GROUPS,
  PLACES,
  LIGHT,
  LIGHT_RULES,
  voice:
    '- Include one camera-angle phrase (low-angle hero stance / drone POV aerial / mirror-reflection / silhouette / wide cinematic vista). Inland only: any water is a tarn, lake, river or waterfall, never the sea. Wildlife, if any, is matchstick-tiny in the distance.',
  extraBans: [
    ['coast', /\b(sea|ocean|fjord|coast|coastal|beach|surf|tidal|sea-stack|sea-arch|sea-cliff)\b/i],
    ['cultural', /\b(standing stones|Stonehenge|Avebury|megalith|rifugio|funicular|cable car)\b/i],
    ['iceland', /\b(Reynisfjara|Vatnajökull|Jökulsárlón|Iceland)\b/i],
  ],
  aliases: {
    'Quiraing Trotternish': 'Quiraing',
    'Tre Cime': 'Tre Cime di Lavaredo',
    'Jotunheimen Besseggen': 'Besseggen',
    'Saxon Switzerland Bastei': 'Bastei',
    Riffelsee: 'Riffelsee',
  },
});
