/* global __dirname */
/**
 * earthbot / african-landscape / subject — African raw HABITAT, THE LAND IS THE HERO (never the wildlife).
 * Recipe: scripts/gen-earthbot-pool.js `african_landscape_subject` (toponym first; a camera-angle phrase;
 * habitat hero fills the frame; wildlife matchstick-tiny at distance; Africa is FLAT or CANOPY only: bans
 * Kilimanjaro / Meru / Ol Doinyo Lengai / Ngorongoro rim / alpenglow / snow peaks / escarpments / cliffs
 * / rift walls, photographer names, humans / villages / kraals / roads / safari trucks, analogues,
 * negation). Pool 2026-09-23: 200 entries, 102 openers, "Tarangire watering hole" ×8, "Okavango papyrus
 * channel" ×8, "Maasai Mara watering hole" ×7. Same idea = same place (habitat) + same light moment.
 */
const path = require('path');
const { landmarkPool } = require('../lib/landmarkPool');

// Recipe coverage per 25: savanna 7, salt pans 3, delta + rivers 4, Congo forest 4, Sahara 2, Namib 2,
// Madagascar 2, fynbos 1.
const GROUPS = {
  savanna: 7,
  'salt-pans': 3,
  'delta-rivers': 4,
  'congo-forest': 4,
  sahara: 2,
  namib: 2,
  madagascar: 2,
  fynbos: 1,
};
const PLACES = [
  // savanna: watering holes, kopjes, iconic trees, plains
  ['Tarangire watering hole', 'broad still pool with golden grass behind', 'savanna'],
  ['Tarangire baobab plain', 'lone ancient baobab on flat grass', 'savanna'],
  ['Maasai Mara watering hole', 'mirror-still pool under acacia silhouettes', 'savanna'],
  ['Maasai Mara kopje', 'granite boulder pile on the short-grass plain', 'savanna'],
  ['Serengeti kopje', 'lichen-crusted granite boulder pile', 'savanna'],
  ['Serengeti umbrella acacia', 'lone flat-crowned acacia on the plain', 'savanna'],
  ['Serengeti short-grass plain', 'flat golden plain to the horizon', 'savanna'],
  ['Etosha waterhole', 'mineral-rimmed pool on flat thornveld', 'savanna'],
  ['Tsavo East red-earth plain', 'red-dust plain with scattered doum palms', 'savanna'],
  ['Ruaha baobab plain', 'baobab-studded dry plain', 'savanna'],
  ['Katavi floodplain', 'dry-season floodplain of cracked grass flats', 'savanna'],
  ['Hwange waterhole', 'wide pan waterhole in teak woodland', 'savanna'],
  ['Chobe floodplain', 'river-edge floodplain with grazing lawns', 'savanna'],
  ['Samburu doum-palm plain', 'doum palms along a sand river', 'savanna'],
  ['Liuwa Plain', 'endless flat grassland under a huge sky', 'savanna'],
  ['Nyerere miombo woodland', 'open miombo woodland with fresh red leaf flush', 'savanna'],
  ['Kruger lowveld', 'knob-thorn and marula savanna', 'savanna'],
  ['Amboseli fever-tree swamp', 'yellow-barked fever trees over a green marsh', 'savanna'],
  ['Murchison grassland', 'Borassus palm savanna on rolling grass', 'savanna'],
  ['Laikipia whistling-thorn plain', 'whistling-thorn scrub plain', 'savanna'],
  ['Mkomazi baobab country', 'baobabs scattered on red plain', 'savanna'],
  ['Ol Pejeta plain', 'golden grass plain with lone acacias', 'savanna'],
  // salt pans
  ['Etosha salt pan', 'glaring white pan to a razor-flat horizon', 'salt-pans'],
  ['Makgadikgadi salt pan', 'pearl-white pan under an enormous sky', 'salt-pans'],
  ['Kubu Island', 'granite outcrop of baobabs on the salt pan edge', 'salt-pans'],
  ['Ntwetwe Pan', 'flat salt crust with heat shimmer', 'salt-pans'],
  ['Sua Pan', 'flooded salt pan mirror', 'salt-pans'],
  ['Deadvlei clay pan', 'white clay pan with petrified camel-thorn trees', 'salt-pans'],
  ['Chalbi Desert salt flat', 'white salt flat in the northern Kenyan desert', 'salt-pans'],
  ['Lake Magadi soda flats', 'pink and white soda crust', 'salt-pans'],
  ['Lake Natron soda flats', 'red-and-white soda crust mirror', 'salt-pans'],
  // delta + rivers
  ['Okavango Delta papyrus channel', 'flat water between glowing papyrus walls', 'delta-rivers'],
  ['Okavango Delta lily lagoon', 'water carpeted in lily pads', 'delta-rivers'],
  ['Okavango palm island', 'fan-palm island in a flooded grass plain', 'delta-rivers'],
  ['Zambezi floodplain', 'broad silver river S-curving through golden plain', 'delta-rivers'],
  ['Zambezi river bend above the falls', 'wide glassy river with palm-fringed banks', 'delta-rivers'],
  ['Chobe River floodplain', 'river channel with flooded grass margins', 'delta-rivers'],
  ['Bangweulu wetlands', 'papyrus swamp and open floodplain', 'delta-rivers'],
  ['Sudd papyrus marsh', 'endless Nile papyrus swamp', 'delta-rivers'],
  ['Nile papyrus marsh', 'papyrus-fringed channel', 'delta-rivers'],
  ['Kafue Flats', 'seasonally flooded grassland', 'delta-rivers'],
  ['Mara River bend', 'brown river bend cutting golden plain', 'delta-rivers'],
  ['Luangwa River oxbow', 'oxbow lagoon with sandbanks and ebony groves', 'delta-rivers'],
  ['Rufiji River delta', 'braided channels between sandbanks', 'delta-rivers'],
  ['Niger inland delta', 'flooded plain of channels and reed islands', 'delta-rivers'],
  ['Lower Zambezi floodplain', 'winterthorn floodplain along the river', 'delta-rivers'],
  ['Shire River marsh', 'reed and papyrus marsh channel', 'delta-rivers'],
  // Congo forest: canopy-down, understory, bai
  ['Congo Basin canopy', 'emerald canopy roof with kapok emergents', 'congo-forest'],
  ['Congo Basin bai clearing', 'forest clearing with a mineral pool', 'congo-forest'],
  ['Dzanga Bai', 'sandy forest clearing ringed by emerald wall', 'congo-forest'],
  ['Mbeli Bai', 'swampy forest clearing', 'congo-forest'],
  ['Lobéké bai', 'still forest clearing pool', 'congo-forest'],
  ['Mahale forest interior', 'buttress-rooted trunks under dappled gold', 'congo-forest'],
  ['Mahale canopy', 'layered canopy seen from above', 'congo-forest'],
  ['Bwindi forest understory', 'dense emerald understory with low mist', 'congo-forest'],
  ['Kibale forest canopy', 'canopy layers with emergent crowns', 'congo-forest'],
  ['Nyungwe canopy', 'mist-draped montane forest canopy', 'congo-forest'],
  ['Odzala forest', 'forest-and-savanna mosaic with a bai', 'congo-forest'],
  ['Ituri forest interior', 'towering hardwood trunks in deep shade', 'congo-forest'],
  ['Salonga river forest', 'blackwater river bend through flooded forest', 'congo-forest'],
  ['Budongo forest interior', 'mahogany trunks over a fern floor', 'congo-forest'],
  ['Semuliki forest', 'lowland rainforest with hot-spring steam', 'congo-forest'],
  // Sahara
  ['Erg Chebbi', 'red-orange dune sea', 'sahara'],
  ['Erg Chigaga', 'wave-after-wave dune sea', 'sahara'],
  ['Tadrart Acacus erg', 'ochre dunes against dark sandstone', 'sahara'],
  ['Ténéré sand sea', 'endless pale dune sea', 'sahara'],
  ['Grand Erg Oriental', 'vast dune sea', 'sahara'],
  ['Ubari sand sea', 'dune sea with a hidden salt lake', 'sahara'],
  ['White Desert', 'chalk mushroom formations on flat sand', 'sahara'],
  ['Erg Admer', 'dune sea against dark plateau', 'sahara'],
  // Namib
  ['Sossusvlei dune face', 'massive orange dune with a knife-edge crest', 'namib'],
  ['Big Daddy dune', 'towering orange dune above the clay pan', 'namib'],
  ['Sandwich Harbour dunes', 'dunes plunging straight into the Atlantic', 'namib'],
  ['Skeleton Coast dunes', 'coastal red dunes under sea fog', 'namib'],
  ['NamibRand plain', 'red dune belt over golden grass plain', 'namib'],
  ['Hiddenvlei', 'small clay pan among orange dunes', 'namib'],
  ['Namib gravel plain', 'flat gravel plain with fairy circles', 'namib'],
  ['Welwitschia plain', 'gravel plain of ancient welwitschia plants', 'namib'],
  // Madagascar
  ['Avenue of the Baobabs', 'colonnade of Grandidier baobabs', 'madagascar'],
  ['Kirindy baobab forest', 'dry forest of bottle-trunk baobabs', 'madagascar'],
  ['Ifaty spiny forest', 'Didierea and Alluaudia spine columns on red laterite', 'madagascar'],
  ['Berenty spiny forest', 'octopus-tree spiny thicket', 'madagascar'],
  ['Andohahela spiny forest', 'spiny forest under a hard blue sky', 'madagascar'],
  ['Baobab Amoureux', 'two baobabs twisted together on flat red ground', 'madagascar'],
  // fynbos + Cape flora
  ['Cape Point fynbos slope', 'protea-and-erica slope to the Atlantic', 'fynbos'],
  ['Kogelberg fynbos', 'dense fynbos rolling to the sea', 'fynbos'],
  ['De Hoop fynbos coast', 'fynbos and white dunes above the sea', 'fynbos'],
  ['Agulhas plain fynbos', 'flat fynbos plain to the southern tip', 'fynbos'],
  ['Namaqualand daisy plain', 'orange daisy carpet to the horizon', 'fynbos'],
  ['Cape of Good Hope fynbos', 'wind-flattened fynbos over the ocean', 'fynbos'],
];
const LIGHT = [
  'golden hour',
  'dusk',
  'blood-red sunset',
  'dawn',
  'sunrise',
  'hard midday',
  'Milky Way night',
  'pre-dawn',
  'electric storm',
  'monsoon rainbow',
  'haboob dust-wall',
];
const LIGHT_RULES = [
  ['Milky Way night', /milky way|moonless|star-crowded|starry|night/i],
  ['haboob dust-wall', /haboob|dust-wall|dust wall|dust storm/i],
  ['monsoon rainbow', /rainbow/i],
  ['electric storm', /electric storm|lightning|storm/i],
  ['blood-red sunset', /blood-red|blood-orange/i],
  ['pre-dawn', /pre-dawn|predawn/i],
  ['golden hour', /golden[- ]hour|last light/i],
  ['hard midday', /midday|noon|hard overhead/i],
  ['sunrise', /sunrise|first light/i],
  ['dawn', /dawn/i],
  ['dusk', /dusk|sunset/i],
];

module.exports = landmarkPool({
  name: 'earthbot/african_landscape/subject',
  poolFile: path.join(__dirname, '../../bots/earthbot/seeds/african_landscape_subject.json'),
  intro:
    'African raw HABITAT, one real place per entry, THE LAND IS THE HERO and never the wildlife: watering-hole vistas, kopjes, iconic trees and plains, salt pans, delta channels and river bends, Congo canopy / understory / bai clearings, Sahara and Namib dune seas, Madagascar baobabs and spiny forest, Cape fynbos.',
  GROUPS,
  PLACES,
  LIGHT,
  LIGHT_RULES,
  wordRange: [30, 65], // the originals run to 64 words (p50 48); the brief still asks for 38-50
  voice:
    '- Include one camera-angle phrase (low-angle hero stance / drone POV aerial / canopy POV looking down / waterline reflection / kopje vantage looking out / silhouette against burning sky / wide cinematic vista). Africa here is FLAT or CANOPY: no mountains, no peaks, no escarpments, no cliffs. Africa-coded materials only: red laterite, acacia, baobab, papyrus, dry golden grass, orange sand, kopje granite, salt crust, protea, Didierea, kapok. Wildlife, if any, is matchstick-tiny at deep distance and named after the habitat.',
  extraBans: [
    // Dune "ridges" and the Rift Valley FLOOR are fine; walls, escarpments, cliffs and peaks are not.
    [
      'mountain',
      /\b(Kilimanjaro|Meru|Ol Doinyo Lengai|Ngorongoro|alpenglow|snow-capped|snowcapped|alpine|escarpment|escarpments|cliff|cliffs|rift walls?|Rift Valley walls?|mountain|mountains|peak|peaks|summit)\b/i,
    ],
    ['analogue-af', /\b(Yellowstone|Patagonian|Australian|Outback|Serengeti-like)\b/i],
    ['built-af', /\b(kraal|kraals|safari|lodge|lodges|track|tracks|jeep)\b/i],
  ],
  aliases: {
    'Tarangire lone ancient baobab': 'Tarangire baobab plain',
    'Serengeti granite kopje': 'Serengeti kopje',
    'Maasai Mara granite kopje': 'Maasai Mara kopje',
    'Etosha watering hole': 'Etosha waterhole',
    'Etosha waterhole basin': 'Etosha waterhole',
    'Namib Deadvlei white clay pan': 'Deadvlei clay pan',
    'Deadvlei white clay pan': 'Deadvlei clay pan',
    'Namib Sossusvlei orange dune face': 'Sossusvlei dune face',
    'Namib Sossusvlei orange dune sea': 'Sossusvlei dune face',
    'Sossusvlei orange dune sea': 'Sossusvlei dune face',
    'Namib coastal red dunes': 'Skeleton Coast dunes',
    'Sahara Erg Chebbi dune sea': 'Erg Chebbi',
    'Erg Chebbi Sahara dune sea': 'Erg Chebbi',
    'Sahara Tadrart Acacus erg': 'Tadrart Acacus erg',
    'Tadrart Acacus Sahara sandstone plateau dune sea': 'Tadrart Acacus erg',
    'Adansonia grandidieri baobabs': 'Avenue of the Baobabs',
    'Avenue of the Baobabs Madagascar': 'Avenue of the Baobabs',
    'Madagascar Didierea spiny forest': 'Ifaty spiny forest',
    'Madagascar Didierea and Alluaudia spiny forest': 'Ifaty spiny forest',
    'Madagascar spiny forest': 'Ifaty spiny forest',
    'Congo Basin natural forest clearing': 'Congo Basin bai clearing',
    'Congo Basin rainforest': 'Congo Basin canopy',
    'Mahale rainforest canopy': 'Mahale canopy',
    'Kibale forest': 'Kibale forest canopy',
    'Bwindi forest': 'Bwindi forest understory',
    'Okavango Delta lily-pad lagoon': 'Okavango Delta lily lagoon',
    'Nile floodplain papyrus marsh': 'Nile papyrus marsh',
    'Zambezi river bend': 'Zambezi river bend above the falls',
    'Tsavo East red-dust plain': 'Tsavo East red-earth plain',
    'Tsavo East dry plain': 'Tsavo East red-earth plain',
    'Tsavo East red-elephant plain': 'Tsavo East red-earth plain',
    'Cape fynbos coastal slope': 'Cape Point fynbos slope',
    'Etosha salt pan vast empty vista': 'Etosha salt pan',
    'Etosha salt pan vast empty expanse': 'Etosha salt pan',
  },
});
