/* global __dirname */
/**
 * earthbot / asia-landscape / subject — pan-Asian raw HABITAT, THE LAND IS THE HERO.
 * Recipe: scripts/gen-earthbot-pool.js `asia_landscape_subject` (toponym first; a camera-angle phrase;
 * habitat hero fills the frame; wildlife matchstick-tiny; bans temples / torii / pagodas / stupas /
 * statues / prayer flags / lanterns / monks, villages / rice terraces / agriculture / roads, photographer
 * names, European-alpine analogues, negation). Pool 2026-09-23: 200 entries, 114 openers, "Jiuzhaigou
 * turquoise lake" ×8, "Tibetan plateau vista" ×8, "Gobi tangerine dune sea" ×7. Same idea = same place
 * (habitat) + same light moment.
 */
const path = require('path');
const { landmarkPool } = require('../lib/landmarkPool');

// Recipe compositions A-O, roughly even coverage.
const GROUPS = {
  fuji: 2,
  huangshan: 2,
  'karst-river': 2,
  'pillar-forest': 2,
  'karst-bay': 2,
  'cedar-forest': 2,
  sakura: 2,
  'winter-north': 2,
  bamboo: 1,
  'turquoise-lakes': 2,
  'tibet-plateau': 2,
  'gobi-desert': 2,
  volcano: 2,
  gorge: 1,
};
const PLACES = [
  ['Kawaguchiko lake', 'Fuji mirrored in still water', 'fuji'],
  ['Lake Motosu', 'Fuji over a deep blue lake', 'fuji'],
  ['Lake Yamanaka', 'Fuji across a wide lake', 'fuji'],
  ['Lake Shoji', 'Fuji over a small mirror lake', 'fuji'],
  ['Lake Sai', 'Fuji above a forest-ringed lake', 'fuji'],
  ['Hakone Ashinoko', 'Fuji beyond a caldera lake', 'fuji'],
  ['Aokigahara forest floor', 'moss-covered lava forest at the foot of Fuji', 'fuji'],
  ['Huangshan West Sea', 'granite peaks in a sea of clouds', 'huangshan'],
  ['Huangshan Lotus Peak', 'granite summit above cloud', 'huangshan'],
  ['Sanqingshan granite pillars', 'granite pillars in mist', 'huangshan'],
  ['Wugong Mountain grass ridge', 'alpine grass ridge above cloud', 'huangshan'],
  ['Zhangye Danxia', 'rainbow-striped sandstone hills', 'huangshan'],
  ['Laojun Mountain', 'granite peaks over a cloud sea', 'huangshan'],
  ['Niubei Mountain', 'cloud-sea plateau edge', 'huangshan'],
  ['Guilin Li River', 'karst pillars rising from a misty river', 'karst-river'],
  ['Xingping', 'karst peaks reflected in the river', 'karst-river'],
  ['Yangshuo karst valley', 'karst towers over the Yulong River', 'karst-river'],
  ['Ninh Binh karst', 'limestone towers over reed-fringed water', 'karst-river'],
  ['Trang An karst', 'karst and winding waterways', 'karst-river'],
  ['Phong Nha karst', 'jungle-crowned limestone towers', 'karst-river'],
  ['Wulong karst', 'natural limestone bridges over a gorge', 'karst-river'],
  ['Vang Vieng karst', 'limestone peaks above a green river', 'karst-river'],
  ['Zhangjiajie pillar forest', 'sandstone pillars crowned with trees', 'pillar-forest'],
  ['Wulingyuan pillars', 'sandstone pillar field in mist', 'pillar-forest'],
  ['Tianzi Mountain pillars', 'pillar spires above a cloud sea', 'pillar-forest'],
  ['Yuanjiajie pillars', 'quartz-sandstone pillar cluster', 'pillar-forest'],
  ['Halong Bay', 'limestone islands in a jade sea', 'karst-bay'],
  ['Bai Tu Long Bay', 'quieter karst bay', 'karst-bay'],
  ['Lan Ha Bay', 'karst islands and hidden lagoons', 'karst-bay'],
  ['Phang Nga Bay', 'limestone islands in a jade bay', 'karst-bay'],
  ['El Nido karst coast', 'limestone cliffs over turquoise lagoons', 'karst-bay'],
  ['Coron limestone lakes', 'limestone walls around clear lakes', 'karst-bay'],
  ['Krabi Railay karst', 'limestone cliffs over a jade sea', 'karst-bay'],
  ['Yakushima cedar forest', 'moss-covered ancient cedars', 'cedar-forest'],
  ['Shiratani Unsuikyo', 'moss-carpeted ravine of cedars', 'cedar-forest'],
  ['Alishan cypress forest', 'giant cypresses in mist', 'cedar-forest'],
  ['Kirishima forest', 'cedar forest on volcanic slopes', 'cedar-forest'],
  ['Togakushi cedar avenue', 'towering cedar corridor', 'cedar-forest'],
  ['Hokkaido boreal forest', 'fir-and-birch forest in mist', 'cedar-forest'],
  ['Mount Yoshino sakura', 'hillside of cherry blossom', 'sakura'],
  ['Hitome Senbonzakura', 'riverside cherry tunnel', 'sakura'],
  ['Miharu Takizakura', 'lone weeping cherry tree', 'sakura'],
  ['Kawaguchiko sakura shore', 'cherry blossom over the lake with Fuji', 'sakura'],
  ['Shizuoka Kawazu sakura', 'early cherry blossom along a river', 'sakura'],
  ['Takato sakura grove', 'dense pink cherry grove', 'sakura'],
  ['Biei snow plain', 'lone frosted trees on a snow plain', 'winter-north'],
  ['Lake Kussharo', 'frozen caldera lake with steam', 'winter-north'],
  ['Kushiro marsh', 'frozen marsh under pale sky', 'winter-north'],
  ['Jilin rime-ice forest', 'trees furred in white rime', 'winter-north'],
  ['Notsuke Peninsula', 'dead trees on a frozen spit', 'winter-north'],
  ['Shiretoko drift ice', 'sea ice against a wild coast', 'winter-north'],
  ['Daisetsuzan snow forest', 'snow-laden conifers under a peak', 'winter-north'],
  ['Lake Toya winter', 'caldera lake under snow', 'winter-north'],
  ['Arashiyama bamboo grove', 'vertical bamboo cathedral', 'bamboo'],
  ['Sagano bamboo forest', 'green bamboo stalks reaching skyward', 'bamboo'],
  ['Shunan bamboo sea', 'rolling bamboo forest', 'bamboo'],
  ['Anji bamboo forest', 'bamboo-carpeted hills', 'bamboo'],
  ['Damyang bamboo forest', 'dense bamboo interior', 'bamboo'],
  ['Jiuzhaigou Five Flower Lake', 'turquoise lake with sunken logs', 'turquoise-lakes'],
  ['Jiuzhaigou Long Lake', 'deep blue lake under forest', 'turquoise-lakes'],
  ['Jiuzhaigou Pearl Shoal', 'travertine cascade shallows', 'turquoise-lakes'],
  ['Jiuzhaigou Mirror Lake', 'glassy lake reflecting forest', 'turquoise-lakes'],
  ['Huanglong travertine pools', 'tiered turquoise pools', 'turquoise-lakes'],
  ['Kuang Si pools', 'turquoise travertine pools in jungle', 'turquoise-lakes'],
  ['Erawan tiered pools', 'emerald tiered pools under trees', 'turquoise-lakes'],
  ['Akan caldera lake', 'caldera lake in morning mist', 'turquoise-lakes'],
  ['Lake Mashu', 'deep cobalt caldera lake', 'turquoise-lakes'],
  ['Namtso lake', 'turquoise lake under snow peaks', 'tibet-plateau'],
  ['Yamdrok lake', 'scorpion-shaped turquoise lake', 'tibet-plateau'],
  ['Pangong Tso', 'blue lake between bare mountains', 'tibet-plateau'],
  ['Tso Moriri', 'high lake in a barren basin', 'tibet-plateau'],
  ['Manasarovar', 'sacred-blue lake under Kailash', 'tibet-plateau'],
  ['Qinghai Lake', 'vast blue lake edged by grassland', 'tibet-plateau'],
  ['Zoige grassland', 'rolling plateau grassland with a winding river', 'tibet-plateau'],
  ['Hoh Xil plateau', 'empty high plateau with distant snow', 'tibet-plateau'],
  ['Yading peaks', 'snow peaks over turquoise lakes', 'tibet-plateau'],
  ['Hunder dunes', 'cold-desert dunes in a mountain valley', 'tibet-plateau'],
  ['Khongoryn Els', 'singing dunes against dry mountains', 'gobi-desert'],
  ['Bayanzag flaming cliffs', 'red badlands at sunset', 'gobi-desert'],
  ['Taklamakan dune corridor', 'endless dune sea', 'gobi-desert'],
  ['Badain Jaran', 'giant dunes with saline lakes', 'gobi-desert'],
  ['Mingsha Shan dunes', 'singing dunes over a crescent lake', 'gobi-desert'],
  ['Kumtag desert', 'dune sea at the desert edge', 'gobi-desert'],
  ['Dunhuang yardangs', 'wind-carved yardang field', 'gobi-desert'],
  ['Tengger desert', 'dune sea to a flat horizon', 'gobi-desert'],
  ['Mount Bromo', 'smoking cone over the sea of sand', 'volcano'],
  ['Tengger caldera', 'ash floor ringed by caldera walls', 'volcano'],
  ['Ijen crater', 'turquoise acid lake in a sulphur crater', 'volcano'],
  ['Kelimutu lakes', 'three coloured crater lakes', 'volcano'],
  ['Rinjani crater lake', 'crater lake with a new cone', 'volcano'],
  ['Batur caldera', 'black lava field and caldera lake', 'volcano'],
  ['Mount Aso caldera', 'grass caldera floor with steaming crater', 'volcano'],
  ['Sakurajima', 'active cone across the bay', 'volcano'],
  ['Mayon', 'perfect volcanic cone', 'volcano'],
  ['Kawah Putih', 'white-turquoise crater lake', 'volcano'],
  ['Taroko marble gorge', 'marble walls above a jade river', 'gorge'],
  ['Tunnel of Nine Turns', 'narrow marble gorge', 'gorge'],
  ['Yehliu hoodoos', 'mushroom rocks on a wave-cut shelf', 'gorge'],
  ['Tiger Leaping Gorge', 'deep gorge with a roaring river', 'gorge'],
  ['Kali Gandaki gorge', 'deepest gorge between snow giants', 'gorge'],
];
const LIGHT = [
  'dawn',
  'sunrise',
  'sea-of-clouds dawn',
  'blue-hour',
  'golden hour',
  'sunset',
  'blood-red sunset',
  'Milky Way night',
  'misty morning',
  'monsoon rainbow',
  'winter dawn',
];
const LIGHT_RULES = [
  ['sea-of-clouds dawn', /sea[- ]of[- ]clouds/i],
  ['Milky Way night', /milky way|starry|star-crowded|night/i],
  ['monsoon rainbow', /rainbow/i],
  ['winter dawn', /winter dawn|winter blue|frost|rime/i],
  ['blood-red sunset', /blood-red/i],
  ['blue-hour', /blue[- ]hour|twilight|pre-dawn/i],
  ['golden hour', /golden[- ]hour|last light/i],
  ['misty morning', /misty morning|morning mist|dawn mist|mist drift/i],
  ['sunrise', /sunrise|first light/i],
  ['dawn', /dawn/i],
  ['sunset', /sunset|dusk/i],
];

module.exports = landmarkPool({
  name: 'earthbot/asia_landscape/subject',
  poolFile: path.join(__dirname, '../../bots/earthbot/seeds/asia_landscape_subject.json'),
  intro:
    'pan-Asian raw HABITAT, one real place per entry, THE LAND IS THE HERO: Fuji lakes, Huangshan cloud seas, karst rivers and bays, sandstone pillar forests, ancient cedar and bamboo forests, sakura groves, Hokkaido and Jilin winter, turquoise travertine lakes, the Tibetan plateau, Gobi and Taklamakan dunes, Indonesian and Japanese volcanoes, marble gorges.',
  GROUPS,
  PLACES,
  LIGHT,
  LIGHT_RULES,
  voice:
    '- Include one camera-angle phrase (low-angle hero stance / drone POV aerial / canopy POV / waterline reflection / sea-of-clouds vantage / silhouette / wide cinematic vista). Asia-coded materials only: granite, karst limestone, marble, volcanic ash, sulphur, bamboo, cedar, birch, sakura, moss, travertine, glacier ice. Pure nature: nothing built, nothing planted, nothing sacred. Describe Asia on its own terms.',
  extraBans: [
    [
      'cultural-asia',
      /\b(torii|pagoda|pagodas|stupa|stupas|statue|statues|prayer flags?|lantern|lanterns|monk|monks|shrine|shrines|Buddha)\b/i,
    ],
    [
      'agriculture',
      /\b(rice terraces?|paddy|paddies|terraced fields?|farmland|lavender field|orchard|plantation|tea fields?)\b/i,
    ],
    ['analogue-asia', /\b(Alps-like|Dolomites|Alps|Alpine-style)\b/i],
  ],
  aliases: {
    'Mt. Fuji silhouette': 'Kawaguchiko lake',
    'Kawaguchiko lake waterline reflection': 'Kawaguchiko lake',
    'Huangshan granite peaks': 'Huangshan West Sea',
    'Huangshan twisted pine': 'Huangshan West Sea',
    'Huangshan sea-of-clouds silhouette': 'Huangshan West Sea',
    'Huangshan granite cliff': 'Huangshan West Sea',
    'Guilin karst valley': 'Guilin Li River',
    'Guilin karst river valley': 'Guilin Li River',
    'Yangshuo Li River bend': 'Yangshuo karst valley',
    'Zhangjiajie sandstone pillar forest': 'Zhangjiajie pillar forest',
    'Wulingyuan sandstone pillar forest': 'Wulingyuan pillars',
    'Wulingyuan pillar forest': 'Wulingyuan pillars',
    'Halong Bay limestone karst archipelago': 'Halong Bay',
    'Halong Bay limestone archipelago': 'Halong Bay',
    'Phang Nga Bay karst islands': 'Phang Nga Bay',
    'Yakushima ancient cedar forest': 'Yakushima cedar forest',
    'Yakushima ancient cedar interior': 'Yakushima cedar forest',
    'Yakushima cedar ridgeline': 'Yakushima cedar forest',
    'Yoshino sakura grove': 'Mount Yoshino sakura',
    'Hokkaido birch grove': 'Biei snow plain',
    'Arashiyama bamboo forest': 'Arashiyama bamboo grove',
    'Jiuzhaigou turquoise lake': 'Jiuzhaigou Five Flower Lake',
    'Tibetan plateau': 'Zoige grassland',
    'Mongolian Gobi tangerine dune sea': 'Khongoryn Els',
    'Gobi sand sea': 'Khongoryn Els',
    'Bayanzag flaming cliffs Gobi': 'Bayanzag flaming cliffs',
    'Bayanzag flaming cliffs Mongolia': 'Bayanzag flaming cliffs',
    'Mount Bromo Indonesian volcanic basin': 'Mount Bromo',
    'Mount Bromo Tengger caldera': 'Mount Bromo',
    'Tengger caldera sea-of-sand': 'Tengger caldera',
    'Ijen volcanic crater Indonesia': 'Ijen crater',
    'Ijen Indonesian volcano': 'Ijen crater',
    'Taroko marble gorge Taiwan': 'Taroko marble gorge',
    'Taroko marble gorge in Taiwan': 'Taroko marble gorge',
    'Seoraksan granite ridge Korea': 'Seoraksan granite ridge',
    'Seoraksan granite peaks Korea': 'Seoraksan granite ridge',
    'Seoraksan granite ridge in Korea': 'Seoraksan granite ridge',
    'Akan caldera volcanic lake Hokkaido': 'Akan caldera lake',
    'Akan volcanic lake Hokkaido': 'Akan caldera lake',
    'Akan volcanic caldera': 'Akan caldera lake',
    'Lake Mashu Hokkaido': 'Lake Mashu',
    'Lake Mashu caldera': 'Lake Mashu',
    'Hokkaido boreal forest interior': 'Hokkaido boreal forest',
  },
});
