/**
 * MagicalLoadingStage — the loading visual for dream generation.
 *
 * Black backdrop + a small lavender wave-of-dots loader + a single
 * clean "Dreaming…" message + a hint that the user can head back and
 * get notified. No mascot, no halo, no rotating subtitles — minimal
 * on purpose. Animations are Reanimated worklets, ~zero JS cost.
 *
 * History (kept terse — see git log for full arc): an earlier
 * iteration had a Skia nebula shader + sparkle field; a follow-up
 * dropped the shader but kept the mascot + lavender pulse halo. Both
 * felt too heavy — Kevin asked for "interesting animation + clean
 * message" instead of a centered glowing ball.
 */

import React, { useEffect, useMemo } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { Image } from 'expo-image';
import Animated, {
  useSharedValue,
  useAnimatedStyle,
  withRepeat,
  withSequence,
  withTiming,
  withDelay,
  Easing,
  interpolate,
} from 'react-native-reanimated';
import { colors } from '@/constants/theme';

// 10 distinct mascot poses generated by `scripts/gen-mascot-poses.js`
// (Sonnet authors the pose phrases, Flux 1.1 Pro Ultra renders each).
// All rendered against a pure-black RGB(0,0,0) backdrop so they blend
// seamlessly into the loading screen's `colors.background` with no
// visible matte/border seam. Local requires → ship with the JS bundle,
// no remote fetch, paints instantly on mount. ~210 KB total across all
// 10 (~16-24 KB each, 512×512 JPG q85).
const MASCOT_SOURCES = [
  require('@/assets/images/mascots/pose-1.jpg'),
  require('@/assets/images/mascots/pose-2.jpg'),
  require('@/assets/images/mascots/pose-3.jpg'),
  require('@/assets/images/mascots/pose-4.jpg'),
  require('@/assets/images/mascots/pose-5.jpg'),
  require('@/assets/images/mascots/pose-6.jpg'),
  require('@/assets/images/mascots/pose-7.jpg'),
  require('@/assets/images/mascots/pose-8.jpg'),
  require('@/assets/images/mascots/pose-9.jpg'),
  require('@/assets/images/mascots/pose-10.jpg'),
];

// ── Wave loader ────────────────────────────────────────────────────────────
// 5 small dots in a horizontal row. Each dot runs the same 1400ms
// scale + opacity + translateY cycle, phase-offset by `index * 140ms`
// so the row reads as a wave traveling left→right and looping. Light,
// recognizable as "loading", and the tiny bounce gives it personality
// without screaming for attention.
const DOT_COUNT = 5;
const DOT_CYCLE_MS = 1400;
const DOT_PHASE_MS = 140;
const DOT_SIZE = 9;

function WaveDot({ index }: { index: number }) {
  const t = useSharedValue(0);

  useEffect(() => {
    t.value = withDelay(
      index * DOT_PHASE_MS,
      withRepeat(
        withTiming(1, { duration: DOT_CYCLE_MS, easing: Easing.inOut(Easing.sin) }),
        -1,
        false
      )
    );
  }, [index, t]);

  const animatedStyle = useAnimatedStyle(() => {
    // t goes 0→1 once per cycle; map a "pulse" curve onto it so the
    // dot peaks in the middle of its cycle then falls back. Using a
    // simple sin-shaped pulse via two interpolations.
    const pulse = interpolate(t.value, [0, 0.5, 1], [0, 1, 0]);
    return {
      opacity: interpolate(pulse, [0, 1], [0.35, 1]),
      transform: [
        { scale: interpolate(pulse, [0, 1], [0.55, 1.15]) },
        { translateY: interpolate(pulse, [0, 1], [0, -6]) },
      ],
    };
  });

  return <Animated.View style={[styles.dot, animatedStyle]} />;
}

function WaveLoader() {
  return (
    <View style={styles.waveRow}>
      {Array.from({ length: DOT_COUNT }).map((_, i) => (
        <WaveDot key={i} index={i} />
      ))}
    </View>
  );
}

// ── Mascot ─────────────────────────────────────────────────────────────────
// Randomly picks one of the 10 poses on mount (stable across re-renders
// via useMemo with an empty dep array) and renders it with a soft sine
// breathe so it feels alive instead of pasted-on. Subtle (translateY
// −4, scale 1→1.025) — we don't want it drawing attention away from
// the wave loader, just gently breathing.
function BreathingMascot() {
  const breathe = useSharedValue(0);

  const mascotSource = useMemo(
    () => MASCOT_SOURCES[Math.floor(Math.random() * MASCOT_SOURCES.length)],
    []
  );

  useEffect(() => {
    breathe.value = withRepeat(
      withSequence(
        withTiming(1, { duration: 2000, easing: Easing.inOut(Easing.sin) }),
        withTiming(0, { duration: 2000, easing: Easing.inOut(Easing.sin) })
      ),
      -1,
      false
    );
  }, [breathe]);

  const animatedStyle = useAnimatedStyle(() => ({
    transform: [
      { translateY: interpolate(breathe.value, [0, 1], [0, -4]) },
      { scale: interpolate(breathe.value, [0, 1], [1, 1.025]) },
    ],
  }));

  return (
    <Animated.View style={animatedStyle}>
      <Image source={mascotSource} style={styles.mascot} contentFit="contain" />
    </Animated.View>
  );
}

export function MagicalLoadingStage() {
  return (
    <View style={styles.stage}>
      <BreathingMascot />
      <WaveLoader />
      <Text style={styles.title}>Dreaming</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  stage: {
    // Tight centered column — the PARENT now controls vertical placement
    // and pairs this block with the CTA cluster below as one unit. This
    // component used to be `flex: 1, justifyContent: 'center'` which let
    // it dominate the screen and float its title in dead space.
    alignItems: 'center',
    paddingHorizontal: 32,
    gap: 24,
  },
  mascot: {
    width: 140,
    height: 140,
  },
  waveRow: {
    flexDirection: 'row',
    alignItems: 'center',
    // Just enough horizontal gap that the dots stay visually separated
    // even at their peak scale (1.15× DOT_SIZE).
    gap: 10,
    // Reserve vertical space for the -6px bounce so the row doesn't
    // shift the layout below it.
    height: DOT_SIZE + 12,
  },
  dot: {
    width: DOT_SIZE,
    height: DOT_SIZE,
    borderRadius: DOT_SIZE / 2,
    backgroundColor: colors.accent,
  },
  title: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
});
