/**
 * Settings → Acknowledgements
 * Lists every open-source package bundled in the app along with its
 * license type and full license text. Required for MIT/BSD/Apache/ISC
 * attribution compliance. Auto-generated by scripts/generate-acknowledgements.js.
 */

import { useMemo, useState, useCallback } from 'react';
import { View, StyleSheet, FlatList, TouchableOpacity, Linking } from 'react-native';
import { Text, TextInput } from '@/components/AppText';
import { Ionicons } from '@expo/vector-icons';
import { ScreenLayout } from '@/components/ScreenLayout';
import { colors } from '@/constants/theme';
import { verticalScale, fontScale } from '@/lib/responsive';
import data from '@/lib/acknowledgements.json';

interface AckPackage {
  name: string;
  version: string;
  license: string;
  homepage: string | null;
  author: string | null;
  // License text is deduped: copyright is stored per-package, the shared body
  // lives in `texts[textHash]` with a placeholder where the copyright goes.
  copyright: string;
  textHash: string | null;
}

interface AckData {
  packages: AckPackage[];
  texts: Record<string, string>;
}

const COPYRIGHT_PLACEHOLDER = '__ACK_COPYRIGHT__';
const { packages: PACKAGES, texts: TEXTS } = data as AckData;

/** Reconstruct a package's exact license text from the shared body + its copyright. */
function licenseTextFor(p: AckPackage): string | null {
  if (!p.textHash) return null;
  const body = TEXTS[p.textHash];
  if (!body) return null;
  return body.replace(COPYRIGHT_PLACEHOLDER, p.copyright || '');
}

export default function AcknowledgementsScreen() {
  const [query, setQuery] = useState('');
  const [expanded, setExpanded] = useState<string | null>(null);

  const filtered = useMemo(() => {
    if (!query.trim()) return PACKAGES;
    const q = query.toLowerCase();
    return PACKAGES.filter(
      (p) =>
        p.name.toLowerCase().includes(q) ||
        p.license.toLowerCase().includes(q) ||
        (p.author?.toLowerCase().includes(q) ?? false)
    );
  }, [query]);

  const handleToggle = useCallback((key: string) => {
    setExpanded((prev) => (prev === key ? null : key));
  }, []);

  const renderItem = useCallback(
    ({ item }: { item: AckPackage }) => {
      const key = `${item.name}@${item.version}`;
      const isOpen = expanded === key;
      return (
        <View style={styles.item}>
          <TouchableOpacity
            style={styles.itemHead}
            onPress={() => handleToggle(key)}
            activeOpacity={0.7}
          >
            <View style={{ flex: 1 }}>
              <Text style={styles.pkgName} numberOfLines={1}>
                {item.name}
              </Text>
              <Text style={styles.pkgMeta} numberOfLines={1}>
                v{item.version} · {item.license}
                {item.author ? ` · ${item.author}` : ''}
              </Text>
            </View>
            <Ionicons
              name={isOpen ? 'chevron-up' : 'chevron-down'}
              size={18}
              color={colors.textSecondary}
            />
          </TouchableOpacity>
          {isOpen && (
            <View style={styles.itemBody}>
              {item.homepage && (
                <TouchableOpacity onPress={() => Linking.openURL(item.homepage!)}>
                  <Text style={styles.link}>{item.homepage}</Text>
                </TouchableOpacity>
              )}
              <Text style={styles.licenseText} selectable>
                {licenseTextFor(item) ??
                  `License: ${item.license}\n(Full license text not bundled. See the package's source repository.)`}
              </Text>
            </View>
          )}
        </View>
      );
    },
    [expanded, handleToggle]
  );

  // swipeBack={false}: this is a long scroll list, and ScreenLayout's custom
  // full-screen horizontal swipe-back fights the FlatList's vertical scroll
  // (janky / dropped swipes, esp. after expanding a license). The `settings`
  // stack is MODAL_SWIPEABLE, so the native edge-swipe — which coordinates with
  // scroll natively — still goes back. Matches bots.tsx + settings/index.tsx.
  return (
    <ScreenLayout header="back" title="Acknowledgements" swipeBack={false}>
      <View style={styles.intro}>
        <Text style={styles.introTitle}>Open-source love 💜</Text>
        <Text style={styles.introBody}>
          DreamBot stands on the shoulders of {PACKAGES.length} open-source packages. Tap any
          package to read its license. Every contributor gets credit here. They made this app
          possible.
        </Text>
      </View>

      <View style={styles.searchWrap}>
        <Ionicons name="search" size={16} color={colors.textSecondary} style={styles.searchIcon} />
        <TextInput
          style={styles.searchInput}
          value={query}
          onChangeText={setQuery}
          placeholder="Search packages…"
          placeholderTextColor={colors.textSecondary}
          autoCorrect={false}
          autoCapitalize="none"
          clearButtonMode="while-editing"
        />
      </View>

      <FlatList
        data={filtered}
        keyExtractor={(item) => `${item.name}@${item.version}`}
        renderItem={renderItem}
        contentContainerStyle={styles.list}
        keyboardShouldPersistTaps="handled"
        initialNumToRender={20}
        maxToRenderPerBatch={20}
        windowSize={10}
        ListEmptyComponent={
          <Text style={styles.empty}>No packages match &ldquo;{query}&rdquo;</Text>
        }
      />
    </ScreenLayout>
  );
}

const styles = StyleSheet.create({
  intro: {
    paddingHorizontal: 16,
    paddingTop: verticalScale(16),
    paddingBottom: verticalScale(12),
  },
  introTitle: {
    color: colors.textPrimary,
    fontSize: fontScale(18),
    fontWeight: '700',
    marginBottom: verticalScale(4),
  },
  introBody: {
    color: colors.textSecondary,
    fontSize: fontScale(14),
    lineHeight: fontScale(20),
  },
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginBottom: verticalScale(8),
    paddingHorizontal: 12,
    paddingVertical: verticalScale(8),
    backgroundColor: colors.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  searchIcon: { marginRight: 8 },
  searchInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: fontScale(15),
    padding: 0,
  },
  list: { paddingBottom: verticalScale(60) },
  item: {
    marginHorizontal: 16,
    marginBottom: verticalScale(8),
    backgroundColor: colors.surface,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  itemHead: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: verticalScale(12),
    gap: 10,
  },
  pkgName: {
    color: colors.textPrimary,
    fontSize: fontScale(15),
    fontWeight: '600',
  },
  pkgMeta: {
    color: colors.textSecondary,
    fontSize: fontScale(12),
    marginTop: verticalScale(2),
  },
  itemBody: {
    paddingHorizontal: 14,
    paddingBottom: verticalScale(14),
    paddingTop: verticalScale(4),
    borderTopWidth: 0.5,
    borderTopColor: colors.border,
    gap: 8,
  },
  link: {
    color: colors.accent,
    fontSize: fontScale(13),
    textDecorationLine: 'underline',
  },
  licenseText: {
    color: colors.textSecondary,
    fontSize: fontScale(12),
    lineHeight: fontScale(18),
    fontFamily: 'Courier',
  },
  empty: {
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: verticalScale(40),
    fontSize: fontScale(14),
  },
});
