/**
 * MangaBot — axis pools. All Sonnet-seeded 50-entry pools.
 * Regenerate: node scripts/gen-seeds/mangabot/gen-<name>.js
 */

const fs = require('fs');
const path = require('path');

function load(name) {
  return JSON.parse(fs.readFileSync(path.join(__dirname, 'seeds', `${name}.json`), 'utf8'));
}

const VIBE_COLOR = {
  cinematic: 'anime cinematic palette, teal-and-orange depth, saturated contrast',
  dark: 'deep inked shadows, charcoal-and-blood palette, Akira-dark atmosphere',
  cozy: 'Ghibli warm golden ambient, soft amber domestic glow',
  epic: 'Demon-Slayer dramatic god-rays, heroic lighting, saturated palette',
  nostalgic: 'Shinkai late-summer amber, copper sunset, faded pastels',
  peaceful: 'Ghibli morning softness, gentle pastel diffuse, pastoral calm',
  whimsical: 'buoyant Ghibli-saturated pastels, dreamy warmth',
  ethereal: 'Ghibli-spirit-world opalescent mist, pearl-white luminance',
  arcane: 'deep violet and emerald spirit-light, mystical Mononoke aura',
  enchanted: 'soft magical glow, dreamy lavender-and-rose, Ghibli-shimmer',
  coquette: 'rose-pink blush atmosphere, soft pastel-shoujo palette',
  voltage: 'Akira neon-blue arcs, electric cyberpunk accents, Blade-Runner vibrance',
  nightshade: 'deep violet moonlight, plum shadows, anime-twilight silvers',
  macabre: 'inked blood-red-and-black, dark-fantasy anime dread',
  shimmer: 'anime sparkle effects, iridescent shoujo highlights, glitter accents',
  surreal: 'dreamy impossible color pairings, Mononoke-spirit-shift atmosphere',
};

module.exports = {
  ANIME_CHARACTERS: load('anime_characters'),
  JAPANESE_LANDSCAPES: load('japanese_landscapes'),
  MYTHOLOGICAL_BEINGS: load('mythological_beings'),
  COZY_ANIME_MOMENTS: load('cozy_anime_moments'),
  KAWAII_MOMENTS: load('kawaii_moments'),
  SLICE_OF_LIFE_MOMENTS: load('slice_of_life_moments'),
  NEO_TOKYO_SETTINGS: load('neo_tokyo_settings'),
  CULTURAL_ELEMENTS: load('cultural_elements'),
  ATMOSPHERES: load('atmospheres'),
  LIGHTING: load('lighting'),
  SCENE_PALETTES: load('scene_palettes'),
  CHARACTER_DETAILS: load('character_details'),
  SHONEN_ACTIONS: load('shonen_actions'),
  SAMURAI_SCENES: load('samurai_scenes'),
  // ============ SAMURAI-ERA path-bespoke 10-axis pools (2026-05-22 migration) ============
  SAMURAI_SCENE_TYPE: load('samurai_scene_type'),
  SAMURAI_LANDSCAPE_SETTING: load('samurai_landscape_setting'),
  SAMURAI_ARCHITECTURAL_ANCHOR: load('samurai_architectural_anchor'),
  SAMURAI_CHARACTER_ROLE: load('samurai_character_role'),
  SAMURAI_ACTION_MOMENT: load('samurai_action_moment'),
  SAMURAI_ATMOSPHERIC_ELEMENT: load('samurai_atmospheric_element'),
  SAMURAI_LIGHT_DRAMA: load('samurai_light_drama'),
  SAMURAI_TIME_OF_DAY: load('samurai_time_of_day'),
  SAMURAI_EMOTIONAL_DNA: load('samurai_emotional_dna'),
  SAMURAI_CAMERA_FRAMING: load('samurai_camera_framing'),
  // Narrative-richness axes (R1 — added after Kevin flagged "clean but bland")
  SAMURAI_STORY_PROP: load('samurai_story_prop'),
  SAMURAI_BACKGROUND_DETAIL: load('samurai_background_detail'),
  // ============ NEO-TOKYO path-bespoke 15-axis pools (2026-05-22 migration) ============
  NEO_TOKYO_SCENE_TYPE: load('neo_tokyo_scene_type'),
  NEO_TOKYO_DISTRICT: load('neo_tokyo_district'),
  NEO_TOKYO_LANDMARK_ANCHOR: load('neo_tokyo_landmark_anchor'),
  NEO_TOKYO_SIGNAGE_DENSITY: load('neo_tokyo_signage_density'),
  NEO_TOKYO_TECH_ARTIFACTS: load('neo_tokyo_tech_artifacts'),
  NEO_TOKYO_VERTICAL_DENSITY: load('neo_tokyo_vertical_density'),
  NEO_TOKYO_CHARACTER_ROLE: load('neo_tokyo_character_role'),
  NEO_TOKYO_ACTION_MOMENT: load('neo_tokyo_action_moment'),
  NEO_TOKYO_WEATHER_AIR: load('neo_tokyo_weather_air'),
  NEO_TOKYO_LIGHT_SIGNATURE: load('neo_tokyo_light_signature'),
  NEO_TOKYO_TIME_OF_DAY: load('neo_tokyo_time_of_day'),
  NEO_TOKYO_EMOTIONAL_DNA: load('neo_tokyo_emotional_dna'),
  NEO_TOKYO_CAMERA_FRAMING: load('neo_tokyo_camera_framing'),
  NEO_TOKYO_STORY_PROP: load('neo_tokyo_story_prop'),
  NEO_TOKYO_BACKGROUND_DETAIL: load('neo_tokyo_background_detail'),
  // ============ GHIBLI-COUNTRYSIDE path-bespoke 14-axis pools (2026-05-22 migration) ============
  GHIBLI_SCENE_TYPE: load('ghibli_scene_type'),
  GHIBLI_LANDSCAPE_SETTING: load('ghibli_landscape_setting'),
  GHIBLI_ARCHITECTURAL_ANCHOR: load('ghibli_architectural_anchor'),
  GHIBLI_CHARACTER_ROLE: load('ghibli_character_role'),
  GHIBLI_ACTION_MOMENT: load('ghibli_action_moment'),
  GHIBLI_WILDFLOWER_GARDEN: load('ghibli_wildflower_garden'),
  GHIBLI_WEATHER_AIR: load('ghibli_weather_air'),
  GHIBLI_LIGHT_QUALITY: load('ghibli_light_quality'),
  GHIBLI_TIME_OF_DAY: load('ghibli_time_of_day'),
  GHIBLI_EMOTIONAL_DNA: load('ghibli_emotional_dna'),
  GHIBLI_CAMERA_FRAMING: load('ghibli_camera_framing'),
  GHIBLI_STORY_PROP: load('ghibli_story_prop'),
  GHIBLI_BACKGROUND_DETAIL: load('ghibli_background_detail'),
  GHIBLI_SPIRIT_ELEMENT: load('ghibli_spirit_element'),
  // ============ ISEKAI-FANTASY path-bespoke 14-axis pools (2026-05-22 migration) ============
  ISEKAI_SCENE_TYPE: load('isekai_scene_type'),
  ISEKAI_FANTASY_WORLD_SETTING: load('isekai_fantasy_world_setting'),
  ISEKAI_ARCHITECTURAL_ANCHOR: load('isekai_architectural_anchor'),
  ISEKAI_CHARACTER_ROLE: load('isekai_character_role'),
  ISEKAI_ACTION_MOMENT: load('isekai_action_moment'),
  ISEKAI_MAGIC_EFFECT: load('isekai_magic_effect'),
  ISEKAI_FANTASY_CREATURE: load('isekai_fantasy_creature'),
  ISEKAI_ATMOSPHERIC_AIR: load('isekai_atmospheric_air'),
  ISEKAI_LIGHT_QUALITY: load('isekai_light_quality'),
  ISEKAI_TIME_OF_DAY: load('isekai_time_of_day'),
  ISEKAI_EMOTIONAL_DNA: load('isekai_emotional_dna'),
  ISEKAI_CAMERA_FRAMING: load('isekai_camera_framing'),
  ISEKAI_STORY_PROP: load('isekai_story_prop'),
  ISEKAI_BACKGROUND_DETAIL: load('isekai_background_detail'),
  ISEKAI_SCENES: load('isekai_scenes'),
  FOOD_ANIME: load('food_anime'),
  ANIME_VILLAGE: load('anime_village'),
  // 12 new path scene pools (rebuild 2026-05-08).
  MECHA_HANGAR_SCENES: load('mecha_hangar_scenes'),
  FESTIVAL_NIGHT_SCENES: load('festival_night_scenes'),
  MAGICAL_GIRL_SCENES: load('magical_girl_scenes'),
  GHIBLI_COUNTRYSIDE_SCENES: load('ghibli_countryside_scenes'),
  OCCULT_TOKYO_SCENES: load('occult_tokyo_scenes'),
  POST_APOCALYPTIC_SCENES: load('post_apocalyptic_scenes'),
  BEACH_EPISODE_SCENES: load('beach_episode_scenes'),
  ROOFTOP_SUNSET_SCENES: load('rooftop_sunset_scenes'),
  CHERRY_BLOSSOM_SCENES: load('cherry_blossom_scenes'),
  SPACE_OPERA_SCENES: load('space_opera_scenes'),
  UNDERWATER_SCENES: load('underwater_scenes'),
  NOIR_SCENES: load('noir_scenes'),
  // Anime-character (male / female) path pools (added 2026-05-08).
  ANIME_SETTING: load('anime_setting'),
  ANIME_VISTA: load('anime_vista'),
  ANIME_ACTIVITY: load('anime_activity'),
  ANIME_SKIN: load('anime_skin'),
  ANIME_EYES: load('anime_eyes'),
  ANIME_HAIR_COLOR: load('anime_hair_color'),
  ANIME_ARCHETYPE_FEMALE: load('anime_archetype_female'),
  ANIME_ARCHETYPE_MALE: load('anime_archetype_male'),
  ANIME_OUTFITS_FEMALE: load('anime_outfits_female'),
  ANIME_OUTFITS_MALE: load('anime_outfits_male'),
  ANIME_HAIRSTYLES_FEMALE: load('anime_hairstyles_female'),
  ANIME_HAIRSTYLES_MALE: load('anime_hairstyles_male'),
  ANIME_ACCESSORIES_FEMALE: load('anime_accessories_female'),
  ANIME_ACCESSORIES_MALE: load('anime_accessories_male'),
  VIBE_COLOR,

  SENSORY_POOLS: {
    female: { smell: load('sensory_female_smell'), sound: load('sensory_female_sound'), touch: load('sensory_female_touch'), temperature: load('sensory_female_temperature'), weight: load('sensory_female_weight'), air: load('sensory_female_air'), lightcolor: load('sensory_female_lightcolor') },
    male: { smell: load('sensory_male_smell'), sound: load('sensory_male_sound'), touch: load('sensory_male_touch'), temperature: load('sensory_male_temperature'), weight: load('sensory_male_weight'), air: load('sensory_male_air'), lightcolor: load('sensory_male_lightcolor') },
    creature: { smell: load('sensory_creature_smell'), sound: load('sensory_creature_sound'), touch: load('sensory_creature_touch'), temperature: load('sensory_creature_temperature'), weight: load('sensory_creature_weight'), air: load('sensory_creature_air'), lightcolor: load('sensory_creature_lightcolor') },
    scene: { smell: load('sensory_scene_smell'), sound: load('sensory_scene_sound'), touch: load('sensory_scene_touch'), temperature: load('sensory_scene_temperature'), weight: load('sensory_scene_weight'), air: load('sensory_scene_air'), lightcolor: load('sensory_scene_lightcolor') },
  },
};
