module.exports = {
  archetype: 'OUTLAWBOT_GUNSLINGER_MALE',
  pools: {
    archetype: 'OUTLAWBOT_GUNSLINGER_MALE_ARCHETYPE',
    hair: 'OUTLAWBOT_GUNSLINGER_MALE_HAIR',
    wardrobe: 'OUTLAWBOT_GUNSLINGER_MALE_WARDROBE',
    weapon: 'OUTLAWBOT_GUNSLINGER_MALE_WEAPON',
    action: 'OUTLAWBOT_GUNSLINGER_MALE_ACTION',
    setting: 'OUTLAWBOT_GUNSLINGER_SETTING',
    atmosphere: 'OUTLAWBOT_GUNSLINGER_ATMOSPHERE',
    composition: 'OUTLAWBOT_GUNSLINGER_COMPOSITION',
  },
};
