module.exports = {
  archetype: 'OUTLAWBOT_GUNSLINGER_FEMALE',
  pools: {
    look: 'OUTLAWBOT_GUNSLINGER_FEMALE_LOOK',
    archetype: 'OUTLAWBOT_GUNSLINGER_FEMALE_ARCHETYPE',
    wardrobe: 'OUTLAWBOT_GUNSLINGER_FEMALE_WARDROBE',
    weapon: 'OUTLAWBOT_GUNSLINGER_FEMALE_WEAPON',
    action: 'OUTLAWBOT_GUNSLINGER_FEMALE_ACTION',
    setting: 'OUTLAWBOT_GUNSLINGER_SETTING',
    atmosphere: 'OUTLAWBOT_GUNSLINGER_ATMOSPHERE',
    composition: 'OUTLAWBOT_GUNSLINGER_COMPOSITION',
  },
};
