-- 181_dlt_clean_mediums.sql
-- DLT "cleaned medium" mapping. Bot mediums in dream_mediums are written for
-- the BOT scene engine (their directive/flux_fragment dictate a cast/scene),
-- which overrides a user's own subject in Dream Like This. This table holds a
-- STYLE-ONLY distilled version per bot medium; DLT looks it up and feeds the
-- clean style to the prompt instead of the raw bot directive. dream_mediums is
-- never mutated. Re-distill / add rows via scripts/distill-clean-mediums.js.

CREATE TABLE IF NOT EXISTS public.dlt_clean_mediums (
  medium_key text PRIMARY KEY REFERENCES public.dream_mediums(key) ON DELETE CASCADE,
  clean_flux_fragment text NOT NULL,
  clean_directive text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- RLS: readable by all (DLT resolution); writes via service role / migration only.
ALTER TABLE public.dlt_clean_mediums ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS dlt_clean_mediums_read ON public.dlt_clean_mediums;
CREATE POLICY dlt_clean_mediums_read ON public.dlt_clean_mediums FOR SELECT USING (true);

INSERT INTO public.dlt_clean_mediums (medium_key, clean_flux_fragment, clean_directive)
VALUES
  ('action_figure', 'Glossy painted plastic with visible articulated joints, vibrant 90s/2000s toy aesthetic, theatrical toy-photography lighting', 'Glossy painted plastic with visible articulated joints, vibrant 90s/2000s toy aesthetic, theatrical toy-photography lighting'),
  ('action_hero_figures', 'Painted plastic toy aesthetic, exaggerated musculature with hyper-detailed sculpting, vibrant primary colors, glossy surfaces, dramatic toy-photography lighting, 90s action figure bombast.', 'Painted plastic toy aesthetic, exaggerated musculature with hyper-detailed sculpting, vibrant primary colors, glossy surfaces, dramatic toy-photography lighting, 90s action figure bombast.'),
  ('ancient_epic', 'Oil-painted classical history style, monumental ruins aesthetic, rich saturated palette, dramatic atmospheric lighting, painterly brushwork, deep perspective, golden hour or twilight mood.', 'Oil-painted classical history style, monumental ruins aesthetic, rich saturated palette, dramatic atmospheric lighting, painterly brushwork, deep perspective, golden hour or twilight mood.'),
  ('army_men', 'Monochromatic army green plastic, simple molded forms, bare plastic texture with subtle play wear, mid-century toy aesthetic, studio daylight rendering.', 'Monochromatic army green plastic, simple molded forms, bare plastic texture with subtle play wear, mid-century toy aesthetic, studio daylight rendering.'),
  ('barbie_figures', 'Glossy molded plastic with stylized proportions, vibrant fashion palette, pristine makeup and hair, bright studio lighting on smooth surfaces, toy-aisle glamour aesthetic', 'Glossy molded plastic with stylized proportions, vibrant fashion palette, pristine makeup and hair, bright studio lighting on smooth surfaces, toy-aisle glamour aesthetic'),
  ('barbie_storytelling_mixed', 'Glossy plastic fashion-doll aesthetic with molded hair, painted-gloss makeup faces, oversized proportions, articulated joints, bright synthetic colors, kid-playroom diorama lighting, practical toy photography finish.', 'Glossy plastic fashion-doll aesthetic with molded hair, painted-gloss makeup faces, oversized proportions, articulated joints, bright synthetic colors, kid-playroom diorama lighting, practical toy photography finish.'),
  ('bloom_conservatory', 'Oil-on-canvas painterly style, dappled glass-filtered light, saturated greens and vibrant blooms, atmospheric botanical detail, warm muted luminosity, Victorian greenhouse aesthetic', 'Oil-on-canvas painterly style, dappled glass-filtered light, saturated greens and vibrant blooms, atmospheric botanical detail, warm muted luminosity, Victorian greenhouse aesthetic'),
  ('bloom_hyperreal_cgi', 'Painterly-photoreal hybrid with volumetric god-rays, bioluminescent sparkles, soft luminous halos, jewel-tone saturated color spectrum, tack-sharp detail, cinematic shallow depth-of-field, magical-realism fantasy aesthetic.', 'Painterly-photoreal hybrid with volumetric god-rays, bioluminescent sparkles, soft luminous halos, jewel-tone saturated color spectrum, tack-sharp detail, cinematic shallow depth-of-field, magical-realism fantasy aesthetic.'),
  ('bloom_painterly_spirit', 'soft oil-painting with Pre-Raphaelite romanticism, luminous brushwork, rich canvas texture, ethereal golden-hour glow, classical fantasy illustration aesthetic, romantic painterly detail', 'soft oil-painting with Pre-Raphaelite romanticism, luminous brushwork, rich canvas texture, ethereal golden-hour glow, classical fantasy illustration aesthetic, romantic painterly detail'),
  ('bloom_steampunk_flora', 'oil painting, steampunk botanical aesthetic, brass and copper mechanical hybrid, sepia and saturated bloom palette, Victorian industrial elegance', 'oil painting, steampunk botanical aesthetic, brass and copper mechanical hybrid, sepia and saturated bloom palette, Victorian industrial elegance'),
  ('burton_puppet', 'Stop-motion puppet aesthetic, exaggerated spindly proportions, stitched fabric-clay surface, sculpted theatrical features, deep shadows, moody single-source lighting, gothic whimsy.', 'Stop-motion puppet aesthetic, exaggerated spindly proportions, stitched fabric-clay surface, sculpted theatrical features, deep shadows, moody single-source lighting, gothic whimsy.'),
  ('calico_figures', 'Flocked plastic with velvety soft texture, oversized painted features, soft pastel palette, warm diffused lighting, miniature cottagecore aesthetic, tactile wholesome charm.', 'Flocked plastic with velvety soft texture, oversized painted features, soft pastel palette, warm diffused lighting, miniature cottagecore aesthetic, tactile wholesome charm.'),
  ('chibibot_pixar', 'Modern Pixar 3D animation with soft subsurface scattering on fluffy textures, volumetric warm god-rays, shallow depth of field with creamy painterly bokeh, saturated jewel-tone palette of amber, emerald, teal, peach and magenta, stylized cute aesthetic with lush magical detail.', 'Modern Pixar 3D animation with soft subsurface scattering on fluffy textures, volumetric warm god-rays, shallow depth of field with creamy painterly bokeh, saturated jewel-tone palette of amber, emerald, teal, peach and magenta, stylized cute aesthetic with lush magical detail.'),
  ('chibibot_render', 'Hyper-detailed 3D CGI with Octane/Redshift rendering, designer-vinyl glossy finish, subsurface scattering on organic surfaces, ultra-crisp form language with graphic-design pattern work, volumetric warm god-rays, saturated jewel-tone palette of amber, emerald, teal, peach, magenta.', 'Hyper-detailed 3D CGI with Octane/Redshift rendering, designer-vinyl glossy finish, subsurface scattering on organic surfaces, ultra-crisp form language with graphic-design pattern work, volumetric warm god-rays, saturated jewel-tone palette of amber, emerald, teal, peach, magenta.'),
  ('dino_diorama', 'stop-motion practical miniature set, handmade clay environment, real plastic toy materials, tactile mixed-media finish, warm practical lighting on miniature scale', 'stop-motion practical miniature set, handmade clay environment, real plastic toy materials, tactile mixed-media finish, warm practical lighting on miniature scale'),
  ('dollhouse_figures', 'Miniature dollhouse aesthetic, painted porcelain faces, hand-sewn fabric clothing, wooden furniture, warm practical lamp-glow lighting, cozy handcrafted interior ambiance.', 'Miniature dollhouse aesthetic, painted porcelain faces, hand-sewn fabric clothing, wooden furniture, warm practical lamp-glow lighting, cozy handcrafted interior ambiance.'),
  ('earthbot_hyperreal', 'ray-traced cinematic CGI, photoreal physically-based materials, micro-displacement textures, subsurface scattering, volumetric god-rays, mirror-clean reflections, AAA cutscene polish, 8K tack-sharp detail', 'ray-traced cinematic CGI, photoreal physically-based materials, micro-displacement textures, subsurface scattering, volumetric god-rays, mirror-clean reflections, AAA cutscene polish, 8K tack-sharp detail'),
  ('earthbot_seasonal', 'Hyperreal Unreal Engine 5 render with ray-traced global illumination, physically-based materials, volumetric god-rays, teal-and-orange cinematic color grade, hard punched shadows, tack-sharp 8K detail, and atmospheric depth.', 'Hyperreal Unreal Engine 5 render with ray-traced global illumination, physically-based materials, volumetric god-rays, teal-and-orange cinematic color grade, hard punched shadows, tack-sharp 8K detail, and atmospheric depth.'),
  ('gi_joe_figures', 'Posable plastic toy aesthetic, painted military detail, articulated joints visible, battle-worn texture, studio toy photography lighting', 'Posable plastic toy aesthetic, painted military detail, articulated joints visible, battle-worn texture, studio toy photography lighting'),
  ('gothbot_dark_warrior', 'Heavy ink stylization with rich tonal depth, dark gothic atmosphere, Berserk manga brushwork, Castlevania painted character detail, Metal Gear Solid character inking, Brom dark fantasy oil-painting finish, weathered scarred aesthetic.', 'Heavy ink stylization with rich tonal depth, dark gothic atmosphere, Berserk manga brushwork, Castlevania painted character detail, Metal Gear Solid character inking, Brom dark fantasy oil-painting finish, weathered scarred aesthetic.'),
  ('gothbot_gothic_print', 'Hyper-detailed painted illustration with sharp ink linework, theatrical high-contrast lighting, rich tonal depth, gothic-horror promotional-art aesthetic, gallery-print fidelity.', 'Hyper-detailed painted illustration with sharp ink linework, theatrical high-contrast lighting, rich tonal depth, gothic-horror promotional-art aesthetic, gallery-print fidelity.'),
  ('gothic', 'Tim Burton gothic aesthetic, monochromatic blacks and grays with muted purples and deep reds, dramatically elongated skeletal proportions, theatrical shadows and ethereal glows, fluid organic linework, hand-crafted imperfect textures, spiral motifs throughout.', 'Tim Burton gothic aesthetic, monochromatic blacks and grays with muted purples and deep reds, dramatically elongated skeletal proportions, theatrical shadows and ethereal glows, fluid organic linework, hand-crafted imperfect textures, spiral motifs throughout.'),
  ('gothic_architecture', 'Oil-painted stone textures, dramatic moonlight through arches, atmospheric fog, vertical composition, painterly brushwork, ancient awe-inspiring mood, epic architectural grandeur.', 'Oil-painted stone textures, dramatic moonlight through arches, atmospheric fog, vertical composition, painterly brushwork, ancient awe-inspiring mood, epic architectural grandeur.'),
  ('gothic_oil_garden', 'Oil-painted Gothic aesthetic, rich jewel-tone palette of deep purples and crimsons, candlelit atmospheric depth, soft impressionistic brushwork, twilight haze and fog, Victorian romantic decay.', 'Oil-painted Gothic aesthetic, rich jewel-tone palette of deep purples and crimsons, candlelit atmospheric depth, soft impressionistic brushwork, twilight haze and fog, Victorian romantic decay.'),
  ('gothic_painted', 'Gothic oil painting with deep crimson and midnight palette, painterly brushwork on textured canvas, atmospheric fog and candlelight, baroque ornamental detail, classical realism softened by atmospheric haze.', 'Gothic oil painting with deep crimson and midnight palette, painterly brushwork on textured canvas, atmospheric fog and candlelight, baroque ornamental detail, classical realism softened by atmospheric haze.'),
  ('gothic_realistic', 'Gothic realistic, dark moody palette, dramatic chiaroscuro lighting, ornate Victorian aesthetics, shadowy atmospheric rendering, intricate detailed realism, cool desaturated tones, melancholic ambiance', 'Gothic realistic, dark moody palette, dramatic chiaroscuro lighting, ornate Victorian aesthetics, shadowy atmospheric rendering, intricate detailed realism, cool desaturated tones, melancholic ambiance'),
  ('gothic_whimsy', 'Dark moody palette with jewel tones, ornate Victorian gothic aesthetic, whimsical playful spirit, romantic candlelit atmosphere, intricate detailed linework, slightly macabre charming mood', 'Dark moody palette with jewel tones, ornate Victorian gothic aesthetic, whimsical playful spirit, romantic candlelit atmosphere, intricate detailed linework, slightly macabre charming mood'),
  ('hot_wheels', 'Die-cast metal toy finish with chrome accents, glossy paint, oversized wheels, practical-set photography on everyday surfaces, bright commercial lighting with headlight cones, speed-blur and dust effects.', 'Die-cast metal toy finish with chrome accents, glossy paint, oversized wheels, practical-set photography on everyday surfaces, bright commercial lighting with headlight cones, speed-blur and dust effects.'),
  ('maritime_oil_classic', 'Classical oil-on-canvas with Turner-inspired brushwork, dramatic stormy atmosphere, palette knife texture for atmospheric effects, deep maritime color palette, atmospheric perspective and luminous sky treatment.', 'Classical oil-on-canvas with Turner-inspired brushwork, dramatic stormy atmosphere, palette knife texture for atmospheric effects, deep maritime color palette, atmospheric perspective and luminous sky treatment.'),
  ('maritime_oil_legend', 'Baroque oil-on-canvas painting, dark dramatic seascape, atmospheric haze, deep saturated palette, single-source dramatic lighting, painterly brushwork, mythological narrative atmosphere', 'Baroque oil-on-canvas painting, dark dramatic seascape, atmospheric haze, deep saturated palette, single-source dramatic lighting, painterly brushwork, mythological narrative atmosphere'),
  ('maritime_oil_romantic', 'Romantic-era maritime oil painting, soft golden-hour light, warm sunset palette, atmospheric brushwork, dreamy seascape aesthetic', 'Romantic-era maritime oil painting, soft golden-hour light, warm sunset palette, atmospheric brushwork, dreamy seascape aesthetic'),
  ('mech_toys', 'Chrome-plated articulated toy aesthetic with hand-painted weathering, panel-line detailing, glowing cockpit-canopy, metallic reflections, and practical physical model finish.', 'Chrome-plated articulated toy aesthetic with hand-painted weathering, panel-line detailing, glowing cockpit-canopy, metallic reflections, and practical physical model finish.'),
  ('model_train_diorama', 'Miniature die-cast toy train aesthetic, brass and chrome metal finish, lit headlamp glow, practical toy-scale rendering with visible mechanical detail and authentic vintage toy patina.', 'Miniature die-cast toy train aesthetic, brass and chrome metal finish, lit headlamp glow, practical toy-scale rendering with visible mechanical detail and authentic vintage toy patina.'),
  ('painted_fantasy_novel', 'painterly fantasy concept art, expressive brushwork, rich saturated colors, atmospheric lighting', 'painterly fantasy concept art, expressive brushwork, rich saturated colors, atmospheric lighting'),
  ('painted_gothic_fantasy', 'Oil-painted gothic dark-fantasy illustration, dramatic chiaroscuro with deep saturated jewel-tones, painterly brushwork, atmospheric shadow, classic dark-fantasy concept-art lineage.', 'Oil-painted gothic dark-fantasy illustration, dramatic chiaroscuro with deep saturated jewel-tones, painterly brushwork, atmospheric shadow, classic dark-fantasy concept-art lineage.'),
  ('plush_fabric', 'Soft plush fabric with visible knit texture, embroidered details, fiberfill body, warm firelight and golden-hour practical lighting, handcrafted miniature set photography, storybook warmth.', 'Soft plush fabric with visible knit texture, embroidered details, fiberfill body, warm firelight and golden-hour practical lighting, handcrafted miniature set photography, storybook warmth.'),
  ('plush_storytelling_mixed', 'Soft plush-fur fiberfill texture with embroidered details, oversized round-pudgy proportions, floppy fabric limbs, cute huggable toy aesthetic, warm storybook diorama lighting on practical household-object sets.', 'Soft plush-fur fiberfill texture with embroidered details, oversized round-pudgy proportions, floppy fabric limbs, cute huggable toy aesthetic, warm storybook diorama lighting on practical household-object sets.'),
  ('real_astro', 'NASA astrophotography, false-color composite wavelengths, vibrant cyan-magenta-gold nebula clouds with volumetric glow, dense blazing star fields with diffraction spikes, deep black void contrast, saturated scientific deep-space imaging aesthetic.', 'NASA astrophotography, false-color composite wavelengths, vibrant cyan-magenta-gold nebula clouds with volumetric glow, dense blazing star fields with diffraction spikes, deep black void contrast, saturated scientific deep-space imaging aesthetic.'),
  ('shortcake_figures', 'Pastel candy-bright plastic, oversized proportions, glittery accents, soft-focus nostalgic 80s toy aesthetic, strawberry pink and rainbow pastels, cheerful bright lighting.', 'Pastel candy-bright plastic, oversized proportions, glittery accents, soft-focus nostalgic 80s toy aesthetic, strawberry pink and rainbow pastels, cheerful bright lighting.'),
  ('space_saga_figures', 'Hand-painted plastic action figures, vintage Kenner bubble-card finish, molded accessories, limited articulation, photographed physical toys on handcrafted dioramas.', 'Hand-painted plastic action figures, vintage Kenner bubble-card finish, molded accessories, limited articulation, photographed physical toys on handcrafted dioramas.'),
  ('star_oil_cosmos', 'Cosmic oil painting with dramatic celestial lighting, saturated palette of deep blues and purples, painterly brushwork, classical space-art aesthetic, sense of vast scale and awe.', 'Cosmic oil painting with dramatic celestial lighting, saturated palette of deep blues and purples, painterly brushwork, classical space-art aesthetic, sense of vast scale and awe.'),
  ('starbot_cosmic_void', 'Photoreal cinematic sci-fi, ray-traced volumetric lighting in vacuum, hyperrealistic hull materials with lit-window grids and hangar bay details, deep void starfield aesthetic.', 'Photoreal cinematic sci-fi, ray-traced volumetric lighting in vacuum, hyperrealistic hull materials with lit-window grids and hangar bay details, deep void starfield aesthetic.'),
  ('starbot_hyperreal', 'hyperrealistic photoreal cinematic sci-fi, ray-traced volumetric lighting, atmospheric depth, weathered future-tech surfaces, subtle lens flare and bloom, 8K film-still precision, Denis Villeneuve aesthetic', 'hyperrealistic photoreal cinematic sci-fi, ray-traced volumetric lighting, atmospheric depth, weathered future-tech surfaces, subtle lens flare and bloom, 8K film-still precision, Denis Villeneuve aesthetic'),
  ('starbot_space_femme', 'slick chrome-and-neon rendering, vibrant glossy sci-fi illustration, bold saturated electric palette, high-contrast dramatic neon-rim lighting, polished crisp comic-cover finish', 'slick chrome-and-neon rendering, vibrant glossy sci-fi illustration, bold saturated electric palette, high-contrast dramatic neon-rim lighting, polished crisp comic-cover finish'),
  ('steambot-hyperreal', 'Crisp vivid cinematic rendering with rich saturated color, sharp focused detail, painterly illustration with photographic clarity, warm gaslit atmosphere, brass and copper detail, Victorian-industrial aesthetic.', 'Crisp vivid cinematic rendering with rich saturated color, sharp focused detail, painterly illustration with photographic clarity, warm gaslit atmosphere, brass and copper detail, Victorian-industrial aesthetic.'),
  ('steambot-painted-interior', 'Oil-painted illustration with visible brushwork, saturated jewel tones, golden atmospheric lighting, Maxfield Parrish elegance, intricate ornate detail, dramatic cinematic rim light, Victorian-industrial warmth, classic illustration depth.', 'Oil-painted illustration with visible brushwork, saturated jewel tones, golden atmospheric lighting, Maxfield Parrish elegance, intricate ornate detail, dramatic cinematic rim light, Victorian-industrial warmth, classic illustration depth.'),
  ('steambot-painted-man', 'Oil-painted illustration with visible brushwork, lush saturated jewel-toned palette, dramatic golden-hour rim lighting, Frazetta-Vallejo fantasy-cover style, painted finish with cinematic depth.', 'Oil-painted illustration with visible brushwork, lush saturated jewel-toned palette, dramatic golden-hour rim lighting, Frazetta-Vallejo fantasy-cover style, painted finish with cinematic depth.'),
  ('steambot-painted-woman', 'Oil-painted illustration with visible brushwork, jewel-toned saturated pigment, dramatic golden-hour rim lighting, Frazetta-Brom-Vallejo fantasy-cover aesthetic, painterly rendered finish.', 'Oil-painted illustration with visible brushwork, jewel-toned saturated pigment, dramatic golden-hour rim lighting, Frazetta-Brom-Vallejo fantasy-cover aesthetic, painterly rendered finish.'),
  ('stitched', 'Embroidered fabric with raised thread stitching, linen backdrop, warm traditional thread palette, handcrafted folk-art aesthetic, slightly imperfect handmade quality, soft cloth texture.', 'Embroidered fabric with raised thread stitching, linen backdrop, warm traditional thread palette, handcrafted folk-art aesthetic, slightly imperfect handmade quality, soft cloth texture.'),
  ('tabletop_minis', 'Hand-painted resin miniature aesthetic, fine brushwork detail, dramatic single-light highlighting, ornate sculpted base, fantasy tabletop gaming style with intense painted precision and hobbyist craftsmanship.', 'Hand-painted resin miniature aesthetic, fine brushwork detail, dramatic single-light highlighting, ornate sculpted base, fantasy tabletop gaming style with intense painted precision and hobbyist craftsmanship.'),
  ('toybox_chaos_mixed', 'Stop-motion diorama with mixed-medium toys in distinct native materials—plush fabric, vinyl, die-cast chrome, glossy paint, flocked velvet—built from practical household objects, cinematic lighting, tactile toy-scale realism.', 'Stop-motion diorama with mixed-medium toys in distinct native materials—plush fabric, vinyl, die-cast chrome, glossy paint, flocked velvet—built from practical household objects, cinematic lighting, tactile toy-scale realism.'),
  ('vampire_portrait', 'Oil-painted chiaroscuro with pale gothic skin tones, crimson accents, rich glazed brushwork, candlelit shadows, classical Renaissance portrait aesthetic.', 'Oil-painted chiaroscuro with pale gothic skin tones, crimson accents, rich glazed brushwork, candlelit shadows, classical Renaissance portrait aesthetic.'),
  ('yumbot_food', 'Hyper-detailed 3D CGI with painterly illustration fusion, glossy-pearlescent Pop-Mart vinyl finish, dewy subsurface-scattered material, pastel-rainbow palette of blush pink, lavender, mint, peach, cream, baby-blue.', 'Hyper-detailed 3D CGI with painterly illustration fusion, glossy-pearlescent Pop-Mart vinyl finish, dewy subsurface-scattered material, pastel-rainbow palette of blush pink, lavender, mint, peach, cream, baby-blue.')
ON CONFLICT (medium_key) DO UPDATE
  SET clean_flux_fragment = EXCLUDED.clean_flux_fragment,
      clean_directive = EXCLUDED.clean_directive;
