-- Dual-character SPECIAL scene pools (goofy + elegant) for nightly couple dreams.
-- Permanent random-pick pool (like nightly_seeds), dashboard-tunable: cull a bad
-- entry by setting disabled = true with no deploy. Generated by
-- scripts/generate-dual-scenarios.js (~500 per pool, sub-theme buckets).
--   goofy   = random funny scenes (any era / absurd); attire may be a period
--             costume OR "normal scene-appropriate everyday clothes".
--   elegant = pretty, dressed-up couple scenes across all eras; attire = elegant
--             formal/period clothing.
-- The nightly engine loads both pools via _shared/pools/dualScenarioLoader.ts,
-- falling back to the in-code MVP arrays in dual_scenarios.ts if the table is
-- empty/unreachable.

CREATE TABLE IF NOT EXISTS public.dual_scenarios (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pool       text NOT NULL CHECK (pool IN ('goofy', 'elegant')),
  scene      text NOT NULL,
  attire     text NOT NULL,
  category   text,
  disabled   boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dual_scenarios_pool
  ON public.dual_scenarios (pool) WHERE disabled = false;
