-- Single-character SPECIAL scene pools (goofy + elegant) for nightly solo dreams —
-- the single-cast counterpart to dual_scenarios (migration 270). Permanent
-- random-pick pool, dashboard-tunable (cull with disabled = true, no deploy).
-- Generated by scripts/generate-single-scenarios.js (~500 per pool, sub-theme
-- buckets), face-visible + tasteful, the ONE person as the clear portrait subject.
--
-- gender: 'any' (gender-neutral — most of goofy), 'male', or 'female'. At render
-- time a solo dream picks from gender='any' UNION the cast member's own gender,
-- so attire matches (a gown for her, a suit for him) and the body — already
-- gender-locked by the slot pipeline — stays consistent.

CREATE TABLE IF NOT EXISTS public.single_scenarios (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pool       text NOT NULL CHECK (pool IN ('goofy', 'elegant')),
  scene      text NOT NULL,
  attire     text NOT NULL,
  gender     text NOT NULL DEFAULT 'any' CHECK (gender IN ('any', 'male', 'female')),
  category   text,
  disabled   boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_single_scenarios_pool_gender
  ON public.single_scenarios (pool, gender) WHERE disabled = false;
