-- 373_new_realface_mediums.sql
--
-- Captures the five new Real-Face mediums added 2026-07-16/17 (Noir, Vintage,
-- Overlay/double_exposure, Glamour/hyperreal-rework, Heirloom) with their final
-- prompts, flags (public + nightly cast + nightly scene), and DreamSmart
-- curation (client_meta.smart_dream_models from the model sweep). Also: the
-- comics/pop_art realistic-face fragment, and engine_config.dream_art_share = 0
-- (Dream-Art drawn-as-character disabled for nightly; cast dreams are Real-Face
-- only). Applied live; this reproduces it on a fresh DB. Re-runnable (upsert).
--
-- Apply in the Supabase dashboard SQL editor.

INSERT INTO public.dream_mediums (key, label, description, directive, flux_fragment, kontext_directive, face_swap_flux_fragment, face_swaps, character_render_mode, is_active, is_public, is_dream_eligible, is_scene_eligible, is_scene_only, is_character_only, is_bot_only, preferred_model, allowed_models, scene_eligible_models, client_meta, sort_order)
VALUES
  ($md$film_noir$md$, $md$Noir$md$, $md$Moody black & white$md$, $md$Render as a dramatic black-and-white film noir photograph: rich high-contrast monochrome with deep inky blacks and luminous bright highlights, bold directional chiaroscuro lighting that sculpts the subject with hard light and deep shadow, a moody, mysterious, atmospheric 1940s-50s cinematic noir mood. Fine photographic grain and dramatic tonal depth, timeless and elegant. Keep every face true-to-life and lifelike within the monochrome: a real photograph, never an illustration.$md$, $md$dramatic black and white film noir photograph, rich high-contrast monochrome, deep inky blacks and luminous highlights, bold directional chiaroscuro lighting, hard light and deep shadow, moody atmospheric 1940s cinematic noir mood, fine film grain, dramatic tonal depth, lifelike photographic faces$md$, $md$Convert this photo into a dramatic black-and-white film noir photograph while keeping the person exact same face, identity, age, gender, expression, pose, and framing. Apply rich high-contrast monochrome, bold chiaroscuro lighting and deep shadows across the whole image, keeping the face true-to-life.$md$, NULL, true, $md$natural$md$, true, true, true, true, false, false, false, $md$black-forest-labs/flux-1.1-pro$md$, ARRAY[$md$google/gemini-2-image$md$]::text[], NULL, $md${"smart_dream_models":["black-forest-labs/flux-2-max","google/gemini-2-image","google/gemini-3-image-preview"],"smart_dream_default":"google/gemini-3-image-preview"}$md$::jsonb, 2),
  ($md$vintage_film$md$, $md$Vintage$md$, $md$Faded film grain$md$, $md$Render as a nostalgic vintage analog film photograph: shot on 35mm or Polaroid, warm faded color, soft film grain, gentle halation and bloom on the highlights, subtle light leaks, slightly muted contrast, and a dreamy 1970s home-movie feel. Aged color cast and soft edges, the cherished look of an old family photo. Keep every face true-to-life and lifelike: a real analog photograph, never an illustration.$md$, $md$nostalgic vintage analog film photograph, 35mm and Polaroid look, warm faded color, soft film grain, gentle halation and light leaks, muted contrast, dreamy 1970s home-movie feel, aged color cast, lifelike photographic faces$md$, $md$Convert this photo into a nostalgic vintage analog film photograph while keeping the person exact same face, identity, age, gender, expression, pose, and framing. Apply warm faded color, soft film grain, gentle halation and light leaks across the image, keeping the face true-to-life.$md$, NULL, true, $md$natural$md$, true, true, true, true, false, false, false, $md$black-forest-labs/flux-1.1-pro$md$, ARRAY[$md$black-forest-labs/flux-1.1-pro$md$, $md$black-forest-labs/flux-2-pro$md$, $md$google/gemini-2-image$md$, $md$openai/gpt-image-2$md$]::text[], NULL, $md${"smart_dream_models":["black-forest-labs/flux-1.1-pro","black-forest-labs/flux-2-max","black-forest-labs/flux-2-pro","google/gemini-2-image","google/gemini-3-image-preview","openai/gpt-image-2"],"smart_dream_default":"black-forest-labs/flux-2-max"}$md$::jsonb, 3),
  ($md$double_exposure$md$, $md$Overlay$md$, $md$Double Exposure$md$, $md$Render as an artistic double-exposure photograph: the subject portrait or silhouette blended with a second image layered inside it (a landscape, forest, cityscape, or sky), the two exposures merging where light and shadow meet. Photographic, elegant, high-contrast, gallery-print quality. The face and silhouette stay clearly readable and true-to-life while the secondary scene fills the darker or lighter regions. A real photographic double exposure, never an illustration.$md$, $md$artistic double exposure photograph, portrait silhouette blended with a layered landscape or cityscape inside it, two exposures merging in light and shadow, elegant high-contrast, gallery-print quality, lifelike clearly-readable face$md$, $md$Convert this photo into an artistic double-exposure photograph while keeping the person exact same face, identity, age, gender, expression, pose, and framing. Blend a secondary landscape or cityscape into the silhouette, keeping the face clearly readable and true-to-life.$md$, NULL, true, $md$natural$md$, true, true, true, true, false, false, false, $md$black-forest-labs/flux-1.1-pro$md$, ARRAY[$md$black-forest-labs/flux-2-pro$md$, $md$openai/gpt-image-2$md$]::text[], NULL, $md${"smart_dream_models":["black-forest-labs/flux-2-max","black-forest-labs/flux-2-pro","google/gemini-2-image","google/gemini-3-image-preview","openai/gpt-image-2"],"smart_dream_default":"google/gemini-3-image-preview"}$md$::jsonb, 4),
  ($md$glamour$md$, $md$Glamour$md$, $md$Soft-focus glamour$md$, $md$Render as a dreamy glamour-shot portrait: the soft-focus, luminous, romantic style of a classic glamour studio photograph. Flattering beauty lighting with a gentle glow, a soft-focus dreamy backdrop, luminous airbrushed skin, radiant highlights and a warm sensual haze, voluminous styling, an idealized camera-loves-you feel with high-gloss beauty-cover polish. Keep the face true-to-life and lifelike: flattering but recognizably the same person, a real glamorous photograph, never an illustration.$md$, $md$dreamy glamour-shot portrait, soft-focus luminous beauty lighting, romantic glowing haze, airbrushed radiant skin, flattering high-gloss beauty-cover polish, dreamy soft backdrop, glamorous idealized studio photograph, lifelike recognizable face$md$, $md$Convert this photo into a dreamy glamour-shot portrait while keeping the person exact same face, identity, age, gender, expression, pose, and framing. Apply soft-focus luminous beauty lighting, a romantic glowing haze, and radiant airbrushed skin, keeping the face flattering but true-to-life.$md$, NULL, true, $md$natural$md$, true, true, true, true, false, false, false, NULL, ARRAY[$md$black-forest-labs/flux-1.1-pro$md$, $md$black-forest-labs/flux-2-pro$md$, $md$google/gemini-2-image$md$, $md$openai/gpt-image-2$md$]::text[], ARRAY[$md$black-forest-labs/flux-1.1-pro$md$, $md$black-forest-labs/flux-1.1-pro-ultra$md$, $md$black-forest-labs/flux-2-max$md$, $md$google/gemini-2-image$md$, $md$openai/gpt-image-2$md$]::text[], $md${"restyle_enabled":false,"recommended_models":["black-forest-labs/flux-2-max","black-forest-labs/flux-2-pro","google/gemini-3-image-preview","openai/gpt-image-2","black-forest-labs/flux-1.1-pro"],"smart_dream_models":["black-forest-labs/flux-1.1-pro","black-forest-labs/flux-2-max","black-forest-labs/flux-2-pro","google/gemini-2-image","google/gemini-3-image-preview","openai/gpt-image-2"],"smart_dream_default":"black-forest-labs/flux-2-max"}$md$::jsonb, 100),
  ($md$heirloom$md$, $md$Heirloom$md$, $md$Warm sepia tone$md$, $md$Render as a warm sepia-toned antique photograph: rich amber and warm-brown monochrome tones, the tender nostalgic look of a treasured old family photograph. Aged photo-paper texture, soft gentle contrast, a faint vignette, delicate warmth and a timeless heirloom feel. Keep every face true-to-life and lifelike within the warm monochrome: a real aged photograph, never an illustration.$md$, $md$warm sepia-toned antique photograph, rich amber and warm-brown monochrome, aged photo-paper texture, soft gentle contrast, faint vignette, tender nostalgic treasured-heirloom look, timeless old family photo, lifelike true-to-life faces$md$, $md$Convert this photo into a warm sepia-toned antique photograph while keeping the person exact same face, identity, age, gender, expression, pose, and framing. Apply rich amber and warm-brown monochrome tones, aged photo-paper texture and a soft vignette across the image, keeping the face true-to-life.$md$, NULL, true, $md$natural$md$, true, true, true, true, false, false, false, $md$black-forest-labs/flux-1.1-pro$md$, ARRAY[$md$black-forest-labs/flux-1.1-pro$md$, $md$black-forest-labs/flux-2-pro$md$, $md$google/gemini-2-image$md$, $md$openai/gpt-image-2$md$]::text[], NULL, $md${"smart_dream_models":["black-forest-labs/flux-1.1-pro","black-forest-labs/flux-2-max","black-forest-labs/flux-2-pro","google/gemini-2-image","google/gemini-3-image-preview","openai/gpt-image-2"],"smart_dream_default":"google/gemini-2-image"}$md$::jsonb, 5)
ON CONFLICT (key) DO UPDATE SET
  label = EXCLUDED.label,
  description = EXCLUDED.description,
  directive = EXCLUDED.directive,
  flux_fragment = EXCLUDED.flux_fragment,
  kontext_directive = EXCLUDED.kontext_directive,
  face_swap_flux_fragment = EXCLUDED.face_swap_flux_fragment,
  face_swaps = EXCLUDED.face_swaps,
  character_render_mode = EXCLUDED.character_render_mode,
  is_active = EXCLUDED.is_active,
  is_public = EXCLUDED.is_public,
  is_dream_eligible = EXCLUDED.is_dream_eligible,
  is_scene_eligible = EXCLUDED.is_scene_eligible,
  is_scene_only = EXCLUDED.is_scene_only,
  is_character_only = EXCLUDED.is_character_only,
  is_bot_only = EXCLUDED.is_bot_only,
  preferred_model = EXCLUDED.preferred_model,
  allowed_models = EXCLUDED.allowed_models,
  scene_eligible_models = EXCLUDED.scene_eligible_models,
  client_meta = EXCLUDED.client_meta,
  sort_order = EXCLUDED.sort_order;

-- Comics + Pop Art: realistic-face fragment (keeps the swapped face lifelike
-- within the graphic style).
UPDATE public.dream_mediums SET face_swap_flux_fragment = $md$realistic human face with natural adult proportions and lifelike features, true-to-life skin, eyes and expression, cleanly integrated with confident comic inking and subtle cel shading, no heavy halftone dots on the face; the rest of the scene in full comic-book style$md$ WHERE key = $md$comics$md$;
UPDATE public.dream_mediums SET face_swap_flux_fragment = $md$realistic human face with natural adult proportions and lifelike features, true-to-life skin, eyes and expression, kept photographic and recognizable; bold pop-art screen-print color and Ben-Day dots on the background and clothing, not on the face$md$ WHERE key = $md$pop_art$md$;

-- Nightly Dream-Art (drawn-as-character) disabled: cast-photo nightly dreams
-- use Real-Face mediums only.
UPDATE public.engine_config SET dream_art_share = 0 WHERE id = 1;
