-- 459: Holiday POSTCARD overlay — decorative "Happy Halloween" / "Merry Christmas" lettering
-- composited onto the day-of hero render so it lands like a holiday postcard (Kevin 2026-09-04).
--
-- Per-holiday artwork + layout live on the catalog row (dashboard-tunable, no deploy):
--   postcard_overlay_url  transparent PNG (ornate lettering + ornaments), generated by
--                         scripts/gen-holiday-postcard.mjs and stored under uploads/assets/holiday/
--   postcard_anchor       'bottom' | 'top'      where the banner sits
--   postcard_width_pct    banner width as % of the render width (aspect preserved)
--   postcard_margin_pct   breathing room from the anchored edge, % of render height
--   postcard_scrim        soft dark vignette behind the banner so it reads on bright scenes
-- The compositing runs in the SEPARATE `holiday-postcard` Edge Function (pure RGBA math in
-- _shared/postcardComposite.ts), called synchronously by nightly-dreams right after the
-- render is persisted; any failure leaves the clean image (never a broken dream).
--
-- Scope switch (engine_config): holiday_postcard_scope
--   'off'     never
--   'day_of'  the day-of hero only (default — "Happy Halloween" belongs on Halloween)
--   'window'  every in-season holiday dream

ALTER TABLE public.holidays
  ADD COLUMN IF NOT EXISTS postcard_overlay_url text,
  ADD COLUMN IF NOT EXISTS postcard_anchor      text NOT NULL DEFAULT 'bottom',
  ADD COLUMN IF NOT EXISTS postcard_width_pct   int  NOT NULL DEFAULT 82,
  ADD COLUMN IF NOT EXISTS postcard_margin_pct  int  NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS postcard_scrim       boolean NOT NULL DEFAULT true;

ALTER TABLE public.holidays DROP CONSTRAINT IF EXISTS holidays_postcard_chk;
ALTER TABLE public.holidays ADD CONSTRAINT holidays_postcard_chk CHECK (
  postcard_anchor IN ('top', 'bottom')
  AND postcard_width_pct BETWEEN 20 AND 100
  AND postcard_margin_pct BETWEEN 0 AND 30
);

COMMENT ON COLUMN public.holidays.postcard_overlay_url IS
  'Transparent PNG composited onto day-of hero renders (holiday-postcard edge fn). NULL = no postcard for this holiday.';

ALTER TABLE public.engine_config
  ADD COLUMN IF NOT EXISTS holiday_postcard_scope text NOT NULL DEFAULT 'day_of';
ALTER TABLE public.engine_config DROP CONSTRAINT IF EXISTS engine_config_holiday_postcard_scope_chk;
ALTER TABLE public.engine_config ADD CONSTRAINT engine_config_holiday_postcard_scope_chk
  CHECK (holiday_postcard_scope IN ('off', 'day_of', 'window'));

COMMENT ON COLUMN public.engine_config.holiday_postcard_scope IS
  'Which holiday dreams get the postcard overlay: off | day_of (hero only, default) | window (every in-season holiday dream).';

SELECT key, postcard_overlay_url, postcard_anchor, postcard_width_pct, postcard_margin_pct, postcard_scrim
FROM public.holidays ORDER BY sort_order;
