-- 478 — Holiday DAY-OF LOOKS (HOLIDAY_DAY_OF_PLAN.md §5d; the NIGHTLY_LOOKS_FEASIBILITY.md pilot).
-- Kevin 2026-09-08: "may as well do both" — (1) the day-of never rolls photography, (2) the day-of draws
-- its medium from a curated per-holiday LOOK set (the six hero-look matrix fragments), each look a
-- dream_mediums row in a reserved namespace the app never lists (is_public=false, is_dream_eligible=false,
-- is_scene_eligible=false, nightly_skip=true — the day-of PINS it by key; the normal rolls never see it),
-- with per-look model membership in client_meta.smart_dream_models (the matrix: F3 polished digital
-- painting failed twice on flux-1.1-pro → excluded there; everything else clean on all five models).
-- uploads.dream_medium = the look key (FK), so Dream Again / DLT / analytics keep working; the client
-- shows the prettified key ("Halloween Storybook Gouache") because get_dream_mediums is public-only.
ALTER TABLE public.holidays
  ADD COLUMN IF NOT EXISTS day_of_look_keys text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS day_of_medium_ban text NOT NULL DEFAULT 'photography';
COMMENT ON COLUMN public.holidays.day_of_look_keys IS
  'DAY-OF LOOKS: dream_mediums keys the day-of cast render pins (one rolled per render; model re-picked from the look''s smart_dream_models). Empty = normal roll minus day_of_medium_ban.';
COMMENT ON COLUMN public.holidays.day_of_medium_ban IS
  'Comma list of medium keys a day-of render never rolls (cast renders when no look resolves, and scene-only renders). Default photography.';

INSERT INTO public.dream_mediums
  (key, label, description, directive, flux_fragment, face_swap_flux_fragment, sort_order, allowed_models, preferred_model, client_meta,
   is_active, is_public, is_dream_eligible, is_scene_eligible, is_scene_only, is_character_only, is_bot_only, nightly_skip, face_swaps, character_render_mode)
SELECT v.key, v.label, v.description, v.directive, v.flux_fragment, v.face_swap_flux_fragment, v.sort_order, v.allowed_models, v.preferred_model, v.client_meta,
       true, false, false, false, false, false, false, true, true, 'natural'
FROM (VALUES
  ('halloween_watercolor_ink', 'Halloween Watercolor Ink', 'Loose watercolor and ink, luminous washes', 'loose watercolor and ink painting with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, transparent pigment washes on textured watercolor paper, soft feathered bleeding edges, visible brushstrokes and fine ink linework, a luminous watercolor palette taking its colours from the scene, naturalistic mature features, painterly realism', 'loose watercolor and ink painting with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, transparent pigment washes on textured watercolor paper, soft feathered bleeding edges, visible brushstrokes and fine ink linework, a luminous watercolor palette taking its colours from the scene, naturalistic mature features, painterly realism', 'loose watercolor and ink painting with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, transparent pigment washes on textured watercolor paper, soft feathered bleeding edges, visible brushstrokes and fine ink linework, a luminous watercolor palette taking its colours from the scene, naturalistic mature features, painterly realism', 900, ARRAY['black-forest-labs/flux-1.1-pro','black-forest-labs/flux-2-flex','google/gemini-2-image','bytedance/seedream-4','xai/grok-imagine-image']::text[], 'black-forest-labs/flux-1.1-pro', '{"day_of_look":true,"smart_dream_models":["black-forest-labs/flux-1.1-pro","black-forest-labs/flux-2-flex","google/gemini-2-image","bytedance/seedream-4","xai/grok-imagine-image"],"smart_dream_default":"black-forest-labs/flux-1.1-pro","recommended_models":["black-forest-labs/flux-1.1-pro","black-forest-labs/flux-2-flex","google/gemini-2-image","bytedance/seedream-4","xai/grok-imagine-image"]}'::jsonb),
  ('halloween_ornate_ink', 'Halloween Ornate Ink', 'Crisp ornate ink illustration, rich color', 'crisp ink illustration with bold confident linework and lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, clean intricate line art, rich saturated color, masterwork hand-drawn editorial illustration, naturalistic mature features, illustrated realism, gallery-quality detailed drawing', 'crisp ink illustration with bold confident linework and lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, clean intricate line art, rich saturated color, masterwork hand-drawn editorial illustration, naturalistic mature features, illustrated realism, gallery-quality detailed drawing', 'crisp ink illustration with bold confident linework and lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, clean intricate line art, rich saturated color, masterwork hand-drawn editorial illustration, naturalistic mature features, illustrated realism, gallery-quality detailed drawing', 901, ARRAY['black-forest-labs/flux-1.1-pro','black-forest-labs/flux-2-flex','google/gemini-2-image','bytedance/seedream-4','xai/grok-imagine-image']::text[], 'black-forest-labs/flux-1.1-pro', '{"day_of_look":true,"smart_dream_models":["black-forest-labs/flux-1.1-pro","black-forest-labs/flux-2-flex","google/gemini-2-image","bytedance/seedream-4","xai/grok-imagine-image"],"smart_dream_default":"black-forest-labs/flux-1.1-pro","recommended_models":["black-forest-labs/flux-1.1-pro","black-forest-labs/flux-2-flex","google/gemini-2-image","bytedance/seedream-4","xai/grok-imagine-image"]}'::jsonb),
  ('halloween_digital_painting', 'Halloween Digital Painting', 'Polished digital painting, concept-art finish', 'polished digital painting, professional concept art, high-quality digital artwork, smooth painterly surfaces with crisp detail, vibrant saturated colors, masterful digital art with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, fine art digital painting', 'polished digital painting, professional concept art, high-quality digital artwork, smooth painterly surfaces with crisp detail, vibrant saturated colors, masterful digital art with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, fine art digital painting', 'polished digital painting, professional concept art, high-quality digital artwork, smooth painterly surfaces with crisp detail, vibrant saturated colors, masterful digital art with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, fine art digital painting', 902, ARRAY['black-forest-labs/flux-2-flex','google/gemini-2-image','bytedance/seedream-4','xai/grok-imagine-image']::text[], 'black-forest-labs/flux-2-flex', '{"day_of_look":true,"smart_dream_models":["black-forest-labs/flux-2-flex","google/gemini-2-image","bytedance/seedream-4","xai/grok-imagine-image"],"smart_dream_default":"black-forest-labs/flux-2-flex","recommended_models":["black-forest-labs/flux-2-flex","google/gemini-2-image","bytedance/seedream-4","xai/grok-imagine-image"]}'::jsonb),
  ('halloween_dark_fantasy_oil', 'Halloween Dark Fantasy Oil', 'Dark-fantasy oil, chiaroscuro, jewel tones', 'painted dark-fantasy concept art with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, oil-painted brushwork, dramatic chiaroscuro, deep saturated jewel tones with painted shadow, atmospheric gothic illustration, rich painterly texture, dark-paperback-cover mood', 'painted dark-fantasy concept art with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, oil-painted brushwork, dramatic chiaroscuro, deep saturated jewel tones with painted shadow, atmospheric gothic illustration, rich painterly texture, dark-paperback-cover mood', 'painted dark-fantasy concept art with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, oil-painted brushwork, dramatic chiaroscuro, deep saturated jewel tones with painted shadow, atmospheric gothic illustration, rich painterly texture, dark-paperback-cover mood', 903, ARRAY['black-forest-labs/flux-1.1-pro','black-forest-labs/flux-2-flex','google/gemini-2-image','bytedance/seedream-4','xai/grok-imagine-image']::text[], 'black-forest-labs/flux-1.1-pro', '{"day_of_look":true,"smart_dream_models":["black-forest-labs/flux-1.1-pro","black-forest-labs/flux-2-flex","google/gemini-2-image","bytedance/seedream-4","xai/grok-imagine-image"],"smart_dream_default":"black-forest-labs/flux-1.1-pro","recommended_models":["black-forest-labs/flux-1.1-pro","black-forest-labs/flux-2-flex","google/gemini-2-image","bytedance/seedream-4","xai/grok-imagine-image"]}'::jsonb),
  ('halloween_storybook_gouache', 'Halloween Storybook Gouache', 'Gouache and ink Halloween picture-book plate', 'rich gouache and ink storybook painting with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, luminous jack-o-lantern glow against inky violet and black shadows, painterly textured brushwork, whimsical spooky illustrated realism, warm candle light on the faces, hand-painted Halloween picture-book plate', 'rich gouache and ink storybook painting with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, luminous jack-o-lantern glow against inky violet and black shadows, painterly textured brushwork, whimsical spooky illustrated realism, warm candle light on the faces, hand-painted Halloween picture-book plate', 'rich gouache and ink storybook painting with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, luminous jack-o-lantern glow against inky violet and black shadows, painterly textured brushwork, whimsical spooky illustrated realism, warm candle light on the faces, hand-painted Halloween picture-book plate', 904, ARRAY['black-forest-labs/flux-1.1-pro','black-forest-labs/flux-2-flex','google/gemini-2-image','bytedance/seedream-4','xai/grok-imagine-image']::text[], 'black-forest-labs/flux-1.1-pro', '{"day_of_look":true,"smart_dream_models":["black-forest-labs/flux-1.1-pro","black-forest-labs/flux-2-flex","google/gemini-2-image","bytedance/seedream-4","xai/grok-imagine-image"],"smart_dream_default":"black-forest-labs/flux-1.1-pro","recommended_models":["black-forest-labs/flux-1.1-pro","black-forest-labs/flux-2-flex","google/gemini-2-image","bytedance/seedream-4","xai/grok-imagine-image"]}'::jsonb),
  ('halloween_classical_oil', 'Halloween Classical Oil', 'Classical oil on canvas, warm chiaroscuro', 'classical oil painting with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, smooth refined brushwork, softly blended tones, rich luminous color, warm chiaroscuro lighting, smooth glazed skin, clean clearly-readable features, elegant oil-on-canvas finish', 'classical oil painting with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, smooth refined brushwork, softly blended tones, rich luminous color, warm chiaroscuro lighting, smooth glazed skin, clean clearly-readable features, elegant oil-on-canvas finish', 'classical oil painting with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, smooth refined brushwork, softly blended tones, rich luminous color, warm chiaroscuro lighting, smooth glazed skin, clean clearly-readable features, elegant oil-on-canvas finish', 905, ARRAY['black-forest-labs/flux-1.1-pro','black-forest-labs/flux-2-flex','google/gemini-2-image','bytedance/seedream-4','xai/grok-imagine-image']::text[], 'black-forest-labs/flux-1.1-pro', '{"day_of_look":true,"smart_dream_models":["black-forest-labs/flux-1.1-pro","black-forest-labs/flux-2-flex","google/gemini-2-image","bytedance/seedream-4","xai/grok-imagine-image"],"smart_dream_default":"black-forest-labs/flux-1.1-pro","recommended_models":["black-forest-labs/flux-1.1-pro","black-forest-labs/flux-2-flex","google/gemini-2-image","bytedance/seedream-4","xai/grok-imagine-image"]}'::jsonb)
) AS v(key, label, description, directive, flux_fragment, face_swap_flux_fragment, sort_order, allowed_models, preferred_model, client_meta)
ON CONFLICT (key) DO UPDATE SET
  label = EXCLUDED.label, description = EXCLUDED.description, directive = EXCLUDED.directive,
  flux_fragment = EXCLUDED.flux_fragment, face_swap_flux_fragment = EXCLUDED.face_swap_flux_fragment,
  sort_order = EXCLUDED.sort_order, allowed_models = EXCLUDED.allowed_models, preferred_model = EXCLUDED.preferred_model,
  client_meta = EXCLUDED.client_meta, is_active = true, is_public = false, is_dream_eligible = false,
  is_scene_eligible = false, nightly_skip = true, face_swaps = true, character_render_mode = 'natural';

UPDATE public.holidays
SET day_of_look_keys = ARRAY['halloween_watercolor_ink', 'halloween_ornate_ink', 'halloween_digital_painting', 'halloween_dark_fantasy_oil', 'halloween_storybook_gouache', 'halloween_classical_oil']::text[]
WHERE key = 'halloween';
