-- 498_nightly_look_approvals.sql — the approval matrix as DATA (Kevin 2026-09-12: "we can go with that and come up
-- with a clean architecture that lets each nightly choose from the pool of models and looks based on if it's a dual
-- or single character dream").
--
-- One row per (look × model × surface) graded in the fixed-scene matrix (NIGHTLY_LOOK_TALLY.md rounds 1-3; verdicts
-- by eye per surface; `source = 'override'` = Kevin's call). The nightly resolver (NIGHTLY_LOOKS_REFACTOR_PLAN.md
-- §2) will pick the MODEL from nightly_model_policy for the render's surface, then roll a LOOK from
--   SELECT look_key FROM nightly_look_approvals WHERE model = <picked> AND surface = <couple|solo> AND approved
-- so a dual dream and a single dream each draw from their own (model × look) pool. `dream_mediums.nightly_surfaces`
-- stays as the model-agnostic UNION (used by the pin route + the QA runner) and is refreshed from this table here.
-- Regenerate rows after any future matrix round: `node scripts/qa-nightly-looks-compare.js --registry` writes the
-- doc; this table is the runtime copy of the same grades (a future script can emit the INSERT block).
CREATE TABLE IF NOT EXISTS public.nightly_look_approvals (
  look_key   text NOT NULL REFERENCES public.dream_mediums(key) ON DELETE CASCADE,
  model      text NOT NULL,
  surface    text NOT NULL CHECK (surface IN ('couple','solo')),
  approved   boolean NOT NULL DEFAULT false,
  source     text NOT NULL DEFAULT 'matrix' CHECK (source IN ('matrix','override')),
  note       text,
  graded_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (look_key, model, surface)
);
ALTER TABLE public.nightly_look_approvals ENABLE ROW LEVEL SECURITY;
-- Engine-only table: no client policies (service role bypasses RLS). Read by the nightly render and QA scripts.
GRANT SELECT ON public.nightly_look_approvals TO service_role;

INSERT INTO public.nightly_look_approvals (look_key, model, surface, approved, source, note) VALUES
  ('nightly_classical_oil', 'black-forest-labs/flux-1.1-pro', 'couple', true, 'matrix', ''),
  ('nightly_classical_oil', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', ''),
  ('nightly_digital_painting', 'black-forest-labs/flux-1.1-pro', 'couple', true, 'matrix', 'Frames the couple wide; faces smaller.'),
  ('nightly_digital_painting', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', ''),
  ('nightly_painted_fantasy', 'black-forest-labs/flux-1.1-pro', 'couple', true, 'matrix', ''),
  ('nightly_painted_fantasy', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Costume drift (frock coats), face fine.'),
  ('nightly_watercolor_ink', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Photo faces pasted on a watercolor world; couple #2 bodies dissolve into the path.'),
  ('nightly_watercolor_ink', 'black-forest-labs/flux-1.1-pro', 'solo', false, 'matrix', 'Solo #2 came back as an older white-bearded man, not Kevin. Solo #1 greyed the hair.'),
  ('nightly_ink_illustration', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Both couples collapsed to faceless scenes (no people at all).'),
  ('nightly_ink_illustration', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Face fine; the ink look barely shows.'),
  ('nightly_storybook_gouache', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #1 bobblehead caricatures; couple #2 a faceless scene.'),
  ('nightly_storybook_gouache', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', ''),
  ('nightly_film_noir', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #2 lost her: Kevin alone with odd selective color.'),
  ('nightly_film_noir', 'black-forest-labs/flux-1.1-pro', 'solo', false, 'matrix', 'Solo #2 came back as an older grey-bearded man, not Kevin.'),
  ('nightly_vintage_film', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #1 rendered Kevin as an older grey-haired man. Couple #2 is lovely.'),
  ('nightly_vintage_film', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', ''),
  ('nightly_baroque_oil', 'black-forest-labs/flux-1.1-pro', 'couple', true, 'matrix', ''),
  ('nightly_baroque_oil', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', ''),
  ('nightly_salon_realism', 'black-forest-labs/flux-1.1-pro', 'couple', true, 'matrix', ''),
  ('nightly_salon_realism', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', ''),
  ('nightly_jewel_realism', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #1 collapsed to a faceless scene of the wrong place.'),
  ('nightly_jewel_realism', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', ''),
  ('nightly_magazine_cover', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #2 lost her: Kevin alone. Couple #1 stiff.'),
  ('nightly_magazine_cover', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Reads as a plain photo; weak as a look.'),
  ('nightly_movie_poster', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Both couples turned to face each other in profile; faces too small to swap.'),
  ('nightly_movie_poster', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', ''),
  ('nightly_scifi_paperback', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Both couples lost her: Kevin alone.'),
  ('nightly_scifi_paperback', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Solo #2 shrank him into a wide vista.'),
  ('nightly_matte_painting', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Both couples lost her: the sweeping scene shrinks the people.'),
  ('nightly_matte_painting', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Scene-heavy framing.'),
  ('nightly_pulp_cover', 'black-forest-labs/flux-1.1-pro', 'couple', true, 'override', 'Kevin override 2026-09-12: pass for couples (couple #1 landed; #2 degraded to a well-rendered solo).'),
  ('nightly_pulp_cover', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', ''),
  ('nightly_fresco', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #1 bobbleheads; couple #2 giant floating heads.'),
  ('nightly_fresco', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Solo #1 is a plain photo with the wrong hair; the fresco look disappears.'),
  ('nightly_pastel_chalk', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #2 giant floating heads; couple #1 her hair drifted blonde.'),
  ('nightly_pastel_chalk', 'black-forest-labs/flux-1.1-pro', 'solo', false, 'matrix', 'Solo #1 came back as an older grey-bearded man, not Kevin.'),
  ('nightly_alla_prima', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #1 lost her: Kevin alone.'),
  ('nightly_alla_prima', 'black-forest-labs/flux-1.1-pro', 'solo', false, 'matrix', 'Solo #1 came back as an older grey-bearded man, not Kevin.'),
  ('nightly_cinematic_still', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #1 profiles facing each other at the table. Couple #2 is the best photo in the set.'),
  ('nightly_cinematic_still', 'black-forest-labs/flux-1.1-pro', 'solo', false, 'matrix', 'Solo #1 came back as an older grey-bearded man, not Kevin.'),
  ('nightly_kodachrome', 'black-forest-labs/flux-1.1-pro', 'couple', true, 'matrix', 'Her hair went curly-blonde in #1; faces fine.'),
  ('nightly_kodachrome', 'black-forest-labs/flux-1.1-pro', 'solo', false, 'matrix', 'Solo #1 came back as an older grey-bearded man, not Kevin.'),
  ('nightly_hand_tinted_photo', 'black-forest-labs/flux-1.1-pro', 'couple', true, 'matrix', ''),
  ('nightly_hand_tinted_photo', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', ''),
  ('nightly_chromolithograph', 'black-forest-labs/flux-1.1-pro', 'couple', true, 'matrix', ''),
  ('nightly_chromolithograph', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', ''),
  ('nightly_oil_pastel', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #2 profiles facing each other.'),
  ('nightly_oil_pastel', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Solo #1 is a plain photo; the pastel look shows only on #2.'),
  ('nightly_technicolor', 'black-forest-labs/flux-1.1-pro', 'couple', true, 'matrix', ''),
  ('nightly_technicolor', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', ''),
  ('nightly_encaustic', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #1 giant floating heads; couple #2 bobbleheads.'),
  ('nightly_encaustic', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', ''),
  ('nightly_painted_comic_cover', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #2 profiles facing each other with small faces. Couple #1 landed and reads as a painted cover.'),
  ('nightly_painted_comic_cover', 'black-forest-labs/flux-1.1-pro', 'solo', false, 'matrix', 'Solo #1 came back as an older grey-bearded man. Solo #2 natural and integrated.'),
  ('nightly_soft_comic', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Both couples turned into profiles facing each other; faces too small to swap.'),
  ('nightly_soft_comic', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Both natural and integrated; the comic look softens into photo-illustration.'),
  ('nightly_rotoscope', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #1 became an integrated big-head caricature with real faces (a Big Head hit, not a rotoscope); couple #2 3D-animated figures in profile.'),
  ('nightly_rotoscope', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Solo #1 photoreal (look absent); solo #2 a fun mild big-head figure with a real face.'),
  ('nightly_painted_animation', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #1 profiles facing each other. Couple #2 landed, painted and natural.'),
  ('nightly_painted_animation', 'black-forest-labs/flux-1.1-pro', 'solo', false, 'matrix', 'Solo #2 came back as an older grey-bearded man. Solo #1 natural.'),
  ('nightly_airbrush_poster', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #2 collapsed into a surreal giant face over a birch forest with a tiny couple. Couple #1 is a genuinely distinct airbrushed poster portrait.'),
  ('nightly_airbrush_poster', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Both natural, integrated; reads photographic rather than airbrushed.'),
  ('nightly_marker', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Both couples became marker caricatures with big heads; her face is drawn, not swapped. Promising as a deliberate caricature/Big Head look, not as a real-face look.'),
  ('nightly_marker', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Solo #1 a real marker illustration with a recognizable face; solo #2 photoreal.'),
  ('nightly_ink_wash_comic', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #1 bobblehead caricature with approximate faces. Couple #2 (retried) landed as a genuine ink-wash illustration, natural and integrated: half-way there.'),
  ('nightly_ink_wash_comic', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Both good: ink-wash illustration and a painted variant, faces natural.'),
  ('nightly_soft_pop_art', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Both couples rendered as giant floating heads over the scene.'),
  ('nightly_soft_pop_art', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Both natural; no pop-art look survives.'),
  ('nightly_lineless_watercolor', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #1 giant floating heads; couple #2 a surreal giant face with a swing.'),
  ('nightly_lineless_watercolor', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Both real watercolor paintings, natural and integrated; the most watercolor-like solo in the set.'),
  ('nightly_watercolor_portrait', 'black-forest-labs/flux-1.1-pro', 'couple', true, 'matrix', 'Both couples landed facing camera in painted watercolor realism; wardrobe drifted formal.'),
  ('nightly_watercolor_portrait', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Both painted, natural, integrated.'),
  ('nightly_digital_watercolor', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #1 bobblehead caricature with drawn faces. Couple #2 landed.'),
  ('nightly_digital_watercolor', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Both natural; the look reads photographic.'),
  ('nightly_gouache_portrait', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #1 profiles facing each other. Couple #2 landed, painted and natural.'),
  ('nightly_gouache_portrait', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Both natural, photographic; gouache look absent.'),
  ('nightly_aquarelle_graphite', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #1 Kevin rendered balding (identity drift); couple #2 giant heads.'),
  ('nightly_aquarelle_graphite', 'black-forest-labs/flux-1.1-pro', 'solo', false, 'matrix', 'Solo #2 came back as an older grey-bearded man. Solo #1 a lovely aquarelle.'),
  ('nightly_soft_brush_illustration', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #2 profiles facing each other. Couple #1 landed as painted realism.'),
  ('nightly_soft_brush_illustration', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Both natural and integrated (the retry landed); reads photographic rather than brush-painted.'),
  ('nightly_pastel_portrait', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #2 profiles facing each other. Couple #1 landed, soft and painted.'),
  ('nightly_pastel_portrait', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Both natural; #1 genuinely pastel.'),
  ('nightly_painted_graphic_novel', 'black-forest-labs/flux-1.1-pro', 'couple', false, 'matrix', 'Couple #1 collapsed to a faceless night path; couple #2 a tight two-face portrait crop that loses the scene.'),
  ('nightly_painted_graphic_novel', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'matrix', 'Both painted, natural, integrated; distinct dark painterly finish.'),
  ('nightly_big_head', 'black-forest-labs/flux-1.1-pro', 'couple', true, 'matrix', 'Integrated big-head caricatures with your real faces (wardrobe drifted to suit and coat); painted as part of the figures. One couple degraded on the stamps but shipped as a couple.'),
  ('nightly_big_head', 'black-forest-labs/flux-1.1-pro', 'solo', false, 'matrix', 'Both solos came back as an older white-haired, white-bearded man: the age-drift defect, exaggerated by the caricature.'),
  ('nightly_baroque_oil', 'xai/grok-imagine-image', 'couple', true, 'matrix', ''),
  ('nightly_baroque_oil', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Darker, moodier than Classical; distinct.'),
  ('nightly_chromolithograph', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Couple #1 heads slightly enlarged (mild print-caricature); #2 clean.'),
  ('nightly_chromolithograph', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Aged printed-plate look with paper border; the most distinct.'),
  ('nightly_classical_oil', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both landed, wardrobe honored.'),
  ('nightly_classical_oil', 'xai/grok-imagine-image', 'solo', true, 'matrix', ''),
  ('nightly_digital_painting', 'xai/grok-imagine-image', 'couple', true, 'matrix', ''),
  ('nightly_digital_painting', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Glossy illustrative finish; distinct.'),
  ('nightly_encaustic', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Reads as generic painted realism.'),
  ('nightly_fresco', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Muted mineral palette; mildly distinct.'),
  ('nightly_hand_tinted_photo', 'xai/grok-imagine-image', 'couple', true, 'matrix', ''),
  ('nightly_hand_tinted_photo', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Soft tinted-photo palette; distinct.'),
  ('nightly_ink_illustration', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Clean linework world with a painted face; reads as illustration and the face still blends.'),
  ('nightly_jewel_realism', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Reads as generic painted realism; little to separate it from Classical.'),
  ('nightly_kodachrome', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both natural; period photo palette.'),
  ('nightly_magazine_cover', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Reads as generic painted realism.'),
  ('nightly_matte_painting', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Reads as generic painted realism.'),
  ('nightly_movie_poster', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Reads as generic painted realism.'),
  ('nightly_oil_pastel', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Soft painterly; mildly distinct.'),
  ('nightly_painted_fantasy', 'xai/grok-imagine-image', 'couple', true, 'matrix', ''),
  ('nightly_painted_fantasy', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Saturated jewel palette, painterly sky; distinct.'),
  ('nightly_pulp_cover', 'xai/grok-imagine-image', 'couple', true, 'override', 'Kevin override 2026-09-12: approved for couples without a render on this model (every couple this model rendered passed).'),
  ('nightly_pulp_cover', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Reads as generic painted realism.'),
  ('nightly_salon_realism', 'xai/grok-imagine-image', 'couple', true, 'matrix', ''),
  ('nightly_salon_realism', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Close to Classical Oil on grok.'),
  ('nightly_scifi_paperback', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Dramatic painted sky; mildly distinct.'),
  ('nightly_storybook_gouache', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Painterly illustration, no caricature on grok.'),
  ('nightly_technicolor', 'xai/grok-imagine-image', 'couple', true, 'matrix', ''),
  ('nightly_technicolor', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Photographic, saturated; distinct from the painted set.'),
  ('nightly_vintage_film', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Faded film photo; distinct.'),
  ('nightly_painted_comic_cover', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both landed; painted comic-cover realism, wardrobe honored, integrated.'),
  ('nightly_painted_comic_cover', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Natural, integrated; reads as painted realism.'),
  ('nightly_soft_comic', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both landed; soft painted comic illustration, her face mildly stylized in #2 but recognizable.'),
  ('nightly_soft_comic', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Illustrated world, natural face; distinct comic-illustration feel.'),
  ('nightly_rotoscope', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both landed; flat-color animated look with painted faces, clearly "animated" yet the faces hold. Distinct.'),
  ('nightly_rotoscope', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Flat-color animated look with a natural face; distinct.'),
  ('nightly_painted_animation', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both landed; painted-film finish, natural faces.'),
  ('nightly_painted_animation', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Painted-film finish, natural.'),
  ('nightly_airbrush_poster', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both landed; painted realism, less distinct on grok.'),
  ('nightly_airbrush_poster', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Painted realism; not very distinct on grok.'),
  ('nightly_marker', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both landed; a real marker illustration, faces natural. Distinct.'),
  ('nightly_marker', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Real marker illustration, natural face; distinct.'),
  ('nightly_ink_wash_comic', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both landed; ink lines with wash, faces slightly illustrated but recognizable. Distinct.'),
  ('nightly_ink_wash_comic', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Ink lines with wash, natural face; distinct.'),
  ('nightly_soft_pop_art', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both landed; bold saturated pop illustration with red accents, faces natural. Distinct.'),
  ('nightly_soft_pop_art', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Bold saturated illustration, natural face; distinct.'),
  ('nightly_painted_graphic_novel', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both landed; painted panels, natural faces.'),
  ('nightly_painted_graphic_novel', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Painted, natural; reads as painted realism.'),
  ('nightly_lineless_watercolor', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both landed; a true watercolor look with natural faces. Distinct.'),
  ('nightly_lineless_watercolor', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'True watercolor with a natural face; distinct.'),
  ('nightly_watercolor_portrait', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both landed; watercolor-painted realism.'),
  ('nightly_watercolor_portrait', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Watercolor-painted realism, natural.'),
  ('nightly_digital_watercolor', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both landed; watercolor illustration, faces natural. Distinct.'),
  ('nightly_digital_watercolor', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Watercolor illustration, natural face; distinct.'),
  ('nightly_gouache_portrait', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both landed; painted, natural.'),
  ('nightly_gouache_portrait', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Painted, natural.'),
  ('nightly_aquarelle_graphite', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both landed; soft painted realism.'),
  ('nightly_aquarelle_graphite', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Soft luminous watercolor with a painted sky; distinct.'),
  ('nightly_soft_brush_illustration', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both landed; brush-painted realism.'),
  ('nightly_soft_brush_illustration', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Brush-painted realism, natural.'),
  ('nightly_pastel_portrait', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both landed; soft pastel painting, natural faces.'),
  ('nightly_pastel_portrait', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Soft pastel painting, natural.'),
  ('nightly_big_head', 'xai/grok-imagine-image', 'couple', true, 'matrix', 'Both landed as INTEGRATED big-head caricatures with your real faces: painted as part of the figure, not pasted. The Big Head idea works on grok.'),
  ('nightly_big_head', 'xai/grok-imagine-image', 'solo', true, 'matrix', 'Mild big-head proportions with your real face, integrated; fun.'),
  ('nightly_classical_oil', 'google/gemini-2-image', 'couple', true, 'matrix', 'Both landed; arms around each other, contact shadows, painted skin.'),
  ('nightly_classical_oil', 'google/gemini-2-image', 'solo', true, 'matrix', 'Painted, integrated, wardrobe honored.'),
  ('nightly_baroque_oil', 'google/gemini-2-image', 'couple', true, 'matrix', 'Both landed; deep varnished tones.'),
  ('nightly_baroque_oil', 'google/gemini-2-image', 'solo', true, 'matrix', 'Darker painted realism; distinct from Classical.'),
  ('nightly_salon_realism', 'google/gemini-2-image', 'couple', true, 'matrix', 'Both landed; period attire, polished finish.'),
  ('nightly_salon_realism', 'google/gemini-2-image', 'solo', true, 'matrix', 'Period costume, highly finished; very distinct.'),
  ('nightly_digital_painting', 'google/gemini-2-image', 'couple', true, 'matrix', 'Both landed; glossy digital finish, faces natural.'),
  ('nightly_digital_painting', 'google/gemini-2-image', 'solo', true, 'matrix', 'Glossy illustrative finish.'),
  ('nightly_painted_fantasy', 'google/gemini-2-image', 'couple', true, 'matrix', 'Both landed; painted skin, saturated palette.'),
  ('nightly_painted_fantasy', 'google/gemini-2-image', 'solo', true, 'matrix', 'Painted, saturated, integrated.'),
  ('nightly_hand_tinted_photo', 'google/gemini-2-image', 'couple', true, 'matrix', 'Both landed; convincing hand-tinted photograph.'),
  ('nightly_hand_tinted_photo', 'google/gemini-2-image', 'solo', true, 'matrix', 'Sepia-tinted period photo; distinct.'),
  ('nightly_chromolithograph', 'google/gemini-2-image', 'couple', true, 'matrix', 'Both landed; printed-plate texture with its own paper border, faces natural.'),
  ('nightly_chromolithograph', 'google/gemini-2-image', 'solo', true, 'matrix', 'Printed plate with paper border and caption line; the most distinct look on gemini.'),
  ('nightly_technicolor', 'google/gemini-2-image', 'couple', true, 'matrix', 'Both landed; photographic, natural; overlaps Kodachrome.'),
  ('nightly_technicolor', 'google/gemini-2-image', 'solo', true, 'matrix', 'Photographic, saturated; natural and integrated.'),
  ('nightly_kodachrome', 'google/gemini-2-image', 'couple', true, 'matrix', 'Both landed; warm period photo, faces natural.'),
  ('nightly_ink_illustration', 'google/gemini-2-image', 'solo', true, 'matrix', 'Illustrated world with a painted face; distinct and it blends.'),
  ('nightly_storybook_gouache', 'google/gemini-2-image', 'solo', true, 'matrix', 'Painted picture-book illustration, no caricature; distinct.'),
  ('nightly_jewel_realism', 'google/gemini-2-image', 'solo', true, 'matrix', 'Painted realism; close to Classical on gemini.'),
  ('nightly_magazine_cover', 'google/gemini-2-image', 'solo', true, 'matrix', 'Painted realism; little to separate from Classical.'),
  ('nightly_movie_poster', 'google/gemini-2-image', 'solo', true, 'matrix', 'Painted realism; little to separate from Classical.'),
  ('nightly_scifi_paperback', 'google/gemini-2-image', 'solo', true, 'matrix', 'Painted with a galaxy sky through the dome; fun and distinct.'),
  ('nightly_matte_painting', 'google/gemini-2-image', 'solo', true, 'matrix', 'Painted realism; close to Classical.'),
  ('nightly_pulp_cover', 'google/gemini-2-image', 'couple', true, 'override', 'Kevin override 2026-09-12: approved for couples without a render on this model (every couple this model rendered passed).'),
  ('nightly_pulp_cover', 'google/gemini-2-image', 'solo', true, 'matrix', 'Painted realism; close to Classical.'),
  ('nightly_fresco', 'google/gemini-2-image', 'solo', true, 'matrix', 'Soft plaster-and-pastel texture; mildly distinct.'),
  ('nightly_oil_pastel', 'google/gemini-2-image', 'solo', true, 'matrix', 'Pastel stroke texture; distinct.'),
  ('nightly_encaustic', 'google/gemini-2-image', 'solo', true, 'matrix', 'Painted realism; close to Classical.'),
  ('nightly_vintage_film', 'google/gemini-2-image', 'solo', true, 'matrix', 'Faded period photo; distinct and natural.'),
  ('nightly_painted_comic_cover', 'google/gemini-2-image', 'couple', true, 'matrix', 'Painted comic-cover illustration, natural faces, wardrobe honored; distinct.'),
  ('nightly_painted_comic_cover', 'google/gemini-2-image', 'solo', true, 'matrix', 'Painted-photo finish, natural.'),
  ('nightly_soft_comic', 'google/gemini-2-image', 'couple', true, 'matrix', 'Soft illustrated comic, natural faces; distinct.'),
  ('nightly_soft_comic', 'google/gemini-2-image', 'solo', true, 'matrix', 'Illustrated, natural.'),
  ('nightly_rotoscope', 'google/gemini-2-image', 'couple', false, 'matrix', 'Both couples came back with cartoon-enlarged eyes and caricature faces: the big-eye failure. Recognizable but not real faces.'),
  ('nightly_rotoscope', 'google/gemini-2-image', 'solo', true, 'matrix', 'One render; mildly caricatured but the face holds.'),
  ('nightly_painted_animation', 'google/gemini-2-image', 'couple', true, 'matrix', 'Painted-film finish, natural faces.'),
  ('nightly_painted_animation', 'google/gemini-2-image', 'solo', true, 'matrix', 'Painted, natural.'),
  ('nightly_airbrush_poster', 'google/gemini-2-image', 'couple', true, 'matrix', 'Painted realism, natural.'),
  ('nightly_airbrush_poster', 'google/gemini-2-image', 'solo', true, 'matrix', 'Painted, natural.'),
  ('nightly_marker', 'google/gemini-2-image', 'couple', true, 'matrix', 'A real marker illustration with natural faces; distinct.'),
  ('nightly_marker', 'google/gemini-2-image', 'solo', true, 'matrix', 'Marker illustration; distinct.'),
  ('nightly_ink_wash_comic', 'google/gemini-2-image', 'couple', true, 'matrix', 'Ink lines with wash, natural faces; distinct.'),
  ('nightly_ink_wash_comic', 'google/gemini-2-image', 'solo', true, 'matrix', 'Ink and wash; distinct.'),
  ('nightly_soft_pop_art', 'google/gemini-2-image', 'couple', true, 'matrix', 'Pop poster with halftone texture and natural faces: pop art that survives the swap. Distinct.'),
  ('nightly_soft_pop_art', 'google/gemini-2-image', 'solo', true, 'matrix', 'Pop poster look; distinct.'),
  ('nightly_painted_graphic_novel', 'google/gemini-2-image', 'couple', true, 'matrix', 'Colored-pencil-and-paint panel look, natural faces; distinct.'),
  ('nightly_painted_graphic_novel', 'google/gemini-2-image', 'solo', true, 'matrix', 'Colored illustration, natural.'),
  ('nightly_lineless_watercolor', 'google/gemini-2-image', 'couple', true, 'matrix', 'True watercolor, natural faces; distinct.'),
  ('nightly_lineless_watercolor', 'google/gemini-2-image', 'solo', true, 'matrix', 'Watercolor, natural; distinct.'),
  ('nightly_watercolor_portrait', 'google/gemini-2-image', 'couple', true, 'matrix', 'Watercolor-painted realism, natural.'),
  ('nightly_watercolor_portrait', 'google/gemini-2-image', 'solo', true, 'matrix', 'Watercolor on #1, photographic on #2.'),
  ('nightly_digital_watercolor', 'google/gemini-2-image', 'couple', true, 'matrix', 'Watercolor illustration, natural faces.'),
  ('nightly_gouache_portrait', 'google/gemini-2-image', 'couple', true, 'matrix', 'Painted, natural.'),
  ('nightly_gouache_portrait', 'google/gemini-2-image', 'solo', true, 'matrix', 'Painted, natural.'),
  ('nightly_aquarelle_graphite', 'google/gemini-2-image', 'couple', true, 'matrix', 'Soft watercolor over pencil, natural faces; distinct.'),
  ('nightly_aquarelle_graphite', 'google/gemini-2-image', 'solo', true, 'matrix', 'Watercolor illustration on #1, photographic on #2.'),
  ('nightly_soft_brush_illustration', 'google/gemini-2-image', 'couple', true, 'matrix', 'Painted, natural.'),
  ('nightly_soft_brush_illustration', 'google/gemini-2-image', 'solo', true, 'matrix', 'One render; painted, natural.'),
  ('nightly_pastel_portrait', 'google/gemini-2-image', 'couple', true, 'matrix', 'Soft painted, natural.'),
  ('nightly_pastel_portrait', 'google/gemini-2-image', 'solo', true, 'matrix', 'Painted, natural.'),
  ('nightly_big_head', 'google/gemini-2-image', 'couple', true, 'matrix', 'Integrated big-head caricatures with your real faces, mid-dance, painted as part of the figures. Exactly the idea; fun and distinct.'),
  ('nightly_big_head', 'google/gemini-2-image', 'solo', true, 'matrix', 'Integrated big-head caricature with a real face; fun.')
ON CONFLICT (look_key, model, surface) DO UPDATE SET
  approved = EXCLUDED.approved, source = EXCLUDED.source, note = EXCLUDED.note, graded_at = now();

-- nightly_surfaces = the union of approved surfaces across models (model-agnostic; the pin route + QA runner read it).
UPDATE public.dream_mediums m SET nightly_surfaces = COALESCE((
  SELECT array_agg(DISTINCT a.surface ORDER BY a.surface) FROM public.nightly_look_approvals a
  WHERE a.look_key = m.key AND a.approved
), '{}'::text[]), is_active = true
WHERE m.nightly_look AND m.key LIKE 'nightly\_%';
-- A look with no approval anywhere stays parked (empty surfaces) but active for re-testing via force_look.
