-- 508_vibe_gap_fill.sql — Kevin 2026-09-11: "any vibes you can think of that we have a missing gap on? i'd like to
-- fish out all possible vibes that work and provide awesome effects". 19 new families covering the gaps in the
-- current 32 (weather, season, pure light effects, palettes), plus the 5 INACTIVE rows revived for the matrix
-- (dreamy, chaos, majestic, ominous, aura: active again but nightly_only, so the Create picker stays unchanged).
-- All nightly_only + not eligible + nightly_pool=false: they render only via force_vibe (matrix rounds h/i/j)
-- until Kevin has seen them; versions (mig 506 pattern) are added after.
INSERT INTO public.dream_vibes (key, label, description, directive, sort_order, is_active, is_dream_eligible, nightly_only, flux_fragment, fragment_position, nightly_pool, client_meta)
VALUES
('snowfall', 'Snowfall', 'First snow', $d$Snow is falling. Fat soft flakes drift through the air and settle on every ledge, leaf and railing; the light is cool, white and hushed, the world muffled and clean. Cold blue shadows, a faint frost sparkle on glass and stone, warm breath in the air, and one warm light glowing somewhere near. The mood is quiet wonder, the first snow of the year.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 50, true, false, true, $d$soft snowflakes drifting through the air and settling on every surface, cool hushed white light, cold blue shadows, one warm glow near the subject$d$, 'early', false, NULL),
('candlelit', 'Candlelit', 'A thousand candles', $d$Hundreds of candles light the scene: clusters on every ledge, floating on the water, lining the path, their flames steady and warm. Deep warm shadow between the pools of candlelight, gold on every surface, a soft flicker on skin. The mood is romantic, reverent and intimate.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 51, true, false, true, $d$hundreds of warm candles glowing on every ledge and along the path, gold candlelight on every surface and the subject, deep warm shadow between$d$, 'early', false, NULL),
('fog', 'Fog', 'Lost in fog', $d$Dense fog fills the scene. Shapes fade into soft grey-white a few steps away; only the nearest things stay crisp, wet and luminous. The light is diffused and directionless, colors muted to soft greys and silvers, a warm lamp or two glowing as haloed blurs. The mood is hushed, mysterious and cinematic.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 52, true, false, true, $d$dense soft fog filling the scene, everything beyond a few steps fading to luminous grey, muted silver light, a haloed warm lamp, the subject crisp and clearly lit$d$, 'early', false, NULL),
('rainfall', 'Rainfall', 'Caught in the rain', $d$Rain is falling. Steady silver streaks through the air, drops bouncing off stone and railings, rings spreading across the water, every surface slick and reflective. The light is cool and soft, colors deepened, a warm glow from a lamp or window doubled in the wet ground. The mood is fresh, romantic and alive.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 53, true, false, true, $d$steady rain falling in silver streaks, drops bouncing off stone and railings, every surface slick and reflective, cool soft light, a warm glow doubled in the wet ground, the subject lit clean$d$, 'early', false, NULL),
('sunrise', 'Sunrise', 'First light', $d$The first minutes of sunrise. A pink-and-orange glow floods in low from one side, long cool shadows stretch the other way, the air fresh and faintly misty, dew sparkling. Everything is touched with rose gold and the sunward side of the scene glows peach. The mood is hopeful, clean and new.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 54, true, false, true, $d$first sunrise light flooding in low and pink-gold from one side, long cool shadows, fresh mist and dew sparkle, a rose-gold glow on every surface and the subject$d$, 'early', false, NULL),
('bioluminescent', 'Bioluminescent', 'Glow in the dark', $d$Night, and the living things glow. Plants, blossoms, fungi and water shimmer with soft teal, blue and violet bioluminescence, lighting the scene from within; spores of light drift through the air. Deep blue darkness between the glowing things, a cool luminous glow on skin. The mood is otherworldly wonder.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 55, true, false, true, $d$night with plants, blossoms and water glowing in soft teal, blue and violet bioluminescence, drifting motes of light, deep blue dark between, a cool luminous glow on the subject$d$, 'early', false, NULL),
('noir', 'Noir', 'Film noir', $d$Hard slanted light and deep shadow. A single strong light source cuts through the scene, throwing venetian-blind stripes and long dramatic shadows; a curl of smoke drifts through the beam; wet surfaces gleam. Rich contrast, a moody restrained palette, a hint of danger and glamour. The mood is mysterious, stylish, mid-century detective.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 56, true, false, true, $d$hard slanted noir light through blinds throwing striped shadows, a curl of smoke in the beam, deep dramatic shadow, wet gleaming surfaces, the subject lit by the key light$d$, 'early', false, NULL),
('caustics', 'Caustics', 'Poolside light', $d$Sunlight bouncing off water. Rippling caustic light-patterns dance across every surface, walls, ceilings and skin, shifting turquoise and gold; the air is bright and watery, reflections everywhere. The mood is playful, summery and mesmerising.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 57, true, false, true, $d$rippling water-light caustics dancing across every surface and the subject, turquoise and gold reflections, bright watery light$d$, 'early', false, NULL),
('opulent', 'Opulent', 'Gilded age', $d$Everything is gilded. Gold leaf, crystal chandeliers, velvet, brocade and marble dress the scene; warm chandelier light glitters in crystal and gilt; rich jewel colors of crimson, emerald and gold. The mood is lavish, regal and celebratory, a palace ball.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 58, true, false, true, $d$gilded opulence, crystal chandeliers and gold leaf dressing the scene, warm chandelier light glittering on velvet, marble and the subject, rich crimson and emerald$d$, 'early', false, NULL),
('synthwave', 'Synthwave', 'Neon sunset', $d$A retro-future sunset palette. Magenta, violet and cyan light wash the scene, a glowing gradient horizon, thin neon grid lines and lens streaks, chrome reflections. The mood is nostalgic 1980s cool, night-drive energy.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 59, true, false, true, $d$synthwave palette of magenta, violet and cyan light washing the scene, glowing neon grid lines and lens streaks, chrome reflections, the subject lit by the glow$d$, 'early', false, NULL),
('autumnal', 'Autumnal', 'Fall colors', $d$Peak autumn. Amber, crimson and gold leaves drift through the air and carpet the ground; low warm light, a cool crisp edge in the air, long soft shadows. The mood is cozy, wistful and golden.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 60, true, false, true, $d$amber, crimson and gold autumn leaves drifting through the air and carpeting the ground, low warm light, long soft shadows, a golden glow on the subject$d$, 'early', false, NULL),
('blossom', 'Blossom', 'Petal storm', $d$Spring in full bloom. Pink and white blossom petals drift through the air and gather on every surface; branches heavy with flowers; soft bright light with a rosy cast. The mood is tender, romantic, new.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 61, true, false, true, $d$pink and white blossom petals drifting through the air and gathering on every surface, branches heavy with flowers, soft bright rosy light on the subject$d$, 'early', false, NULL),
('starlit', 'Starlit', 'Under the stars', $d$A deep clear night. Starlight and a faint milky-way glow silver the scene; cool blue-black shadows; one warm lantern near the people; everything else quiet and vast. The mood is awe and intimacy at once.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 62, true, false, true, $d$deep clear night with starlight and a faint milky-way glow silvering every surface, cool blue shadows, one warm lantern lighting the subject$d$, 'early', false, NULL),
('godrays', 'God Rays', 'Light through the haze', $d$Shafts of light. Sunbeams break through gaps and haze in bright volumetric rays, dust and motes glittering in the beams, pools of light on the ground, everything else in soft shadow. The mood is sacred, cinematic, breathtaking.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 63, true, false, true, $d$bright volumetric sunbeams cutting through haze in visible rays, glittering motes in the light, pools of light on the ground and the subject, soft shadow elsewhere$d$, 'early', false, NULL),
('fireworks', 'Fireworks', 'Grand finale', $d$Night, and fireworks bloom overhead. Bursts of red, gold, violet and green color light the scene and reflect off every surface; glowing sparks drift down; faces lit by the flashes. The mood is celebration, wonder, a perfect finale.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 64, true, false, true, $d$fireworks bursting in red, gold, violet and green, their glow lighting every surface and the subject, drifting glowing sparks, night blue between the bursts$d$, 'early', false, NULL),
('carnival', 'Carnival', 'Big top', $d$A carnival is in town. Striped tents, strings of bulbs, spinning lights and painted signs dress the scene; cotton-candy pinks and popcorn golds; a warm glittering glow. The mood is giddy, playful, nostalgic fun.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 65, true, false, true, $d$carnival set dressing of striped tents, strings of bulbs and spinning lights, cotton-candy pink and popcorn gold, a warm glittering glow on the subject$d$, 'early', false, NULL),
('cotton_candy', 'Cotton Candy', 'Pastel dreamscape', $d$Pastel dreamscape light. Wherever sky shows it is cotton-candy pink, lilac and baby blue; the whole scene bathes in a soft pastel glow, edges hazy and sweet, a gentle sparkle. The mood is dreamy and delighted.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 66, true, false, true, $d$soft pastel light of cotton-candy pink, lilac and baby blue over everything, a hazy sweet glow, a gentle sparkle, the subject lit soft and warm$d$, 'early', false, NULL),
('overcast', 'Overcast', 'Nordic grey', $d$A soft overcast day. Even grey-white light with no hard shadows, a muted palette of slate, moss, bone and rust, cool damp air, a quiet Scandinavian calm. The mood is moody, honest, understated.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 67, true, false, true, $d$soft overcast light with no hard shadows, a muted palette of slate, moss and bone, cool damp air, the subject lit even and clean$d$, 'early', false, NULL),
('stained_glass', 'Stained Glass', 'Cathedral light', $d$Colored light through stained glass. Ruby, sapphire, emerald and amber light falls in patterns across the floor, the walls and the people; motes drift in the colored beams; a cathedral hush. The mood is reverent, glowing, beautiful.
IMPORTANT: this vibe colors the SCENE and ATMOSPHERE only — the subject's skin, hair, and physical complexion stay their natural selves, never tinted to match this palette.$d$, 68, true, false, true, $d$ruby, sapphire, emerald and amber stained-glass light falling in patterns across every surface and the subject, glowing colored beams, a cathedral hush$d$, 'early', false, NULL)
ON CONFLICT (key) DO UPDATE SET
  label = EXCLUDED.label, description = EXCLUDED.description, directive = EXCLUDED.directive,
  sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, is_dream_eligible = EXCLUDED.is_dream_eligible,
  nightly_only = EXCLUDED.nightly_only, flux_fragment = EXCLUDED.flux_fragment,
  fragment_position = EXCLUDED.fragment_position, nightly_pool = EXCLUDED.nightly_pool;

UPDATE public.dream_vibes AS v SET is_active = true, nightly_only = true, is_dream_eligible = false,
  flux_fragment = f.frag, fragment_position = 'early', nightly_pool = false
FROM (VALUES
  ('dreamy', $d$soft ethereal haze with light glowing from within the scene, pastel lavender, blush and powder-blue light, edges dissolving, the subject softly lit$d$),
  ('chaos', $d$clashing multi-colored light from every direction, electric complementary colors at full saturation, wild energy, the subject clearly lit$d$),
  ('majestic', $d$regal golden light, royal purples and deep crimsons, monumental grandeur on every surface, the subject lit like royalty$d$),
  ('ominous', $d$heavy storm-charged light, unnatural stillness, deep teal, bruised purple and sickly green against black, a foreboding glow on the subject$d$),
  ('aura', $d$soft glowing halos of colored light around everything, warm golden and cool prismatic auras in the air, light emanating from within, a luminous aura on the subject$d$)
) AS f(key, frag) WHERE v.key = f.key;
