-- 511_legacy_mediums_as_looks.sql — Kevin 2026-09-12: "the variety and type of looks over the last 30 renders in my posts
-- album is the same look and feel i want to have across nightly, with the addition of our new looks that are additive".
-- The looks path rolled only the 49 new catalog rows; the mediums his posts rendered with were absent. Two facts from
-- the 1.2.0 code: on flux-1.1-pro every face-swap render replaced the rolled medium's fragment with one of FOUR curated
-- override fragments (faceSwapModelOverrides.ts: watercolor-ink, crisp ornate illustration, polished digital render,
-- adult cartoon) — three are already catalog looks, the fourth is added here; on the other models the medium's own
-- fragment rendered. So the eight rows below are the legacy natural face-swap mediums' own fragments (canvas, comics,
-- pop_art, watercolor, illustration, pencil, glamour; photography excluded: the legacy path re-rolled it away for
-- character dreams) plus the adult-cartoon override, as catalog looks (nightly_look=true, never public, never in the
-- legacy roll). Approvals: adult_cartoon on flux-1.1-pro couple+solo by override (production-proven), plus the two
-- override looks that the matrix had not approved for flux couples (watercolor_ink, ink_illustration) — they ARE
-- what 1.2.0 shipped on flux couples. The seven legacy-derived looks get approvals from a matrix run, not by fiat.
INSERT INTO public.dream_mediums
  (key, label, directive, flux_fragment, face_swap_flux_fragment, sort_order, is_active, is_public, is_dream_eligible,
   is_scene_eligible, face_swaps, character_render_mode, nightly_look, nightly_surfaces, weight, nightly_family,
   nightly_enabled, client_meta)
VALUES
('nightly_canvas', 'Canvas Oil', $d$Classical oil-painting style in the luminous old-master tradition (Rembrandt, Velazquez) — rich saturated color built through smooth layered glazing, warm chiaroscuro lighting with soft modeled shadows and brilliant highlights. Refined, controlled brushwork that suggests form and mass through smooth glazed surfaces. Warm undertones with selective cool accents; traditional pigments (burnt umber, raw sienna, ivory black, lead white, ultramarine, cadmium yellow).$d$, $d$classical oil painting on canvas, rich saturated oil color, soft refined brushwork, warm luminous chiaroscuro lighting, smooth glazed painterly finish, elegant old-master oil-on-canvas look$d$, $d$classical oil painting, smooth refined brushwork, softly blended tones, rich luminous color, warm chiaroscuro lighting, smooth glazed skin, clean clearly-readable faces and features, elegant oil-on-canvas finish$d$, 900, true, false, false, false, true, 'natural', true, ARRAY['couple','solo'], 1, 'painted_realism', true, '{"legacy_medium":"canvas"}'::jsonb),
('nightly_comics', 'Comics', $d$Create images in the style of printed comics, drawing from the full spectrum of comics traditions. Adapt the specific style to the subject. American superhero comics tradition (Marvel + DC + Image lineage) carries bold confident ink linework with varying weights, vibrant saturated colors, flat color fills, cel-shaded forms, Ben-Day dots, heroic proportions, detailed cross-hatching. European bandes dessinées tradition carries cleaner illustrative linework, richer detailed backgrounds, sophisticated muted palettes, ligne claire register. Indie graphic novel tradition carries restrained painterly coloring, introspective character focus, muted palettes, sophisticated illustration. Alternative indie comix tradition carries hand-drawn rough-edged linework, heavy cross-hatching, expressive grit, energetic mark-making. Modern webcomic tradition carries clean digital linework, simplified character design, expressive minimalism, flat bright colors. Shared qualities: sequential art feel, confident linework as foundation, printed-media aesthetic with halftone, registration marks, paper texture as suggestion.$d$, $d$comic book art, graphic novel illustration, confident ink linework, flat color fills, cel shading, halftone Ben-Day dots, printed comic aesthetic, varied comics traditions$d$, $d$realistic human face with natural adult proportions and lifelike features, true-to-life skin, eyes and expression, cleanly integrated with confident comic inking and subtle cel shading, no heavy halftone dots on the face; the rest of the scene in full comic-book style$d$, 901, true, false, false, false, true, 'natural', true, ARRAY['couple','solo'], 1, 'comic_print', true, '{"legacy_medium":"comics"}'::jsonb),
('nightly_pop_art', 'Pop Art', $d$Render as bold pop art — the graphic, high-impact visual language of screen-printed posters and 1960s commercial art. VISUAL IDENTITY: thick black ink outlines defining every shape, flat high-contrast color fills with no subtle gradients, halftone dot patterns for shading and texture, clean vector-like contours. COLOR: vibrant saturated palette dominated by primary colors (red, blue, yellow) plus hot pink, cyan, and orange. Colors are flat and punchy — never muddy, never muted, never photorealistic. Every color choice should feel like a deliberate graphic design decision. COMPOSITION: simplified bold shapes, dramatic cropped framing, strong figure-ground contrast. Backgrounds are flat color fields or simple geometric patterns. TEXTURE: visible halftone dots, screen-print registration marks, comic book print grain. The image should feel like it was pulled from a printing press, not a camera. STYLE: channel the energy of Lichtenstein and Warhol without copying specific works. Exaggerated expressions, playful graphic boldness, retro advertising confidence. Always crisp, flat, and punchy.$d$, $d$premium pop-art illustration, crisp clean outlines, Ben-Day halftone dot shading for depth and texture, rich saturated retro palette, expressive lighting, detailed textured environment with layered depth, playful visual energy, vintage print-inspired poster texture$d$, $d$premium pop-art illustration, crisp clean outlines, Ben-Day halftone dot shading for depth and texture on clothing and environment, rich saturated retro palette, expressive lighting, detailed textured scene with layered depth, playful visual energy, vintage print-inspired poster texture, lifelike adult face with realistic human proportions and true-to-life eyes at natural size and spacing, natural recognizable skin unified by the scene light, a fine outline settling the face into the illustration$d$, 902, true, false, false, false, true, 'natural', true, ARRAY['couple','solo'], 1, 'comic_print', true, '{"legacy_medium":"pop_art"}'::jsonb),
('nightly_watercolor_paper', 'Watercolor on Paper', $d$Classical watercolor in the tradition of John Singer Sargent. Transparent layered washes building form through light and shadow. Skin rendered with warm peachy washes over cool blue undertones. Focal features painted with precision, while peripheral elements dissolve into looser, more abstract washes. White paper preserved as the brightest highlights — bare paper IS the white in this medium. Colors are luminous and clean, built through glazing rather than mixing. Brushwork is confident and economical — every stroke serves a purpose. Background washes are loose and atmospheric, suggesting environment without defining it. The image radiates the elegance and spontaneity of a master watercolorist working quickly and decisively. Paper texture visible throughout. Warm and cool temperature shifts create depth and dimension.$d$, $d$watercolor painting on cold-press paper, transparent pigment washes bleeding into wet paper, soft feathered edges where colors bleed together, visible paper grain and tooth texture, white unpainted paper for highlights, loose flowing brushstrokes, watery diluted pigment pools, painted watercolor register throughout$d$, $d$watercolor painting on cold-press paper with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, transparent pigment washes bleeding into wet paper around the figures, soft feathered edges where colors bleed together, visible paper grain, white unpainted paper for highlights, loose flowing brushstrokes$d$, 903, true, false, false, false, true, 'natural', true, ARRAY['couple','solo'], 1, 'watercolor', true, '{"legacy_medium":"watercolor"}'::jsonb),
('nightly_hand_drawn_illustration', 'Hand-Drawn Illustration', $d$Vibrant hand-drawn illustration with bold, confident strokes and rich saturated color. Decisive gestural linework defines forms — each stroke feels intentional and economical. Colors are vivid and layered with visible mark-making, mixing on the surface to create depth and energy. Ink outlines ground the composition while color fills bring warmth and life. Textures feel handmade — visible paper grain, brushstroke direction, slight imperfections that prove a human hand made this. The style is fresh, immediate, and alive — like opening a beautifully illustrated book or flipping through a concept artist's personal sketchbook. Influences: editorial illustration, concept art, modern picture books, graphic novel coloring. Warm, inviting, artistically confident.$d$, $d$vibrant hand-drawn illustration, bold confident brushstrokes, rich saturated vivid colors, spontaneous gestural linework, visible paper texture, fluid pigment washes, preserved paper luminosity, fresh immediate handmade feel$d$, $d$vibrant hand-drawn illustration with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, bold confident brushstrokes, rich saturated vivid colors, spontaneous gestural linework, visible paper texture, fluid pigment washes, fresh immediate handmade feel$d$, 904, true, false, false, false, true, 'natural', true, ARRAY['couple','solo'], 1, 'painted_realism', true, '{"legacy_medium":"illustration"}'::jsonb),
('nightly_colored_pencil', 'Colored Pencil', $d$Render as a detailed colored pencil drawing on textured paper — ALWAYS full color, rich and vibrant, the kind of work you would see from a master colored pencil artist. The medium is ALWAYS the full prismacolor spectrum — color is the entire point. Visual identity: visible individual pencil strokes built up in layers, directional hatching to suggest form, clearly drawn edges, paper texture showing through the color subtly everywhere, highlights preserved as white paper rather than added as opaque white. Color use: the full spectrum of colored pencils, layered to create depth through transparency, optical blending on the paper rather than mixing on a palette, slight waxy sheen where pencil layers are built up thickly, full saturation built up through many passes. Shading uses cross-hatching, stippling, and directional strokes — darker areas show as tighter denser pencil marks, lighter areas show paper tooth more visibly. Confident lines that show the hand of the artist, occasional eraser marks or overlapping strokes adding to the handmade feel.$d$, $d$colored pencil drawing, prismacolor art, visible pencil strokes, directional hatching, paper texture showing through, layered transparent color, hand-drawn quality, grainy tooth texture, confident linework with eraser marks, waxy colored pencil sheen, master colored pencil art style$d$, $d$realistic human face with normal sized eyes and natural adult proportions, thin subtle eyebrows, the face rendered true-to-life and lifelike, drawn in colored pencil, prismacolor art, visible pencil strokes, directional hatching, paper texture showing through, layered transparent color, hand-drawn quality, grainy tooth texture, confident linework$d$, 905, true, false, false, false, true, 'natural', true, ARRAY['couple','solo'], 1, 'painted_realism', true, '{"legacy_medium":"pencil"}'::jsonb),
('nightly_glamour', 'Glamour Shot', $d$Render as a dreamy glamour-shot portrait: the soft-focus, luminous, romantic style of a classic glamour studio photograph. Flattering beauty lighting with a gentle glow, a soft-focus dreamy backdrop, luminous airbrushed skin, radiant highlights and a warm sensual haze, voluminous styling, an idealized camera-loves-you feel with high-gloss beauty-cover polish. Keep the face true-to-life and lifelike: flattering but recognizably the same person, a real glamorous photograph, never an illustration.$d$, $d$dreamy glamour-shot portrait, soft-focus luminous beauty lighting, romantic glowing haze, airbrushed radiant skin, flattering high-gloss beauty-cover polish, dreamy soft backdrop, glamorous idealized studio photograph, lifelike recognizable face$d$, $d$dreamy glamour-shot photograph with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, soft-focus luminous beauty lighting, romantic glowing haze, radiant skin, flattering high-gloss beauty-cover polish, dreamy soft backdrop$d$, 906, true, false, false, false, true, 'natural', true, ARRAY['couple','solo'], 1, 'photographic', true, '{"legacy_medium":"glamour"}'::jsonb),
('nightly_adult_cartoon', 'Adult Cartoon', $d$Render as a grounded semi-realistic comic-book illustration: painted graphic-novel art with bold ink linework and rich flat color, the people drawn with naturalistic mature features.$d$, $d$grounded semi-realistic comic-book illustration, painted graphic-novel art, bold confident ink linework and rich saturated flat color, detailed hand-painted art, illustrated realism$d$, $d$grounded semi-realistic comic-book illustration, painted graphic-novel art with lifelike adult faces, realistic human facial proportions with true-to-life eyes at natural size and spacing, bold confident ink linework and rich saturated flat color, detailed hand-painted character art, naturalistic mature features, illustrated realism$d$, 907, true, false, false, false, true, 'natural', true, ARRAY['couple','solo'], 1, 'comic_print', true, '{"legacy_medium":"flux_override_adult_cartoon", "banned_vibes": ["epic"]}'::jsonb)
ON CONFLICT (key) DO UPDATE SET
  label = EXCLUDED.label, directive = EXCLUDED.directive, flux_fragment = EXCLUDED.flux_fragment,
  face_swap_flux_fragment = EXCLUDED.face_swap_flux_fragment, sort_order = EXCLUDED.sort_order, is_active = true,
  is_public = false, is_dream_eligible = false, is_scene_eligible = false, face_swaps = true,
  character_render_mode = 'natural', nightly_look = true, nightly_surfaces = EXCLUDED.nightly_surfaces,
  weight = EXCLUDED.weight, nightly_family = EXCLUDED.nightly_family, nightly_enabled = true,
  client_meta = EXCLUDED.client_meta;

INSERT INTO public.nightly_look_approvals (look_key, model, surface, approved, source, note) VALUES
  ('nightly_adult_cartoon', 'black-forest-labs/flux-1.1-pro', 'couple', true, 'override', '1.2.0 flux override fragment (production-proven)'),
  ('nightly_adult_cartoon', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'override', '1.2.0 flux override fragment (production-proven)'),
  ('nightly_watercolor_ink', 'black-forest-labs/flux-1.1-pro', 'couple', true, 'override', '1.2.0 flux override fragment (production-proven); matrix had rejected couples'),
  ('nightly_watercolor_ink', 'black-forest-labs/flux-1.1-pro', 'solo', true, 'override', '1.2.0 flux override fragment (production-proven)'),
  ('nightly_ink_illustration', 'black-forest-labs/flux-1.1-pro', 'couple', true, 'override', '1.2.0 flux override fragment (production-proven); matrix had rejected couples')
ON CONFLICT (look_key, model, surface) DO UPDATE SET approved = EXCLUDED.approved, source = EXCLUDED.source, note = EXCLUDED.note;
