-- 606: Surreal Dreams round 2 + solo and scene-only (Kevin 2026-09-30: ship Glowing Elements and Impossible Whimsy,
-- round 2 for Land of Giants and Gravity's Off; "single and scene only" for the surreal cards).
--
-- 1. location_cards.couples_ok (default true). false = a couple dream never lands here: nightly-dreams re-rolls a couple
--    place pick to another of the dreamer's places. Set false for the four Surreal Dreams cards.
-- 2. The couple rows of the surreal scenes lose the Impossible Whimsy tag (they keep Just for Fun, since all are goofy),
--    so a couple can't reach a surreal scene through the scope roll either.
-- 3. Round 1 showed Land of Giants' objects and Gravity's Off's weightlessness didn't read. Their spots are rewritten
--    (one recognisable object or an unmistakable float named first: "A stapler the size of a cathedral among green
--    hills", "Waterfalls pouring upward off cliff edges into open sky"), with eligibility re-derived from the new scale;
--    33 weak spots across all four cards are switched off (is_active = false). Re-runnable.

ALTER TABLE public.location_cards ADD COLUMN IF NOT EXISTS couples_ok boolean NOT NULL DEFAULT true;
UPDATE public.location_cards SET couples_ok = false WHERE picker_tile = 'surreal_dreams';

UPDATE public.dual_scenarios SET location_keys = array_remove(location_keys, 'impossible wonderland')
WHERE 'impossible wonderland' = ANY(location_keys);

UPDATE public.location_iconic_spots SET spot_text = 'A stapler the size of a cathedral among green hills', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '05ee2de9-cd68-461f-94fe-38d7aa38c44c' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A stapler the size of a cathedral among green hills');
UPDATE public.location_iconic_spots SET spot_text = 'A red telephone booth tall as a skyscraper on a plain', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '093ba04e-1f56-4e1f-93fd-bb3fd290ca13' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A red telephone booth tall as a skyscraper on a plain');
UPDATE public.location_iconic_spots SET spot_text = 'Giant pinwheels taller than mountains on a flat green plain', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '0b9c397c-022a-4ecf-b8a9-4197d6ca4a40' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Giant pinwheels taller than mountains on a flat green plain');
UPDATE public.location_iconic_spots SET spot_text = 'A shoelace wide as a highway looped over mountain peaks', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '169e8bfc-ea7d-46c4-b947-bb159a73e763' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A shoelace wide as a highway looped over mountain peaks');
UPDATE public.location_iconic_spots SET spot_text = 'Birthday candles tall as skyscrapers burning in a wheat field', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '17ae2a14-a992-41f7-8503-c53e2e5d5f12' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Birthday candles tall as skyscrapers burning in a wheat field');
UPDATE public.location_iconic_spots SET spot_text = 'Piano keys wide as city blocks stretching to the horizon', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '182fada5-5475-4418-92d1-759ff9e5692b' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Piano keys wide as city blocks stretching to the horizon');
UPDATE public.location_iconic_spots SET spot_text = 'White dice taller than skyscrapers on a flat desert plain', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '1f0fe739-ec0a-4530-b8a5-86907cdac2cc' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'White dice taller than skyscrapers on a flat desert plain');
UPDATE public.location_iconic_spots SET spot_text = 'A waffle iron the size of a stadium on green plains', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '25066142-ecd4-4207-a25d-436bf1571e41' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A waffle iron the size of a stadium on green plains');
UPDATE public.location_iconic_spots SET spot_text = 'A firefly the size of a blimp drifting over dark forest', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '2b2218b3-5749-408f-bc59-7ba273135fcf' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A firefly the size of a blimp drifting over dark forest');
UPDATE public.location_iconic_spots SET spot_text = 'A teacup the size of a lake among green hills', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '2dfaf566-220c-4f62-a9b0-4549ad66a544' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A teacup the size of a lake among green hills');
UPDATE public.location_iconic_spots SET spot_text = 'A silver serving tray wide as a valley holding green hills', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '2ea12983-0243-458f-8586-b9e77aadb907' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A silver serving tray wide as a valley holding green hills');
UPDATE public.location_iconic_spots SET spot_text = 'A violin as tall as a mountain range on a plain', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '2fc7c56c-5e0b-414b-b0b2-b41e46acafe9' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A violin as tall as a mountain range on a plain');
UPDATE public.location_iconic_spots SET spot_text = 'A paper crane the size of a cathedral in a meadow', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '34da176f-c4c9-45ed-94b5-06f1c245ac41' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A paper crane the size of a cathedral in a meadow');
UPDATE public.location_iconic_spots SET spot_text = 'A grand piano the size of a city block on flat earth', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '3568b695-67d2-47da-82a2-1f15efa126fd' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A grand piano the size of a city block on flat earth');
UPDATE public.location_iconic_spots SET spot_text = 'A rolled newspaper as wide as a tunnel mouth on hillside', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '38e8da61-9681-46bc-a993-8e2059cea850' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A rolled newspaper as wide as a tunnel mouth on hillside');
UPDATE public.location_iconic_spots SET spot_text = 'A coffee mug the size of a lake among rolling hills', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '3cad9593-c135-4179-806d-09b31798bc4a' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A coffee mug the size of a lake among rolling hills');
UPDATE public.location_iconic_spots SET spot_text = 'Giant jigsaw pieces shaped like continents floating on calm ocean', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '452474ef-9e4d-42f0-9ed3-12ef0616fd78' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Giant jigsaw pieces shaped like continents floating on calm ocean');
UPDATE public.location_iconic_spots SET spot_text = 'A butterfly the size of a building gliding over green hills', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '4c0b51eb-721e-49aa-a489-64b83a71a4a6' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A butterfly the size of a building gliding over green hills');
UPDATE public.location_iconic_spots SET spot_text = 'A grandfather clock tall as a skyscraper on an open plain', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '4f19c9b9-016f-48dd-a799-9b6d6c0fe2d6' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A grandfather clock tall as a skyscraper on an open plain');
UPDATE public.location_iconic_spots SET spot_text = 'A gong as wide as a lake propped on a hillside', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '55205d47-99a8-4adc-beae-c576cc2d99fe' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A gong as wide as a lake propped on a hillside');
UPDATE public.location_iconic_spots SET spot_text = 'A single guitar string stretched canyon-wide humming over still water', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '5af0d4ba-2d86-439b-b1be-6c7081a6a6b4' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A single guitar string stretched canyon-wide humming over still water');
UPDATE public.location_iconic_spots SET spot_text = 'A kitchen chair tall as a cathedral spire on a plain', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '5ef571d4-a539-4bb7-aca3-9c62a29ed5c8' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A kitchen chair tall as a cathedral spire on a plain');
UPDATE public.location_iconic_spots SET spot_text = 'A fortune cookie the size of a stadium cracked on a hillside', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '62cce4bf-c1a6-4223-97db-917551850a16' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A fortune cookie the size of a stadium cracked on a hillside');
UPDATE public.location_iconic_spots SET spot_text = 'A cheese grater tall as a skyscraper standing on flat plain', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '6977d03a-2885-4e3d-b00f-d8cbdd37c85d' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A cheese grater tall as a skyscraper standing on flat plain');
UPDATE public.location_iconic_spots SET spot_text = 'A music box the size of a concert hall on green hills', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '6b25caa3-0bd8-464d-976e-0cf325f82409' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A music box the size of a concert hall on green hills');
UPDATE public.location_iconic_spots SET spot_text = 'A grandfather clock taller than any skyscraper on an open plain', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '72da7259-edb4-4ed1-8ec8-c11b30f0ae68' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A grandfather clock taller than any skyscraper on an open plain');
UPDATE public.location_iconic_spots SET spot_text = 'A hole-puncher the size of a building over a circular lake', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '7d202378-c6d6-4212-aba2-fafe47a481be' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A hole-puncher the size of a building over a circular lake');
UPDATE public.location_iconic_spots SET spot_text = 'An egg beater as tall as a skyscraper on a flat plain', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '80d0a135-72c8-4a62-8b4a-b012b5fcab92' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'An egg beater as tall as a skyscraper on a flat plain');
UPDATE public.location_iconic_spots SET spot_text = 'Cocktail umbrellas tall as towers shading a small town below', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '81022c66-eb70-43bb-b7ec-31695f6eb993' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Cocktail umbrellas tall as towers shading a small town below');
UPDATE public.location_iconic_spots SET spot_text = 'An accordion as wide as a mountain range on green plains', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '86dfc982-f3c5-4193-9ad4-92c6c37a49ab' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'An accordion as wide as a mountain range on green plains');
UPDATE public.location_iconic_spots SET spot_text = 'A thick rubber band looped around three tall city skyscrapers', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '9bbd6d7b-8a53-4797-967d-afe225a9e32a' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A thick rubber band looped around three tall city skyscrapers');
UPDATE public.location_iconic_spots SET spot_text = 'A plastic comb as long as a city block on flat plain', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '9ecddd04-f194-43b6-b7a8-cbba8168ba27' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A plastic comb as long as a city block on flat plain');
UPDATE public.location_iconic_spots SET spot_text = 'A garlic press the size of a factory on rocky ground', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'a125563a-5fe3-429e-a47b-d02e0358f678' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A garlic press the size of a factory on rocky ground');
UPDATE public.location_iconic_spots SET spot_text = 'A stack of books each as tall as a mountain', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'a1373a32-ce2e-4671-9bdd-a66f59783a66' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A stack of books each as tall as a mountain');
UPDATE public.location_iconic_spots SET spot_text = 'A tea bag the size of a barn steeping in a lake', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'a32d2776-27f6-4d1e-9553-e6b3fc3ae5b0' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A tea bag the size of a barn steeping in a lake');
UPDATE public.location_iconic_spots SET spot_text = 'A jellyfish as wide as a city drifting over green hills', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'abdbb7c8-e24c-4862-bc1a-593144538fef' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A jellyfish as wide as a city drifting over green hills');
UPDATE public.location_iconic_spots SET spot_text = 'A zipper as long as a coastline lying across the ocean', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'ad265ea2-cb90-497b-a7fb-df2ff88b4dcc' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A zipper as long as a coastline lying across the ocean');
UPDATE public.location_iconic_spots SET spot_text = 'Fortune cookie slips each as large as a field across blue sky', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'af7b0e4e-0c58-441e-b0a3-bda99b36fdab' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Fortune cookie slips each as large as a field across blue sky');
UPDATE public.location_iconic_spots SET spot_text = 'A single guitar string as wide as a road across a valley', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'b18bf39a-4cc4-43e5-abd2-fdf7fad3a6af' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A single guitar string as wide as a road across a valley');
UPDATE public.location_iconic_spots SET spot_text = 'A corkscrew the size of a lighthouse standing on bare rock', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'b453c68a-5d58-4b62-926c-56c8af0878cb' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A corkscrew the size of a lighthouse standing on bare rock');
UPDATE public.location_iconic_spots SET spot_text = 'A rubber doorstop the size of a hill between two cliffs', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'b617ce0a-b9af-49cb-93a4-2fd34e0a2927' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A rubber doorstop the size of a hill between two cliffs');
UPDATE public.location_iconic_spots SET spot_text = 'A paint roller as wide as a stadium rolling over grey clouds', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'b655ba93-0c15-4d0a-a3ff-7cef4cf589db' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A paint roller as wide as a stadium rolling over grey clouds');
UPDATE public.location_iconic_spots SET spot_text = 'A silver thimble the size of a hill on a green plain', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'b701be85-a94e-47e3-b6bb-a1dcaf207461' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A silver thimble the size of a hill on a green plain');
UPDATE public.location_iconic_spots SET spot_text = 'A rubber band wide as a highway stretched between two mountain peaks', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'bcd6198e-f2a5-4a17-a178-f399866cbd73' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A rubber band wide as a highway stretched between two mountain peaks');
UPDATE public.location_iconic_spots SET spot_text = 'A dining table stretching to the horizon on a flat plain', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'c0effcd4-9836-456d-bc1f-7e96c779002b' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A dining table stretching to the horizon on a flat plain');
UPDATE public.location_iconic_spots SET spot_text = 'A basting brush as tall as a building on golden sand', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'c37f48c2-8701-4332-8a5f-1039f451e6f6' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A basting brush as tall as a building on golden sand');
UPDATE public.location_iconic_spots SET spot_text = 'An elevator the size of a skyscraper standing on an open plain', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'c5284bfc-cf6c-40da-88a1-a8ad12551384' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'An elevator the size of a skyscraper standing on an open plain');
UPDATE public.location_iconic_spots SET spot_text = 'Pink eraser the size of a hill beside a mountain', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'ccd4e1d1-9d18-4be6-8a80-178669c1702f' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Pink eraser the size of a hill beside a mountain');
UPDATE public.location_iconic_spots SET spot_text = 'Giant wooden floorboards with canyons between each plank', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'cea1ac99-ce36-40ad-a4f5-5ab2580e6bcb' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Giant wooden floorboards with canyons between each plank');
UPDATE public.location_iconic_spots SET spot_text = 'Giant teddy bear tall as a skyscraper on a city street', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'd291ca51-72fa-438d-96db-f8cc1274fbe2' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Giant teddy bear tall as a skyscraper on a city street');
UPDATE public.location_iconic_spots SET spot_text = 'Giant teddy bears taller than buildings roaming empty city streets', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'd37b0d03-c994-47f1-a2c5-609c3d6a7e5f' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Giant teddy bears taller than buildings roaming empty city streets');
UPDATE public.location_iconic_spots SET spot_text = 'Wind chimes each tube tall as a redwood in a field', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'd5161691-21bd-4215-aab4-23ce3905ebac' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Wind chimes each tube tall as a redwood in a field');
UPDATE public.location_iconic_spots SET spot_text = 'Rubber stamp the size of a barn beside rolling hills', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'd7b9007c-0c59-4391-a50e-818e9c72834c' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Rubber stamp the size of a barn beside rolling hills');
UPDATE public.location_iconic_spots SET spot_text = 'A ballpoint pen cap the size of a stadium on a plain', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'd809425d-8ede-431f-9a90-2313debf476d' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'A ballpoint pen cap the size of a stadium on a plain');
UPDATE public.location_iconic_spots SET spot_text = 'Open tackle box the size of a stadium on green hills', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'd9e83fc6-16bc-46f7-87e4-3cabdd02ba22' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Open tackle box the size of a stadium on green hills');
UPDATE public.location_iconic_spots SET spot_text = 'Giant spiral seashell the size of a cathedral on a beach', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'daebf93b-c813-4964-83e5-4b8e9bf3da71' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Giant spiral seashell the size of a cathedral on a beach');
UPDATE public.location_iconic_spots SET spot_text = 'Giant brass accordion the size of a building in a meadow', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'e137ee25-faa3-4a79-805e-a9e01d3cd2ef' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Giant brass accordion the size of a building in a meadow');
UPDATE public.location_iconic_spots SET spot_text = 'Hopscotch grid chalked across moon craters Earth huge overhead', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'e22bf7ed-0154-468e-abae-e3d94a3b09e1' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Hopscotch grid chalked across moon craters Earth huge overhead');
UPDATE public.location_iconic_spots SET spot_text = 'Safety scissors the size of a bridge over a green valley', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'e272a565-2f91-4984-b5c1-9e020cd9b79e' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Safety scissors the size of a bridge over a green valley');
UPDATE public.location_iconic_spots SET spot_text = 'Ice cream scoop the size of a house beside rolling hills', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'f56759fb-9a96-44c1-9526-f8fd1b526e98' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Ice cream scoop the size of a house beside rolling hills');
UPDATE public.location_iconic_spots SET spot_text = 'Yellow rubber duck the size of an ocean liner on calm sea', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'f64204c6-c101-4642-8b12-d3db0bed6736' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Yellow rubber duck the size of an ocean liner on calm sea');
UPDATE public.location_iconic_spots SET spot_text = 'Giant white bathtub filling an entire valley yellow duck floating inside', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'fd3dbb71-186a-4dbf-8d4c-bd2c8558da49' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'land of giants' AND d.spot_text = 'Giant white bathtub filling an entire valley yellow duck floating inside');
UPDATE public.location_iconic_spots SET spot_text = 'Waterfalls pouring upward off cliff edges into open sky', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '01c9ddc0-af67-4bb0-aff7-07bc1ea25d60' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Waterfalls pouring upward off cliff edges into open sky');
UPDATE public.location_iconic_spots SET spot_text = 'Valleys of green meadow floating inverted above mountain peaks', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '03334120-32b9-4882-b942-fefdfa2f6377' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Valleys of green meadow floating inverted above mountain peaks');
UPDATE public.location_iconic_spots SET spot_text = 'Upward-crashing bioluminescent ocean waves with fish mid-air above', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '04c9facc-c5e4-4dd6-b925-a6a8b520ad35' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Upward-crashing bioluminescent ocean waves with fish mid-air above');
UPDATE public.location_iconic_spots SET spot_text = 'Courtyard fountain shooting water upward, sideways, and down simultaneously', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '06c1f7d4-7d94-4c7e-a943-4348b3ac023b' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Courtyard fountain shooting water upward, sideways, and down simultaneously');
UPDATE public.location_iconic_spots SET spot_text = 'Floating rocks and trees drifting inside a vast soap-bubble', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '08a1d1fa-aaee-4516-b993-cde8c29412db' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Floating rocks and trees drifting inside a vast soap-bubble');
UPDATE public.location_iconic_spots SET spot_text = 'Floating trees with roots dangling in air, leaves below', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '09822b49-d636-4cda-be36-d6ee0bf25c88' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Floating trees with roots dangling in air, leaves below');
UPDATE public.location_iconic_spots SET spot_text = 'Snow globe interior with snowflakes rising upward in swirls', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '0e2bd19c-d5e6-4c35-b043-870c3d6af2df' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Snow globe interior with snowflakes rising upward in swirls');
UPDATE public.location_iconic_spots SET spot_text = 'Swimming pool hanging vertically, water and fish spilling upward', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '0e3ea576-7fe8-4947-bf4b-acb178ad5eeb' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Swimming pool hanging vertically, water and fish spilling upward');
UPDATE public.location_iconic_spots SET spot_text = 'Stone staircase rising into open sky above a floating balcony', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '14b3181e-afc5-4ee4-bb12-a9f5f7279725' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Stone staircase rising into open sky above a floating balcony');
UPDATE public.location_iconic_spots SET spot_text = 'Luminous trees hanging root-up from black sky above rainbow pools', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '24dd8637-9329-47d0-af8d-8a0ef77b48ab' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Luminous trees hanging root-up from black sky above rainbow pools');
UPDATE public.location_iconic_spots SET spot_text = 'Books, chairs, and lanterns drifting up against ceiling in clusters', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '2dfc35a7-13e6-4ded-9d23-423dd44157b8' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Books, chairs, and lanterns drifting up against ceiling in clusters');
UPDATE public.location_iconic_spots SET spot_text = 'Building stones rising freely above rooftops into cloud-city above', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '2ef6fa3d-98f5-4769-917d-79fd3f048f92' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Building stones rising freely above rooftops into cloud-city above');
UPDATE public.location_iconic_spots SET spot_text = 'Laundry sheets drifting horizontally between two floating moonlit rocks', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '3087492a-9cc0-4b42-a8f7-be83c01fbddf' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Laundry sheets drifting horizontally between two floating moonlit rocks');
UPDATE public.location_iconic_spots SET spot_text = 'Candle flames burning straight downward, smoke curling toward the floor', spot_kind = 'intimate', pure_scene_eligible = false, character_eligible = true WHERE id = '317e36b3-de7a-4d44-a5e2-11605a5a95d0' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Candle flames burning straight downward, smoke curling toward the floor');
UPDATE public.location_iconic_spots SET spot_text = 'Staircase of liquid marble flowing visibly upward against gravity', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '32c26b80-a640-4a07-a19e-a9c4064b7038' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Staircase of liquid marble flowing visibly upward against gravity');
UPDATE public.location_iconic_spots SET spot_text = 'Gears and clock parts raining upward, assembling into floating timepieces', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '394129c4-2cc6-445c-94f7-8fe90251f516' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Gears and clock parts raining upward, assembling into floating timepieces');
UPDATE public.location_iconic_spots SET spot_text = 'Horizon rolled back revealing upside-down mirrored landscape beneath the sky', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '3ca025b0-4dfa-4056-a547-fb08fb72f078' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Horizon rolled back revealing upside-down mirrored landscape beneath the sky');
UPDATE public.location_iconic_spots SET spot_text = 'Grand hall hanging inverted from earth, chandeliers pointing toward space', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '3d32b7e5-6b9e-455b-8ddf-2de4623d9f6e' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Grand hall hanging inverted from earth, chandeliers pointing toward space');
UPDATE public.location_iconic_spots SET spot_text = 'Subway train running along skyscraper wall, newspapers floating beside windows', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '3e6d58ed-90ff-40ee-bcf0-76a5909f9fce' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Subway train running along skyscraper wall, newspapers floating beside windows');
UPDATE public.location_iconic_spots SET spot_text = 'Skyscrapers leaning and swaying, confetti raining upward from ground level', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '3e929770-84e6-444e-85c4-20c4dd793460' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Skyscrapers leaning and swaying, confetti raining upward from ground level');
UPDATE public.location_iconic_spots SET spot_text = 'River climbing vertical cliff face into mid-air lake above', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '40fa54db-2e3e-42a4-8871-760c84613bc5' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'River climbing vertical cliff face into mid-air lake above');
UPDATE public.location_iconic_spots SET spot_text = 'Escalator steps flowing upward as a river carrying live fish', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '49584542-af4c-4b8c-b0b9-4a089212fc07' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Escalator steps flowing upward as a river carrying live fish');
UPDATE public.location_iconic_spots SET spot_text = 'Carbonated ocean with sea creatures hanging mid-air in upward bubbles', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '5af00846-5981-4b73-98b5-e4332107b26e' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Carbonated ocean with sea creatures hanging mid-air in upward bubbles');
UPDATE public.location_iconic_spots SET spot_text = 'Glass floor revealing underground city built sideways beneath your feet', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '5af3b153-be50-4e53-a489-a1e5a56872b3' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Glass floor revealing underground city built sideways beneath your feet');
UPDATE public.location_iconic_spots SET spot_text = 'Waterfalls spiraling upward, condensing into floating stone stepping-pads', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '5ce59fac-7490-4be9-b71c-4a76e1eb7406' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Waterfalls spiraling upward, condensing into floating stone stepping-pads');
UPDATE public.location_iconic_spots SET spot_text = 'Tree-branching staircases with steps leading up to floating sky platforms', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '60a55f6a-4a05-49ba-b9aa-24ca87075026' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Tree-branching staircases with steps leading up to floating sky platforms');
UPDATE public.location_iconic_spots SET spot_text = 'Flowers hanging root-free from sky like stalactites, petals facing down', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '66a26ffb-c9d7-4631-a275-c7b8417fe019' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Flowers hanging root-free from sky like stalactites, petals facing down');
UPDATE public.location_iconic_spots SET spot_text = 'Puddle rain rising upward as inverse waterfalls piercing open sky', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '6891f848-2dcc-4c2e-9075-05e589a5a7ed' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Puddle rain rising upward as inverse waterfalls piercing open sky');
UPDATE public.location_iconic_spots SET spot_text = 'Clouds sinking to ground while boulders drift upward like balloons', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '69d166b5-38f2-444e-b011-4e52172f0fb8' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Clouds sinking to ground while boulders drift upward like balloons');
UPDATE public.location_iconic_spots SET spot_text = 'Clouds raining upward into space above inverted hanging treetops', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '6dfdf40d-09c1-4028-812b-8d59cadd1590' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Clouds raining upward into space above inverted hanging treetops');
UPDATE public.location_iconic_spots SET spot_text = 'Sideways trees with roots in floating horizontal rivers of water', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '7173cb26-e139-4dd8-95df-f021b57e131c' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Sideways trees with roots in floating horizontal rivers of water');
UPDATE public.location_iconic_spots SET spot_text = 'Puddles clinging flat to vertical stone walls, splashes frozen sideways', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '7436545a-1d4d-4014-b1d2-1036d27c3690' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Puddles clinging flat to vertical stone walls, splashes frozen sideways');
UPDATE public.location_iconic_spots SET spot_text = 'River flowing straight upward into ceiling of cascading overhead streams', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '762ba3fd-1795-4351-9f01-f472b0fe1e79' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'River flowing straight upward into ceiling of cascading overhead streams');
UPDATE public.location_iconic_spots SET spot_text = 'Shower water arcing across ceiling then raining from light fixtures', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '78dd7a52-ab7a-4f61-89ed-3a74ee6a566b' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Shower water arcing across ceiling then raining from light fixtures');
UPDATE public.location_iconic_spots SET spot_text = 'Rain rising upward from ground while mist snows gently downward', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '7e7804d6-5e68-429f-b9f6-deea4d230a50' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Rain rising upward from ground while mist snows gently downward');
UPDATE public.location_iconic_spots SET spot_text = 'Silver rain falling upward into mirror lakes on cloud undersides', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '834cfd60-9105-4cbf-845f-af3055791584' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Silver rain falling upward into mirror lakes on cloud undersides');
UPDATE public.location_iconic_spots SET spot_text = 'Stone balconies suspended in open sky, columns hanging down from clouds', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '84a05618-838f-47c5-bb35-d755dde2153a' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Stone balconies suspended in open sky, columns hanging down from clouds');
UPDATE public.location_iconic_spots SET spot_text = 'Open books floating in mid-air, arranged as walkable bridges over void', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = '87550334-ad8c-4922-b573-c24f4328b68e' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Open books floating in mid-air, arranged as walkable bridges over void');
UPDATE public.location_iconic_spots SET spot_text = 'Giant soap bubbles floating above meadow, each holding a sideways world', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '8f581790-538d-4483-92ea-86a6e7333b0a' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Giant soap bubbles floating above meadow, each holding a sideways world');
UPDATE public.location_iconic_spots SET spot_text = 'Playground slide extending straight upward through clouds toward open stars', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '9465319d-92e5-4112-939b-b7d9d0ba2540' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Playground slide extending straight upward through clouds toward open stars');
UPDATE public.location_iconic_spots SET spot_text = 'Ocean waves crashing up into sky, seaweed tangled in inverted clouds', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '9588747e-c2f8-420c-ac66-f321ad5b250c' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Ocean waves crashing up into sky, seaweed tangled in inverted clouds');
UPDATE public.location_iconic_spots SET spot_text = 'Boulders drifting freely upward while feathers are pinned to ground', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '96080763-32aa-469b-96e5-fab3c910f74b' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Boulders drifting freely upward while feathers are pinned to ground');
UPDATE public.location_iconic_spots SET spot_text = 'Stones and pebbles raining upward into clouds of pulverized diamond', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '9a40bf63-a39e-48b4-b5b2-c1fe224c2332' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Stones and pebbles raining upward into clouds of pulverized diamond');
UPDATE public.location_iconic_spots SET spot_text = 'Beach sand streaming upward from footprints toward a floating sky-ocean', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '9ac23907-9d81-4abc-acfe-c9408f8ff8a6' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Beach sand streaming upward from footprints toward a floating sky-ocean');
UPDATE public.location_iconic_spots SET spot_text = 'Waterfall pouring upward off cliff, origami fish mid-flight', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = '9d10c05c-4a3f-40c8-acb2-76e97f20e204' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Waterfall pouring upward off cliff, origami fish mid-flight');
UPDATE public.location_iconic_spots SET spot_text = 'Floating garden islands trailing roots, flowers dangling downward', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'a935754c-6acd-4167-99fe-aa8218baf20b' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Floating garden islands trailing roots, flowers dangling downward');
UPDATE public.location_iconic_spots SET spot_text = 'Honey drops rising upward, each globule holding a galaxy', spot_kind = 'intimate', pure_scene_eligible = false, character_eligible = true WHERE id = 'ae467727-a977-48a1-8e2a-5327ae3aed61' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Honey drops rising upward, each globule holding a galaxy');
UPDATE public.location_iconic_spots SET spot_text = 'Staircases ascending into open sky, furnished rooms on clouds', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'b16dcb17-3d1a-4340-ab1f-f2beed723644' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Staircases ascending into open sky, furnished rooms on clouds');
UPDATE public.location_iconic_spots SET spot_text = 'City blocks floating inverted, streets overhead, buildings hanging down', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'b2dace52-d7cd-49ed-b215-7f8faafd077c' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'City blocks floating inverted, streets overhead, buildings hanging down');
UPDATE public.location_iconic_spots SET spot_text = 'Underground cavern waterfall rising upward into ceiling of clouds', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'c351839e-d134-402b-8edc-9b8ebdfba282' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Underground cavern waterfall rising upward into ceiling of clouds');
UPDATE public.location_iconic_spots SET spot_text = 'Cloud city floating high, long balloon strings trailing to ground', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'c4a75c76-896f-4116-9616-ed6470c6bc05' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Cloud city floating high, long balloon strings trailing to ground');
UPDATE public.location_iconic_spots SET spot_text = 'Boulders drifting upward like balloons above sinking soap bubbles', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'c73d8e45-5cef-459d-8c2f-10fbae7120e8' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Boulders drifting upward like balloons above sinking soap bubbles');
UPDATE public.location_iconic_spots SET spot_text = 'Floating cloud islands bridged by arched fossilized-wind walkways', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'ce3cbfdf-667a-4af2-ad3d-9aaf7c842a0c' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Floating cloud islands bridged by arched fossilized-wind walkways');
UPDATE public.location_iconic_spots SET spot_text = 'Room flipped: chairs and tables floating below a walkable ceiling', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'cfe72ee0-0d10-4035-a0ad-6173fd6df4a0' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Room flipped: chairs and tables floating below a walkable ceiling');
UPDATE public.location_iconic_spots SET spot_text = 'Enormous flying whale carrying a city on its back', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'd97a2475-b37a-4c65-ada8-03c1268c212c' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Enormous flying whale carrying a city on its back');
UPDATE public.location_iconic_spots SET spot_text = 'Giant water bubbles drifting mid-air, seagulls nesting inside them', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'd9928860-1f7a-48e8-a5cf-72e6c247e2a6' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Giant water bubbles drifting mid-air, seagulls nesting inside them');
UPDATE public.location_iconic_spots SET spot_text = 'Liquid-metal river flowing uphill through glowing silk-leafed trees', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'dfc642e8-e352-4c32-a4dc-20269176960e' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Liquid-metal river flowing uphill through glowing silk-leafed trees');
UPDATE public.location_iconic_spots SET spot_text = 'Bioluminescent snowflakes drifting upward off a dark open plain', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'e3bf191b-cc25-46b7-9aff-b3c086a56ceb' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Bioluminescent snowflakes drifting upward off a dark open plain');
UPDATE public.location_iconic_spots SET spot_text = 'Ice spires growing upward from ground toward frozen aurora ceiling', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'e3fbf37d-db19-40c0-90aa-2e7edb2c2e26' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Ice spires growing upward from ground toward frozen aurora ceiling');
UPDATE public.location_iconic_spots SET spot_text = 'Hollow storm cloud, waterfall rising upward through its interior', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'ef8c3bad-7e09-4865-a358-20b2251e1378' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Hollow storm cloud, waterfall rising upward through its interior');
UPDATE public.location_iconic_spots SET spot_text = 'Mountains inverted, peaks buried underground, flat bases touching clouds', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'f73f651b-b789-441c-ac38-f1c0aec3aba3' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Mountains inverted, peaks buried underground, flat bases touching clouds');
UPDATE public.location_iconic_spots SET spot_text = 'Crystalline towers hanging downward from clouds into deep mist', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'f7b27bef-213b-4bd1-a9a8-a7a04eeac009' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Crystalline towers hanging downward from clouds into deep mist');
UPDATE public.location_iconic_spots SET spot_text = 'Café tables floating high over town square, coffee rising upward', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'f7e0b4ae-cc23-4df6-bf74-e8bc781245cb' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Café tables floating high over town square, coffee rising upward');
UPDATE public.location_iconic_spots SET spot_text = 'Staircases descending into open sky with nothing below them', spot_kind = 'medium', pure_scene_eligible = true, character_eligible = true WHERE id = 'f8611af7-3e5f-464a-9408-22f51ad50c6e' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Staircases descending into open sky with nothing below them');
UPDATE public.location_iconic_spots SET spot_text = 'Floating meadow islands spinning slowly, waterfalls spiraling off edges', spot_kind = 'wide', pure_scene_eligible = true, character_eligible = false WHERE id = 'fa1d1b63-0fd7-49b4-bf11-c82d0d0599ae' AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots d WHERE d.location_key = 'gravity-free realm' AND d.spot_text = 'Floating meadow islands spinning slowly, waterfalls spiraling off edges');

UPDATE public.location_iconic_spots SET is_active = false WHERE id IN ('2a297c10-edb7-4c81-bda5-8945ae484978', '44c84383-c0d1-4187-93bf-2ae047d88e77', 'ba6fb0b7-6974-4a11-8688-d625848e9a3a', '01b67d33-1b0a-4dc0-a8a6-21da90c1fcc9', '05b10dfd-905d-413b-ad2f-5727a6e12d49', '0f266704-6452-451c-b97a-d48a2756c5ad', '308b9800-5481-408d-8f19-15838f448d81', '5aa739b9-6049-4f5e-8ddb-4bf7685e12ea', '5e3972fd-6a8a-4f95-8a6a-5de1926cab5b', 'c502445c-ffc5-43f7-8487-81dae2d47008', 'c6edd6cb-2e2c-4cc3-b668-074ad198a2ee', '27d41926-3c80-4c90-9a6b-8bc6127faf1d', '3039a993-b2a2-4b58-bfc0-46293d4fbf9f', '4cbf2e5d-7d75-451c-b934-6379a0d79e7a', '56c2e347-0120-4224-ab4b-dba4ca731be3', '5894fdf1-14a7-4d51-9d6a-5ee505fb3b07', '6b5add17-ce3d-4002-a1b7-e535a9628b6f', '6ec26674-f1ac-41e2-8b35-6fe5050e82ee', '6f6705d9-4922-4a53-9f23-44bfdd47379f', '887d4629-dea9-4ca7-9b6d-794b4d9fbc62', '8f858cfc-88ba-4c85-a9fb-ce9635b069a7', '93a97977-566e-4e8e-9260-e895b3c4dbf2', 'ef5818e7-4549-4687-b9d9-d27b3e72842f', 'f5131392-a662-4090-8b3b-a696c7e4b66a', '3bc0364d-f9ee-4ee7-b358-1a4668bd25b8', '4abe1054-c0d2-46e4-98ec-17721cf3355a', '55829edc-5504-4167-adc3-94a3375c2853', '5e77ecd3-3263-42e1-b9ed-3cd684ae4f59', '778690db-fdc8-459d-8040-a6086d3a8169', '82fbee5e-c36d-44bc-a4b8-dc817c3360a9', '942592bf-50ae-4168-8070-dbe603defc66', 'aa2cdd63-0d17-4990-bd39-8cd5bc5aef46', 'f8e2e576-089d-47be-861d-cadf27f46875');
