-- 614: top up the three Romantic Escapes places (Kevin 2026-09-30: "top up the romance cards"). The tile audit found
-- them the shallowest cards in the picker: Lavender Fields 28 spots (14 usable in a dream with a face), Tuscan Villa 41,
-- Cherry Blossoms 55. New specific named places per new sub-region (Kenroku-en, Kakunodate, La Foce, Bagno Vignoni,
-- Grignan, Tihany, Wanaka...), told to avoid every place already used, strictly graded S/A, then the same set-dresser
-- pass as mig 605; 4 off-card results removed by hand (a Florence church twice, a harbour square, a garbled line).
-- Eligibility per the playbook: cast = non-wide, scene-only = non-intimate. After: Cherry 83, Tuscan 72, Lavender 70.
-- Re-runnable.

INSERT INTO public.location_iconic_spots (location_key, spot_text, spot_kind, quality_tier, is_active, pure_scene_eligible, character_eligible) VALUES
  ('cherry blossoms', 'Daigo-ji Sambo-in garden, gnarled blossom boughs over mossy stone', 'intimate', 'S', true, false, true),
  ('cherry blossoms', 'Daigo-ji five-storey pagoda, petals drifting past ancient cypress wood', 'medium', 'S', true, true, true),
  ('cherry blossoms', 'Daigo-ji garden pond, blossoms arching over still mirrored water', 'intimate', 'A', true, false, true),
  ('cherry blossoms', 'Hirano Shrine ancient cherry grove, stone lanterns lining the petal-strewn path', 'wide', 'A', true, true, false),
  ('cherry blossoms', 'Okazaki Canal, blossom canopy over still water, Higashiyama peaks beyond', 'wide', 'S', true, true, false),
  ('cherry blossoms', 'Keage Incline, iron rails vanishing beneath a soft cherry blossom canopy', 'medium', 'S', true, true, true),
  ('cherry blossoms', 'Kofuku-ji five-storey pagoda rising above Nara Park''s pale blossom sea', 'medium', 'S', true, true, true),
  ('cherry blossoms', 'Yoshino Kinpusen-ji Zao-do gate, cherry blossoms crowding its ancient timbers', 'medium', 'S', true, true, true),
  ('cherry blossoms', 'Nara Park stone lantern avenue, petals drifting over mossy paving', 'wide', 'A', true, true, false),
  ('cherry blossoms', 'Yoshino Kamichikurin-in terrace, blossoms spilling down the sacred hillside', 'wide', 'A', true, true, false),
  ('cherry blossoms', 'Kema Sakuranomiya stone embankment, blossom boughs arching low over the path', 'intimate', 'A', true, false, true),
  ('cherry blossoms', 'Himeji Kokoen walled garden, blossoms reflected in a stone-edged pond', 'intimate', 'A', true, false, true),
  ('cherry blossoms', 'Nara Ukimido hexagonal pavilion, cherry petals drifting on Sagiike Pond', 'medium', 'A', true, true, true),
  ('cherry blossoms', 'Yoshimizu Shrine veranda, blossoming hillsides cascading softly to the valley', 'wide', 'S', true, true, false),
  ('cherry blossoms', 'Kakunodate samurai lane, weeping cherry boughs over honey-toned earthen walls', 'wide', 'S', true, true, false),
  ('cherry blossoms', 'Kakunodate Bukeyashiki gate framed by cascading weeping cherry boughs', 'medium', 'A', true, true, true),
  ('cherry blossoms', 'Miharu Takizakura, solitary ancient weeping cherry, petals drifting to open hillside', 'medium', 'S', true, true, true),
  ('cherry blossoms', 'Takato Castle ruins, blush-pink blossom sea across mossy terraced embankments', 'wide', 'S', true, true, false),
  ('cherry blossoms', 'Kenroku-en Kotoji stone lantern, blossom boughs reflected in the garden pond', 'medium', 'S', true, true, true),
  ('cherry blossoms', 'Shiroishi River, thousand cherry trees lining the embankment in soft bloom', 'wide', 'S', true, true, false),
  ('cherry blossoms', 'Bomun Lake blossom-lined promenade, Gyeongju stone pagoda reflected in still water', 'wide', 'A', true, true, false),
  ('cherry blossoms', 'Gyeongju Anapji Pond, blossom boughs framing a reflected ancient stone pavilion', 'medium', 'A', true, true, true),
  ('cherry blossoms', 'Yeouido Hangang Park blossom avenue, petals drifting toward the gleaming river', 'wide', 'S', true, true, false),
  ('cherry blossoms', 'Yeouido 63 Building rising beyond a dense, pale cherry blossom canopy', 'medium', 'A', true, true, true),
  ('cherry blossoms', 'Amsterdam Bloesempark, blossoming trees and petals mirrored in the Amstel', 'wide', 'A', true, true, false),
  ('cherry blossoms', 'Branch Brook Park, Cathedral Basilica rising softly beyond a cherry blossom avenue', 'wide', 'S', true, true, false),
  ('cherry blossoms', 'Brooklyn Botanic Garden Cherry Esplanade, a pale pink avenue to the horizon', 'wide', 'S', true, true, false),
  ('cherry blossoms', 'Brooklyn Botanic Garden Japanese Hill-and-Pond, blossoms edging a mossy stone lantern', 'medium', 'A', true, true, true),
  ('tuscan villa', 'Piazzale Michelangelo stone terrace, bronze David, climbing roses on the balustrade', 'wide', 'S', true, true, false),
  ('tuscan villa', 'Bardini Garden wisteria tunnel, violet cascades over moss-worn stone steps', 'medium', 'A', true, true, true),
  ('tuscan villa', 'Bardini Garden belvedere balustrade, potted lemon trees framing Florence''s dome', 'wide', 'A', true, true, false),
  ('tuscan villa', 'San Miniato al Monte forecourt, marble facade, wrought-iron lanterns on honey-stone steps', 'medium', 'A', true, true, true),
  ('tuscan villa', 'Piazza del Campo, Siena, fan-shaped brick expanse, stone lanterns along the rim', 'wide', 'S', true, true, false),
  ('tuscan villa', 'Torre del Mangia, Siena, soaring above rooftops, climbing roses on the base', 'medium', 'A', true, true, true),
  ('tuscan villa', 'Monteriggioni circular walls, fourteen towers, wild roses threading the ancient ramparts', 'wide', 'A', true, true, false),
  ('tuscan villa', 'Monteriggioni inner piazza, stone-paved oval, a wrought-iron bench beneath blossoming boughs', 'intimate', 'A', true, false, true),
  ('tuscan villa', 'Sant''Antimo abbey apse, pale travertine, climbing roses softening the cypress grove', 'medium', 'A', true, true, true),
  ('tuscan villa', 'Lucca Renaissance ramparts, tree-lined promenade, linen-draped tables among the oak canopy', 'wide', 'A', true, true, false),
  ('tuscan villa', 'Lucca Piazza dell''Anfiteatro, oval ring of medieval facades draped in climbing roses', 'medium', 'A', true, true, true),
  ('tuscan villa', 'Argiano Montalcino hilltop terrace, linen-draped tables among Brunello vines, Monte Amiata beyond', 'wide', 'A', true, true, false),
  ('lavender fields', 'Simiane-la-Rotonde rotunda above lavender-filled valley, honey-stone walls', 'medium', 'A', true, true, true),
  ('lavender fields', 'Forcalquier citadel terrace, lavender-bordered steps, wrought-iron bench', 'medium', 'A', true, true, true),
  ('lavender fields', 'Plateau d''Albion lavender ocean rolling to bare limestone ridgeline', 'wide', 'A', true, true, false),
  ('lavender fields', 'Valensole stone farmhouse doorway, lavender rows, climbing roses on walls', 'intimate', 'A', true, false, true),
  ('lavender fields', 'Valensole almond tree rising from a flowering lavender sea', 'medium', 'S', true, true, true),
  ('lavender fields', 'Forcalquier Couvent des Cordeliers cloister, lavender edging honey-stone columns', 'intimate', 'A', true, false, true),
  ('lavender fields', 'Simiane-la-Rotonde lavender-lined path curving toward the Romanesque rotunda', 'medium', 'A', true, true, true),
  ('lavender fields', 'Château du Bois distillery courtyard, copper alembic, climbing roses on stone', 'intimate', 'A', true, false, true),
  ('lavender fields', 'Abbaye de Sénanque stone bell tower rising above violet rows', 'medium', 'S', true, true, true),
  ('lavender fields', 'Château du Bois lavender rows descending toward the Luberon valley', 'wide', 'A', true, true, false),
  ('lavender fields', 'Lourmarin château stone staircase, lavender-edged balustrades, potted lemon trees', 'intimate', 'A', true, false, true),
  ('lavender fields', 'Abbaye de Sénanque lavender-lined footpath beside the ancient cloister wall', 'intimate', 'S', true, false, true),
  ('lavender fields', 'Silvacane Abbey apse, honey-stone Romanesque curve above a lavender border', 'medium', 'A', true, true, true),
  ('lavender fields', 'Château de Trigance stone ramparts above terraced Var lavender slopes', 'medium', 'A', true, true, true),
  ('lavender fields', 'Thoronet Abbey cloister, lavender edging the central stone wellhead', 'intimate', 'A', true, false, true),
  ('lavender fields', 'Shikisai-no-Oka flower terraces descending toward Tokachi-Dake peaks', 'wide', 'S', true, true, false),
  ('lavender fields', 'Kanno Farm hilltop lavender rows beside a red-roofed timber barn', 'medium', 'A', true, true, true),
  ('lavender fields', 'Nakafurano lavender hill crest, a weathered wooden observation tower', 'medium', 'A', true, true, true),
  ('lavender fields', 'Hinode Park lavender slope curving to the Furano basin below', 'wide', 'A', true, true, false),
  ('lavender fields', 'Nakafurano valley lavender patchwork, stone lanterns lining the ridge path', 'wide', 'A', true, true, false),
  ('lavender fields', 'Hitchin Lavender hillside rows, a wrought-iron bench among the blossoms', 'wide', 'A', true, true, false),
  ('lavender fields', 'Yorkshire Lavender terrace, Howardian Hills rolling beyond a honey-stone wall', 'wide', 'A', true, true, false),
  ('lavender fields', 'Wanaka Lavender Farm rows framing snowy Buchanan Peaks, a tiny footbridge', 'medium', 'S', true, true, true),
  ('lavender fields', 'Jardin du Soleil lavender labyrinth, Sequim, fairy lights on a pergola', 'medium', 'A', true, true, true),
  ('lavender fields', 'Sequim lavender fields, linen-draped tables among the violet rows', 'wide', 'A', true, true, false),
  ('tuscan villa', 'La Foce zigzag cypress road, pale clay hillside', 'wide', 'S', true, true, false),
  ('tuscan villa', 'La Foce garden, clipped box parterre beside a stone sundial', 'intimate', 'A', true, false, true),
  ('tuscan villa', 'La Foce wisteria pergola, stone columns draped in violet clusters', 'intimate', 'A', true, false, true),
  ('tuscan villa', 'Villa Vignamaggio vine-covered courtyard, terracotta urns along the colonnade', 'medium', 'A', true, true, true),
  ('tuscan villa', 'Boboli Gardens Kaffeehaus terrace, stone balustrade above Florence rooftops', 'medium', 'A', true, true, true),
  ('tuscan villa', 'Boboli Gardens Vasca dell''Isola, tiny arched bridge over still water', 'medium', 'A', true, true, true),
  ('tuscan villa', 'Monticchiello stone lane, climbing roses between honey-stone walls', 'intimate', 'A', true, false, true),
  ('tuscan villa', 'Bagno Vignoni stone loggia, potted lemon trees above the thermal pool', 'medium', 'S', true, true, true),
  ('tuscan villa', 'Monticchiello belvedere, stone parapet above Val d''Orcia patchwork hills', 'wide', 'A', true, true, false),
  ('tuscan villa', 'San Biagio travertine forecourt, petals drifting toward vine-covered hills', 'medium', 'A', true, true, true),
  ('tuscan villa', 'Pienza Via dell''Amore, climbing roses on honey-stone walls', 'intimate', 'A', true, false, true),
  ('tuscan villa', 'Cortona Via Janelli, medieval stone overhang arching a cobbled lane', 'intimate', 'A', true, false, true),
  ('tuscan villa', 'Montepulciano Piazza Grande well, wrought-iron crown above travertine surround', 'intimate', 'A', true, false, true),
  ('tuscan villa', 'Pienza Palazzo Piccolomini hanging garden, boxwood parterres above Val d''Orcia', 'wide', 'S', true, true, false),
  ('tuscan villa', 'Pienza cathedral apse terrace, stone balustrade above cypress-dotted valley', 'wide', 'A', true, true, false),
  ('tuscan villa', 'Siena Duomo, marble-striped facade above wide cathedral steps', 'medium', 'A', true, true, true),
  ('tuscan villa', 'Contrada alley Siena, narrow stone lane draped with silk banners', 'intimate', 'A', true, false, true),
  ('tuscan villa', 'Lucca Piazza San Michele, carved Romanesque arcade of climbing roses', 'medium', 'A', true, true, true),
  ('tuscan villa', 'Castello di Brolio garden terrace, stone balustrade above cypress avenues', 'wide', 'A', true, true, false),
  ('lavender fields', 'Tihany lavender terraces, stone retaining walls descending to Lake Balaton', 'wide', 'A', true, true, false),
  ('lavender fields', 'Tihany Old Church ruins, lavender borders framing weathered Romanesque stone', 'medium', 'A', true, true, true),
  ('lavender fields', 'Velo Grablje stone lane, lavender spilling softly between ancient cobbles', 'medium', 'A', true, true, true),
  ('lavender fields', 'Stari Grad plain, dry-stone lavender enclosures beneath distant Biokovo ridge', 'wide', 'A', true, true, false),
  ('lavender fields', 'Grignan château terrace, lavender parterre descending toward the Drôme valley', 'medium', 'S', true, true, true),
  ('lavender fields', 'Nyons olive-mill courtyard, lavender borders edging the worn stone threshold', 'intimate', 'A', true, false, true),
  ('lavender fields', 'Grignan collegiate church, lavender-edged honey-limestone steps and carved doorway', 'intimate', 'A', true, false, true),
  ('lavender fields', 'Grignan château great lawn, lavender parterre framing the Renaissance stone façade', 'wide', 'S', true, true, false),
  ('lavender fields', 'Gordes cobblestone lane, lavender spilling against sun-warmed golden stone walls', 'intimate', 'A', true, false, true),
  ('lavender fields', 'Gordes stone fountain basin, lavender borders ringing the quiet village square', 'medium', 'A', true, true, true),
  ('lavender fields', 'Roussillon village gateway arch, lavender borders framing warm ochre stone', 'medium', 'A', true, true, true),
  ('lavender fields', 'Gordes rampart overlook, lavender-stitched stone terraces cascading toward the valley', 'wide', 'S', true, true, false),
  ('lavender fields', 'Gordes Romanesque church portal, lavender flanking the carved honey-stone arch', 'medium', 'A', true, true, true),
  ('lavender fields', 'Roussillon ochre path, lavender-bordered terraces descending toward the Luberon plain', 'wide', 'A', true, true, false),
  ('lavender fields', 'Bridestowe Estate, purple lavender rows sweeping toward the Ben Lomond plateau', 'wide', 'S', true, true, false),
  ('lavender fields', 'Pelindaba Lavender Farm, fragrant rows descending toward the San Juan Island shore', 'wide', 'A', true, true, false),
  ('lavender fields', 'Terra Rosa lavender terraces above Lake Wanaka, Buchanan Peaks rising beyond', 'wide', 'A', true, true, false)
ON CONFLICT (location_key, spot_text) DO NOTHING;
