-- 615: three new Dreamscapes worlds (Kevin 2026-09-30: "yes, build all three"): Celestial, Overgrown Wonders and
-- Impossible Architecture, the thinnest tile's top-up (2 cards, 206 spots before this). Spots: the paid-for surreal
-- rewrites of each world's source categories (cosmic; overgrown + decay_beauty; impossible_architecture), minus the ones
-- live in Glowing Elements and Impossible Whimsy, curated against the world's concept, topped up with fresh spots and
-- strictly graded (S, then A), near-duplicates dropped. Every spot carries its wonder in the look itself: Flux drops
-- impossible scale and physics (the lesson that retired Land of Giants and Gravity's Off, mig 609).
-- Recipes from generate-full-location-card.js under descriptive names, renamed here; biome fantasy_imagined; biome_config
-- cleared for gen-location-biome.js / gen-location-wardrobe.js, then imagined = true. Like the other Dreamscapes cards:
-- couples_ok = false (solo and scene-only, Kevin) and admin_only until the 1.11.0 go-live. Re-runnable.

UPDATE public.location_cards SET name = 'celestial realm' WHERE name ILIKE 'celestial, a dreamy world%'
  AND NOT EXISTS (SELECT 1 FROM public.location_cards WHERE name = 'celestial realm');
UPDATE public.location_cards SET display_name = 'Celestial', picker_category = 'surreal_dreams', picker_tile = 'surreal_dreams',
  picker_sort_order = 30, biome = 'fantasy_imagined', biome_config = NULL, is_approved = true, admin_only = true,
  content_kind = 'place', couples_ok = false, sub_regions = ARRAY['Planet-rise meadows and gardens', 'Starlit lakes, shores and waterfalls', 'Observatories, domes and glass pavilions', 'Nebula valleys and cloud terraces']::text[], must_include = ARRAY['a ringed planet or a huge moon low over the horizon', 'nebula colours in the sky', 'stars reflected in still water', 'glass observatories, pavilions and telescope terraces', 'flower meadows and gardens under the cosmos', 'dreamy, luminous, romantic']::text[]
WHERE name = 'celestial realm';
INSERT INTO public.location_iconic_spots (location_key, spot_text, spot_kind, quality_tier, is_active, pure_scene_eligible, character_eligible) VALUES
  ('celestial realm', 'Ringed planet low over a moonlit observatory terrace', 'wide', 'S', true, true, false),
  ('celestial realm', 'Garden where luminous planets ripen on silver-leafed vines', 'medium', 'S', true, true, true),
  ('celestial realm', 'Saturn''s jewelled rings arching over a glowing crystal lake', 'wide', 'S', true, true, false),
  ('celestial realm', 'Ringed planets stacked at the horizon above silver wheat fields', 'wide', 'S', true, true, false),
  ('celestial realm', 'Galactic arm curving low over a mirrored mountain lake', 'wide', 'S', true, true, false),
  ('celestial realm', 'Star-field reflected across a vast flooded plain of still water', 'wide', 'S', true, true, false),
  ('celestial realm', 'Sapphire gas giant cradled between two moonlit mountain peaks', 'wide', 'S', true, true, false),
  ('celestial realm', 'Moonlit stone amphitheatre open to a vast nebula-filled sky', 'wide', 'S', true, true, false),
  ('celestial realm', 'Wide lavender lake perfectly mirroring a ringed planet above', 'wide', 'S', true, true, false),
  ('celestial realm', 'Ringed planet filling the sky above a single moonlit gazebo', 'medium', 'S', true, true, true),
  ('celestial realm', 'Silver-leafed orchard beneath a swollen luminous harvest moon', 'medium', 'S', true, true, true),
  ('celestial realm', 'Ancient stone sundial beneath a ringed planet at low noon', 'medium', 'S', true, true, true),
  ('celestial realm', 'Wisteria-covered pergola beneath twin glowing moons', 'medium', 'S', true, true, true),
  ('celestial realm', 'Vine-draped marble columns framing a luminous planetary ring above', 'medium', 'S', true, true, true),
  ('celestial realm', 'Spiral staircase of pale stone ascending into nebula-coloured clouds', 'medium', 'S', true, true, true),
  ('celestial realm', 'Cliff-edge telescope platform facing a low ringed planet', 'medium', 'S', true, true, true),
  ('celestial realm', 'Willow-draped lakeside pavilion beneath a low amber gas giant', 'medium', 'S', true, true, true),
  ('celestial realm', 'Ancient armillary sphere on a pedestal beneath a nebula sky', 'medium', 'S', true, true, true),
  ('celestial realm', 'Cobblestone courtyard with a ringed planet framed by rooftops', 'medium', 'S', true, true, true),
  ('celestial realm', 'Alcove window seat framing a single luminous ringed planet', 'intimate', 'S', true, false, true),
  ('celestial realm', 'Ivy-covered doorway framing a low luminous crescent moon beyond', 'intimate', 'S', true, false, true),
  ('celestial realm', 'Balcony railing draped with star-jasmine beneath a low ringed planet', 'intimate', 'S', true, false, true),
  ('celestial realm', 'Solar eclipse forming a luminous halo-doorway in a nebula sky', 'wide', 'A', true, true, false),
  ('celestial realm', 'Constellation patterns traced in luminous dots across a violet sky', 'wide', 'A', true, true, false),
  ('celestial realm', 'Moon crater garden with vast ringed planet hanging overhead', 'wide', 'A', true, true, false),
  ('celestial realm', 'Jupiter''s vast luminous storm-eye visible through a glass observatory dome', 'medium', 'A', true, true, true),
  ('celestial realm', 'Jupiter''s great luminous eye-storm beyond a moonlit telescope terrace', 'wide', 'A', true, true, false),
  ('celestial realm', 'Three moons rising above a glowing lavender meadow', 'wide', 'A', true, true, false),
  ('celestial realm', 'Luminous nebula ceiling arching above a wide garden terrace', 'wide', 'A', true, true, false),
  ('celestial realm', 'Twin suns setting behind a ridge of pale crystalline hills', 'wide', 'A', true, true, false),
  ('celestial realm', 'Aurora ribbons layered above an endless field of silver grass', 'wide', 'A', true, true, false),
  ('celestial realm', 'Glass bridge over a star-scattered canyon beneath a ringed sky', 'wide', 'A', true, true, false),
  ('celestial realm', 'Cascading terraced pools reflecting a violet galactic core overhead', 'wide', 'A', true, true, false),
  ('celestial realm', 'Glowing planetary rings reflected in a calm glacier lake', 'wide', 'A', true, true, false),
  ('celestial realm', 'Pearl-coloured moon clusters above fog-softened meadow hills', 'wide', 'A', true, true, false),
  ('celestial realm', 'Crystal observatory dome cradling a glowing nebula within', 'medium', 'A', true, true, true),
  ('celestial realm', 'Moonlit pavilion columns wreathed in soft auroral light', 'medium', 'A', true, true, true),
  ('celestial realm', 'Glass greenhouse glowing from within under a deep nebula sky', 'medium', 'A', true, true, true),
  ('celestial realm', 'Stepped fountain of star-reflected water on a moonlit terrace', 'medium', 'A', true, true, true),
  ('celestial realm', 'Luminous tide pool with nebula colours shimmering beneath its surface', 'medium', 'A', true, true, true),
  ('celestial realm', 'Copper-domed observatory atop a hill ringed with glowing mist', 'medium', 'A', true, true, true),
  ('celestial realm', 'Star-bright koi pond set in a moonlit walled garden', 'medium', 'A', true, true, true),
  ('celestial realm', 'Luminous cave mouth opening to a meadow under nebula skies', 'medium', 'A', true, true, true),
  ('celestial realm', 'Stone bridge over a star-filled stream beneath a glowing moon', 'medium', 'A', true, true, true),
  ('celestial realm', 'Geode grotto walls glowing violet beneath a cracked crystal ceiling', 'medium', 'A', true, true, true),
  ('celestial realm', 'Moonlit stone jetty extending into a star-scattered luminous lake', 'medium', 'A', true, true, true),
  ('celestial realm', 'Glowing orrery of crystal planets on a candlelit reading table', 'intimate', 'A', true, false, true),
  ('celestial realm', 'Tiled fountain niche with star-maps inlaid in glowing mosaic', 'intimate', 'A', true, false, true),
  ('celestial realm', 'Canopied reading nook with a crystal window full of stars', 'intimate', 'A', true, false, true),
  ('celestial realm', 'Pocket garden of luminous night-blooming flowers under a crescent moon', 'intimate', 'A', true, false, true),
  ('celestial realm', 'Glass cabinet of miniature glowing planets on dark velvet shelves', 'intimate', 'A', true, false, true),
  ('celestial realm', 'Starlit reflecting pool set into a quiet enclosed courtyard', 'intimate', 'A', true, false, true),
  ('celestial realm', 'Circular garden well with glowing star-charts carved into its rim', 'intimate', 'A', true, false, true)
ON CONFLICT (location_key, spot_text) DO NOTHING;

UPDATE public.location_cards SET name = 'overgrown wonders' WHERE name ILIKE 'overgrown wonders, a dream world%'
  AND NOT EXISTS (SELECT 1 FROM public.location_cards WHERE name = 'overgrown wonders');
UPDATE public.location_cards SET display_name = 'Overgrown Wonders', picker_category = 'surreal_dreams', picker_tile = 'surreal_dreams',
  picker_sort_order = 40, biome = 'fantasy_imagined', biome_config = NULL, is_approved = true, admin_only = true,
  content_kind = 'place', couples_ok = false, sub_regions = ARRAY['Palaces and ballrooms in bloom', 'Libraries and reading rooms of vines', 'Cathedrals, chapels and cloisters of moss and flowers', 'Stations, theatres and glasshouses gone green']::text[], must_include = ARRAY['flowers and vines covering grand architecture', 'trees growing through floors and roofs', 'sunbeams through broken glass roofs and domes', 'moss, ferns and blossoms on marble and stone', 'lush and peaceful, never grim or rotten']::text[]
WHERE name = 'overgrown wonders';
INSERT INTO public.location_iconic_spots (location_key, spot_text, spot_kind, quality_tier, is_active, pure_scene_eligible, character_eligible) VALUES
  ('overgrown wonders', 'Skyscrapers draped in cascading purple-blossomed vines, windows wreathed in flowers', 'wide', 'S', true, true, false),
  ('overgrown wonders', 'Ballroom ceiling collapsed into a canopy of wisteria chandeliers', 'wide', 'S', true, true, false),
  ('overgrown wonders', 'Cathedral nave flooded knee-deep with white water lilies and moss', 'wide', 'S', true, true, false),
  ('overgrown wonders', 'Train station concourse roofless, blossoming cherry trees filling every platform', 'wide', 'S', true, true, false),
  ('overgrown wonders', 'Grand library atrium where shelves have become living hedgerows, blossom-topped', 'wide', 'S', true, true, false),
  ('overgrown wonders', 'Ruined amphitheatre terraces buried under rolling seas of lavender', 'wide', 'S', true, true, false),
  ('overgrown wonders', 'Conservatory long-hall where roof arches frame successive blossom-tree archways', 'wide', 'S', true, true, false),
  ('overgrown wonders', 'Baroque theatre exterior swallowed by climbing roses, balconies floral-crowned', 'wide', 'S', true, true, false),
  ('overgrown wonders', 'Marble staircase balustrade entirely consumed by spiralling pink roses', 'medium', 'S', true, true, true),
  ('overgrown wonders', 'Glasshouse door frame laced with passionflower blooms, sunbeams pouring through', 'medium', 'S', true, true, true),
  ('overgrown wonders', 'Spiral staircase colonised by ferns at every step, moss-carpeted treads', 'medium', 'S', true, true, true),
  ('overgrown wonders', 'Rusted iron library ladder draped entirely in delicate flowering jasmine', 'intimate', 'S', true, false, true),
  ('overgrown wonders', 'Library shelves where books root into blossoming story trees', 'wide', 'A', true, true, false),
  ('overgrown wonders', 'Marble fountain basins overflowing with luminescent lily ponds', 'medium', 'A', true, true, true),
  ('overgrown wonders', 'Terraced opera house tiers blanketed in cascading fern waterfalls', 'wide', 'A', true, true, false),
  ('overgrown wonders', 'Grand staircase plaza cascading with curtains of rose-draped balustrades', 'wide', 'A', true, true, false),
  ('overgrown wonders', 'Iron-lattice bridge over a gorge carpeted entirely in emerald moss', 'wide', 'A', true, true, false),
  ('overgrown wonders', 'Bathhouse marble pool brimming with floating pink water lilies', 'medium', 'A', true, true, true),
  ('overgrown wonders', 'Museum gallery archways framed entirely in living orchid curtains', 'medium', 'S', true, true, true),
  ('overgrown wonders', 'Ballroom chandelier swallowed entirely by cascading climbing roses', 'intimate', 'S', true, false, true),
  ('overgrown wonders', 'Train station platform clock pillar wrapped entirely in flowering ivy', 'intimate', 'A', true, false, true),
  ('overgrown wonders', 'Palace orangery with shattered panes, sunflowers rising through every gap', 'medium', 'S', true, true, true),
  ('overgrown wonders', 'Cathedral side chapel floor upholstered in dense violet-flowering moss', 'intimate', 'S', true, false, true),
  ('overgrown wonders', 'Iron-lattice arcade colonised by wisteria, purple clusters brushing every arch', 'medium', 'S', true, true, true),
  ('overgrown wonders', 'Bathhouse changing room alcove cushioned entirely in flowering jasmine vines', 'intimate', 'A', true, false, true),
  ('overgrown wonders', 'Clock tower belfry where climbing hydrangeas veil every brass bell', 'intimate', 'S', true, false, true),
  ('overgrown wonders', 'Library spiral gallery where every tier trails cascading flowering ivy', 'wide', 'A', true, true, false),
  ('overgrown wonders', 'Conservatory curved bench enveloped in a flowering rose canopy', 'intimate', 'A', true, false, true),
  ('overgrown wonders', 'Museum marble corridor where orchids spill from every wall niche', 'medium', 'A', true, true, true),
  ('overgrown wonders', 'Opera house stage floor blanketed in deep emerald ferns', 'medium', 'A', true, true, true),
  ('overgrown wonders', 'Palace ballroom columns crowned with cascading hydrangea garlands', 'medium', 'S', true, true, true),
  ('overgrown wonders', 'Theatre box draped entirely in curtains of flowering wisteria', 'intimate', 'S', true, false, true),
  ('overgrown wonders', 'Grand arcade vaulted ceiling swallowed by blossoming magnolia canopy', 'wide', 'S', true, true, false),
  ('overgrown wonders', 'Cloister garden courtyard carpeted in luminous violet-blue hydrangeas', 'wide', 'A', true, true, false),
  ('overgrown wonders', 'Bathhouse domed ceiling fractured open, cherry blossoms filling the vault', 'medium', 'S', true, true, true),
  ('overgrown wonders', 'Observatory copper telescope wrapped in a coil of climbing roses', 'intimate', 'S', true, false, true),
  ('overgrown wonders', 'Museum gallery skylight laced with a tracery of flowering ivy', 'medium', 'A', true, true, true),
  ('overgrown wonders', 'Palace corridor wall niches brimming with cascading pink orchids', 'medium', 'A', true, true, true),
  ('overgrown wonders', 'Train station iron canopy threaded entirely with blossoming wisteria', 'wide', 'S', true, true, false),
  ('overgrown wonders', 'Cathedral rose window ledge cushioned in dense flowering jasmine', 'intimate', 'A', true, false, true),
  ('overgrown wonders', 'Opera house gilded balcony railing laced with climbing hydrangeas', 'intimate', 'A', true, false, true),
  ('overgrown wonders', 'Carousel canopy smothered in a wreath of blush climbing roses', 'medium', 'S', true, true, true),
  ('overgrown wonders', 'Library reading alcove walls upholstered entirely in soft green moss', 'intimate', 'S', true, false, true),
  ('overgrown wonders', 'Glasshouse iron framework jewelled with hanging orchid clusters', 'medium', 'S', true, true, true),
  ('overgrown wonders', 'Bathhouse vaulted archway framed in a cascade of magnolia branches', 'medium', 'S', true, true, true),
  ('overgrown wonders', 'Clock tower stairwell walls furred with luminous fern fronds', 'intimate', 'A', true, false, true),
  ('overgrown wonders', 'Museum rotunda floor flooded shallow, water lilies drifting below skylights', 'wide', 'S', true, true, false),
  ('overgrown wonders', 'Library mezzanine railing colonised by cascading wisteria tendrils', 'medium', 'A', true, true, true),
  ('overgrown wonders', 'Arcade shop-front archways threaded with blossoming jasmine garlands', 'medium', 'A', true, true, true),
  ('overgrown wonders', 'Conservatory iron chair and table consumed by flowering ivy growth', 'intimate', 'A', true, false, true),
  ('overgrown wonders', 'Cathedral column base ringed by a moat of pink hydrangeas', 'intimate', 'A', true, false, true),
  ('overgrown wonders', 'Train station departure board lattice threaded with climbing cherry blossom', 'medium', 'S', true, true, true),
  ('overgrown wonders', 'Bathhouse mosaic floor half-revealed beneath a lawn of soft moss', 'medium', 'S', true, true, true),
  ('overgrown wonders', 'Observatory stone parapet edged with a row of blooming magnolias', 'wide', 'A', true, true, false),
  ('overgrown wonders', 'Cloister arcade corner overgrown into a bower of cherry blossoms', 'intimate', 'S', true, false, true),
  ('overgrown wonders', 'Grand library dome shattered open, fern fronds feathering toward light', 'wide', 'S', true, true, false),
  ('overgrown wonders', 'Carousel horse reins woven through with fresh wisteria sprays', 'intimate', 'S', true, false, true),
  ('overgrown wonders', 'Clock tower face cracked, hydrangea blossoms filling each numeral gap', 'medium', 'S', true, true, true),
  ('overgrown wonders', 'Museum glass cabinet interior colonised by a living orchid garden', 'intimate', 'S', true, false, true)
ON CONFLICT (location_key, spot_text) DO NOTHING;

UPDATE public.location_cards SET name = 'impossible architecture' WHERE name ILIKE 'impossible architecture, a dream world%'
  AND NOT EXISTS (SELECT 1 FROM public.location_cards WHERE name = 'impossible architecture');
UPDATE public.location_cards SET display_name = 'Impossible Architecture', picker_category = 'surreal_dreams', picker_tile = 'surreal_dreams',
  picker_sort_order = 50, biome = 'fantasy_imagined', biome_config = NULL, is_approved = true, admin_only = true,
  content_kind = 'place', couples_ok = false, sub_regions = ARRAY['Endless libraries and archives', 'Staircases and bridges into the clouds', 'Floating towers and sky palaces', 'Doorways and arches that open onto other places']::text[], must_include = ARRAY['architecture as the landscape: stairs, arches, towers, halls', 'clouds and open sky around and through the buildings', 'endless repetition of shelves, arches or stairs', 'serene, elegant and luminous, never ominous']::text[]
WHERE name = 'impossible architecture';
INSERT INTO public.location_iconic_spots (location_key, spot_text, spot_kind, quality_tier, is_active, pure_scene_eligible, character_eligible) VALUES
  ('impossible architecture', 'Honeycomb palace of towering hexagonal amber chambers', 'wide', 'S', true, true, false),
  ('impossible architecture', 'Cathedral of glass-clear arches and pillars filled with water', 'medium', 'S', true, true, true),
  ('impossible architecture', 'Palace built from giant spiral seashells with pearl-lined chambers', 'wide', 'S', true, true, false),
  ('impossible architecture', 'Library staircase of stacked books, gilded spines forming every step', 'medium', 'S', true, true, true),
  ('impossible architecture', 'Elevator shaft descending through glowing amber and crystal geological strata', 'intimate', 'S', true, false, true),
  ('impossible architecture', 'Floating archipelago of palace rooftops linked by arched glass walkways', 'wide', 'S', true, true, false),
  ('impossible architecture', 'Spiralling amphitheatre of white marble rising through layered cloud platforms', 'wide', 'S', true, true, false),
  ('impossible architecture', 'Staircase carved entirely from a single translucent alabaster boulder', 'medium', 'S', true, true, true),
  ('impossible architecture', 'Courtyard of columns and walls grown from geometric crystal', 'medium', 'A', true, true, true),
  ('impossible architecture', 'Twin staircases meeting at a midair landing above open sky', 'medium', 'A', true, true, true),
  ('impossible architecture', 'City of iridescent domes nested inside translucent soap-bubble walls', 'wide', 'A', true, true, false),
  ('impossible architecture', 'Cliffside city of balconied rooms carved directly into pale limestone', 'wide', 'A', true, true, false),
  ('impossible architecture', 'Stepped pyramid of open terraces, each terrace a walled garden', 'wide', 'A', true, true, false),
  ('impossible architecture', 'Brass arcade of interlocking gear-shaped archways', 'medium', 'A', true, true, true),
  ('impossible architecture', 'Rose quartz colonnade reflected in a still mercury floor', 'intimate', 'S', true, false, true),
  ('impossible architecture', 'Alabaster bridge curving between two doorless ivory towers', 'wide', 'A', true, true, false),
  ('impossible architecture', 'Stained glass rotunda with a floor of layered coloured panels', 'medium', 'A', true, true, true),
  ('impossible architecture', 'Mirrored hall of angled panels multiplying a single candle arch', 'intimate', 'S', true, false, true),
  ('impossible architecture', 'Amphitheatre of pale blue terraces cut into a cloudbank', 'wide', 'S', true, true, false),
  ('impossible architecture', 'Freestanding marble doorframe opening onto a porcelain courtyard', 'medium', 'A', true, true, true),
  ('impossible architecture', 'Library of hexagonal alcoves stacked floor to vanishing ceiling', 'intimate', 'S', true, false, true),
  ('impossible architecture', 'Glass dome resting on a lattice of slender alabaster ribs', 'medium', 'A', true, true, true),
  ('impossible architecture', 'Colonnaded terrace of rose quartz pillars above a cloud valley', 'wide', 'S', true, true, false),
  ('impossible architecture', 'Brass tower wound with an external helical staircase', 'medium', 'A', true, true, true),
  ('impossible architecture', 'Prism cathedral interior fracturing white light into floor mosaics', 'medium', 'S', true, true, true),
  ('impossible architecture', 'Arched bridge of translucent green glass spanning two cloud towers', 'wide', 'S', true, true, false),
  ('impossible architecture', 'Corridor of tall oval mirrors each framing a different sky', 'intimate', 'S', true, false, true),
  ('impossible architecture', 'Rotunda of alabaster ribs meeting at a skylight oculus', 'medium', 'A', true, true, true),
  ('impossible architecture', 'Winding staircase of brass treads cantilevered from a glass wall', 'medium', 'A', true, true, true),
  ('impossible architecture', 'Colonnade of twisted white marble columns beneath an open sky', 'medium', 'A', true, true, true),
  ('impossible architecture', 'Tower interior of concentric balconies circling a hollow luminous core', 'intimate', 'S', true, false, true),
  ('impossible architecture', 'Vast arcade of repeating pointed arches in pale limestone', 'wide', 'A', true, true, false),
  ('impossible architecture', 'Doorframe of carved rose quartz standing at a cloudbank edge', 'medium', 'S', true, true, true),
  ('impossible architecture', 'Spiral ramp of stained glass panels ascending a cylindrical shaft', 'medium', 'S', true, true, true),
  ('impossible architecture', 'Terrace of polished white stone cantilevered from a sky island', 'medium', 'A', true, true, true),
  ('impossible architecture', 'Intimate stairwell of alabaster steps lit by embedded glass tiles', 'intimate', 'A', true, false, true),
  ('impossible architecture', 'Glass hall with chevron vaults refracting light along the floor', 'medium', 'A', true, true, true),
  ('impossible architecture', 'Porcelain archway encrusted with miniature sculpted relief towers', 'intimate', 'S', true, false, true),
  ('impossible architecture', 'Mirrored dome enclosing a single brass spiral staircase', 'medium', 'S', true, true, true),
  ('impossible architecture', 'Narrow gallery of floor-to-ceiling leaded glass botanical panels', 'intimate', 'A', true, false, true),
  ('impossible architecture', 'Floating staircase of frosted glass treads between two open towers', 'medium', 'A', true, true, true),
  ('impossible architecture', 'Colonnaded sky bridge of pale ivory linking cloud-top pavilions', 'wide', 'S', true, true, false),
  ('impossible architecture', 'Pagoda tiers of turquoise-glazed porcelain diminishing into cloud', 'medium', 'S', true, true, true),
  ('impossible architecture', 'Open rotunda of slender brass columns beneath a crystal canopy', 'medium', 'A', true, true, true),
  ('impossible architecture', 'Arcade of interlocking alabaster horseshoe arches above a mirror floor', 'wide', 'S', true, true, false),
  ('impossible architecture', 'Spiral tower of open brass rings ascending through a cloudbank', 'wide', 'S', true, true, false),
  ('impossible architecture', 'Amphitheatre of rose quartz tiers encircling a glass stage floor', 'wide', 'S', true, true, false),
  ('impossible architecture', 'Suspended library of glass shelves spanning two alabaster cliff faces', 'wide', 'A', true, true, false),
  ('impossible architecture', 'Pagoda of interlocked white marble rings diminishing to a needle', 'medium', 'S', true, true, true),
  ('impossible architecture', 'Freestanding porcelain arch encrusted with bas-relief seashell spirals', 'medium', 'S', true, true, true),
  ('impossible architecture', 'Brass bridge of gear-toothed railings between two stained glass towers', 'medium', 'A', true, true, true),
  ('impossible architecture', 'Terrace of rose quartz slabs cantilevered above an alabaster gorge', 'medium', 'S', true, true, true),
  ('impossible architecture', 'Staircase of hollow glass treads each enclosing a preserved fern', 'medium', 'A', true, true, true),
  ('impossible architecture', 'Rotunda of tall arched niches each framing a porcelain tower', 'medium', 'S', true, true, true),
  ('impossible architecture', 'Latticed ivory gazebo at the centre of a cloud-island garden', 'medium', 'A', true, true, true),
  ('impossible architecture', 'Arched aqueduct of pale limestone carrying a still glass channel', 'medium', 'A', true, true, true),
  ('impossible architecture', 'Vaulted hall of alabaster ribs webbed with stained amber glass', 'medium', 'S', true, true, true),
  ('impossible architecture', 'Freestanding doorframe of woven brass wire standing over open cloud', 'intimate', 'S', true, false, true),
  ('impossible architecture', 'Corner of interlocking brass shelves holding spheres of coloured glass', 'intimate', 'A', true, false, true),
  ('impossible architecture', 'Porcelain alcove tiled in relief maps of imaginary palace grounds', 'intimate', 'A', true, false, true),
  ('impossible architecture', 'City of glass-floored plazas linked by arched alabaster overpasses', 'wide', 'A', true, true, false),
  ('impossible architecture', 'Endless hall of alternating ivory pilasters and stained glass bays', 'wide', 'S', true, true, false),
  ('impossible architecture', 'Sky archipelago of white stone terraces connected by glass-railed bridges', 'wide', 'S', true, true, false)
ON CONFLICT (location_key, spot_text) DO NOTHING;

DO $$
BEGIN
  IF (SELECT count(*) FROM public.location_cards WHERE name IN ('celestial realm', 'overgrown wonders', 'impossible architecture') AND picker_tile = 'surreal_dreams') <> 3 THEN
    RAISE EXCEPTION '615: expected the 3 renamed cards (did every recipe save?)';
  END IF;
END $$;
