-- 640: snow words off the warm cards (NIGHTLY_POOL_CLEANUP_PLAN.md phase 4; Kevin 2026-09-30: "do the snow rewording in
-- phase 4"). The outfit logic reads a spot's words (sceneSetting.ts: ski, snow, snowy, igloo, chalet, blizzard, sled...)
-- and dresses the cast for snow, so a spot where snow is only distant scenery or part of a name put parkas on a savanna,
-- a summer village street or a toy shop. Each rewrite keeps the place and the view and drops only the trigger word.
-- Kept as-is (the snow IS the place): the ski areas, Kilimanjaro's summit and crater, Ruapehu, Popocatepetl's pass,
-- Harbin, Sapporo's snow festival, the snow monkeys, Zao's statues, Kenroku-en's snow lanterns, Ainokura and Bodie in
-- snow, the spy lair's ski chalets, the Snow Queen's palace. Re-runnable (guarded on the old text).

UPDATE public.location_iconic_spots SET spot_text = 'Hardangerfjord apple orchard shoreline at Lofthus below the Folgefonna plateau' WHERE location_key = 'norwegian fjords' AND spot_text = 'Hardangerfjord apple orchard shoreline at Lofthus with snow-capped Folgefonna plateau behind';
UPDATE public.location_iconic_spots SET spot_text = 'Sognefjord wide open expanse from Balestrand waterfront looking toward distant mountain headlands' WHERE location_key = 'norwegian fjords' AND spot_text = 'Sognefjord wide open expanse from Balestrand waterfront looking toward distant snow-capped headlands';
UPDATE public.location_iconic_spots SET spot_text = 'Lewa Conservancy open savanna with Mount Kenya rising behind' WHERE location_key = 'african safari' AND spot_text = 'Lewa Conservancy open savanna with Mount Kenya snow peak backdrop';
UPDATE public.location_iconic_spots SET spot_text = 'Closet of clothes tailored from pressed seasons and crystallized frost' WHERE location_key = 'impossible wonderland' AND spot_text = 'Closet of clothes tailored from pressed seasons and crystallized snow';
UPDATE public.location_iconic_spots SET spot_text = 'Glass globes each containing a tiny orbiting solar system' WHERE location_key = 'impossible wonderland' AND spot_text = 'Snow globes each containing a tiny orbiting solar system';
UPDATE public.location_iconic_spots SET spot_text = 'Lake Thun castle Spiez vineyard terrace framing the pyramid of the Niesen' WHERE location_key = 'swiss alps' AND spot_text = 'Lake Thun castle Spiez vineyard terrace framing snow-capped Niesen';
UPDATE public.location_iconic_spots SET spot_text = 'Domes built from compressed sunlight, glowing warm within' WHERE location_key = 'luminous realm' AND spot_text = 'Igloos built from compressed sunlight, glowing warm within';
UPDATE public.location_iconic_spots SET spot_text = 'A drift of microscopic galaxies melting into glowing cosmic puddles' WHERE location_key = 'luminous realm' AND spot_text = 'Snow of microscopic galaxies melting into glowing cosmic puddles';
UPDATE public.location_iconic_spots SET spot_text = 'A flurry of glowing butterflies melting into pools of liquid moonlight' WHERE location_key = 'luminous realm' AND spot_text = 'Snow of glowing butterflies melting into pools of liquid moonlight';
UPDATE public.location_iconic_spots SET spot_text = 'Lewis Lake glassy surface framed by lodgepole pines and distant peaks at the south entrance' WHERE location_key = 'yellowstone' AND spot_text = 'Lewis Lake glassy surface framed by lodgepole pines and distant snowy peaks at the south entrance';
UPDATE public.location_iconic_spots SET spot_text = 'Canal Beagle rocky islet sea lion colony with the Darwin Range behind' WHERE location_key = 'patagonia' AND spot_text = 'Canal Beagle rocky islet sea lion colony with snow-capped Darwin Range behind';
UPDATE public.location_iconic_spots SET spot_text = 'Crystal Globe Pavilion central dome' WHERE location_key = 'enchanted toy shop' AND spot_text = 'Crystal Snow Globe Pavilion central dome';
UPDATE public.location_iconic_spots SET spot_text = 'The Fairest Mirror Pavilion reflective glass structure' WHERE location_key = 'enchanted toy shop' AND spot_text = 'The Snow White Mirror Pavilion reflective glass structure';
UPDATE public.location_iconic_spots SET spot_text = 'Crystal Globe Gallery suspended from raftered ceiling' WHERE location_key = 'enchanted toy shop' AND spot_text = 'Crystal Snow Globe Gallery suspended from raftered ceiling';
UPDATE public.location_iconic_spots SET spot_text = 'Curved bow launch ramp for STOVL aircraft' WHERE location_key = 'carrier flight deck' AND spot_text = 'Ski-jump ramp on bow for STOVL aircraft launch';
UPDATE public.location_iconic_spots SET spot_text = 'Wanaka Lavender Farm rows framing the Buchanan Peaks, a tiny footbridge' WHERE location_key = 'lavender fields' AND spot_text = 'Wanaka Lavender Farm rows framing snowy Buchanan Peaks, a tiny footbridge';
UPDATE public.location_iconic_spots SET spot_text = 'Steep granite waterfall trail above Tenaya Canyon' WHERE location_key = 'yosemite' AND spot_text = 'Snow Creek steep waterfall trail route';
UPDATE public.location_iconic_spots SET spot_text = 'The Seven Dwarfs'' Cottage in a forest clearing' WHERE location_key = 'princess garden castle' AND spot_text = 'Snow White''s Seven Dwarfs'' Cottage in forest clearing';
UPDATE public.location_iconic_spots SET spot_text = 'Berchtesgaden mountain village street with painted alpine houses' WHERE location_key = 'germany' AND spot_text = 'Berchtesgaden mountain village street with painted alpine chalets';
UPDATE public.location_iconic_spots SET spot_text = 'Thredbo Alpine Village summer wildflower walks' WHERE location_key = 'australia' AND spot_text = 'Thredbo Alpine Village ski resort summer wildflower walks';
UPDATE public.location_iconic_spots SET spot_text = 'Old Town of Lijiang rooftop labyrinth of grey tile and wooden eaves below the Yulong peaks' WHERE location_key = 'china' AND spot_text = 'Old Town of Lijiang rooftop labyrinth of grey tile and wooden eaves above Jade Dragon Snow Mountain';
UPDATE public.location_iconic_spots SET spot_text = 'Tin Mal Mosque ruined mihrab arches framed against the High Atlas peaks' WHERE location_key = 'morocco' AND spot_text = 'Tin Mal Mosque ruined mihrab arches framed against the High Atlas snow peaks';
