-- 648_men_wardrobe_whimsy_toned: the A/B for CARD_WARDROBE_GENDER_PLAN.md (switch on, Kevin's account) dressed men in
-- menswear on every card, but Impossible Wonderland's pick rendered a pink pastel tailcoat, candy-striped breeches and
-- white stockings: in-world, and the look Kevin called "fruity". The softest men's entries on the whimsical cards are
-- rewritten so the world shows through deep colour, armour and tailoring rather than blush, ruffles and stockings (Kawaii
-- Candy Land in cherry red and chocolate, Pastel Dreamscape in cream, slate and plum). Period norms stay (Rome's toga, a
-- pirate's ruffled shirt). Re-sets each card's full WARDROBE_MEN. Re-runnable.

UPDATE public.location_cards SET biome_config = biome_config || jsonb_build_object('WARDROBE_MEN', '["Billowing pearl-white silk frock coat with cloud-gradient lining, silver celestial-buckle belt", "Sculpted cumulus plate armour over storm-grey wool doublet, prismatic crystal pauldrons, silver boots", "Sleek opalescent leather fitted suit, high mandarin collar, cascading glowing-pearl chest buttons", "Deep storm-charcoal brocade duster, iridescent inner lining, wind-swept hem, crystal-tipped high boots", "Storm-grey brocade doublet with silver crescent-moon buckles, dark fitted breeches, tall riding boots, a sky-blue cloak", "Rugged sky-blue suede flight jacket over fitted ivory linen, storm-bolt embroidered shoulder panels", "Regal deep-violet velvet longcoat with gold cloud-motif brocade cuffs, towering silver-tipped collar"]'::jsonb)
  WHERE name = 'cloud kingdom';
UPDATE public.location_cards SET biome_config = biome_config || jsonb_build_object('WARDROBE_MEN', '["Sculpted amethyst-veined plate armour over deep violet brocade doublet, jagged geode pauldrons, mirrored-quartz greaves", "Floor-length prismatic frock coat, faceted crystal buttons, fitted onyx trousers, selenite-tipped boots", "Iridescent chainmail tunic over liquid-silver breeches, raw-quartz gauntlets, luminous gem-cluster gorget", "Midnight-blue leather duster with shattered-prism inlays, crystal-shard epaulettes, knee-high mirrored boots", "Glacial-white elven silk surcoat over carved moonstone breastplate, cascading crystal bead belt, bare-leather sandal boots", "Sleek obsidian fitted suit, embedded luminous quartz shards at lapels, dramatic layered prismatic cape, spiked crown", "Rugged geode-textured scale armour, laced leather tunic beneath, rough-cut crystal pendant cluster, storm-grey breeches", "Heavy amethyst-velvet cloak over a jeweled doublet, faceted crystal pauldrons, dark fitted trousers, raw-quartz-hilted sword"]'::jsonb)
  WHERE name = 'crystal caverns';
UPDATE public.location_cards SET biome_config = biome_config || jsonb_build_object('WARDROBE_MEN', '["Silver-etched elven doublet over brocade breeches, vine-laced tall boots, luminous antler clasp", "Iridescent beetle-shell plate armour, obsidian gauntlets, sweeping midnight cloak, rune-carved pauldrons", "Deep emerald frock coat in crushed velvet, gold-knot buttons, shadow-cloth breeches, gnarled staff", "Dragonscale breastplate over fitted leather trousers, billowing hood, glowing amber amulet, hip blade", "Moss-green leather ranger tunic over dark breeches, crystal-studded belt, silver-streaked hair tied back, a carved longbow", "Moss-green asymmetric duster, shadow-cloth fitted trousers, twin curved blades crossed at the back", "Moonpetal court doublet, silver-thread lacing, firefly-woven cravat, cascading split-hem brocade coat", "Woad-painted oak-bark chest piece over sculpted linen breeches, golden-chained boots, warrior-druid staff"]'::jsonb)
  WHERE name = 'enchanted forest';
UPDATE public.location_cards SET biome_config = biome_config || jsonb_build_object('WARDROBE_MEN', '["Iridescent brocade frock coat, brass clockwork buttons, velvet breeches, curled-toe enchanted boots", "Fitted doublet in candy-jewel silk, ruffled ivory cravat, fitted trousers, tiny clockwork crown", "Deep emerald velvet tailcoat, ruffled shirt, gold pocket-watch chain, buckle boots", "Patchwork leather duster with marionette-string gold chains, metallic trousers, buckle shoes", "Sleek midnight-and-scarlet ringmaster tailcoat, gilded belt, tall lacquered boots, ivory-tipped cane", "Midnight toymaker''s greatcoat with brass clockwork buttons, fitted metallic waistcoat, dark breeches, polished black boots"]'::jsonb)
  WHERE name = 'enchanted toy shop';
UPDATE public.location_cards SET biome_config = biome_config || jsonb_build_object('WARDROBE_MEN', '["Iridescent beetle-shell frock coat over ivory silk breeches, dewdrop crown, crystal-buckled flat boots", "Bronze petal-scale armoured doublet, gilded vine belt, dark breeches, tall amber leather boots", "Midnight velvet fae-court tunic over slim charcoal breeches, living-flower crown, silver-embroidered flat boots", "Draped violet-and-aquamarine silk greatcoat, moon-pearl lapel pins, wide breeches, enchanted ribbon sword-knot", "Floral brocade fitted jacket, thorn-and-rose epaulettes, ivory linen breeches, jeweled elbow-length gauntlets", "Deep bronze silk double-breasted suit, gilded antler clasp, dark pocket square, polished pointed boots", "Dark green velvet frock coat with gold teacup-embroidered cuffs, black breeches, a gemstone-topped cane, tall black top hat", "Dark-fae fitted obsidian wool longcoat, starlit silver scale armour breastplate, amethyst signet rings, silver-tipped pointed boots"]'::jsonb)
  WHERE name = 'fairy tea party';
UPDATE public.location_cards SET biome_config = biome_config || jsonb_build_object('WARDROBE_MEN', '["Iridescent frock coat over crystal-buttoned waistcoat, mirrored gauntlets, gravity-defying sculptural epaulettes", "Playing-card doublet in black and crimson, dark breeches, gilded pocket watch dripping starlight, sharp-toed brass boots", "Billowing opalescent phantom duster, luminous ankle-cuffed boots, impossible floating silhouette in shifting fabric", "Sleek white armoured breastplate hand-painted with surrealist motifs, glowing trim seams, crown of bent clocks", "Deep jewel-toned structured frock coat over liquid trousers, moth-wing clasp, chess-piece-buckled boots", "Mad-hatter emerald tailcoat, dark striped waistcoat, black trousers, tall top hat banded with playing cards", "Midnight-blue longcoat lined with shifting aurora light, dark tunic and breeches, braided gold belt, stars orbiting at the shoulders"]'::jsonb)
  WHERE name = 'impossible wonderland';
UPDATE public.location_cards SET biome_config = biome_config || jsonb_build_object('WARDROBE_MEN', '["Cherry-red velvet frock coat with candy-stripe lining, dark breeches, gold epaulettes, a hard-candy brooch", "Iridescent sugar-foil fitted suit, slim trousers, sculptural gumdrop cufflinks, mirror-polished dress shoes", "Polished candy-apple-red plate armour, sculpted pauldrons, crystalline sword, gold-plumed helm", "Black leather duster studded with confetti gems, dark fitted trousers, sprinkle-embossed leather boots", "Raspberry scale armour over a dark fitted tunic, chocolate-brown cape, crystalline wand at the hip", "Structured chocolate-brown leather tunic with caramel-drip trim, dark trousers, a macaron medallion", "Cherry-red vinyl flight jacket, deep magenta wool trousers, hard-candy toggles, black leather boots"]'::jsonb)
  WHERE name = 'kawaii candy land';
UPDATE public.location_cards SET biome_config = biome_config || jsonb_build_object('WARDROBE_MEN', '["Sculpted emerald plate armour with ivy-crawling joints, gold vine pauldrons, antlered visor", "Midnight velvet frock coat blooming sculpted fungi, fitted breeches, jeweled root-branch walking staff", "Moss-green doublet over bark-textured breeches, bioluminescent spore buttons, trailing enchanted-vine capelet", "Sleek dark-leather duster overgrown with climbing floral brocade panels, amber-jewel lapel pin", "Regal hooded cloak of tattered botanical velvet over leather armour, sculpted rose epaulettes, gilded thorn-crown, dark boots", "Fitted obsidian wool suit wrapped in spiraling sculptural vines, winged shoulder silhouette, glowing root clasp", "Iridescent silk brocade frock coat, vine-panel waistcoat, giant bloom-and-antler crown headdress", "Rugged waxed-linen flight jacket encrusted with living leaf-scale patches, bark-handled sword, moss-wrapped boots"]'::jsonb)
  WHERE name = 'overgrown wonders';
UPDATE public.location_cards SET biome_config = biome_config || jsonb_build_object('WARDROBE_MEN', '["iridescent mint plate armour with opalescent pauldrons, lavender plume, crystal-pommel sword", "Cream brocade frock coat with dusty-violet lining, dark slate breeches, an amethyst cravat pin", "Sleek slate-grey fitted suit with holographic lapels, soft-lilac pocket square, polished oxford shoes", "sculpted pastel-ombre scale armour over cloud-white linen tunic, trailing iridescent silk battle-cloak", "Long ivory duster over a fitted charcoal doublet, crystal-buckled boots, stardust-dusted epaulettes", "Deep plum velvet tailcoat, dark silver-grey trousers, stacked gemstone rings, a blossom boutonnière", "Structured cream leather flight jacket with mint stitching, pale gold trousers, opal-inlaid leather gauntlets", "Rugged sand-washed leather duster, scale-panelled dark trousers, rough-cut amethyst amulet, flat obsidian boots"]'::jsonb)
  WHERE name = 'pastel dreamscape';
UPDATE public.location_cards SET biome_config = biome_config || jsonb_build_object('WARDROBE_MEN', '["Ivory frock coat with crimson climbing-rose embroidery, gold epaulettes, champagne breeches, knee boots", "Rose-gold plate armour chased with blooming roses, scarlet cloak, gauntleted gloves, plumed helm", "Burgundy velvet doublet, ivory breeches, rose-quartz buttons, swept-back rapier with floral hilt", "Deep crimson tailcoat with gold rose embroidery, ivory waistcoat, slim black trousers, gilded buckle shoes", "Deep crimson duster over embroidered tunic and breeches, thorn-worked leather belt, dark riding boots", "Pale gold fitted suit, rose-silk lining, climbing-vine jacquard, jeweled cufflinks, white gloves", "Dramatic midnight-blue frock coat slashed with rose-gold, pearl buttons, ivory cravat, silver-capped boots", "Scale armour in burnished rose-copper, thorned pauldrons, forest-green cloak, vine-etched longsword at hip"]'::jsonb)
  WHERE name = 'rose garden palace';
UPDATE public.location_cards SET biome_config = biome_config || jsonb_build_object('WARDROBE_MEN', '["Liquid-mercury frock coat over iridescent scale-plate doublet, bioluminescent trim, jellyfish-silk cravat", "Abyssal black-pearl greatcoat with living-coral epaulettes, sea-glass buttons, fitted obsidian breeches and barnacle-silver boots", "Sleek atlantean warrior scale-armour: iridescent blue-green moulded breastplate, golden trident, form-fitted iridescent greaves", "Aquamarine silk tunic over dark scale-panelled breeches, tidal crown, a phosphorescent sash at the hip", "Deep-ocean commander: high-collared pearlescent fitted suit, bioluminescent swirling inlay, dramatic fishtail duster coat trailing behind", "Sculpted indigo velvet admiral''s coat: sea-serpent-scale lapels, gold shoulder fins, fitted iridescent trousers, pearl-handled ceremonial sword", "Fierce ocean-hunter: strapped onyx leather harness over midnight-blue armoured tunic, shell-carved daggers, storm-wave engraved pauldrons", "Crystalline sea-warlock: structured standing-collar robe in layered teal and deep violet brocade, living-light trim, black-pearl signet rings"]'::jsonb)
  WHERE name = 'underwater city atlantis';
UPDATE public.location_cards SET biome_config = biome_config || jsonb_build_object('WARDROBE_MEN', '["White and silver frock coat over a dark waistcoat, charcoal breeches, luminous horn-crested boots", "Shimmering rose-gold elven plate armour over fitted pearlescent underlayer, jewelled gauntlets, crested helm", "Structured champagne brocade doublet, velvet fitted trousers, opalescent cloak clasped with unicorn sigil", "Deep violet wool fitted suit, star-dusted lapels, glowing runic silver chain, mirrored crescent-toe boots", "Iridescent scale-mail tunic over dark breeches, crystal-tipped pauldrons, gleaming crescent blade at the hip", "Dramatic silver-embroidered white leather duster, liquid-satin trousers, cascading crystal sash, jewelled belt", "Deep teal silk frock coat, prismatic brocade waistcoat, fitted trousers, an antler circlet", "Midnight-teal velvet cloak over fitted silver-threaded tunic, knee-high jewelled boots, glowing amber brooch"]'::jsonb)
  WHERE name = 'unicorn meadow';
