-- 651_camera_spots_reworded_last: the last camera-direction spots left after mig 644 (NIGHTLY_POOL_CLEANUP_PLAN.md
-- open items), reworded into place phrasing by scripts/reword-camera-spots.js and reviewed ("Jingshan Park view over
-- Forbidden City" -> "Jingshan Park summit with the Forbidden City spreading below"). Same guards as 644. Re-runnable.

UPDATE public.location_iconic_spots s SET spot_text = 'Open pit-lane bay, halogen beams slicing chassis shadows across recessed drain channels in flat noon glare, the pit wall rising at the near edge' WHERE s.id = '39d863d6-20d8-40d2-a34f-2b772ab4d62b' AND s.spot_text = 'Over-pit-wall vantage looking back into open bay, halogen beams slicing chassis shadows across recessed drain channels in flat noon glare'
  AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots o WHERE o.location_key = s.location_key AND o.spot_text = 'Open pit-lane bay, halogen beams slicing chassis shadows across recessed drain channels in flat noon glare, the pit wall rising at the near edge');
UPDATE public.location_iconic_spots s SET spot_text = 'Aventine Keyhole with St. Peter''s dome perfectly framed within it' WHERE s.id = '46324008-dbe9-43f9-bc16-d66e5971b85e' AND s.spot_text = 'Aventine Keyhole view of St. Peter''s dome'
  AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots o WHERE o.location_key = s.location_key AND o.spot_text = 'Aventine Keyhole with St. Peter''s dome perfectly framed within it');
UPDATE public.location_iconic_spots s SET spot_text = 'Col de la Croix mountain saddle road, the lagoon spreading below with the full island and reef stretching to the horizon' WHERE s.id = '5898137d-8007-4a4b-b119-88af0081bc3f' AND s.spot_text = 'Panoramic lagoon view from the Col de la Croix mountain saddle road with full island and reef below'
  AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots o WHERE o.location_key = s.location_key AND o.spot_text = 'Col de la Croix mountain saddle road, the lagoon spreading below with the full island and reef stretching to the horizon');
UPDATE public.location_iconic_spots s SET spot_text = 'Full cottage clearing spreading to the surrounding canopy, lichen-covered roof and rust chimney pot at its centre, trees pressing close on all sides' WHERE s.id = 'a45dce99-1bc9-402d-998f-4b8dd4003b65' AND s.spot_text = 'Overhead wide of full cottage clearing, lichen roof, rust chimney pot, surrounding canopy pressing close'
  AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots o WHERE o.location_key = s.location_key AND o.spot_text = 'Full cottage clearing spreading to the surrounding canopy, lichen-covered roof and rust chimney pot at its centre, trees pressing close on all sides');
UPDATE public.location_iconic_spots s SET spot_text = 'Ballycastle harbour with Rathlin Island across the water' WHERE s.id = 'ca83b11b-9523-4fb0-9adc-d3c28600eca9' AND s.spot_text = 'Ballycastle harbour view toward Rathlin Island'
  AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots o WHERE o.location_key = s.location_key AND o.spot_text = 'Ballycastle harbour with Rathlin Island across the water');
UPDATE public.location_iconic_spots s SET spot_text = 'Jingshan Park summit with the Forbidden City spreading below' WHERE s.id = 'd16c0fcb-28df-4b86-ba52-66b967332613' AND s.spot_text = 'Jingshan Park view over Forbidden City'
  AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots o WHERE o.location_key = s.location_key AND o.spot_text = 'Jingshan Park summit with the Forbidden City spreading below');
UPDATE public.location_iconic_spots s SET spot_text = 'Three-tiered station interior under a pin-spot grid, sharp light cones isolating individual consoles in pools, surrounding space falling to navy shadow, holographic blue filling the gaps between all tiers' WHERE s.id = 'ff0ec4df-5df4-49d6-9ffe-e3e3e967c775' AND s.spot_text = 'Overhead pin-spot grid across all three tiers, sharp light cones isolating individual consoles in pools, surrounding space falling to navy shadow, holographic blue filling the gaps'
  AND NOT EXISTS (SELECT 1 FROM public.location_iconic_spots o WHERE o.location_key = s.location_key AND o.spot_text = 'Three-tiered station interior under a pin-spot grid, sharp light cones isolating individual consoles in pools, surrounding space falling to navy shadow, holographic blue filling the gaps between all tiers');
