-- 665_scenario_action_resplit_after_corridor_rewrites.sql — 15 scenario rows whose `action` (mig 516: a VERBATIM
-- slice of `scene`) went stale when migs 660 / 663 / 664 reworded the scene (2026-10-02).
--
-- Found by scripts/scan-scenario-actions.js (exit 1, 15 of 2,480). Effect while stale: the engine cuts the action out
-- of the scene by exact match (nightly-dreams applySpecial), finds nothing, so it renders the WHOLE new scene as the
-- place AND the OLD action as the people clause: the pre-rewrite wording comes back ("he stands planted wide-legged
-- BEHIND her" where the rewrite said "beside her", "neon TUNNEL lights") and the action text doubles.
-- Fix: re-derive each action from its new scene with the same splitter that built the column
-- (scripts/lib/scenarioSplit.js, allowBare on dual rows). 14 split at the same point as before; the one Halloween
-- row held a scenery fragment and its new scene has no people clause, so its action becomes NULL (the pose fallback
-- covers it). The rewrite tool now writes this update itself (fix-holiday-corridor-seeds.js writeSql).
-- Guarded on the current scene and the stale action. ROLLBACK: swap each SET and WHERE action value.

UPDATE public.dual_scenarios SET action = 'both mid-rally on inline skates pumping hard strokes on separate tracks arms swinging wide a lane apart both laughing toward the camera' WHERE id = 'aba102e3-56e0-4726-8dc8-acc832698395' AND scene = 'city waterfront skate rink both mid-rally on inline skates pumping hard strokes on separate tracks arms swinging wide a lane apart both laughing toward the camera' AND action = 'both midrallying on inline skates pumping hard strokes on separate lanes arms swinging wide a lane apart both laughing toward the camera';
UPDATE public.dual_scenarios SET action = 'she clambers up onto a low stone wall raising a glowing red paper fish lantern on a stick overhead, he scrambles up beside her hoisting a round golden lantern toward the hanging lights above, both laughing amid swaying luminous color' WHERE id = 'e8fabc40-8fa0-40c6-b17e-fd943bd36539' AND scene = 'Lantern festival night market, she clambers up onto a low stone wall raising a glowing red paper fish lantern on a stick overhead, he scrambles up beside her hoisting a round golden lantern toward the hanging lights above, both laughing amid swaying luminous color.' AND action = 'she clambers up onto a low stone step raising a glowing red paper fish lantern on a stick overhead, he scrambles up beside her hoisting a round golden lantern toward the hanging lights above, both laughing amid a corridor of swaying luminous color';
UPDATE public.dual_scenarios SET action = 'she holds a shimmering Bifrost lantern at chest level grinning bold at camera, he plants one boot on the rail laughing fierce, aurora columns and distant Asgard spires behind' WHERE id = '7f4f2c1d-eaa7-46e5-a2b0-bd28939dfc54' AND scene = 'Couple perched on the broad rainbow rail of Bifrost at cosmic twilight, she holds a shimmering Bifrost lantern at chest level grinning bold at camera, he plants one boot on the rail laughing fierce, aurora columns and distant Asgard spires behind.' AND action = 'she holds a shimmering Bifrost lantern at chest level grinning bold at camera, he plants one boot on the rainbow rail laughing fierce, aurora columns and distant Asgard spires behind';
UPDATE public.dual_scenarios SET action = NULL WHERE id = 'd8e8edf5-633a-47d7-80d7-2ef1ac0f8dd3' AND scene = 'Stacked-pumpkin clearing at the heart of the patch, towering carved and fiercely glowing pumpkin stacks rising on all sides, crimson fog rolling low, floating paper lanterns casting light overhead, silver moonbeams cutting through darkness, fireflies sparkling.' AND action = 'each carved and glowing fiercely, crimson fog rolling low, floating paper lanterns illuminating way, silver moonbeams cutting through darkness, fireflies sparkling';
UPDATE public.dual_scenarios SET action = 'he plants one boot on the rail low smirking wide at camera, she stands beside him arms open fierce and bold' WHERE id = 'f183d134-598b-470d-8dec-791fbb014176' AND scene = 'Neon-drenched footbridge side rail over a rain-flooded lower city, holograms reflecting below; he plants one boot on the rail low smirking wide at camera, she stands beside him arms open fierce and bold.' AND action = 'he plants one boot on the railing low smirking wide at camera, she stands beside him arms open fierce and bold';
UPDATE public.dual_scenarios SET action = 'she reads hieroglyphics from a stone wall with wide delighted eyes, he leans against the adjacent wall arms crossed grinning at camera' WHERE id = '918984bf-84e0-4abe-abf8-b0bc3511ab74' AND scene = 'Ancient tomb chamber glowing with golden candlelight, she reads hieroglyphics from a stone wall with wide delighted eyes, he leans against the adjacent wall arms crossed grinning at camera.' AND action = 'she reads hieroglyphics from a stone wall with wide delighted eyes, he leans against the opposite wall arms crossed grinning at camera';
UPDATE public.dual_scenarios SET action = 'she stands mid-step grinning fiercely at camera, he stands at the water''s edge hands on hips bold and laughing at viewer' WHERE id = 'a4f9dfee-a101-4140-8a13-263392a4c8c3' AND scene = 'Ancient stone bridge abutment beside a glowing underground river, she stands mid-step grinning fiercely at camera, he stands at the water''s edge hands on hips bold and laughing at viewer.' AND action = 'she strides forward mid-step grinning fiercely at camera, he stands at the bridge edge hands on hips bold and laughing at viewer';
UPDATE public.dual_scenarios SET action = 'she holds a glowing datapad at chest height beaming at camera, he leans on the railing arms folded smirking fierce' WHERE id = '51aa0a37-e185-4157-86eb-cd5d29585cf7' AND scene = 'Back-alley hacker den fire-escape platform, cascading neon code projections behind them; she holds a glowing datapad at chest height beaming at camera, he leans on the railing arms folded smirking fierce.' AND action = 'she holds a glowing datapad at chest height beaming at camera, he leans on the doorframe arms folded smirking fierce';
UPDATE public.dual_scenarios SET action = 'she strides forward one arm swung wide laughing at camera, he stands at the platform edge arms crossed grinning powerfully, starfields below' WHERE id = '8186bbaf-ca7e-48ef-b26c-d3c26e24d1a9' AND scene = 'Couple stands on a wide moonlit platform of solid starlight between two star-clusters, she strides forward one arm swung wide laughing at camera, he stands at the platform edge arms crossed grinning powerfully, starfields below.' AND action = 'she strides forward one arm swung wide laughing at camera, he stands at the bridge center arms crossed grinning powerfully, starfields below';
UPDATE public.dual_scenarios SET action = 'she grips the rope rail with a fierce grin, he stands planted wide-legged beside her with arms confidently crossed' WHERE id = '836ff952-aced-4fda-ae61-a16526901c6e' AND scene = 'Rickety rope-railed timber platform above a deep jungle canyon, she grips the rope rail with a fierce grin, he stands planted wide-legged beside her with arms confidently crossed.' AND action = 'she grips the rope rail mid-stride grinning fiercely, he stands planted wide-legged behind her with arms confidently crossed';
UPDATE public.dual_scenarios SET action = 'she points one arm downward at a swirling galaxy below grinning at camera, he stands upright beside her arms crossed smiling wide, stars glittering all around them' WHERE id = 'b45e7799-4ee9-4ae2-8c9e-d43760ee1612' AND scene = 'Standing at the wide constellation-mapped viewing platform of a linked-star sky bridge, she points one arm downward at a swirling galaxy below grinning at camera, he stands upright beside her arms crossed smiling wide, stars glittering all around them.' AND action = 'she points one arm downward at a swirling galaxy below grinning at camera, he stands upright beside her arms crossed smiling wide, stars mapping the path behind';
UPDATE public.dual_scenarios SET action = 'both uplifted faces and the entire luminous scene surrounding them' WHERE id = 'ad289996-48d7-4cf0-be3b-835297343d0f' AND scene = 'Two figures stride forward together into a Diwali night courtyard blazing with thousands of oil diyas, arms thrown wide and faces turned bright toward the viewer, chests open to the golden light, a warm gap of glowing air between their two radiant expressions, the magic of flickering flame dancing across both uplifted faces and the entire luminous scene surrounding them.' AND action = 'both uplifted faces and the entire luminous scene stretching behind them';
UPDATE public.dual_scenarios SET action = 'she leans on the rail grinning fierce at camera, he stands straight laughing bold hands in coat pockets, lantern-lit bridge arches and bioluminescent ice below' WHERE id = '79c1b210-c401-4833-ba53-53cce8951590' AND scene = 'Couple stands at the broad stone rail of a frozen river overlook at night, she leans on the rail grinning fierce at camera, he stands straight laughing bold hands in coat pockets, lantern-lit bridge arches and bioluminescent ice below.' AND action = 'she leans on the bridge rail grinning fierce at camera, he stands straight laughing bold hands in coat pockets, lantern-lit bridge arches and bioluminescent ice below';
UPDATE public.single_scenarios SET action = 'each star-point blazing gold, deep violet starfield blazing all around' WHERE id = '5706a215-8c8f-4179-b46a-67b8be12e2ca' AND scene = 'Poised on a star-chart dais ringed by giant glowing constellations, each star-point blazing gold, deep violet starfield blazing all around.' AND action = 'each star-point blazing gold, deep violet starfield stretching endlessly behind';
UPDATE public.single_scenarios SET action = 'both hands gripping the door frame at chest level, neon ceiling lights blazing behind him' WHERE id = 'ec6d50b9-1aa6-4716-9d18-291f48654141' AND scene = 'A man leans over the open door of a wide-body muscle car inside a smoke-filled parking vault, both hands gripping the door frame at chest level, neon ceiling lights blazing behind him.' AND action = 'both hands gripping the door frame at chest level, neon tunnel lights blazing behind him';
