/**
 * Face-swap safe actions — every action explicitly states face direction.
 * Generated by ChatGPT, curated for face-swap reliability.
 * Every entry contains a "face turned toward" clause.
 */

type Entry = {
  text: string;
  weight: number;
  tags?: string[];
};

export const ACTIONS_FACESWAP: Entry[] = [
  {
    text: 'walking toward the camera with a confident stride, looking toward the camera',
    weight: 8,
    tags: ['walking', 'dramatic'],
  },
  {
    text: 'running through the scene while glancing back toward the camera, face turned toward the viewer',
    weight: 8,
    tags: ['running', 'intense'],
  },
  {
    text: 'stepping forward through drifting smoke, three-quarter front angle, eyes visible and facing camera',
    weight: 7,
    tags: ['walking', 'mysterious'],
  },
  {
    text: 'standing in the rain wiping water from their forehead, head turned toward the camera',
    weight: 7,
    tags: ['standing', 'dramatic'],
  },
  {
    text: 'leaning against a wall while lighting a match, face turned toward the viewer',
    weight: 7,
    tags: ['standing', 'mysterious'],
  },
  {
    text: 'holding a lantern low near the waist while walking forward, looking toward the camera',
    weight: 7,
    tags: ['holding', 'mysterious'],
  },
  {
    text: 'holding a glowing artifact at chest height, eyes visible and facing camera',
    weight: 8,
    tags: ['holding', 'dramatic'],
  },
  {
    text: 'turning mid-step as if someone called their name, face turned toward the viewer',
    weight: 7,
    tags: ['walking', 'mysterious'],
  },
  {
    text: 'standing with arms crossed in a strong stance, looking toward the camera',
    weight: 7,
    tags: ['standing', 'dramatic'],
  },
  {
    text: 'standing with hands in pockets while wind moves their hair, head turned toward the camera',
    weight: 7,
    tags: ['standing', 'calm'],
  },
  {
    text: 'walking through a crowded market holding a small object close, glancing toward the camera',
    weight: 7,
    tags: ['walking', 'mysterious'],
  },
  {
    text: 'stepping carefully across broken glass, face turned toward the viewer',
    weight: 7,
    tags: ['walking', 'intense'],
  },
  {
    text: 'running while clutching a bag to their side, head turned toward the camera',
    weight: 8,
    tags: ['running', 'intense'],
  },
  {
    text: 'ducking under falling debris while glancing toward the camera, face clearly visible',
    weight: 8,
    tags: ['running', 'intense'],
  },
  {
    text: 'jumping across a gap between rooftops, eyes visible and facing camera',
    weight: 7,
    tags: ['jumping', 'intense'],
  },
  {
    text: 'sliding to a stop on wet pavement, face turned toward the viewer',
    weight: 7,
    tags: ['running', 'dramatic'],
  },
  {
    text: 'climbing a ladder quickly while looking toward the camera',
    weight: 7,
    tags: ['climbing', 'intense'],
  },
  {
    text: 'pulling themselves up onto a ledge, face turned toward the viewer',
    weight: 7,
    tags: ['climbing', 'intense'],
  },
  {
    text: 'kneeling beside a glowing object on the ground, head turned toward the camera',
    weight: 7,
    tags: ['holding', 'mysterious'],
  },
  {
    text: 'holding a torn map at chest height, glancing toward the camera',
    weight: 7,
    tags: ['holding', 'mysterious'],
  },
  {
    text: 'turning a flashlight beam into the darkness, head turned toward the camera',
    weight: 7,
    tags: ['holding', 'mysterious'],
  },
  {
    text: 'opening a heavy door while glancing toward the camera, face clearly visible',
    weight: 7,
    tags: ['holding', 'dramatic'],
  },
  {
    text: 'pushing aside hanging vines with one hand, face turned toward the viewer',
    weight: 7,
    tags: ['walking', 'mysterious'],
  },
  {
    text: 'standing in a doorway framed by light, three-quarter front angle facing the viewer',
    weight: 8,
    tags: ['standing', 'dramatic'],
  },
  {
    text: 'walking out of a foggy tunnel into moonlight, looking toward the camera',
    weight: 7,
    tags: ['walking', 'mysterious'],
  },
  {
    text: 'stepping through drifting snow while glancing toward the camera',
    weight: 7,
    tags: ['walking', 'dramatic'],
  },
  {
    text: 'standing at the edge of a vast vista but turning face toward the viewer',
    weight: 7,
    tags: ['standing', 'dramatic'],
  },
  {
    text: 'standing under neon signs with rain dripping from their hair, face turned toward the viewer',
    weight: 8,
    tags: ['standing', 'dramatic'],
  },
  {
    text: 'walking past flickering lights while glancing toward the camera',
    weight: 7,
    tags: ['walking', 'mysterious'],
  },
  {
    text: 'standing still as wind blows dust around them, eyes visible and facing camera',
    weight: 7,
    tags: ['standing', 'dramatic'],
  },
  {
    text: 'walking forward through falling ash, head turned toward the camera',
    weight: 7,
    tags: ['walking', 'dramatic'],
  },
  {
    text: 'drawing a blade while looking toward the camera, eyes visible',
    weight: 7,
    tags: ['fighting', 'intense'],
  },
  {
    text: 'standing in a defensive stance with weapon lowered, glancing toward the camera',
    weight: 7,
    tags: ['fighting', 'dramatic'],
  },
  {
    text: 'standing over a fallen enemy with weapon lowered, looking toward the camera',
    weight: 7,
    tags: ['fighting', 'dramatic'],
  },
  {
    text: 'casting swirling magic from both hands, eyes visible and facing camera',
    weight: 8,
    tags: ['casting', 'dramatic'],
  },
  {
    text: 'holding a glowing spell orb between palms at chest height, looking toward the camera',
    weight: 8,
    tags: ['casting', 'mysterious'],
  },
  {
    text: 'summoning floating runes around their body, face turned toward the viewer',
    weight: 7,
    tags: ['casting', 'dramatic'],
  },
  {
    text: 'opening a portal with one hand extended, face turned toward the viewer',
    weight: 7,
    tags: ['casting', 'dramatic'],
  },
  {
    text: 'walking forward as magic trails behind them, face turned toward the viewer',
    weight: 7,
    tags: ['casting', 'dramatic'],
  },
  {
    text: 'sitting on a ledge with legs dangling, looking toward the camera',
    weight: 6,
    tags: ['sitting', 'calm'],
  },
  {
    text: 'sitting at a table with a drink in hand, face turned toward the viewer',
    weight: 6,
    tags: ['sitting', 'mysterious'],
  },
  {
    text: 'sitting beside a campfire warming hands low, head turned toward the camera',
    weight: 6,
    tags: ['sitting', 'calm'],
  },
  {
    text: 'sitting in the driver seat with door open, head turned toward the camera',
    weight: 7,
    tags: ['sitting', 'dramatic'],
  },
  {
    text: 'sitting under a neon sign as rain falls, eyes visible and facing camera',
    weight: 7,
    tags: ['sitting', 'dramatic'],
  },
  {
    text: 'speaking to someone off-camera while keeping face turned toward the viewer',
    weight: 6,
    tags: ['speaking', 'mysterious'],
  },
  {
    text: 'whispering into a radio held near chest height, eyes visible and facing camera',
    weight: 7,
    tags: ['speaking', 'intense'],
  },
  {
    text: 'smirking slightly as if they know something, looking toward the camera',
    weight: 6,
    tags: ['standing', 'mysterious'],
  },
  {
    text: 'staring intensely at the viewer with a calm controlled expression, face turned toward the camera',
    weight: 7,
    tags: ['standing', 'intense'],
  },
  {
    text: 'turning their head sharply toward the camera as if hearing something behind you',
    weight: 7,
    tags: ['standing', 'intense'],
  },
  {
    text: 'walking through shallow water with ripples reflecting light, face turned toward the viewer',
    weight: 7,
    tags: ['walking', 'dramatic'],
  },
  {
    text: 'standing in a storm with lightning flashing, head turned toward the camera',
    weight: 7,
    tags: ['standing', 'dramatic'],
  },
  {
    text: 'walking through heavy snowfall while glancing toward the camera',
    weight: 7,
    tags: ['walking', 'dramatic'],
  },
  {
    text: 'standing under drifting cherry blossoms, eyes visible and facing camera',
    weight: 6,
    tags: ['standing', 'calm'],
  },
  {
    text: 'walking through a field of tall grass while glancing toward the camera',
    weight: 6,
    tags: ['walking', 'calm'],
  },
  {
    text: 'holding a guitar low near the waist while looking toward the camera',
    weight: 7,
    tags: ['holding', 'calm'],
  },
  {
    text: 'standing beside a vehicle with hand on the door, face turned toward the viewer',
    weight: 6,
    tags: ['standing', 'dramatic'],
  },
  {
    text: 'walking away from a car but turning head back toward the camera, face visible',
    weight: 7,
    tags: ['walking', 'mysterious'],
  },
  {
    text: 'sitting on the hood of a vehicle with arms relaxed, looking toward the camera',
    weight: 6,
    tags: ['sitting', 'dramatic'],
  },
  {
    text: 'standing in front of a giant portal while looking toward the camera, face clearly visible',
    weight: 8,
    tags: ['standing', 'dramatic'],
  },
  {
    text: 'walking down a long corridor of light with face turned toward the viewer',
    weight: 7,
    tags: ['walking', 'dramatic'],
  },
  {
    text: 'standing beneath towering statues with head turned toward the camera',
    weight: 7,
    tags: ['standing', 'dramatic'],
  },
  {
    text: 'walking through ruins with cloak flowing behind, eyes visible and facing camera',
    weight: 7,
    tags: ['walking', 'dramatic'],
  },
  {
    text: 'walking toward the camera through drifting lanterns, face turned toward the viewer',
    weight: 7,
    tags: ['walking', 'calm'],
  },
  {
    text: 'sprinting through neon reflections while keeping face turned toward the camera',
    weight: 8,
    tags: ['running', 'intense'],
  },
  {
    text: 'walking forward calmly as explosions flare behind, face turned toward the viewer',
    weight: 8,
    tags: ['walking', 'dramatic'],
  },
  {
    text: 'standing in swirling fog with a calm expression, looking toward the camera',
    weight: 7,
    tags: ['standing', 'mysterious'],
  },
  {
    text: 'standing in a shaft of god rays, three-quarter front angle facing the viewer',
    weight: 8,
    tags: ['standing', 'dramatic'],
  },
  {
    text: 'walking forward as fireflies swirl around, face turned toward the viewer',
    weight: 6,
    tags: ['walking', 'calm'],
  },
  {
    text: 'raising one hand as lightning crackles around fingers, face turned toward the viewer',
    weight: 7,
    tags: ['casting', 'dramatic'],
  },
  {
    text: 'walking toward the camera through a circle of runes, eyes visible',
    weight: 7,
    tags: ['walking', 'dramatic'],
  },
  {
    text: 'walking through a spaceport corridor with face turned toward the viewer',
    weight: 7,
    tags: ['walking', 'dramatic'],
  },
  {
    text: 'holding a futuristic helmet under one arm while glancing toward the camera',
    weight: 6,
    tags: ['holding', 'dramatic'],
  },
  {
    text: 'walking forward as neon holograms flicker, eyes visible and facing camera',
    weight: 7,
    tags: ['walking', 'dramatic'],
  },
  {
    text: 'holding a glowing energy core at chest height, face turned toward the viewer',
    weight: 8,
    tags: ['holding', 'dramatic'],
  },
  {
    text: 'standing under flickering fluorescent lights, head turned toward the camera',
    weight: 6,
    tags: ['standing', 'dramatic'],
  },
  {
    text: 'walking down ancient stone steps while glancing toward the camera',
    weight: 7,
    tags: ['walking', 'mysterious'],
  },
  {
    text: 'touching an ancient carved door with one hand, eyes visible and facing camera',
    weight: 7,
    tags: ['holding', 'mysterious'],
  },
  {
    text: 'holding a torch low while stepping into a crypt, face turned toward the viewer',
    weight: 7,
    tags: ['holding', 'dramatic'],
  },
  {
    text: 'standing under gothic arches with face turned toward the viewer, eyes visible',
    weight: 7,
    tags: ['standing', 'dramatic'],
  },
  {
    text: 'walking forward as shadows move behind them, face turned toward the viewer',
    weight: 7,
    tags: ['walking', 'intense'],
  },
  {
    text: 'walking forward through falling embers, eyes visible and facing camera',
    weight: 7,
    tags: ['walking', 'dramatic'],
  },
  {
    text: 'standing beside a molten river with face turned toward the viewer',
    weight: 7,
    tags: ['standing', 'dramatic'],
  },
  {
    text: 'standing with one knee on a step as if preparing to rise, looking toward the camera',
    weight: 6,
    tags: ['standing', 'intense'],
  },
  {
    text: 'walking through a field of glowing particles, face turned toward the viewer',
    weight: 6,
    tags: ['walking', 'mysterious'],
  },
  {
    text: 'walking toward the camera while cloak trails behind, three-quarter front angle',
    weight: 7,
    tags: ['walking', 'dramatic'],
  },
  {
    text: 'standing under stained glass light patterns, face turned toward the viewer',
    weight: 7,
    tags: ['standing', 'dramatic'],
  },
  {
    text: 'walking toward the camera through a tunnel of light, face turned toward the viewer',
    weight: 7,
    tags: ['walking', 'dramatic'],
  },
  {
    text: 'standing in the center of the scene holding an object low, face turned toward the viewer',
    weight: 6,
    tags: ['holding', 'calm'],
  },
];
