/**
 * Auto-generated by scripts/generate-scene-pools.js
 * 80 entries — do not edit manually, regenerate instead.
 */

type Entry = {
  text: string;
  weight: number;
  tags?: string[];
  rarity?: 'safe' | 'bold' | 'chaotic';
};

export const ACTIONS_WIDE: Entry[] = [
  {
    text: 'balancing on a narrow beam with arms extended for stability',
    weight: 5,
    tags: ['athletics'],
  },
  {
    text: 'swinging from a rope with legs bent mid-arc through space',
    weight: 5,
    tags: ['athletics'],
    rarity: 'bold',
  },
  {
    text: 'leaping from rooftop to rooftop with arms outstretched for balance',
    weight: 5,
    tags: ['athletics', 'exploration'],
    rarity: 'bold',
  },
  {
    text: 'deflecting incoming blades with twin daggers crossed in front defensively',
    weight: 5,
    tags: ['combat'],
    rarity: 'bold',
  },
  {
    text: 'crouching low and drawing a bow back with arms fully extended',
    weight: 5,
    tags: ['combat', 'athletics'],
  },
  {
    text: 'leaping sideways off a collapsing platform, arms windmilling for balance',
    weight: 5,
    tags: ['athletics', 'survival'],
    rarity: 'bold',
  },
  {
    text: 'pulling a wounded companion upright while scanning for danger',
    weight: 5,
    tags: ['combat', 'survival'],
  },
  {
    text: 'throwing a punch mid-swing with full body rotation and power',
    weight: 5,
    tags: ['combat', 'athletics'],
    rarity: 'bold',
  },
  {
    text: 'gripping reins tight while a massive beast rears beneath them',
    weight: 5,
    tags: ['riding', 'combat'],
    rarity: 'bold',
  },
  {
    text: 'leaping between floating platforms, arms windmilling to maintain balance mid-air',
    weight: 5,
    tags: ['athletics', 'exploration'],
    rarity: 'bold',
  },
  {
    text: 'crawling through a narrow passage, reaching forward with one arm extended',
    weight: 5,
    tags: ['exploration'],
  },
  {
    text: 'lifting a heavy fallen beam off someone trapped beneath it',
    weight: 5,
    tags: ['athletics', 'survival'],
    rarity: 'bold',
  },
  {
    text: 'sliding downhill with arms spread wide for balance, snow spraying',
    weight: 5,
    tags: ['athletics', 'survival'],
    rarity: 'bold',
  },
  {
    text: 'pulling themselves up over a wall edge, arms straining with effort',
    weight: 5,
    tags: ['athletics'],
  },
  {
    text: 'leaping sideways while drawing a sword from its sheath mid-air',
    weight: 5,
    tags: ['combat', 'athletics'],
    rarity: 'bold',
  },
  {
    text: 'pulling a bowstring back with arrow aimed diagonally upward, shoulders tense',
    weight: 5,
    tags: ['combat', 'athletics'],
  },
  {
    text: 'balancing on one leg atop a narrow beam, arms extended wide',
    weight: 5,
    tags: ['athletics'],
  },
  {
    text: 'leaping sideways through the air while drawing a blade mid-flight',
    weight: 5,
    tags: ['combat', 'athletics'],
    rarity: 'bold',
  },
  {
    text: 'pressing both palms against an invisible barrier while struggling forward',
    weight: 5,
    tags: ['athletics', 'survival'],
    rarity: 'bold',
  },
  {
    text: 'kneeling while channeling glowing energy upward from both palms, head tilted back',
    weight: 5,
    tags: ['magic', 'combat'],
    rarity: 'bold',
  },
  {
    text: 'throwing a grappling hook upward, body twisting with the motion',
    weight: 5,
    tags: ['athletics', 'exploration'],
    rarity: 'bold',
  },
  {
    text: 'spinning mid-air with dual blades extended in opposite directions',
    weight: 5,
    tags: ['combat', 'athletics'],
    rarity: 'bold',
  },
  {
    text: 'carrying an injured companion over their shoulders while moving carefully forward',
    weight: 5,
    tags: ['athletics', 'survival'],
  },
  {
    text: 'grappling with an opponent, arms locked in a wrestling hold',
    weight: 5,
    tags: ['combat', 'athletics'],
  },
  {
    text: 'wielding dual daggers while spinning in a wide defensive circle',
    weight: 5,
    tags: ['combat', 'athletics'],
    rarity: 'bold',
  },
  {
    text: 'running with cloak billowing while clutching an ancient scroll tightly',
    weight: 5,
    tags: ['athletics', 'exploration'],
    rarity: 'bold',
  },
  {
    text: 'performing a backflip while drawing twin daggers from their belt',
    weight: 5,
    tags: ['athletics', 'combat'],
    rarity: 'bold',
  },
  {
    text: 'dancing with a staff in fluid spinning motion, body arched sideways',
    weight: 5,
    tags: ['athletics', 'creative'],
    rarity: 'bold',
  },
  {
    text: 'swimming upward through water with one arm reaching toward surface',
    weight: 5,
    tags: ['athletics', 'survival'],
  },
  {
    text: 'shielding their eyes from a blinding flash, arm raised protectively overhead',
    weight: 5,
    tags: ['combat', 'magic'],
    rarity: 'bold',
  },
  {
    text: 'deflecting incoming projectiles with a glowing shield raised at shoulder height',
    weight: 5,
    tags: ['combat', 'magic'],
    rarity: 'bold',
  },
  {
    text: 'crouching low while picking a lock with concentrated focus',
    weight: 5,
    tags: ['exploration'],
  },
  {
    text: 'levitating cross-legged with arms outstretched, surrounded by swirling debris',
    weight: 5,
    tags: ['magic'],
    rarity: 'bold',
  },
  {
    text: 'parrying multiple strikes in rapid succession, blade held diagonally across body',
    weight: 5,
    tags: ['combat'],
    rarity: 'bold',
  },
  {
    text: 'pushing a massive stone block with both arms extended, muscles straining visibly',
    weight: 5,
    tags: ['athletics'],
    rarity: 'bold',
  },
  {
    text: 'pulling an arrow from a quiver while pivoting sideways in motion',
    weight: 5,
    tags: ['combat', 'athletics'],
    rarity: 'bold',
  },
  {
    text: 'channeling raw energy through both palms while suspended in midair',
    weight: 5,
    tags: ['magic', 'athletics'],
    rarity: 'bold',
  },
  {
    text: 'sword thrust lunging forward with back leg extended in sharp line',
    weight: 5,
    tags: ['combat', 'athletics'],
  },
  {
    text: 'rolling sideways to evade an attack, body coiled in motion',
    weight: 5,
    tags: ['combat', 'athletics'],
  },
  {
    text: 'juggling glowing orbs while balancing on one foot, body tilted sideways',
    weight: 5,
    tags: ['athletics', 'magic'],
    rarity: 'bold',
  },
  {
    text: 'pulling someone up by the arm while kneeling at an edge',
    weight: 5,
    tags: ['athletics', 'emotional'],
  },
  {
    text: 'hurling a glowing potion overhead while mid-stride, arm extended upward',
    weight: 5,
    tags: ['combat', 'athletics'],
    rarity: 'bold',
  },
  {
    text: 'dragging an injured companion sideways while watching for threats ahead',
    weight: 5,
    tags: ['combat', 'survival'],
  },
  {
    text: 'dodging sideways as projectiles streak past their silhouette in motion',
    weight: 5,
    tags: ['combat', 'athletics'],
    rarity: 'bold',
  },
  {
    text: 'throwing a net upward while stepping back, arms fully extended',
    weight: 5,
    tags: ['athletics', 'combat'],
  },
  {
    text: 'spinning a staff overhead while advancing in a low crouch',
    weight: 5,
    tags: ['combat', 'athletics'],
    rarity: 'bold',
  },
  {
    text: 'surfing down a steep slope with arms extended for balance',
    weight: 5,
    tags: ['athletics', 'survival'],
    rarity: 'bold',
  },
  {
    text: 'leaping between rooftops with one leg extended, arms windmilling for balance',
    weight: 5,
    tags: ['athletics', 'exploration'],
    rarity: 'bold',
  },
  {
    text: 'balancing on one hand in an impossible gravity-defying handstand pose',
    weight: 5,
    tags: ['athletics'],
    rarity: 'bold',
  },
  {
    text: 'pulling a rope hand over hand while bracing feet against resistance',
    weight: 5,
    tags: ['athletics'],
  },
  {
    text: 'lunging forward with spear extended, other arm trailing for balance',
    weight: 5,
    tags: ['combat', 'athletics'],
  },
  {
    text: 'vaulting over a collapsing bridge, legs tucked, arms extended forward',
    weight: 5,
    tags: ['athletics', 'exploration'],
    rarity: 'bold',
  },
  {
    text: 'grappling with a shadowy figure, locked in close combat struggle',
    weight: 5,
    tags: ['combat'],
    rarity: 'bold',
  },
  {
    text: 'kneeling while planting a glowing seed into fractured earth below',
    weight: 5,
    tags: ['creative', 'magic'],
    rarity: 'bold',
  },
  {
    text: 'pulling themselves through a narrow opening, shoulders compressed and twisted sideways',
    weight: 5,
    tags: ['exploration', 'athletics'],
  },
  {
    text: 'vaulting over an obstacle with hands planted, legs tucked midair',
    weight: 5,
    tags: ['athletics'],
    rarity: 'bold',
  },
  {
    text: 'pushing through heavy winds with both arms raised forward defensively',
    weight: 5,
    tags: ['athletics', 'survival'],
    rarity: 'bold',
  },
  {
    text: 'leaping sideways through shattering glass, arms crossed over face protectively',
    weight: 5,
    tags: ['athletics', 'combat'],
    rarity: 'bold',
  },
  {
    text: 'throwing a dagger mid-spin, body twisting with the release',
    weight: 5,
    tags: ['combat', 'athletics'],
    rarity: 'bold',
  },
  {
    text: 'surfing atop a wave of crystalline energy, arms outstretched',
    weight: 5,
    tags: ['athletics', 'magic'],
    rarity: 'bold',
  },
  {
    text: 'shield-bashing an attacker sideways, driving forward with extended arm',
    weight: 5,
    tags: ['combat'],
    rarity: 'bold',
  },
  {
    text: 'playing a violin mid-leap as sheet music swirls around them',
    weight: 5,
    tags: ['creative', 'athletics'],
    rarity: 'bold',
  },
  {
    text: 'drawing glowing runes in air with sweeping hand gestures',
    weight: 5,
    tags: ['magic'],
    rarity: 'bold',
  },
  {
    text: 'kneeling while summoning ethereal spirits that circle around their body',
    weight: 5,
    tags: ['magic'],
    rarity: 'bold',
  },
  {
    text: 'pressing both palms together as magical energy swirls between hands',
    weight: 5,
    tags: ['magic'],
  },
  {
    text: 'floating horizontally while absorbing streams of colored light into chest',
    weight: 5,
    tags: ['magic'],
    rarity: 'chaotic',
  },
  {
    text: 'conducting an invisible orchestra with sweeping arms, body twisting sideways gracefully',
    weight: 5,
    tags: ['creative'],
  },
  {
    text: 'painting luminous brushstrokes midair while leaning forward, colors trailing from fingertips',
    weight: 5,
    tags: ['creative'],
    rarity: 'bold',
  },
  {
    text: 'dancing in slow pirouettes as silk ribbons spiral upward defying gravity',
    weight: 5,
    tags: ['creative'],
    rarity: 'bold',
  },
  {
    text: 'sculpting reality by pulling and stretching the air with outstretched hands',
    weight: 5,
    tags: ['creative'],
    rarity: 'chaotic',
  },
  {
    text: 'leaning sideways off motorcycle while hair streams wildly behind',
    weight: 5,
    tags: ['riding'],
    rarity: 'bold',
  },
  { text: 'gripping ship wheel tightly as body braces against wind', weight: 5, tags: ['riding'] },
  {
    text: 'surfing upward on crystalline wave with arms spread wide',
    weight: 5,
    tags: ['riding'],
    rarity: 'chaotic',
  },
  {
    text: 'dropping to knees with arms outstretched, head tilted skyward mourning',
    weight: 5,
    tags: ['emotional'],
  },
  {
    text: 'embracing invisible presence with eyes closed, tears streaming down cheeks',
    weight: 5,
    tags: ['emotional'],
  },
  {
    text: 'laughing while spinning with both arms raised high above head',
    weight: 5,
    tags: ['emotional'],
  },
  {
    text: 'reaching forward desperately with trembling hand extended toward unseen hope',
    weight: 5,
    tags: ['emotional'],
  },
  {
    text: 'tracing fingertips across hovering star map while leaning sideways',
    weight: 5,
    tags: ['exploration'],
    rarity: 'bold',
  },
  {
    text: 'crouching low while unrolling ancient scroll with both hands',
    weight: 5,
    tags: ['exploration'],
  },
  {
    text: 'rotating translucent celestial sphere overhead with upward reaching arms',
    weight: 5,
    tags: ['exploration'],
    rarity: 'bold',
  },
];
