/**
 * Auto-generated by scripts/generate-scene-pools.js
 * 60 entries — do not edit manually, regenerate instead.
 */

type Entry = {
  text: string;
  weight: number;
  tags?: string[];
  rarity?: 'safe' | 'bold' | 'chaotic';
};

export const BACKGROUND: Entry[] = [
  {
    text: "colossal ring megastructure encircling the planet's curved edge",
    weight: 5,
    tags: ['space'],
  },
  {
    text: 'colossal stone titans standing knee-deep in the ocean',
    weight: 5,
    tags: ['coastal', 'nature'],
  },
  {
    text: "fractured moon looming massive beyond the canyon's edge",
    weight: 5,
    tags: ['space', 'nature'],
  },
  {
    text: 'crumbling citadel towers stretching endlessly along the mountain ridge',
    weight: 5,
    tags: ['mountains', 'nature'],
  },
  {
    text: 'massive sandstorm wall consuming the distant desert horizon',
    weight: 5,
    tags: ['nature'],
  },
  {
    text: 'volcanic mountain range glowing beneath ash-darkened crimson sky',
    weight: 5,
    tags: ['mountains', 'fire'],
  },
  {
    text: 'ancient crystalline spires piercing through perpetual storm clouds',
    weight: 5,
    tags: ['mountains', 'nature'],
  },
  { text: "massive orbital ring encircling the planet's curved edge", weight: 5, tags: ['space'] },
  {
    text: 'shattered moon fragments scattered across the darkening horizon',
    weight: 5,
    tags: ['space', 'nature'],
  },
  {
    text: 'colossal ice shelf stretching endlessly across frozen ocean',
    weight: 5,
    tags: ['nature', 'coastal'],
  },
  {
    text: 'endless procession of ancient monuments receding into desert haze',
    weight: 5,
    tags: ['nature'],
  },
  {
    text: 'rolling thunder clouds stacked impossibly high beyond ancient peaks',
    weight: 5,
    tags: ['mountains', 'nature'],
  },
  {
    text: 'colossal dam spanning the width of the mountain range',
    weight: 5,
    tags: ['mountains', 'nature'],
  },
  {
    text: 'distant binary suns bleeding crimson through planetary dust clouds',
    weight: 5,
    tags: ['space'],
  },
  {
    text: 'endless desert dunes rippling toward a wavering mirage horizon',
    weight: 5,
    tags: ['nature'],
  },
  {
    text: 'sprawling orbital shipyards stretch across the starlit void',
    weight: 5,
    tags: ['space'],
  },
  {
    text: 'endless archipelago dissolving into mist and open sea',
    weight: 5,
    tags: ['coastal', 'nature'],
  },
  {
    text: 'continent-sized wall stretching beyond the curve of the world',
    weight: 5,
    tags: ['mountains'],
  },
  {
    text: 'endless bone-white salt flats meeting distant violet mountains',
    weight: 5,
    tags: ['mountains', 'nature'],
  },
  { text: 'massive glass domes stretching beyond the curved horizon', weight: 5, tags: ['space'] },
  {
    text: 'shattered moon fragments scattered across the twilight horizon',
    weight: 5,
    tags: ['space', 'nature'],
  },
  { text: 'massive pulsar beam sweeping across the distant starfield', weight: 5, tags: ['space'] },
  {
    text: 'towering waterfalls cascading from continent-sized cliffs into void',
    weight: 5,
    tags: ['nature', 'space'],
  },
  {
    text: 'massive gas giant looming above jagged alien horizons',
    weight: 5,
    tags: ['space', 'mountains'],
  },
  {
    text: 'massive tidal wave frozen mid-crash across distant waters',
    weight: 5,
    tags: ['coastal', 'nature'],
  },
  { text: 'silhouette of planetary rings arching across infinite sky', weight: 5, tags: ['space'] },
  {
    text: 'shattered moon suspended low above jagged mountain silhouettes',
    weight: 5,
    tags: ['mountains', 'space'],
  },
  {
    text: 'canyon layers receding into atmospheric purple haze',
    weight: 5,
    tags: ['mountains', 'nature'],
  },
  {
    text: 'massive thunderhead anvils towering across the entire horizon',
    weight: 5,
    tags: ['nature'],
  },
  {
    text: 'volcanic mountain chain stretching beyond all visible horizon',
    weight: 5,
    tags: ['mountains', 'fire'],
  },
  { text: 'celestial bridge arching across the star-filled void', weight: 5, tags: ['space'] },
  {
    text: 'plateau layers stacked deep into purple distance',
    weight: 5,
    tags: ['mountains', 'nature'],
  },
  { text: 'twin galaxies colliding in the deep starfield beyond', weight: 5, tags: ['space'] },
  {
    text: 'sprawling jungle canopy vanishing into atmospheric blue gradient',
    weight: 5,
    tags: ['nature'],
  },
  {
    text: 'glaciers descending into polar sea beneath auroral glow',
    weight: 5,
    tags: ['coastal', 'nature'],
  },
  {
    text: 'forest-covered ridges layered into atmospheric blue distance',
    weight: 5,
    tags: ['mountains', 'nature'],
  },
  { text: 'twin galaxies merging in the star-filled void beyond', weight: 5, tags: ['space'] },
  {
    text: 'massive terraform engines rising through stratospheric cloud layers',
    weight: 5,
    tags: ['space', 'nature'],
  },
  {
    text: 'colossal lighthouse beaming across storm-blackened ocean expanse',
    weight: 5,
    tags: ['coastal'],
  },
  {
    text: 'massive radio telescope arrays receding into starlit darkness',
    weight: 5,
    tags: ['space', 'nature'],
  },
  {
    text: 'skyscraper necropolis piercing through perpetual low-hanging fog',
    weight: 5,
    tags: ['skyline'],
  },
  {
    text: 'fractal coastline dissolving into atmospheric perspective and silver distance',
    weight: 5,
    tags: ['coastal', 'nature'],
  },
  { text: 'crater rim ascending toward distant ringworld arc', weight: 5, tags: ['space'] },
  {
    text: 'colossal stone arches bridging distant mountain peaks at sunset',
    weight: 5,
    tags: ['mountains', 'nature'],
  },
  { text: 'colossal tree roots descending into abyssal mist below', weight: 5, tags: ['nature'] },
  {
    text: 'colossal ice cliffs descending into polar darkness',
    weight: 5,
    tags: ['nature', 'coastal'],
  },
  {
    text: 'steppe grasslands stretching to curved planetary edge',
    weight: 5,
    tags: ['space', 'nature'],
  },
  {
    text: 'orbital debris field glowing with atmospheric reentry fire',
    weight: 5,
    tags: ['space', 'fire'],
  },
  {
    text: 'colossal stone hands emerging from distant earth',
    weight: 5,
    tags: ['mountains', 'nature'],
  },
  {
    text: 'suspension bridges spanning continent-wide between mountain ranges',
    weight: 5,
    tags: ['mountains', 'nature'],
  },
  {
    text: 'colossal stone gateway framing distant purple mountains beyond',
    weight: 5,
    tags: ['mountains', 'nature'],
  },
  {
    text: 'colossal stone heads half-buried across the desert horizon',
    weight: 5,
    tags: ['nature'],
  },
  {
    text: 'massive desert butte formations receding into heat shimmer',
    weight: 5,
    tags: ['mountains', 'nature'],
  },
  { text: "black hole's accretion disk bending light across space", weight: 5, tags: ['space'] },
  {
    text: 'massive refinery complex bleeding smoke into orange sky',
    weight: 5,
    tags: ['fire', 'nature'],
  },
  {
    text: 'wind turbines stretching endlessly across rolling distant hills',
    weight: 5,
    tags: ['nature', 'mountains'],
  },
  {
    text: 'massive terraforming spires piercing stratocumulus cloud layers',
    weight: 5,
    tags: ['space', 'nature'],
  },
  {
    text: 'continental ice sheet glowing beneath triple moons',
    weight: 5,
    tags: ['space', 'nature'],
  },
  {
    text: 'colossal sequoia forest stretching to hazy blue infinity',
    weight: 5,
    tags: ['nature', 'mountains'],
  },
  { text: "colossal dam holding back an entire ocean's weight", weight: 5 },
];
