/**
 * Dual character action pools — relationship-aware pose seeds for two-person renders.
 *
 * COMPANION: universal pool for any two people sharing a scene.
 * PARTNER: additional pool for romantic partners only — comfortable intimacy, not cheesy.
 *
 * Every entry must:
 *   - Describe what BOTH characters are doing (left person + right person)
 *   - Keep heads on separate sides (no leaning into each other)
 *   - Describe BODY POSE only — face direction is overridden by the brief
 *   - Both characters STATIONARY — no walking, stepping, navigating, arriving
 *   - Both characters roughly SIDE BY SIDE — not one behind the other
 *   - Scene-neutral — body poses must work in ANY setting
 */

export const DUAL_ACTIONS_COMPANION: string[] = [
  'one leaning on a railing, the other standing a few feet away with arms crossed',
  'one crouching to examine something on the ground, the other standing nearby with one hand on their hip',
  'one sitting on a ledge or step, the other standing beside them with arms crossed',
  'one adjusting their gear or bag, the other standing with hands in pockets',
  'one photographing something with a camera held at chest level, the other standing beside them pointing at something off to the side',
  'both standing still, one with hands at their sides, the other with one hand resting on their hip',
  'one standing at the edge of a drop or overlook, the other a few steps back on safer ground',
  'one kneeling to tie a boot or adjust something, the other standing beside them with hands on hips',
  'one reaching up toward a high object, the other standing nearby with arms folded',
  'both standing in a wide open space, one with hands on hips, the other shielding their eyes',
  'one examining a detail on a wall with one hand raised, the other standing nearby with arms crossed',
  'both resting against opposite sides of a pillar or structure',
  'one waving or signaling toward something unseen, the other standing with their arms at their sides',
  'one sketching or writing in a notebook, the other standing beside them with a cup in hand',
  'one reaching into a bag or container, the other standing by with hands ready to help',
  'one stretching or rolling their shoulders, the other standing still with arms crossed',
  'both seated on separate surfaces at slightly different heights, one with legs stretched out, the other with arms on their knees',
  'one leaning against a wall with arms folded, the other standing a few feet away adjusting their jacket',
  'both standing at a balcony railing, one with elbows on the rail, the other standing upright with hands in pockets',
  'one adjusting their hat or sunglasses, the other standing nearby drinking from a cup',
  'one with a hand resting on a post or column, the other standing a few steps away checking a device',
  'both seated on a bench, one with legs crossed, the other leaning forward with elbows on knees',
  'one standing with a bag slung over one shoulder, the other beside them stretching one arm overhead',
  'both standing in waist-deep grass or flowers, one brushing a hand through the plants, the other standing still',
  'one perched on a rock or boulder, the other standing beside it with one hand resting on the stone',
  'one holding a lantern or light source at their side, the other standing nearby with hands in jacket pockets',
  'both standing at a market stall or counter, one examining an object, the other resting an elbow on the surface',
  'one with their hands behind their head stretching, the other standing with arms crossed',
  'both standing under a large tree, one leaning against the trunk, the other standing free with a hand on their chin',
  'both standing at the edge of water, one with hands in pockets, the other bending slightly to look at the surface',
  'one holding something up for the other to see, both standing a couple feet apart',
  'both leaning on opposite ends of the same fence or railing',
  'one standing with their weight on one leg, the other nearby with feet planted and arms crossed',
  'one holding a map or device at chest height, the other standing beside them pointing at something on it',
  'both standing under an archway, one with their back against the pillar, the other with a hand resting on the stone',
  'one sitting on a low wall, the other standing beside them with one foot up on the wall',
  'one shielding their eyes from light, the other standing beside them with arms at their sides',
  'one holding something up to inspect it in the light, the other standing nearby with a hand on their chin',
  'both standing at a window, one with their hands on the sill, the other standing beside them arms crossed',
  'one crouching beside an animal or plant, the other standing a few feet away with hands in pockets',
  'both standing on a rooftop or elevated platform, one near the edge, the other a few feet back',
  'one pointing something out low and to the side, the other standing beside them looking where they point',
  'one standing with one hand in their pocket and the other gesturing, the second person standing with both hands in pockets',
  'one rolling up their sleeves, the other standing beside them with thumbs hooked in their belt',
  'both standing under an awning or shelter, one leaning on a support beam, the other standing free',
  'one tapping their foot while standing, the other beside them rolling up their sleeves',
  'both crouching at different heights examining separate objects on the ground',
  'one standing with hands clasped behind their back, the other nearby wiping their hands on a cloth',
  'one sitting cross-legged on the ground, the other standing beside them holding a water bottle',
  'one standing on one foot adjusting their sock, the other nearby with hands on their belt',
  'both leaning against separate trees or posts, one with ankle crossed, the other standing straight',
  'one kneeling on one knee sorting through items, the other standing with arms akimbo',
  'both standing in an open area, one scratching their head, the other with hands in back pockets',
  'one standing with a towel draped over their shoulder, the other beside them adjusting their sleeve',
  'one sitting on steps with chin in hand, the other standing beside them with weight shifted',
  'both standing under cover, one brushing dust off their clothes, the other standing with hands free',
  'one standing while checking their watch, the other beside them stretching their back',
  'both positioned near a fence, one gripping the rails, the other standing back with crossed ankles',
  'one crouching to pick something up, the other standing nearby holding their jacket',
  'both standing on uneven ground, one with hand on knee for balance, the other stable with arms crossed',
  'one standing while tying something around their waist, the other beside them holding a small object',
  'both near a large stone or structure, one sitting on it, the other standing against it',
  'one standing while adjusting their backpack straps, the other nearby with hands in front pockets',
  'both in an outdoor space, one kneeling to examine plants, the other standing with arms folded behind back',
  'one sitting with legs dangling over an edge, the other standing safely back with hands in pockets',
  'both standing near a vertical surface, one with palm pressed against it, the other arms crossed',
  'one standing while wrapping something around their wrist, the other beside them holding a cup',
  'both standing near a boundary or edge, one closer with hand extended, the other back with arms down',
  'one standing while opening a container, the other nearby with hands clasped in front',
  'both positioned around outdoor furniture, one sitting sideways, the other standing beside it',
  'one standing on tiptoes reaching for something, the other nearby with hands behind their head',
  'both near a large opening or doorway, one in it, the other beside it with shoulder against frame',
  'one crouching low to the ground investigating, the other standing tall beside them with loose arms',
  'one standing while tucking something into their belt, the other beside them drinking from bottle',
  'one sitting backwards on a chair or bench, the other standing beside them with relaxed posture',
  'both standing in dappled light, one wiping their brow, the other standing still with hands down',
  'one standing while fastening something at their neck, the other beside them with thumbs in pockets',
  'one kneeling beside luggage or gear, the other standing nearby with hands on their lower back',
  'one sitting with back straight and hands on knees, the other standing beside them stretching arms',
  'both near a workspace or table, one leaning over it, the other standing upright beside it',
  'one standing while shaking out a piece of clothing, the other nearby with hands interlocked behind back',
  'both in an open area, one bending to touch the ground, the other standing straight with relaxed shoulders',
  'one balancing on a log or beam, the other standing on solid ground with arms at their sides',
  'one squatting to collect something from the ground, the other standing nearby holding a small bag',
  'both standing at different elevations, one step higher with hand on railing, the other below with crossed arms',
  'one standing while combing their hair with fingers, the other nearby checking their phone',
  'one standing while sharpening a tool on a stone, the other beside them wiping their hands',
  'one sitting with feet flat on ground and hands on thighs, the other standing with weight on one hip',
  'one standing while braiding rope or cord, the other nearby with arms folded across chest',
  'both near a campfire or fire pit, one crouching to tend it, the other standing back with crossed arms',
  'one perching on a fence post, the other standing beside the fence with hands in back pockets',
  'one standing while threading something through a loop, the other nearby tapping their fingers on their leg',
  'both at a picnic table, one sitting on top of it, the other standing at the end',
  'both near exercise equipment, one using it, the other standing beside it with water bottle',
  'one standing while peeling fruit with a knife, the other beside them holding a plate',
  'both near playground equipment, one sitting on a swing, the other standing beside the swing set',
  'one standing while applying something to their skin, the other nearby holding a tube or bottle',
  'one standing while carving something with a small blade, the other beside them brushing away shavings',
  'one lying on their back on a blanket, the other sitting cross-legged beside the blanket',
  'one sitting straddling a bench, the other standing at the side of the bench',
  'both near a fountain or water feature, one trailing fingers in water, the other standing dry',
  'one sitting with legs crossed on a cushion, the other standing nearby with arms behind back',
  'both near a statue or monument, one touching its base, the other standing back respectfully',
  'one digging in soil with a small shovel, the other standing beside them holding seeds',
  'one standing while testing the weight of an object, the other beside them with arms relaxed',
  'one sitting yoga-style with straight spine, the other standing nearby in a casual stretch',
  'one standing while painting or drawing on an easel, the other beside them mixing colors',
  'one standing while folding a piece of fabric, the other beside them sorting through buttons in a small box',
  'one sitting on a tree stump whittling wood, the other standing nearby collecting wood shavings in their palm',
  'both near a rope swing, one testing the knot strength, the other standing back with hands on hips',
  'one crouching to scoop water from a stream, the other standing upstream with sleeves rolled up',
  'one standing while threading a needle, the other beside them holding a spool of thread',
  'both near a wooden crate, one prying it open with a crowbar, the other standing ready with gloves',
  'one sitting on a milk crate patching a hole in fabric, the other standing beside them holding scissors',
  'one standing while blowing on something hot in their hands, the other nearby fanning themselves with a hat',
  'both near a wooden post, one hammering a nail into it, the other standing back covering their ears',
  'one crouching to catch dripping water in a container, the other standing nearby wringing out a wet cloth',
  'one standing while polishing something shiny with a rag, the other beside them holding cleaning supplies',
  'one standing while filing the edge of a metal tool, the other beside them testing its sharpness carefully',
  'one standing while pressing flowers between book pages, the other beside them selecting specimens',
  'one crouching to repair a broken wheel spoke, the other standing nearby with replacement parts',
  'one lying flat on their stomach reading, the other sitting cross-legged nearby organizing items in a small pouch',
  'one sitting backwards on a chair whittling a stick, the other standing nearby sweeping wood curls with a broom',
  'one crouching to catch rainwater in a wide bowl, the other standing nearby wringing out their soaked sleeves',
  'one sitting on a wooden crate playing a flute, the other standing nearby keeping rhythm by clapping softly',
  'one standing while lacing up tall boots, the other beside them brushing mud off their own shoes',
  'one sitting on a fence rail whistling a tune, the other standing nearby tuning a stringed instrument',
  'one standing while folding a letter, the other beside them melting wax for a seal',
  'one crouching to examine footprints in dirt, the other standing nearby holding a magnifying glass',
  'both near a tall ladder, one holding it steady, the other standing back with hands ready to help',
  'one sitting on a barrel tapping their fingers, the other standing beside them humming quietly',
  'one standing while braiding their hair, the other nearby sorting through hair ribbons',
  'one kneeling to pack items into a satchel, the other standing with a rolled map under their arm',
  'one standing while measuring fabric with a ruler, the other beside them marking measurements with chalk',
  'both near a pulley system, one pulling the rope, the other standing ready with outstretched arms',
  'one crouching to blow on embers, the other standing nearby shielding the flame with cupped hands',
  'one standing while braiding leather strips, the other beside them holding the loose ends',
  'one sitting on a wooden stool carving soap, the other standing nearby catching the shavings',
  'one standing while practicing knot tying, the other beside them holding different types of rope',
  'one kneeling to collect morning dew in a cloth, the other standing nearby wringing out their own rag',
  'one standing while balancing a stick on their finger, the other beside them clapping encouragement',
  'both near a sundial, one reading the shadow, the other standing beside them checking an hourglass',
  'one standing while binding pages together, the other beside them holding the finished sections',
  'one sitting on a tree root carving initials, the other standing nearby keeping watch',
  'one standing while practicing balance on one foot, the other beside them ready to steady if needed',
  'one kneeling to sift sand through fingers, the other standing nearby shaking sand from their shoes',
  'one standing while braiding flower stems, the other beside them selecting blooms from a basket',
  'one sitting on a log skinning a stick, the other standing nearby collecting the bark strips',
  'both near a wooden lever, one preparing to push it, the other standing ready to catch the result',
  'one crouching to trace patterns in dust, the other standing nearby brushing dust from their clothes',
  'one standing while testing the flexibility of a thin branch, the other beside them holding similar twigs',
  'one sitting on a mushroom-covered log picking specimens, the other standing nearby holding a collection pouch',
  'both near a rope and pulley, one threading the rope, the other standing back ensuring it runs smoothly',
  'one kneeling to scrape moss from a rock, the other standing nearby holding the cleaned pieces',
  'one standing while practicing hand shadows, the other beside them positioning a light source',
  'one sitting on a wooden bench peeling bark, the other standing nearby weaving the strips',
  'both near a spinning wheel mechanism, one giving it momentum, the other standing back timing its rotations',
  'one standing while practicing whistling bird calls, the other beside them cupping their ear to listen',
  'one crouching to stack flat stones, the other standing nearby selecting suitable rocks',
  'one sitting on a cushion sorting buttons by color, the other standing nearby organizing them into containers',
  'one sitting on a wooden crate sorting feathers by type, the other standing nearby holding a collection bag',
  'both near a weather monitoring device, one adjusting its position, the other standing back reading measurements',
  'one standing while practicing origami folds, the other beside them smoothing out practice papers',
  'one crouching to build a small cairn, the other standing nearby selecting appropriately sized stones',
  'one sitting on a tree stump sorting acorns, the other standing nearby shaking more from their pockets',
  'both near a compass rose drawn in sand, one pointing to directions, the other standing back with a real compass',
  'one standing while practicing card shuffling, the other beside them ready to help gather any dropped cards',
  'one kneeling to arrange twigs in geometric patterns, the other standing nearby providing design suggestions',
  'one sitting on a boulder sorting pebbles by color, the other standing nearby rinsing their hands in a basin',
  'one crouching to arrange leaves in artistic patterns, the other standing nearby pressing the best ones in a book',
  'one kneeling to retie their shoelaces, the other standing nearby with one hand resting on a nearby surface',
  'one sitting with their back against a wall, the other standing a few feet away with weight shifted',
  'both standing in an open space, one with hands clasped in front, the other with thumbs hooked in belt loops',
  'one sitting on steps with hands flat beside them, the other standing nearby with one hand on hip',
  'both positioned around a pillar, one touching it with fingertips, the other standing away with arms down',
  'one crouching with one hand touching the ground, the other standing tall with hands behind head',
  'both standing near a corner, one leaning into it, the other standing straight several feet away',
  'one crouching low with hands near their feet, the other standing upright with arms folded',
  'both near a post, one leaning sideways against it, the other standing perpendicular with hands at sides',
  'both standing at different angles, one facing left with hands down, the other angled right with crossed arms',
  'one standing while tapping their fingers against their leg, the other beside them standing perfectly still',
  'one crouching with hands hovering over something, the other standing nearby with arms folded behind back',
  'one sitting with one leg extended, the other standing nearby with weight on one leg',
  'both standing in morning light, one yawning with hand over mouth, the other beside them stretching their arms overhead',
  'both sitting on separate rocks, one with hands on ankles, the other leaning back with palms flat',
  'one kneeling with both hands flat on the ground, the other standing nearby with jacket draped over arm',
  'both standing under shelter, one with hand on their stomach, the other beside them checking their sleeve',
  'one sitting sideways on a ledge, the other standing perpendicular to them with hands loosely clasped',
  'both near a vertical beam, one standing close with hand flat against it, the other several feet away',
  'one kneeling with hands resting on their heels, the other standing tall beside them with relaxed shoulders',
  'one standing while pulling something from their pocket, the other beside them wiping their nose with back of hand',
  'one standing while tucking hair behind their ear, the other beside them standing with feet shoulder width apart',
  'both positioned around outdoor seating, one perched on the edge, the other standing beside it with loose posture',
  'one crouching with fingers spread on ground, the other standing nearby with head tilted slightly',
  'both near a low barrier, one sitting on it sideways, the other standing beside it with casual stance',
  'one standing while lifting something light overhead, the other beside them standing with feet planted wide',
  'both in dappled shade, one sitting with spine straight, the other standing nearby with weight distributed evenly',
  'one sitting with elbows on knees and chin up, the other standing nearby with one foot slightly forward',
  'one standing while smoothing down their shirt, the other beside them standing with hands near their sides',
  'one sitting cross-legged with hands on ankles, the other standing beside them bouncing lightly on their toes',
];

export const DUAL_ACTIONS_PARTNER: string[] = [
  'sitting side by side, comfortable silence, one with chin in hand, the other with arms resting on their knees',
  'both holding the same railing or ledge, hands close but not touching',
  'both standing at an overlook, one with elbows on the railing, the other standing close with arms crossed',
  'one with chin resting on their own hand, the other standing beside them',
  'standing near each other at a scenic overlook, one leaning on the railing, the other standing with arms crossed',
  'both laughing at something, caught mid-reaction, standing a couple feet apart',
  'one tucking hair behind their own ear, the other standing beside them',
  'sitting together on a blanket or bench, knees almost touching',
  'one holding an umbrella or shade, the other standing beside them in the shade',
  'both standing close together, one with arms crossed, the other with hands clasped behind their back',
  'one absentmindedly fixing their sleeve, the other standing close',
  'both leaning forward on a railing, elbows on the rail, standing close',
  'sharing a quiet moment, both looking outward, standing close with no words needed',
  'one resting a hand on a railing, the other standing close with their arms loosely crossed',
  'both standing under a tree, one leaning against the trunk, the other standing close with their shoulder almost touching',
  'both standing still, shoulders close, one with hands in pockets, the other with arms loosely at their sides',
  'both sitting on steps, at slightly different heights, shoulders close',
];

/**
 * Pick a dual action seed based on the plus_one's relationship.
 * Partner/significant_other: 30% romantic pool, 70% companion pool.
 * Everyone else: companion pool only.
 */
export function pickDualAction(relationship: string | undefined): string {
  const isPartner = relationship === 'partner' || relationship === 'significant_other';

  if (isPartner && Math.random() < 0.3) {
    return DUAL_ACTIONS_PARTNER[Math.floor(Math.random() * DUAL_ACTIONS_PARTNER.length)];
  }
  return DUAL_ACTIONS_COMPANION[Math.floor(Math.random() * DUAL_ACTIONS_COMPANION.length)];
}
