/**
 * Auto-generated by scripts/generate-scene-pools.js
 * 60 entries — do not edit manually, regenerate instead.
 */

type Entry = {
  text: string;
  weight: number;
  tags?: string[];
  rarity?: 'safe' | 'bold' | 'chaotic';
};

export const FOREGROUND: Entry[] = [
  {
    text: 'foreground framed by twisted iron railing and scattered autumn leaves',
    weight: 5,
    tags: ['urban', 'nature'],
  },
  {
    text: 'foreground framed by rain-streaked window glass with condensation droplets',
    weight: 5,
    tags: ['rain', 'interior'],
  },
  {
    text: 'foreground framed by weathered wooden beams and dangling chains',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by silk curtains billowing in the wind',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by flickering candlelight and ornate metalwork',
    weight: 5,
    tags: ['interior'],
  },
  { text: 'foreground framed by weathered rope nets and fishing buoys', weight: 5 },
  {
    text: 'foreground framed by cracked concrete pillars and exposed rebar',
    weight: 5,
    tags: ['urban', 'interior'],
  },
  {
    text: 'foreground framed by bamboo stalks and scattered autumn leaves',
    weight: 5,
    tags: ['nature'],
  },
  {
    text: 'foreground framed by crumbling brick and tangled vines',
    weight: 5,
    tags: ['urban', 'nature'],
  },
  {
    text: 'foreground framed by frosted glass panels and condensation droplets',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by icicles and frost-covered branches',
    weight: 5,
    tags: ['snow', 'nature'],
  },
  { text: 'foreground framed by charred timber and ash debris', weight: 5, tags: ['fire'] },
  {
    text: 'foreground framed by rusted chain-link fence and overgrown weeds',
    weight: 5,
    tags: ['urban', 'nature'],
  },
  {
    text: 'foreground framed by carved doorway and flickering candles',
    weight: 5,
    tags: ['interior'],
  },
  { text: 'foreground framed by tangled barbed wire and fog', weight: 5 },
  {
    text: 'foreground framed by shattered mirrors and jagged reflective shards',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by translucent fabric billowing in dim light',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by weathered driftwood and tangled seaweed strands',
    weight: 5,
    tags: ['underwater', 'nature'],
  },
  {
    text: 'foreground framed by hanging copper bells and weathered chimes',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by stacked crates and scattered packing straw',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by flickering neon signs and steam vents',
    weight: 5,
    tags: ['urban'],
  },
  {
    text: 'foreground framed by candelabra shadows and melting wax pools',
    weight: 5,
    tags: ['interior', 'fire'],
  },
  {
    text: 'foreground framed by dripping stalactites and cave formations',
    weight: 5,
    tags: ['underwater'],
  },
  {
    text: 'foreground framed by thick moss-covered tree trunks and ferns',
    weight: 5,
    tags: ['nature'],
  },
  {
    text: 'foreground framed by crystalline stalactites and mineral deposits',
    weight: 5,
    tags: ['interior', 'underwater'],
  },
  {
    text: 'foreground framed by skeletal umbrella spokes and pooling rain',
    weight: 5,
    tags: ['rain'],
  },
  { text: 'foreground framed by dangling roots and earth clumps', weight: 5, tags: ['nature'] },
  {
    text: 'foreground framed by leather saddle straps and dusty riding gear',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by rain-streaked windshield with wipers frozen mid-sweep',
    weight: 5,
    tags: ['rain'],
  },
  {
    text: 'foreground framed by rusted scaffolding and torn plastic sheeting',
    weight: 5,
    tags: ['urban'],
  },
  {
    text: 'foreground framed by stacked sandbags and muddy tire tracks',
    weight: 5,
    tags: ['urban'],
  },
  {
    text: 'foreground framed by flickering candlelight through ornate cathedral columns',
    weight: 5,
    tags: ['interior'],
  },
  { text: 'foreground framed by tattered prayer flags whipping in wind', weight: 5 },
  { text: 'foreground framed by stacked barrels and coiled rope', weight: 5, tags: ['interior'] },
  {
    text: 'foreground framed by water-stained tiles and peeling wallpaper fragments',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by tangled fishing nets and rusted hooks',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by dusty bookshelves and stacked parchment scrolls',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by hanging lanterns with flickering oil flames',
    weight: 5,
    tags: ['fire', 'interior'],
  },
  {
    text: 'foreground framed by cracked porcelain and delicate teacup fragments',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by skeletal wheat stalks and harvested stubble',
    weight: 5,
    tags: ['nature'],
  },
  {
    text: 'foreground framed by skeletal coral and sea-worn shells',
    weight: 5,
    tags: ['underwater', 'nature'],
  },
  { text: 'foreground framed by swaying cattails and marsh reeds', weight: 5, tags: ['nature'] },
  {
    text: 'foreground framed by rusted chain and padlock swaying gently',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground with splintered wooden planks and scattered nails framing debris',
    weight: 5,
    tags: ['interior'],
  },
  { text: 'foreground framed by dripping icicles and frozen lattice', weight: 5, tags: ['snow'] },
  {
    text: 'foreground framed by splintered wooden shutters and peeling paint',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by dripping stalactites and mineral deposits',
    weight: 5,
    tags: ['underwater'],
  },
  {
    text: 'foreground framed by shattered stained glass fragments and lead caming',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by wet cobblestones and flickering gaslight shadows',
    weight: 5,
    tags: ['urban', 'rain'],
  },
  {
    text: 'foreground framed by hanging tapestries with golden tassels swaying',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by coiled garden hose and terracotta pots',
    weight: 5,
    tags: ['interior', 'nature'],
  },
  {
    text: 'foreground framed by dangling monastery bells and incense smoke',
    weight: 5,
    tags: ['interior', 'fire'],
  },
  {
    text: 'foreground framed through clay pottery shards and terracotta fragments',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by hanging kelp and seaweed tendrils',
    weight: 5,
    tags: ['underwater', 'nature'],
  },
  {
    text: 'foreground framed by cracked television screens stacked on milk crates',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by willow branches sweeping across wet riverbank stones',
    weight: 5,
    tags: ['nature', 'rain'],
  },
  {
    text: 'foreground framed through tangled blackberry thorns and wild roses',
    weight: 5,
    tags: ['nature'],
  },
  {
    text: 'foreground framed by fractured marble columns and scattered rose petals',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by peeling paint and warped window shutters',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'foreground framed by jagged icicles and frost-covered pine needles',
    weight: 5,
    tags: ['snow', 'nature'],
  },
];
