/**
 * Auto-generated by scripts/generate-scene-pools.js
 * 50 entries — do not edit manually, regenerate instead.
 */

type Entry = {
  text: string;
  weight: number;
  tags?: string[];
  rarity?: 'safe' | 'bold' | 'chaotic';
};

export const MIDGROUND: Entry[] = [
  {
    text: 'weathered statues lining a cobblestone path through the plaza',
    weight: 5,
    tags: ['urban'],
  },
  {
    text: 'scattered market stalls with flickering lanterns between pathways',
    weight: 5,
    tags: ['urban', 'interior'],
  },
  { text: 'stone archways framing the distant mountain peaks beyond', weight: 5, tags: ['nature'] },
  { text: 'flames from scattered oil barrels flickering in darkness', weight: 5, tags: ['fire'] },
  { text: 'rows of skeletal trees creating depth and shadow', weight: 5, tags: ['nature'] },
  {
    text: 'abandoned cable cars suspended between crumbling support towers',
    weight: 5,
    tags: ['urban', 'nature'],
  },
  { text: 'dust devils spiraling across the cracked desert floor', weight: 5, tags: ['nature'] },
  { text: 'rows of abandoned vehicles receding into mist', weight: 5, tags: ['urban', 'nature'] },
  {
    text: 'cascading waterfalls connecting multiple levels of rock formations',
    weight: 5,
    tags: ['nature'],
  },
  { text: 'floating paper lanterns drifting through the air slowly', weight: 5 },
  {
    text: 'wooden scaffolding crisscrossing between crumbling buildings',
    weight: 5,
    tags: ['urban', 'interior'],
  },
  {
    text: 'crowds gathering beneath towering broadcast screens',
    weight: 5,
    tags: ['urban', 'interior'],
  },
  {
    text: 'shallow canals cutting through crumbling pathways',
    weight: 5,
    tags: ['urban', 'nature'],
  },
  { text: 'wrought iron fencing dividing cracked cobblestone paths', weight: 5, tags: ['urban'] },
  {
    text: 'crumbling stone steps ascending through overgrown terraces',
    weight: 5,
    tags: ['nature'],
  },
  {
    text: 'makeshift tents clustered along a sloping hillside',
    weight: 5,
    tags: ['urban', 'nature'],
  },
  { text: 'crumbling pillars supporting overhead ruins', weight: 5, tags: ['interior'] },
  { text: 'cargo containers stacked in irregular towers', weight: 5, tags: ['urban'] },
  {
    text: 'suspension footbridges swaying gently between the plateaus',
    weight: 5,
    tags: ['nature'],
  },
  { text: 'rubble and debris scattered across uneven terrain', weight: 5, tags: ['urban'] },
  {
    text: 'fabric banners strung between buildings fluttering in wind',
    weight: 5,
    tags: ['urban', 'nature'],
  },
  { text: 'train tracks converging toward a distant platform', weight: 5, tags: ['urban'] },
  { text: 'windmills turning slowly against the hazy horizon', weight: 5, tags: ['nature'] },
  { text: 'railway tracks curving through the industrial yard', weight: 5, tags: ['urban'] },
  { text: 'terraced rice paddies climbing the hillside', weight: 5, tags: ['nature'] },
  {
    text: 'conveyor belts moving materials through industrial space',
    weight: 5,
    tags: ['interior'],
  },
  { text: 'rooftops layered in descending elevation toward horizon', weight: 5, tags: ['urban'] },
  { text: 'suspension cables cutting through empty space', weight: 5, tags: ['urban'] },
  {
    text: 'hanging laundry lines stretching between worn buildings',
    weight: 5,
    tags: ['urban', 'interior'],
  },
  {
    text: 'gondolas drifting through narrow waterways between buildings',
    weight: 5,
    tags: ['urban', 'underwater'],
  },
  { text: 'rows of weathered fence posts cutting through mist', weight: 5, tags: ['nature'] },
  {
    text: 'fog banks rolling between illuminated structures',
    weight: 5,
    tags: ['urban', 'nature'],
  },
  {
    text: 'wooden crates partially submerged in murky floodwater',
    weight: 5,
    tags: ['underwater', 'urban'],
  },
  { text: 'wrought-iron gates standing partially open ahead', weight: 5, tags: ['interior'] },
  { text: 'rows of prayer flags dancing in wind', weight: 5, tags: ['nature'] },
  { text: 'cargo nets draped between rusted loading cranes', weight: 5, tags: ['urban'] },
  {
    text: 'chain-link fencing separating rusted industrial equipment',
    weight: 5,
    tags: ['urban', 'interior'],
  },
  { text: 'ruins partially collapsed stretching toward the horizon', weight: 5 },
  {
    text: 'geometric shadows stretching across cracked pavement below',
    weight: 5,
    tags: ['urban'],
  },
  {
    text: 'rows of wooden piers extending into dark water',
    weight: 5,
    tags: ['nature', 'underwater'],
  },
  { text: 'industrial pipes crisscrossing through empty air', weight: 5, tags: ['interior'] },
  { text: 'smoke vents releasing irregular plumes into stillness', weight: 5, tags: ['fire'] },
  { text: 'rope bridges connecting cliff-face platforms precariously', weight: 5 },
  {
    text: 'hanging gardens cascading down multiple tiers',
    weight: 5,
    tags: ['nature', 'interior'],
  },
  {
    text: 'stone fountain with water quietly spilling over edges',
    weight: 5,
    tags: ['nature', 'urban'],
  },
  { text: 'power lines cutting across the empty space', weight: 5, tags: ['urban'] },
  { text: 'fishing nets draped over wooden posts', weight: 5, tags: ['nature'] },
  {
    text: 'shipping containers arranged in towering irregular stacks',
    weight: 5,
    tags: ['urban', 'interior'],
  },
  {
    text: 'metal grates and walkways connecting industrial platforms',
    weight: 5,
    tags: ['interior'],
  },
  {
    text: 'raised wooden boardwalk cutting through shallow marshland',
    weight: 5,
    tags: ['nature'],
  },
];
