/**
 * Scene cluster pool — split into SPOTS (passive backdrops) and
 * ACTIVITIES (signature scenarios with both characters doing X).
 * Both flavors preserve clean face-swap geometry: no profile, no overlap,
 * no back-turned. Default pick blends both; force_cluster_kind body param
 * lets QA force one or the other.
 */

export const SCENE_CLUSTERS_SPOTS: Record<string, string[]> = {
  'los angeles': [
    'the narrow alley between downtown skyscrapers with fire escape ladders overhead',
    'the rooftop garden of a mid-wilshire apartment building with potted succulents',
    'the concrete steps leading down to the los angeles river channel',
    'the vintage diner booth with cracked vinyl seats in silver lake',
    "the parking structure's top level with painted directional arrows on asphalt",
    'the metro platform bench beneath flickering fluorescent tube lighting fixtures',
    "the griffith observatory's copper dome exterior walkway with brass railings",
    'the venice boardwalk basketball court with chain-link nets and painted lines',
    "the beverly hills mansion's kidney-shaped swimming pool deck with diving board",
    "the chinatown herb shop's wooden counter covered in glass specimen jars",
    'the santa monica pier carousel house with hand-painted horses frozen mid-gallop',
    'the hollywood boulevard star embedded in terrazzo sidewalk surrounded by tourist feet',
    'the echo park lake pedal boat dock with metal cleats and rope bumpers',
    "the watts towers' mosaic-covered spire base with embedded bottle fragments",
    'the melrose avenue vintage clothing rack between mirrored changing room curtains',
    'the dodger stadium upper deck concrete bleacher seat with cup holders',
    "the getty center's travertine courtyard fountain with geometric water jets",
    'the olvera street market stall displaying handwoven textiles on wooden dowels',
    'the mulholland drive scenic overlook guardrail with city sprawl beyond',
    'the broadway theater district marquee ladder access point behind neon letters',
    "the korean town spa's jade sauna bench with heated stone surfaces",
    'the venice canals footbridge arching over narrow waterway with kayak below',
    'the los feliz hillside hiking trail switchback with exposed tree roots',
    "the downtown flower market's refrigerated display case filled with cut roses",
    'the malibu beach volleyball net post anchored deep in sand',
    "the pasadena craftsman bungalow's wraparound porch swing with chain suspension",
    'the beverly center mall escalator midpoint with glass panel city views',
    "the exposition park rose garden's wrought iron bench between blooming bushes",
    "the hollywood sign hiking trail's wooden fence overlook with warning signs",
    'the little tokyo ramen counter stool facing steaming kitchen prep station',
    "the westwood cemetery's marble headstone engraved with entertainment industry names",
    "the rodeo drive boutique's velvet rope stanchion beside mirrored entrance doors",
    "the los angeles county museum's outdoor tar pit observation platform",
    "the highland park coffee roastery's burlap sack storage area with metal scoops",
    'the pacific palisades bluff edge wooden bench facing ocean horizon',
    'the arts district warehouse loading dock with corrugated metal roll-up doors',
    "the laurel canyon recording studio's soundproof booth with acoustic foam panels",
    "the downtown library's marble reading room table with brass desk lamps",
    "the venice muscle beach outdoor gym's parallel bars with ocean breeze",
    "the silver lake reservoir's chain-link perimeter fence with jogging path beyond",
    "the beverly hills hotel's poolside cabana with striped canvas curtains",
    "the grand central market's butcher block counter with hanging scale hooks",
    "the griffith park merry-go-round's ticket booth window with faded paint",
    'the melrose trading post flea market table covered in vintage camera equipment',
    "the downtown loft's freight elevator with accordion gate and pulleys",
    'the manhattan beach strand bicycle path with painted lane divider lines',
    "the korean bell pavilion's ornate wooden platform with ceremonial bronze vessel",
    "the pink's hot dog stand's outdoor picnic table with checkered tablecloth pattern",
    "the runyon canyon hiking trail's rocky outcrop ledge with carved graffiti initials",
  ],
  'las vegas': [
    'the cramped counting room behind reinforced steel doors with surveillance monitors',
    'the vintage neon sign workshop cluttered with glass tubes and electrical components',
    'the rooftop helipad overlooking the geometric patterns of casino parking structures',
    'the underground tunnel system connecting hotel basements with utility pipes overhead',
    'the abandoned construction site elevator shaft with exposed rebar and concrete levels',
    'the casino cage window with stacked chip trays and currency counting machines',
    'the backstage area of a showroom with costume racks and mirror-lined dressing stations',
    'the narrow alleyway between casinos filled with industrial dumpsters and service equipment',
    'the penthouse balcony garden with artificial turf and potted palm arrangements',
    'the sports book area with wall-mounted screens and tiered seating arrangements',
    'the hotel laundry facility with industrial washing machines and hanging uniform racks',
    'the casino surveillance catwalk suspended above the gaming floor with camera equipment',
    'the themed restaurant kitchen with specialized cooking equipment and ingredient storage areas',
    'the chapel altar decorated with plastic flowers and red velvet draping',
    'the parking garage stairwell with numbered level markers and emergency lighting fixtures',
    'the pool deck maintenance shed storing chemical barrels and cleaning equipment',
    'the casino floor pit surrounded by curved dealer stations and chip sorting areas',
    'the hotel registration desk with computer terminals and key card programming machines',
    'the convention center loading dock with hydraulic lifts and equipment dollies',
    'the rooftop cooling system area with massive air conditioning units and ductwork',
    'the slot machine repair workshop with circuit boards and diagnostic equipment',
    'the hotel housekeeping cart storage room with towel shelves and cleaning supply dispensers',
    'the casino floor carpet replacement area with industrial adhesive and installation tools',
    'the buffet serving line with heated food wells and sneeze guard installations',
    'the hotel corridor intersection with directional signage and decorative column bases',
    'the casino cashier booth interior with bill validators and coin counting machinery',
    'the theater fly gallery with rope systems and lighting equipment suspended overhead',
    'the hotel pool filtration room with pumps and chemical injection system controls',
    'the casino floor beverage station with ice machines and drink preparation equipment',
    'the gift shop stockroom with merchandise boxes and price tag application stations',
    'the hotel elevator mechanical room with cable systems and safety inspection certificates',
    'the casino high roller suite bar area with premium bottle displays and mixing stations',
    'the themed attraction queue area with rope barriers and interactive display elements',
    'the hotel conference room with modular table arrangements and presentation equipment mounts',
    'the casino floor security checkpoint with metal detector frames and inspection tables',
    'the backstage magic show preparation area with trick apparatus and prop storage cabinets',
    'the hotel business center with computer workstations and document printing equipment',
    'the casino dealer break room with lockers and uniform hanging areas',
    'the themed restaurant seating booth with custom upholstery and decorative table fixtures',
    'the hotel guest corridor with ice machine alcoves and emergency exit hardware',
    'the casino floor progressive jackpot display area with digital counters and promotional banners',
    'the wedding chapel dressing room with vanity mirrors and flower arrangement preparation space',
    'the hotel rooftop antenna farm with communication equipment and satellite dish installations',
    'the casino floor money cart pathway with reinforced flooring and security camera coverage',
    'the themed bar mixing station with specialty glassware racks and ingredient refrigeration units',
    'the hotel pool cabana interior with privacy curtains and personal service equipment',
    'the casino floor slot tournament area with specialized seating and scoreboard displays',
    'the backstage costume fitting room with measurement tools and alteration equipment',
    'the hotel corridor art installation alcove with sculptural elements and display lighting fixtures',
    'the casino floor promotional prize display case with security locks and inventory tracking systems',
  ],
  hawaii: [
    'the weathered wooden pier extending into crystal-clear turquoise lagoon water',
    'inside the dim lava tube cave with rough black volcanic rock walls',
    'atop the red cinder cone crater rim overlooking dormant volcanic landscape below',
    'beside the traditional thatched-roof hale with woven palm frond walls and supports',
    'the narrow bamboo bridge crossing over rushing mountain stream through rainforest',
    'inside the abandoned sugar plantation mill with rusted machinery and concrete foundations',
    'the terraced taro fields with flooded paddies reflecting surrounding green mountains',
    'beneath the massive banyan tree with aerial roots creating natural archway passages',
    'the black sand beach shoreline where volcanic rock meets crashing ocean waves',
    'inside the traditional poi-making area with wooden bowls and stone grinding tools',
    'the cliff-edge heiau temple platform constructed from carefully stacked lava stones',
    'beside the vintage pineapple cannery conveyor belt with industrial processing equipment remains',
    'the hidden waterfall grotto behind curtain of falling water on moss-covered rocks',
    'inside the old whaling station building with thick stone walls and iron hooks',
    'the coral reef tide pool trapped between jagged volcanic rock formations',
    'beside the hand-carved outrigger canoe resting on smooth beach pebbles and sand',
    'the mountain ridge trail overlook with native ohia lehua trees and fern undergrowth',
    'inside the traditional imu underground oven pit lined with hot lava stones',
    'the fishing village dock with weathered nets draped over wooden posts',
    'beside the ancient petroglyph wall carved into dark basaltic rock face',
    'the macadamia nut orchard pathway between rows of mature flowering trees',
    'inside the abandoned military bunker with concrete walls and rusted metal doors',
    'the natural hot spring pool surrounded by tropical vegetation and steam vents',
    'beside the traditional calabash gourd workshop with carved wooden tools scattered about',
    'the rocky tide line where green sea turtles rest on warm basalt ledges',
    'inside the historic mission church with coral block walls and simple wooden pews',
    'the coffee plantation drying deck with beans spread across wooden screening platforms',
    'beside the hand-built stone wall marking ancient land division boundaries through forest',
    'the sea cliff bird watching station with rough wooden bench and binocular stand',
    'inside the traditional kapa cloth making area with wooden beaters and mulberry bark',
    'the mountain stream swimming hole carved naturally into volcanic rock basin below',
    'beside the vintage sugar cane railway tracks overgrown with wild tropical plants',
    'the sacred grove of native koa trees with massive trunks and canopy overhead',
    'inside the fish auction house with concrete floors and hanging scale equipment',
    'the remote beach cove accessible only through narrow gap between towering rock walls',
    'beside the traditional fishing shrine with offerings placed on carved wooden platform',
    'the hillside terraced gardens with native plants arranged in geometric stone patterns',
    'inside the old paniolo ranch barn with wooden stalls and leather tack hanging',
    'the natural arch formation carved by ocean waves into coastal cliff face',
    'beside the hand-woven fishing net repair station with tools and cordage materials',
    'the mountaintop radio tower clearing with equipment buildings and access road',
    'inside the traditional luau preparation kitchen with large wooden cutting blocks and utensils',
    'the secluded monastery garden with meditation paths between rows of cultivated herbs',
    'beside the vintage lighthouse keeper quarters with thick walls and narrow windows',
    'the geothermal field with natural steam vents rising from cracked earth surface',
    'inside the traditional voyaging navigation school with star charts and wayfinding instruments',
    'the mangrove swamp boardwalk winding between twisted root systems and shallow water',
    'beside the hand-carved tikis standing guard at entrance to sacred ceremonial grounds',
    'the abandoned resort swimming pool now filled with rainwater and tropical vegetation',
    'inside the working blacksmith forge with traditional hawaiian metalworking tools and anvil',
  ],
  'bora bora tahiti': [
    'the narrow bamboo walkway connecting overwater bungalow platforms above the lagoon',
    'inside the glass-bottom boat cabin with steering wheel and navigation equipment',
    'the thatched-roof beach bar counter made from polished driftwood planks',
    'underneath the raised stilts of an overwater villa looking up at floorboards',
    'the volcanic rock tide pool filled with coral fragments and sea anemones',
    'the hotel reception desk carved from single piece of tamanu wood',
    'inside the outrigger canoe storage shed lined with paddles and fishing nets',
    'the diving equipment rack beside concrete steps leading into deep water',
    'the traditional fare kitchen with stone oven and woven palm leaf walls',
    'the narrow sandy path between towering coconut palm tree trunks',
    'the floating dock extension with metal cleats and rubber bumper strips',
    'inside the pearl farm sorting room with microscopes and grading tables',
    'the hilltop radar station platform overlooking multiple lagoon sections',
    'the beachside massage pavilion with bamboo floor mats and oil storage shelves',
    'underneath the main resort pier looking up through wooden support beams',
    'the traditional breadfruit roasting pit surrounded by volcanic stone circle',
    'the snorkeling gear rental kiosk with fins hanging from wooden pegs',
    'inside the catamaran sail storage compartment below deck level',
    'the coral garden viewing platform with underwater viewing windows installed',
    'the beach volleyball court net post anchored in white sand',
    'the traditional tamaaraa feast preparation area with banana leaf stations',
    'inside the island supply boat cargo hold filled with provision crates',
    'the lagoon edge mangrove root system creating natural archway entrance',
    'the resort laundry facility with industrial washers and drying line posts',
    'the traditional dance performance circular stage made from coral stones',
    'inside the marine biology research station with specimen tanks and equipment',
    'the helicopter landing pad marked with painted concrete circle and windsock',
    'the traditional fishing canoe repair workshop with tools and wood shavings',
    'underneath the resort restaurant deck looking up at table legs and floorboards',
    'the beach bonfire pit surrounded by driftwood log seating arrangement',
    'inside the island clinic examination room with medical supplies and equipment',
    'the traditional vanilla plantation drying shed with hanging bean bundles',
    'the resort wine cellar carved into hillside volcanic rock formation',
    'the floating restaurant kitchen boat anchored near the main dining platform',
    'underneath the airport runway observation tower looking up at control equipment',
    'the traditional copra drying platform made from woven coconut palm fronds',
    'inside the island telecommunications building with satellite dishes and radio equipment',
    'the beach hammock anchor posts carved from ironwood tree trunks',
    'the lagoon research buoy maintenance platform with scientific monitoring equipment',
    'inside the traditional thatched-roof church with hand-carved wooden pews',
    'the coral restoration project underwater work platform suspended by chains',
    'the resort spa treatment room floor made from smooth river stones',
    'inside the island generator building with diesel engines and electrical panels',
    'the traditional navigation stone platform used for celestial observation teaching',
    'the beach shower stall made from bamboo walls and coral stone floor',
    'inside the pearl diving equipment shed with air compressors and diving bells',
    'the floating wedding chapel platform decorated with native hibiscus flower posts',
    'the traditional fishing net repair station with wooden frames and cordage spools',
    'inside the island radio station broadcast booth with vintage transmitting equipment',
    'the resort infinity pool edge where water meets natural lagoon boundary',
  ],
  'caribbean island': [
    'the weathered dock planks where fishing nets hang drying on metal hooks',
    "inside the cramped lighthouse keeper's quarters with nautical charts covering every wall",
    'the coral stone steps leading down to a hidden freshwater cenote',
    'atop the crumbling watchtower overlooking jagged volcanic cliffs and tide pools',
    'the narrow bamboo bridge spanning between two moss-covered limestone pillars',
    'inside the abandoned rum distillery with copper stills and broken ceramic jugs',
    'the sandy clearing where driftwood benches circle a fire pit lined with conch shells',
    'beneath the stilted beach hut where hammocks swing between salt-stained support posts',
    'the rocky outcrop cave entrance framed by dangling aerial roots and fern fronds',
    "atop the wooden pier's end platform with rusty cleats and coiled rope piles",
    "inside the island's tiny post office with hand-carved sorting cubbies and vintage scales",
    'the terraced garden steps carved into hillside rock with ceramic water catchment bowls',
    "beside the beached catamaran's hull now serving as a makeshift tool shed",
    'the narrow alleyway between coral block buildings with clotheslines overhead',
    'inside the palm thatch market stall displaying woven baskets and carved wooden masks',
    'the natural swimming hole surrounded by smooth boulders and overhanging sea grape branches',
    "atop the fort's cannon platform with iron wheels and pyramid-stacked cannonballs",
    'beside the traditional bread oven built from stacked stones and clay mortar',
    'the covered veranda with rocking chairs facing geometric tile floor patterns',
    "inside the boat builder's workshop with wood shavings and half-finished hull frames",
    "the windmill's upper platform with massive wooden gears and canvas sail remnants",
    'beside the roadside fruit stand with hand-painted signs and bamboo display racks',
    'the monastery ruins with crumbling archways and wild orchids growing through cracks',
    "inside the island school's single classroom with chalkboard and mismatched wooden desks",
    'the natural arch formation creating a frame for distant ocean views',
    'beside the solar panel array mounted on concrete blocks behind chain-link fencing',
    'the tide pool terrace with naturally carved channels and trapped colorful fish',
    'inside the customs house with official stamps and faded maritime regulation posters',
    'the hillside switchback trail with hand-carved wooden railings and erosion barriers',
    'beside the rain collection cistern with mesh covers and overflow pipes',
    'the beach cave entrance accessible only during low tide periods',
    'inside the conch shell processing station with grinding wheels and sorting tables',
    'the cemetery overlooking the sea with coral headstones and iron crosses',
    'beside the community radio tower with guy wires and weathered equipment boxes',
    'the mangrove boardwalk threading between twisted roots and brackish water channels',
    'inside the island clinic with medical supplies stored in glass-front cabinets',
    'the coconut grove clearing with machete-scarred trees and husking stations',
    'beside the desalination plant intake pipes extending into crystal-clear shallows',
    'the rooftop garden terrace with raised beds and drip irrigation tubing',
    "inside the island's single gas station with hand-pumped fuel dispensers",
    'the natural spring source bubbling up through layered sedimentary rock formations',
    'beside the satellite dish installation surrounded by backup generators and cable runs',
    'the beach volleyball court with rope boundaries and driftwood scoreboards',
    'inside the turtle conservation hatchery with temperature-controlled sand boxes',
    'the zipline platform built around massive mahogany tree trunk and heavy branches',
    'beside the wind-powered water pump with spinning blades and storage tanks',
    'the coral reef snorkel station with gear racks and underwater viewing tubes',
    'inside the ice house with thick walls and vintage refrigeration machinery',
  ],
  'moab arches': [
    'narrow slot canyon passage with striped sandstone walls towering overhead',
    'ancient petroglyphs carved into smooth red rock face beside weathered boulder',
    'natural stone bridge spanning deep desert wash with scattered juniper trees below',
    "precarious rocky outcrop jutting from massive arch formation's eastern edge",
    'hidden alcove behind fallen sandstone slabs with pack rat midden deposits',
    'steep talus slope of fractured red rock leading to towering fin formation',
    'natural stone amphitheater with curved walls and sandy floor depression',
    'narrow ledge system traversing vertical cliff face with iron oxide staining',
    'collapsed rock shelter with massive capstone creating protected overhang space',
    'eroded sandstone knobs and hoodoos clustered in small desert clearing',
    'natural water pocket carved into solid rock with mineral deposit rings',
    'ancient sand dune crossbedding exposed in vertical cliff wall section',
    'narrow chimney crack between two massive sandstone fin formations',
    'weathered stone steps naturally carved by millennia of water erosion',
    'balanced rock formation perched atop slender sandstone pedestal base',
    'deep pothole depression filled with wind-blown sand and desert debris',
    'natural stone arch spanning narrow canyon with cottonwood trees below',
    'vertical crack system with wedged boulders creating natural ladder rungs',
    'smooth sandstone dome with desert varnish streaking down curved surface',
    'narrow ridge connecting two separate arch formations across small valley',
    'natural stone window opening in massive cliff wall formation',
    'eroded sandstone caves with multiple chambers carved by ancient waters',
    'tilted rock slabs creating natural stairs up steep canyon wall',
    'narrow corridor between parallel sandstone fins with gravelly floor',
    'natural stone platform overlooking expansive desert valley and distant mountains',
    'weathered sandstone pillar with horizontal bedding layers clearly visible',
    'ancient rockfall debris field with house-sized boulders scattered randomly',
    'natural stone bench carved into cliff base by wind erosion',
    'narrow passage through keyhole opening in massive sandstone wall',
    'eroded sandstone badlands with intricate maze of small washes',
    'natural stone bridge with deep pools carved in bedrock below',
    'vertical sandstone wall with horizontal traverse ledge system',
    'collapsed arch remnant creating natural stone gateway and frame',
    'smooth sandstone bowl depression with scattered desert wildflower patches',
    'narrow slot with polished walls worn smooth by flash flooding',
    'natural stone ramp leading up massive sandstone dome formation',
    'deep alcove with seeping spring creating hanging garden microhabitat',
    'weathered sandstone tower standing isolated in small desert basin',
    'natural stone arch framing distant mountain peaks through opening',
    'eroded cliff face with honeycomb weathering patterns in rock',
    'narrow peninsula of stone jutting into temporary desert playa',
    'natural stone steps descending into hidden canyon floor depression',
    'massive boulder jam creating natural bridge across narrow wash',
    'weathered sandstone fin with natural windows and openings throughout',
    'smooth rock slides polished by centuries of wind and sand',
    'natural stone terrace system carved into sloping cliff face',
    'eroded sandstone maze with interconnected passages and dead ends',
    'natural stone viewing platform atop narrow sandstone spine formation',
    'deep canyon confluence where multiple washes merge and separate',
    'weathered cliff alcove with natural stone seats and resting spots',
  ],
  'space station': [
    'the narrow maintenance crawlway between humming server racks and cooling pipes',
    "the curved observation bubble protruding from the station's outer hull",
    'the zero-gravity gymnasium with padded walls and floating exercise equipment',
    'the hydroponic garden chamber with vertical growing towers and irrigation lines',
    'the cramped airlock vestibule with emergency suits hanging on magnetic hooks',
    'the central communications array surrounded by blinking antenna control panels',
    "the rotating habitat ring's jogging track with artificial gravity underfoot",
    "the machine shop's workbench cluttered with metal shavings and precision tools",
    "the waste processing facility's control station overlooking recycling chambers",
    "the chapel's meditation alcove with a small porthole facing deep space",
    "the crew quarters' communal kitchen with magnetic meal containers",
    "the emergency shelter pod's reinforced interior with backup life support",
    "the cargo bay's loading platform beside massive shipping containers",
    "the research lab's specimen storage wall with hundreds of labeled samples",
    "the reactor room's elevated catwalk overlooking fusion containment units",
    "the docking bay's traffic control booth with approach vector displays",
    "the water reclamation plant's filtration chamber with transparent processing tubes",
    "the crew lounge's reading nook with built-in bookshelf and cushioned seating",
    "the navigation deck's star chart table with holographic projection capabilities",
    "the medical bay's surgical suite with retractable operating table",
    "the quarters' personal workspace with fold-down desk and storage compartments",
    "the greenhouse dome's central fountain surrounded by flowering plants",
    "the engine room's diagnostic station monitoring thrust vector systems",
    "the recreation room's gaming corner with wall-mounted entertainment screens",
    "the galley's food preparation area with magnetic cutting boards",
    "the sleeping pod's cramped bunk with personal storage nets",
    "the conference room's presentation wall displaying mission timeline charts",
    "the atmospheric processor's monitoring console tracking oxygen levels",
    "the workshop's 3d printer station with spools of construction filament",
    "the observation lounge's curved seating area facing the main viewport",
    "the laboratory's chemical analysis station with protective glass barriers",
    "the fitness center's resistance training harness mounted to ceiling tracks",
    "the storage compartment's inventory shelving system with labeled containers",
    "the communications room's radio operator desk with multiple frequency controls",
    "the quarters' hygiene station with water recycling shower compartment",
    "the research dome's telescope mount with precision tracking mechanisms",
    "the cafeteria's serving line with heated food distribution units",
    "the backup bridge's emergency command chair facing simplified control arrays",
    "the manufacturing bay's assembly line with robotic fabrication arms",
    "the crew recreation area's artificial window displaying earth imagery",
    "the maintenance shaft's tool storage alcove with organized equipment racks",
    'the medical isolation chamber with transparent quarantine barriers',
    "the library's digital archive terminal with floating holographic displays",
    "the laundry facility's cleaning unit dispensing sanitized clothing",
    "the crew meeting area's circular table with integrated data displays",
    'the solar panel maintenance platform overlooking massive energy collectors',
    "the sleeping quarters' privacy curtain surrounding personal sleeping space",
    "the geology lab's rock sample analysis station with microscopic equipment",
    "the mess hall's waste disposal unit with automated sorting mechanisms",
    "the command center's tactical display showing surrounding space debris",
    'the botanical research greenhouse with climate control monitoring stations',
    "the crew gymnasium's climbing wall with magnetic handholds",
    "the quarters' personal communication booth for private video calls",
    'the backup life support chamber with redundant oxygen generation systems',
    "the recreation deck's virtual reality pod with motion tracking sensors",
    "the medical bay's rehabilitation area with physical therapy equipment",
    "the storage bay's inventory robot charging station with docking ports",
    "the crew quarters' social area with modular furniture arrangements",
    "the laboratory's clean room entrance with decontamination spray nozzles",
    "the navigation room's course plotting table with interstellar maps",
    "the pressurized greenhouse's mushroom cultivation racks with humidity control nozzles",
    "the outer hull maintenance bay's robotic arm storage cradles",
    "the crew quarters' fold-out dining table with magnetic plate holders",
    "the atmospheric recycling plant's carbon dioxide scrubber chambers",
    "the observation deck's telescope housing with manual adjustment wheels",
    "the emergency pod's launch tube with countdown timer displays",
    "the solar array control room's panel alignment monitoring screens",
    "the crew lounge's holographic fireplace alcove with comfort seating",
    "the backup generator room's fuel cell stack with warning indicators",
    "the medical bay's centrifuge chamber for blood sample processing",
    "the quarters' murphy bed frame with integrated storage drawers",
    "the communications array's satellite dish maintenance platform",
    "the hydroponics lab's nutrient mixing station with chemical dispensers",
    "the cargo hold's magnetic crane operator booth overlooking shipping lanes",
    "the crew recreation center's ping pong table with tethered paddles",
    "the water treatment facility's membrane filter replacement chamber",
    "the workshop's metal fabrication forge with automated hammering arms",
    "the sleeping quarters' personal ventilation duct with adjustable airflow",
    "the bridge's backup navigation console with mechanical compass displays",
    "the botanical lab's pollination chamber with artificial bee drones",
    "the crew quarters' personal storage locker with biometric lock",
    "the reactor cooling system's heat exchanger monitoring station",
    "the mess hall's automated dishwashing unit with sanitization cycles",
    "the external repair bay's pressure suit testing chamber",
    "the crew fitness area's stationary bike with resistance magnetic wheels",
    "the laboratory's specimen freezer unit with temperature alarm systems",
    "the quarters' fold-down workspace with integrated computer terminal",
    "the docking bay's umbilical connection panel with fluid transfer gauges",
    "the atmospheric processor's humidity regulation chamber with mist nozzles",
    "the crew lounge's coffee brewing station with zero gravity dispensers",
    "the medical bay's x-ray imaging booth with lead-lined protective walls",
    "the storage area's automated retrieval system with conveyor belt mechanisms",
    "the observatory's spectrometer calibration bench with precision optical equipment",
    "the crew quarters' personal bathroom pod with vacuum waste systems",
    "the power distribution room's circuit breaker panels with status indicators",
    "the recreation area's chess board table with magnetized game pieces",
    "the laboratory's gas chromatography station with sample injection ports",
    "the crew dining area's food rehydration unit with steam vents",
    "the maintenance tunnel's pipe junction box with valve control wheels",
    "the medical facility's pharmacy storage cabinet with dose measurement scales",
    "the quarters' personal exercise corner with resistance band anchor points",
    "the communications room's message encryption terminal with security protocols",
    "the botanical section's seed germination chamber with growth monitoring sensors",
    "the crew workspace's document scanner with digital archive upload",
    "the atmospheric control room's pressure regulation valve assembly",
    "the recreation deck's musical instrument storage with acoustic dampening",
    "the laboratory's protein crystallization chamber with temperature gradient controls",
    "the crew quarters' personal reading lamp with adjustable beam focus",
    "the waste management facility's compactor chamber with hydraulic compression rams",
    "the external sensor array's calibration booth with signal amplification equipment",
  ],
  'alien planet': [
    'the crystalline cave entrance with hexagonal mineral formations jutting from walls',
    'the abandoned mining shaft with rusted extraction equipment and drill bits',
    'the floating platform suspended above a methane lake by invisible fields',
    'the spiral observation tower carved from a single massive bone structure',
    'the underground fungal garden with bioluminescent spore cultivation pods',
    'the crashed starship cockpit half-buried in purple sand dunes',
    'the ancient stone circle with hovering monoliths defying gravity',
    'the geothermal vent field with steaming mineral deposits and bubbling pools',
    'the tree hollow within a massive silicon-based organism with glowing sap',
    'the cliff edge overlooking a valley of razor-sharp glass formations',
    'the abandoned research station with specimen containers and analysis equipment',
    'the natural amphitheater formed by curved rock walls and acoustic chambers',
    'the frozen waterfall of liquid nitrogen with ice crystal formations',
    'the underground river crossing with stepping stones of polished metal',
    'the gravity-defying rock garden with floating boulders and twisted plants',
    'the ancient burial mound entrance guarded by weathered alien statues',
    'the observation deck built into a living mountain with breathing vents',
    'the dried lakebed covered in hexagonal mud cracks and salt deposits',
    'the jungle clearing surrounded by carnivorous plants with snapping jaws',
    'the underground laboratory with containment cells and monitoring equipment',
    'the natural bridge spanning a chasm filled with swirling toxic gases',
    'the abandoned settlement with dome-shaped dwellings and windmill generators',
    'the crater rim with exposed geological layers showing planetary history',
    'the floating island connected to others by energy beam bridges',
    'the underground thermal spring with therapeutic mineral deposits and steam',
    'the ancient temple with rotating stone rings and celestial alignment markers',
    'the scrap yard filled with alien technology and mechanical debris',
    'the vertical cliff face with carved handholds and viewing platforms',
    'the desert oasis with metallic trees and liquid mercury pools',
    'the underground bunker with blast doors and emergency supply caches',
    'the natural cathedral with towering spire formations and echoing chambers',
    'the abandoned spaceport with rusted landing pads and fuel storage tanks',
    'the maze of coral-like structures with twisting passages and hidden chambers',
    'the mountain peak observatory with giant lens arrays and tracking equipment',
    'the underground mushroom forest with towering caps and dense spore clouds',
    'the floating rock formation with ancient carvings and wind chimes',
    'the dried riverbed with exposed alien fossils and skeletal remains',
    'the natural hot springs terraced into colorful mineral step formations',
    'the abandoned factory with conveyor belts and alien manufacturing equipment',
    'the cliff dwelling carved into rock face with narrow balconies',
    'the underground ice cavern with frozen waterfalls and crystal formations',
    'the floating garden platform with exotic alien flora and irrigation systems',
    'the natural stone arch spanning between two mountain peaks',
    'the abandoned observatory with massive telescope and star charts',
    'the underground tunnel system with bioluminescent wall markings and pathways',
    'the crater lake shore with black sand beaches and steaming geysers',
    'the ancient amphitheater with tiered seating carved from living rock',
    'the floating research station tethered to ground by energy cables',
    'the underground crystal chamber with resonating sound amplification properties',
    'the mountain cave mouth with stalactites and ancient cave paintings',
  ],
  'cyberpunk megacity': [
    'cramped noodle vendor stall wedged between towering holographic billboards and steam vents',
    'rooftop garden terrace with hydroponic towers overlooking corporate district traffic streams below',
    'underground mag-lev platform edge where commuter pods arrive through translucent tubes',
    'corporate executive washroom with mirror walls and biometric scanner door controls',
    'back-alley dumpster alcove behind chrome-clad restaurant with grease-stained concrete walls',
    'glass elevator shaft ascending through the hollow center of residential megablock tower',
    'abandoned subway tunnel intersection with rusted rail switches and cable junction boxes',
    'penthouse balcony jutting from glass pyramid apex above sprawling neon grid cityscape',
    'drone maintenance bay with robotic arms suspended from reinforced industrial ceiling tracks',
    'street-level phone booth cluster beneath massive video screen advertising neural implants',
    'fire escape landing halfway up brick tenement wall facing data center cooling towers',
    'underground parking garage ramp spiraling down past concrete pillars and security cameras',
    'rooftop helipad circle painted on weathered surface surrounded by communication antenna arrays',
    'corporate lobby reception desk carved from single block of synthetic marble',
    'narrow bridge walkway connecting two apartment towers high above busy traffic intersection',
    'basement server room corridor lined with humming processor banks and fiber optic bundles',
    'corner newsstand kiosk surrounded by magazine racks displaying digital publication covers',
    'loading dock platform where delivery trucks back up to warehouse roll-up doors',
    'outdoor market stall selling circuit boards spread on folding tables under canvas awning',
    'glass-walled conference room table surrounded by ergonomic chairs overlooking financial district',
    'emergency stairwell landing with concrete steps and yellow safety railings between floor levels',
    'rooftop water tank platform with maintenance ladders and piping infrastructure visible around edges',
    'sidewalk bus stop bench beside digital transit schedule display and covered waiting area',
    'corporate cafeteria serving counter with food dispensers and employee badge scanning stations',
    'underground tunnel maintenance hatch opening with ladder rungs leading down into darkness',
    'residential balcony clothesline strung between metal railings with potted plants along edges',
    'parking meter post on sidewalk corner next to pedestrian crossing signal control box',
    'rooftop greenhouse dome interior with climate control vents and automated watering system tracks',
    'basement workshop table scattered with electronic components and soldering equipment',
    'glass skybridge tube connecting office buildings with pedestrian walkway and handrail supports',
    'street vendor cart parked beside traffic light pole selling synthetic food from heated compartments',
    'corporate executive elevator interior with polished metal panels and floor selection touchscreen interface',
    'underground storage vault door with heavy hinges and electronic lock mechanism mounted',
    'rooftop satellite dish installation platform surrounded by communication equipment and cable conduits',
    'sidewalk recycling station with sorted material bins and automated collection chute openings',
    'residential kitchen counter with built-in appliances and cabinet storage underneath preparation surface',
    'corporate security checkpoint turnstile gate with metal detector arch and guard station booth',
    'underground utility tunnel junction where water pipes intersect with electrical conduit pathways',
    'rooftop air conditioning unit cluster with cooling fans and refrigeration lines connecting buildings',
    'sidewalk food cart workspace with cooking surface and ingredient storage compartments built-in',
    'basement laundry room with industrial washing units and clothes hanging lines across ceiling',
    'corporate boardroom presentation screen wall with conference table seating arranged facing display',
    'underground pedestrian tunnel entrance with tiled walls and directional signage mounted overhead',
    'rooftop communication tower base platform with guy-wire anchor points and equipment housing structures',
    'sidewalk repair station with tool chest and work surface for fixing electronic devices',
    'basement boiler room with heating pipes and pressure gauges mounted on brick walls',
    'corporate archive storage room with filing cabinets and document retrieval system access terminals',
    'underground tunnel service alcove with utility shutoff valves and emergency equipment storage brackets',
    'rooftop zen meditation space with cushioned seating area surrounded by bamboo privacy screens',
    'sidewalk augmented reality arcade booth with haptic feedback gloves and neural interface headsets',
  ],
  'mars colony': [
    'the hydroponic greenhouse with tiered growing chambers and nutrient flow monitors',
    'the cramped airlock vestibule with decontamination nozzles and pressure suit hooks',
    'the solar panel maintenance platform overlooking the rust-colored canyon below',
    'the underground water reclamation facility with massive filtration tanks and piping',
    "the observation deck's curved transparent dome revealing the alien landscape",
    'the machine shop with 3d printers and spare habitat module components',
    "the dining hall's communal tables beneath exposed ventilation ducting",
    "the medical bay's examination pod with diagnostic screens and equipment carts",
    'the communications tower base surrounded by satellite dishes and transmission equipment',
    'the waste processing chamber with recycling units and compaction machinery',
    "the exercise room's treadmill facing a simulated earth landscape display",
    "the library alcove carved into the habitat's curved interior wall",
    "the geology lab's rock analysis station with microscopes and sample containers",
    "the reactor room's control panel array monitoring fusion core temperature",
    "the emergency shelter's reinforced bunker with supply lockers lining the walls",
    'the mining equipment garage housing rovers and drilling apparatus',
    'the botanical research station with specimen preservation units and growth charts',
    'the corridor junction where multiple habitat tubes converge with directional signage',
    'the water storage cavern with enormous tanks and pressure monitoring systems',
    "the workshop's welding station surrounded by metal fabrication tools",
    "the children's play area with climbing structures adapted for martian gravity",
    "the cafeteria's food preparation counter with atmospheric processors humming overhead",
    "the sleeping quarters' privacy pod with personal storage compartments",
    "the laboratory's centrifuge station for separating martian soil samples",
    "the trading post's merchant stalls displaying earth imports and local crafts",
    'the vehicle maintenance bay with atmospheric rovers in various repair states',
    "the meditation chamber's circular seating area beneath a transparent ceiling panel",
    "the server room housing the colony's data storage and communication systems",
    "the loading dock's cargo platform where supply drops are sorted and distributed",
    "the meeting hall's amphitheater seating facing a large presentation screen",
    "the rooftop garden's elevated planters with automated watering systems",
    'the emergency supply depot with shelving units packed with survival equipment',
    'the artisan workshop where colonists create furniture from recycled materials',
    'the weather monitoring station with atmospheric sensors and data collection equipment',
    "the childcare center's soft play area with educational displays about mars",
    'the thermal regulation room housing heating units and environmental controls',
    'the memorial wall displaying names and photographs of earth families',
    'the fabrication bay where building materials are produced from martian resources',
    "the social lounge's conversation pit with cushioned seating around low tables",
    "the research archive's climate-controlled storage for scientific documentation",
    'the security checkpoint with scanners and identification verification systems',
    "the fitness center's resistance training equipment designed for low gravity",
    "the colony administrator's office with planning charts covering the walls",
    'the recycling center where plastics and metals are sorted for reprocessing',
    'the backup life support chamber with redundant oxygen generation systems',
    'the community bulletin board area with announcements and personal messages',
    "the quarantine facility's isolation chambers for incoming personnel health screening",
    "the tool library's organized storage racks for shared equipment and instruments",
    "the stargazing platform's telescope mount pointing toward earth's distant star",
    'the colony entrance vestibule with welcome signs and orientation materials',
  ],
};

export const SCENE_CLUSTERS_ACTIVITIES: Record<string, string[]> = {
  'los angeles': [
    'standing side-by-side on hollywood walk of fame looking for stars on ground',
    'walking side-by-side through venice beach boardwalk with street performers around',
    'standing side-by-side at griffith observatory with city sprawl behind',
    'sitting side-by-side on santa monica pier bench watching ferris wheel',
    'standing side-by-side holding surfboards at malibu beach ready to enter water',
    'walking side-by-side through beverly hills palm tree lined residential street',
    'standing side-by-side at mulholland drive scenic overlook viewing los angeles basin',
    'sitting side-by-side at outdoor farmers market table eating fresh produce',
    'standing side-by-side outside chinese theatre comparing handprints in cement',
    'walking side-by-side down melrose avenue browsing vintage shop windows',
    'standing side-by-side at dodger stadium concourse holding baseball game programs',
    'sitting side-by-side at rooftop bar table with downtown skyline backdrop',
    'standing side-by-side on manhattan beach volleyball court holding ball',
    'walking side-by-side through little tokyo district past colorful storefronts',
    'standing side-by-side at getty center balcony overlooking pacific ocean',
    'sitting side-by-side on redondo beach fishing pier with rods extended',
    'standing side-by-side at rodeo drive crosswalk holding luxury shopping bags',
    'walking side-by-side through arts district checking street art murals',
    'standing side-by-side at hollywood sign viewpoint taking photos together',
    'sitting side-by-side at outdoor taco truck picnic table sharing plates',
    'standing side-by-side on runyon canyon hiking trail with city view',
    'walking side-by-side through grand central market past food vendor stalls',
    'standing side-by-side at lakers game entrance holding tickets and jerseys',
    'sitting side-by-side at outdoor cafe on sunset strip people watching',
    'standing side-by-side at santa monica muscle beach watching workout demonstrations',
    'walking side-by-side through olvera street past mexican craft vendor booths',
    'standing side-by-side at universal studios entrance holding park maps',
    'sitting side-by-side on hermosa beach blanket with volleyball nets nearby',
    'standing side-by-side outside walt disney concert hall admiring metallic architecture',
    'walking side-by-side through west hollywood rainbow crosswalk during festival',
    'standing side-by-side at la brea tar pits museum entrance reading exhibits',
    'sitting side-by-side at korean barbecue restaurant table with grilling meat',
    'standing side-by-side on angeles crest highway mountain overlook viewing valley',
    'walking side-by-side through pasadena old town antique shopping district',
    'standing side-by-side at lacma urban lights installation between lamp posts',
    'sitting side-by-side at in-n-out burger outdoor patio sharing animal style fries',
    'standing side-by-side on catalina island ferry deck approaching santa catalina',
    'walking side-by-side through chinatown past red lanterns and herb shops',
    'standing side-by-side at malibu creek state park trailhead with hiking gear',
    'sitting side-by-side at comedy club table waiting for standup show',
    'standing side-by-side outside dolby theatre holding oscars ceremony viewing tickets',
    'walking side-by-side through exposition park rose garden between flower beds',
    'standing side-by-side at topanga state park mountain trail junction consulting map',
    'sitting side-by-side at beachside fish taco stand counter ordering food',
    'standing side-by-side at warner bros studio tour entrance holding visitor passes',
    'walking side-by-side through highland park hipster neighborhood browsing coffee shops',
    'standing side-by-side at point dume nature preserve cliff edge overlooking malibu',
    'sitting side-by-side at dodgers game bleacher seats holding foam fingers',
    'standing side-by-side at observatory planetarium entrance checking show schedules',
    'walking side-by-side through silver lake reservoir path with downtown backdrop',
  ],
  'las vegas': [
    'standing side-by-side at slot machines in casino, pulling handles',
    'sitting side-by-side at blackjack table, cards visible on felt',
    'standing side-by-side at craps table, dice in motion',
    'walking side-by-side through casino floor, bright lights overhead',
    'standing side-by-side at roulette wheel, chips on table',
    'sitting side-by-side at poker table, cards in hands',
    'standing side-by-side holding cocktails at casino bar',
    'walking side-by-side down the strip, neon signs glowing',
    'standing side-by-side in front of bellagio fountains, water shooting up',
    'sitting side-by-side watching cirque du soleil performance, stage ahead',
    'standing side-by-side at buffet line, plates in hands',
    'walking side-by-side through venetian canal shops, gondolas nearby',
    'standing side-by-side at high roller observation wheel entrance',
    'sitting side-by-side in high roller cabin, city sprawling below',
    'standing side-by-side at welcome to las vegas sign',
    'walking side-by-side through fremont street experience, lights overhead',
    'standing side-by-side at wedding chapel entrance, bouquet visible',
    'sitting side-by-side at magic show, performer on stage',
    'standing side-by-side at sports betting window, tickets in hand',
    'walking side-by-side through red rock canyon trail',
    'standing side-by-side at hoover dam overlook, concrete structure behind',
    'sitting side-by-side at outdoor pool deck, drinks nearby',
    'standing side-by-side at zipline platform, harnesses secured',
    'walking side-by-side through valley of fire, red rocks visible',
    'standing side-by-side at helicopter tour boarding area',
    'sitting side-by-side in helicopter cabin, desert landscape below',
    'standing side-by-side at grand canyon skywalk entrance',
    'walking side-by-side through mob museum exhibits',
    'standing side-by-side at neon museum sign graveyard',
    'sitting side-by-side at steakhouse table, wine glasses present',
    'standing side-by-side at celebrity chef restaurant entrance',
    'walking side-by-side through forum shops, roman statues nearby',
    'standing side-by-side at nightclub entrance, rope barriers visible',
    'sitting side-by-side at rooftop lounge, city lights twinkling',
    'standing side-by-side at poolside cabana, towels draped',
    'walking side-by-side through downtown container park, shipping containers stacked',
    'standing side-by-side at pawn stars shop entrance',
    'sitting side-by-side at comedy show, comedian on stage',
    'standing side-by-side at tattoo parlor consultation counter',
    'walking side-by-side through arts district murals, colorful walls behind',
    'standing side-by-side at dispensary counter, products displayed',
    'sitting side-by-side at spa relaxation area, robes worn',
    'standing side-by-side at shooting range counter, targets visible',
    'walking side-by-side through chinatown plaza, lanterns hanging',
    'standing side-by-side at golf course tee box, clubs ready',
    'sitting side-by-side at race and sports book, screens displaying odds',
    'standing side-by-side at escape room entrance, puzzle props nearby',
    'walking side-by-side through cosmopolitan terrace gardens',
    'standing side-by-side at vintage vegas car show, classic automobiles displayed',
    'sitting side-by-side at wine tasting bar, glasses lined up',
  ],
  hawaii: [
    'standing side-by-side holding surfboards upright on waikiki beach',
    'sitting side-by-side at a luau feast table with poi and kalua pig',
    'standing side-by-side at diamond head crater rim overlook',
    'walking side-by-side through honolulu chinatown market stalls',
    'standing side-by-side holding snorkel gear at hanauma bay',
    'sitting side-by-side on a catamaran deck heading to molokini crater',
    'standing side-by-side at rainbow falls waterfall viewing platform',
    'walking side-by-side along the road to hana coastal path',
    'standing side-by-side at mauna kea observatory stargazing area',
    'sitting side-by-side at a poke bowl counter in haleiwa',
    'standing side-by-side holding ukuleles at a music lesson',
    'walking side-by-side through a macadamia nut farm orchard',
    'standing side-by-side at kilauea volcano national park overlook',
    'sitting side-by-side on a beach mat with shave ice',
    'standing side-by-side holding fishing rods on a pier',
    'walking side-by-side through waimea canyon hiking trail',
    'standing side-by-side at pearl harbor memorial visitor center',
    'sitting side-by-side at a traditional hawaiian cultural show',
    'standing side-by-side holding mai tais at a tiki bar',
    'walking side-by-side along black sand beach at punaluu',
    'standing side-by-side at a farmers market buying fresh pineapple',
    'sitting side-by-side in outrigger canoe on calm lagoon',
    'standing side-by-side at napali coast helicopter tour landing',
    'walking side-by-side through bamboo forest on pipiwai trail',
    'standing side-by-side holding leis at polynesian cultural center',
    'sitting side-by-side at a coffee plantation tasting counter',
    'standing side-by-side at haleakala summit for sunrise viewing',
    'walking side-by-side along kaanapali beach boardwalk',
    'standing side-by-side holding coconuts at a roadside stand',
    'sitting side-by-side on a lanai overlooking kona coast',
    'standing side-by-side at akaka falls state park viewing deck',
    'walking side-by-side through lahaina historic whaling town',
    'standing side-by-side holding paddles after kayaking session',
    'sitting side-by-side at a beachside plate lunch wagon',
    'standing side-by-side at wailua river fern grotto entrance',
    'walking side-by-side along hookipa beach watching windsurfers',
    'standing side-by-side holding tropical fruits at dole plantation',
    'sitting side-by-side on a sunset dinner cruise deck',
    'standing side-by-side at sea life park dolphin encounter pool',
    'walking side-by-side through thurston lava tube cave',
    'standing side-by-side holding diving masks at molokini crater',
    'sitting side-by-side at a hawaiian bbq mixed plate restaurant',
    'standing side-by-side at iao valley state monument lookout',
    'walking side-by-side along lanikai beach powder sand shore',
    'standing side-by-side holding hiking poles at makapuu lighthouse',
    'sitting side-by-side at a beachfront spa relaxation area',
    'standing side-by-side at byodo temple bell ceremony',
    'walking side-by-side through kauai botanical gardens pathway',
    'standing side-by-side holding fresh coconut water on beach',
    'sitting side-by-side watching hula dancers at hotel performance',
  ],
  'bora bora tahiti': [
    'standing side-by-side on overwater bungalow deck looking toward lagoon',
    'sitting side-by-side in outrigger canoe holding paddles upright',
    'standing side-by-side at coral garden snorkel spot with masks raised',
    'walking side-by-side on motu island white sand beach',
    'standing side-by-side holding fresh coconuts at roadside stand',
    'sitting side-by-side on catamaran deck during lagoon tour',
    'standing side-by-side at mount otemanu viewpoint with hiking poles',
    'sitting side-by-side at lagoon-side restaurant with poisson cru plates',
    'standing side-by-side on pontoon dock preparing for ray feeding',
    'walking side-by-side through vaitape village main street',
    'standing side-by-side at pearl farm display counter examining tahitian pearls',
    'sitting side-by-side in glass-bottom boat looking through clear panels',
    'standing side-by-side on beach holding stand-up paddleboards vertically',
    'sitting side-by-side at tiki bar with tropical cocktails',
    'standing side-by-side at matira beach point watching lagoon waves',
    'walking side-by-side on raised coral walkway between motus',
    'standing side-by-side on helicopter landing pad before aerial tour',
    'sitting side-by-side on resort swing over turquoise lagoon water',
    'standing side-by-side at local market examining vanilla beans',
    'sitting side-by-side in traditional polynesian sailing canoe',
    'standing side-by-side on shark and ray excursion platform',
    'walking side-by-side through hotel gardens toward overwater villas',
    'standing side-by-side at sunset cruise departure dock',
    'sitting side-by-side on beach loungers between palm trees',
    'standing side-by-side at four seasons resort dock with snorkel gear',
    'walking side-by-side on wooden walkway connecting overwater bungalows',
    'standing side-by-side at lagoonarium feeding tropical fish',
    'sitting side-by-side on catamaran trampoline net over water',
    'standing side-by-side at bloody mary restaurant reading bamboo menu',
    'walking side-by-side on circle island road past coconut groves',
    'standing side-by-side at intercontinental thalasso spa entrance',
    'sitting side-by-side in lagoon chairs partially submerged in water',
    'standing side-by-side on private beach with pareo sarongs',
    'walking side-by-side through bora bora yacht club marina',
    'standing side-by-side at belvedere lookout point overlooking lagoon',
    'sitting side-by-side on outrigger canoe beach learning paddle techniques',
    'standing side-by-side at local church for sunday polynesian service',
    'walking side-by-side on coral sand toward lagoon picnic setup',
    'standing side-by-side at jet ski rental dock with life jackets',
    'sitting side-by-side on resort deck receiving traditional flower leis',
    'standing side-by-side at diving center preparing for lagoon dive',
    'walking side-by-side through coconut plantation on island tour',
    'standing side-by-side at food truck ordering fresh fish plates',
    'sitting side-by-side in beach cabana with woven palm roof',
    'standing side-by-side at tahitian dance show holding programs',
    'walking side-by-side on airport dock toward seaplane departure',
    'standing side-by-side at souvenir shop examining handwoven baskets',
    'sitting side-by-side on traditional polynesian bench under breadfruit tree',
    'standing side-by-side at aqua safari helmet diving preparation station',
    'sitting side-by-side on floating platform in middle of lagoon',
  ],
  'caribbean island': [
    'standing side-by-side holding snorkel gear on white sand beach',
    'sitting side-by-side at beachfront rum bar with tropical drinks',
    'standing side-by-side at conch shell vendor stall in local market',
    'walking side-by-side through colorful colonial town streets',
    'standing side-by-side holding fresh coconuts with straws',
    'sitting side-by-side on catamaran deck with ocean behind',
    'standing side-by-side at spice market examining local seasonings',
    'walking side-by-side on wooden pier extending into turquoise water',
    'standing side-by-side holding fishing rods at charter boat rail',
    'sitting side-by-side at steel drum performance in town square',
    'standing side-by-side at banana plantation during farm tour',
    'walking side-by-side through outdoor craft market stalls',
    'standing side-by-side holding kayak paddles beside rental stand',
    'sitting side-by-side at beachside jerk chicken restaurant',
    'standing side-by-side at waterfall swimming hole overlook',
    'walking side-by-side on coastal trail with ocean views',
    'standing side-by-side at local art gallery examining paintings',
    'sitting side-by-side on hammocks strung between palm trees',
    'standing side-by-side holding diving masks at reef tour boat',
    'walking side-by-side through sugar cane field on plantation tour',
    'standing side-by-side at reggae record shop browsing vinyl',
    'sitting side-by-side at sunset sailing trip aboard yacht',
    'standing side-by-side at historic fort cannon overlooking harbor',
    'walking side-by-side through botanical garden tropical plant paths',
    'standing side-by-side holding beach volleyball at resort court',
    'sitting side-by-side at coffee plantation tasting local beans',
    'standing side-by-side at sea turtle nesting beach observation point',
    'walking side-by-side on mangrove boardwalk nature trail',
    'standing side-by-side holding parasailing harnesses before launch',
    'sitting side-by-side at floating tiki bar in lagoon',
    'standing side-by-side at local distillery sampling aged rum',
    'walking side-by-side through limestone cave system tour',
    'standing side-by-side holding windsurfing boards at equipment rental',
    'sitting side-by-side at beachfront lobster shack dinner',
    'standing side-by-side at coral reef glass bottom boat rail',
    'walking side-by-side through friday night fish market',
    'standing side-by-side holding stand-up paddleboards at beach launch',
    'sitting side-by-side at carnival steel pan band performance',
    'standing side-by-side at iguana sanctuary feeding station',
    'walking side-by-side on black sand volcanic beach shoreline',
    'standing side-by-side at local cigar rolling workshop',
    'sitting side-by-side at oceanview restaurant with conch fritters',
    'standing side-by-side holding tennis rackets at resort court',
    'walking side-by-side through rainforest canopy bridge tour',
    'standing side-by-side at deep sea fishing boat equipment check',
    'sitting side-by-side at beachside domino game watching locals',
    'standing side-by-side holding surfboards at famous surf break',
    'walking side-by-side through historic plantation house grounds',
    'standing side-by-side at zipline platform overlooking jungle canopy',
    'sitting side-by-side at ferry dock waiting for inter-island transport',
  ],
  'moab arches': [
    'standing side-by-side beneath delicate arch looking up at the natural stone formation',
    'walking side-by-side along fiery furnace narrow canyon trail between red rock walls',
    'standing side-by-side at courthouse towers viewpoint with massive sandstone spires behind',
    'sitting side-by-side on slickrock ledge overlooking arches national park visitor center',
    'standing side-by-side reading trail map at devils garden trailhead entrance',
    'walking side-by-side on sandy wash trail toward landscape arch formation',
    'standing side-by-side at balanced rock formation with enormous boulder overhead',
    'sitting side-by-side on red sandstone bench at park avenue viewpoint',
    'standing side-by-side with hiking poles at windows section double arch opening',
    'walking side-by-side along primitive trail through desert sage and juniper trees',
    'standing side-by-side at turret arch framing delicate arch in natural window',
    'sitting side-by-side on carved rock steps at courthouse wash picnic area',
    'standing side-by-side with backpacks at broken arch trailhead starting hiking adventure',
    'walking side-by-side on established trail toward north and south windows',
    'standing side-by-side at wolfe ranch cabin historic homestead ruins display',
    'sitting side-by-side on smoothed sandstone at sand dune arch natural alcove',
    'standing side-by-side reading interpretive sign about geological formation processes',
    'walking side-by-side along moab fault zone exposed in weathered rock layers',
    'standing side-by-side with cameras at panorama point overlooking salt valley',
    'sitting side-by-side on natural stone amphitheater overlooking entrada sandstone formations',
    'standing side-by-side at pine tree arch hidden in devils garden area',
    'walking side-by-side on boardwalk section protecting fragile desert soil crust',
    'standing side-by-side with water bottles at eye of whale arch',
    'sitting side-by-side watching rock climbers scale sandstone walls at wall street',
    'standing side-by-side at three gossips towering red rock monoliths formation',
    'walking side-by-side through narrow fin formations carved by wind and water',
    'standing side-by-side at ribbon arch delicate span high above canyon floor',
    'sitting side-by-side on natural sandstone throne at courthouse towers overlook',
    'standing side-by-side with binoculars spotting desert bighorn sheep on cliff faces',
    'walking side-by-side along wash bottom following ancient water carved channels',
    'standing side-by-side at double o arch twin openings in massive rock wall',
    'sitting side-by-side sharing trail snacks at landscape arch longest natural span',
    'standing side-by-side photographing petroglyphs on courthouse wash rock panels',
    'walking side-by-side on primitive trail to tower arch remote formation',
    'standing side-by-side at fiery furnace guided tour meeting point entrance',
    'sitting side-by-side on red rock ledge watching sunset through delicate arch',
    'standing side-by-side with permits for canyoneering in technical slot canyons',
    'walking side-by-side toward klondike bluffs less crowded northern park section',
    'standing side-by-side at marching men rock formation resembling stone soldiers',
    'sitting side-by-side at camp site in devils garden established camping area',
    'standing side-by-side studying geological cross section exposed in road cut',
    'walking side-by-side on entrada sandstone following natural joint fractures',
    'standing side-by-side with climbing gear at three penguins rock formation',
    'sitting side-by-side watching desert wildlife from natural stone blind',
    'standing side-by-side at partition arch hidden opening in massive fin',
    'walking side-by-side through sand dune wash carved between towering walls',
    'standing side-by-side photographing arch formations framed by desert vegetation',
    'sitting side-by-side on petrified sand dune admiring vast desert landscape',
    'standing side-by-side at navajo arch secluded opening in remote canyon',
    'walking side-by-side returning from backcountry exploration carrying hiking gear',
  ],
  'space station': [],
  'alien planet': [
    'standing side-by-side observing floating crystal formations through protective visors',
    'walking side-by-side on glowing mineral pathways between towering spire rocks',
    'sitting side-by-side at observation deck watching binary suns through telescopes',
    'standing side-by-side collecting luminescent samples in containment pods',
    'walking side-by-side through zero-gravity bubble chambers wearing magnetic boots',
    'standing side-by-side at alien wildlife sanctuary feeding docile tentacled creatures',
    'sitting side-by-side in hovering transport pods overlooking purple canyon landscapes',
    'standing side-by-side operating translation devices at alien communication monuments',
    'walking side-by-side through bioluminescent forest trails with glow sticks',
    'standing side-by-side at spaceport terminal checking departure schedules on holographic displays',
    'sitting side-by-side at anti-gravity cafe with floating beverage spheres',
    'standing side-by-side wearing breathing apparatus at methane geysers viewpoint',
    'walking side-by-side on suspension bridges over phosphorescent acid lakes',
    'standing side-by-side at alien market examining exotic crystalline fruits',
    'sitting side-by-side in pressurized dome watching aurora storms through transparent walls',
    'standing side-by-side operating sonic mapping equipment near underground cavern entrance',
    'walking side-by-side through artificial atmosphere tunnels between surface domes',
    'standing side-by-side at magnetic field generator watching metal objects levitate',
    'sitting side-by-side on hover platforms crossing vast chasms between mesa formations',
    'standing side-by-side wearing radiation suits collecting samples from meteor impact crater',
    'walking side-by-side on moving walkways through underwater city observation tubes',
    'standing side-by-side at alien archaeological site examining hieroglyphic energy patterns',
    'sitting side-by-side in climate pods watching terraforming machines reshape distant mountains',
    'standing side-by-side operating holographic star charts at navigation training center',
    'walking side-by-side through hydroponic gardens in biodome agricultural facilities',
    'standing side-by-side at plasma fountain plaza watching colorful energy displays',
    'sitting side-by-side on crystalline benches listening to harmonic resonance concerts',
    'standing side-by-side wearing exosuits exploring abandoned alien temple complex',
    'walking side-by-side on electromagnetic paths through floating rock garden formations',
    'standing side-by-side at quantum laboratory observing particle beam experiments',
    'sitting side-by-side in meditation chambers experiencing telepathic communication training',
    'standing side-by-side operating gravity simulators testing different planetary conditions',
    'walking side-by-side through prismatic canyon where walls reflect rainbow spectrum',
    'standing side-by-side at alien embassy learning diplomatic protocols through neural interfaces',
    'sitting side-by-side on thermal vents warming up in protective environmental suits',
    'standing side-by-side at mineral extraction site watching robotic harvesters work',
    'walking side-by-side through time distortion fields experiencing temporal displacement effects',
    'standing side-by-side operating atmospheric processors monitoring oxygen production levels',
    'sitting side-by-side in sensory deprivation tanks experiencing alien consciousness simulation',
    'standing side-by-side at energy barrier checkpoint scanning identification through biometric readers',
    'walking side-by-side on spiral ramps ascending massive alien pyramid structures',
    'standing side-by-side at xenobiology lab observing microscopic alien life forms',
    'sitting side-by-side in memory banks downloading historical data from ancient civilizations',
    'standing side-by-side operating dimensional portals testing interdimensional travel technology',
    'walking side-by-side through magnetic storm shelters during electromagnetic weather events',
    'standing side-by-side at fusion reactor facility monitoring clean energy production systems',
    'sitting side-by-side in virtual reality chambers experiencing alien cultural immersion programs',
    'standing side-by-side at planetary defense grid observing asteroid deflection systems',
    'walking side-by-side through preserved alien cities frozen in temporal stasis fields',
    'standing side-by-side at interstellar communication array receiving messages from distant galaxies',
  ],
  'cyberpunk megacity': [
    'standing side-by-side at neon market stall examining holographic merchandise displays',
    'walking side-by-side through elevated glass walkway between towering arcology buildings',
    'sitting side-by-side at rooftop bar overlooking sprawling cityscape of glowing towers',
    'standing side-by-side at cybernetic enhancement clinic consultation counter comparing options',
    'walking side-by-side down rain-slicked alley lined with glowing advertisement holograms',
    'standing side-by-side at virtual reality arcade entrance selecting immersive experience pods',
    'sitting side-by-side on maglev train seats watching city blur past windows',
    'standing side-by-side at drone racing track holding remote controllers watching aerial competition',
    'walking side-by-side through underground tunnel system connecting megacity districts',
    'standing side-by-side at street food vendor sampling synthetic protein dishes',
    'sitting side-by-side at data cafe terminals browsing neural network interfaces',
    'standing side-by-side on observation deck of massive corporate tower surveying cityscape',
    'walking side-by-side through hydroponics market examining vertical farming produce displays',
    'standing side-by-side at black market tech bazaar inspecting illegal cybernetic implants',
    'sitting side-by-side in autonomous taxi watching holographic entertainment system together',
    'standing side-by-side at memory trading post negotiating purchase of experience recordings',
    'walking side-by-side along canal system beneath towering megastructures and bridges',
    'standing side-by-side at underground fighting arena betting terminals placing wagers',
    'sitting side-by-side at synthesized sushi bar watching robotic chef prepare meals',
    'standing side-by-side at corporate security checkpoint scanning biometric identification together',
    'walking side-by-side through climate-controlled biodome park within concrete jungle',
    'standing side-by-side at neural interface salon selecting consciousness expansion programs',
    'sitting side-by-side on magnetic levitation bench in central plaza people-watching',
    'standing side-by-side at holographic art gallery admiring three-dimensional light sculptures',
    'walking side-by-side through abandoned sector exploring derelict buildings and machinery',
    'standing side-by-side at augmented reality gaming center wearing headset equipment',
    'sitting side-by-side at pharmacology bar sampling mood-altering synthetic cocktails together',
    'standing side-by-side at recycling facility watching automated systems process urban waste',
    'walking side-by-side through vertical gardens climbing exterior walls of towers',
    'standing side-by-side at cryptocurrency exchange terminal transferring digital currency funds',
    'sitting side-by-side in capsule hotel pod sharing compact living space',
    'standing side-by-side at genetic modification clinic reviewing enhancement procedure options',
    'walking side-by-side through pedestrian tubes connecting massive residential arcology blocks',
    'standing side-by-side at underground music venue watching cyberpunk band perform',
    'sitting side-by-side at automated restaurant being served by robotic waitstaff',
    'standing side-by-side at airship terminal waiting for transport to upper city',
    'walking side-by-side through industrial district observing massive manufacturing machinery operations',
    'standing side-by-side at information broker stall purchasing restricted corporate data',
    'sitting side-by-side on high-speed rail platform waiting for intercity transport',
    'standing side-by-side at body modification parlor selecting cosmetic cybernetic upgrades',
    'walking side-by-side through night market illuminated by pulsing neon signs',
    'standing side-by-side at energy weapon testing range holding plasma rifles',
    'sitting side-by-side at meditation center practicing consciousness uploading techniques together',
    'standing side-by-side at corporate espionage museum examining historical surveillance equipment',
    'walking side-by-side through sewage treatment facility observing advanced filtration technology',
    'standing side-by-side at identity falsification shop obtaining new documentation papers',
    'sitting side-by-side at zero gravity recreation center floating in weightless chamber',
    'standing side-by-side at demolition site watching controlled building implosion spectacle',
    'walking side-by-side through refugee camp outside city walls distributing supplies',
    'standing side-by-side at quantum computer facility observing massive processing arrays',
  ],
  'mars colony': [
    'standing side-by-side at the mars observation deck viewing earth through the dome',
    'walking side-by-side through the hydroponic food gardens between raised plant beds',
    'standing side-by-side at the airlock window watching a dust storm approach',
    'sitting side-by-side in the recreation pod playing holographic chess',
    'standing side-by-side at the mineral processing station examining red rock samples',
    'walking side-by-side down the main habitat corridor toward the central hub',
    'standing side-by-side at the communications array sending messages to earth',
    'sitting side-by-side in the gravity gym on exercise bikes facing forward',
    'standing side-by-side at the solar panel field checking maintenance tablets',
    'walking side-by-side across the landing pad toward an incoming shuttle',
    'standing side-by-side at the water reclamation plant monitoring filtration systems',
    'sitting side-by-side in the mess hall sharing packaged astronaut meals',
    'standing side-by-side at the geological survey station sorting martian soil samples',
    'walking side-by-side through the underground tunnels between habitat modules',
    'standing side-by-side at the weather monitoring station reading atmospheric data',
    'sitting side-by-side in the library pod accessing earth cultural archives',
    'standing side-by-side at the greenhouse dome harvesting fresh vegetables',
    'walking side-by-side on the elevated walkway between biodome sections',
    'standing side-by-side at the research lab examining microorganism cultures',
    'sitting side-by-side in the meditation chamber facing the transparent aluminum walls',
    'standing side-by-side at the metal fabrication shop operating 3d printers',
    'walking side-by-side through the market corridor trading supplies with colonists',
    'standing side-by-side at the oxygen generation facility monitoring gas levels',
    'sitting side-by-side in the recreation lounge watching earth documentaries',
    'standing side-by-side at the rover maintenance bay preparing for surface exploration',
    'walking side-by-side across the pressurized courtyard between residential blocks',
    'standing side-by-side at the planetary communication dish sending data transmissions',
    'sitting side-by-side in the medical bay getting routine health screenings',
    'standing side-by-side at the ice mining operation examining frozen water deposits',
    'walking side-by-side through the vertical farming towers checking crop growth',
    'standing side-by-side at the nuclear reactor control room monitoring power systems',
    'sitting side-by-side in the virtual reality pod experiencing simulated earth environments',
    'standing side-by-side at the atmospheric processor checking carbon dioxide scrubbers',
    'walking side-by-side on the habitat ring observing artificial gravity demonstrations',
    'standing side-by-side at the spacesuit maintenance station preparing protective gear',
    'sitting side-by-side in the cafeteria sharing locally grown martian potatoes',
    'standing side-by-side at the satellite uplink facility coordinating earth communications',
    'walking side-by-side through the laboratory corridor carrying scientific equipment',
    'standing side-by-side at the thermal regulation center monitoring habitat temperatures',
    'sitting side-by-side in the common room playing low gravity recreational games',
    'standing side-by-side at the emergency shelter inspecting backup life support',
    'walking side-by-side across the central plaza toward the administrative complex',
    'standing side-by-side at the terraforming station releasing atmospheric conditioning agents',
    'sitting side-by-side in the transportation hub waiting for inter-settlement transport',
    'standing side-by-side at the construction site assembling new habitat expansion modules',
    'walking side-by-side through the shopping district browsing locally manufactured goods',
    'standing side-by-side at the waste processing plant converting refuse into useful materials',
    'sitting side-by-side in the social center participating in colony governance meetings',
    'standing side-by-side at the astronomical observatory tracking nearby celestial bodies',
    'walking side-by-side on the perimeter walkway checking habitat structural integrity',
  ],
};

// Combined pool kept for back-compat — mirrors blended pick behavior.
export const SCENE_CLUSTERS: Record<string, string[]> = Object.fromEntries(
  Object.keys(SCENE_CLUSTERS_SPOTS).map((loc) => [
    loc,
    [...(SCENE_CLUSTERS_SPOTS[loc] ?? []), ...(SCENE_CLUSTERS_ACTIVITIES[loc] ?? [])],
  ])
);

export type ClusterKind = 'spot' | 'activity';

/**
 * Pick a scene cluster for the location.
 * @param locationName — case-insensitive location key
 * @param kind — optional force "spot" or "activity" (default: blended)
 */
export function pickSceneCluster(
  locationName: string | undefined,
  kind?: ClusterKind
): string | null {
  if (!locationName) return null;
  const key = locationName.toLowerCase();
  let pool: string[] = [];
  if (kind === 'spot') pool = SCENE_CLUSTERS_SPOTS[key] ?? [];
  else if (kind === 'activity') pool = SCENE_CLUSTERS_ACTIVITIES[key] ?? [];
  else pool = SCENE_CLUSTERS[key] ?? [];
  if (pool.length === 0) return null;
  return pool[Math.floor(Math.random() * pool.length)];
}
