/**
 * Scene cluster pool — specific sub-spots within each location.
 *
 * Keyed by location card name. Picked at runtime alongside the rolled
 * location to break the tendency to default to 5-10 generic imagery
 * patterns per location category.
 *
 * Each entry describes a SPECIFIC physical spot/vantage point — no
 * people, no time of day, no mood (those are other layers).
 */

export const SCENE_CLUSTERS: Record<string, string[]> = {
  'space station': [
    'the narrow maintenance crawlway between humming server racks and cooling pipes',
    "the curved observation bubble protruding from the station's outer hull",
    'the zero-gravity gymnasium with padded walls and floating exercise equipment',
    'the hydroponic garden chamber with vertical growing towers and irrigation lines',
    'the cramped airlock vestibule with emergency suits hanging on magnetic hooks',
    'the central communications array surrounded by blinking antenna control panels',
    "the rotating habitat ring's jogging track with artificial gravity underfoot",
    "the machine shop's workbench cluttered with metal shavings and precision tools",
    "the waste processing facility's control station overlooking recycling chambers",
    "the chapel's meditation alcove with a small porthole facing deep space",
    "the crew quarters' communal kitchen with magnetic meal containers",
    "the emergency shelter pod's reinforced interior with backup life support",
    "the cargo bay's loading platform beside massive shipping containers",
    "the research lab's specimen storage wall with hundreds of labeled samples",
    "the reactor room's elevated catwalk overlooking fusion containment units",
    "the docking bay's traffic control booth with approach vector displays",
    "the water reclamation plant's filtration chamber with transparent processing tubes",
    "the crew lounge's reading nook with built-in bookshelf and cushioned seating",
    "the navigation deck's star chart table with holographic projection capabilities",
    "the medical bay's surgical suite with retractable operating table",
    "the quarters' personal workspace with fold-down desk and storage compartments",
    "the greenhouse dome's central fountain surrounded by flowering plants",
    "the engine room's diagnostic station monitoring thrust vector systems",
    "the recreation room's gaming corner with wall-mounted entertainment screens",
    "the galley's food preparation area with magnetic cutting boards",
    "the sleeping pod's cramped bunk with personal storage nets",
    "the conference room's presentation wall displaying mission timeline charts",
    "the atmospheric processor's monitoring console tracking oxygen levels",
    "the workshop's 3d printer station with spools of construction filament",
    "the observation lounge's curved seating area facing the main viewport",
    "the laboratory's chemical analysis station with protective glass barriers",
    "the fitness center's resistance training harness mounted to ceiling tracks",
    "the storage compartment's inventory shelving system with labeled containers",
    "the communications room's radio operator desk with multiple frequency controls",
    "the quarters' hygiene station with water recycling shower compartment",
    "the research dome's telescope mount with precision tracking mechanisms",
    "the cafeteria's serving line with heated food distribution units",
    "the backup bridge's emergency command chair facing simplified control arrays",
    "the manufacturing bay's assembly line with robotic fabrication arms",
    "the crew recreation area's artificial window displaying earth imagery",
    "the maintenance shaft's tool storage alcove with organized equipment racks",
    'the medical isolation chamber with transparent quarantine barriers',
    "the library's digital archive terminal with floating holographic displays",
    "the laundry facility's cleaning unit dispensing sanitized clothing",
    "the crew meeting area's circular table with integrated data displays",
    'the solar panel maintenance platform overlooking massive energy collectors',
    "the sleeping quarters' privacy curtain surrounding personal sleeping space",
    "the geology lab's rock sample analysis station with microscopic equipment",
    "the mess hall's waste disposal unit with automated sorting mechanisms",
    "the command center's tactical display showing surrounding space debris",
    'the botanical research greenhouse with climate control monitoring stations',
    "the crew gymnasium's climbing wall with magnetic handholds",
    "the quarters' personal communication booth for private video calls",
    'the backup life support chamber with redundant oxygen generation systems',
    "the recreation deck's virtual reality pod with motion tracking sensors",
    "the medical bay's rehabilitation area with physical therapy equipment",
    "the storage bay's inventory robot charging station with docking ports",
    "the crew quarters' social area with modular furniture arrangements",
    "the laboratory's clean room entrance with decontamination spray nozzles",
    "the navigation room's course plotting table with interstellar maps",
    "the pressurized greenhouse's mushroom cultivation racks with humidity control nozzles",
    "the outer hull maintenance bay's robotic arm storage cradles",
    "the crew quarters' fold-out dining table with magnetic plate holders",
    "the atmospheric recycling plant's carbon dioxide scrubber chambers",
    "the observation deck's telescope housing with manual adjustment wheels",
    "the emergency pod's launch tube with countdown timer displays",
    "the solar array control room's panel alignment monitoring screens",
    "the crew lounge's holographic fireplace alcove with comfort seating",
    "the backup generator room's fuel cell stack with warning indicators",
    "the medical bay's centrifuge chamber for blood sample processing",
    "the quarters' murphy bed frame with integrated storage drawers",
    "the communications array's satellite dish maintenance platform",
    "the hydroponics lab's nutrient mixing station with chemical dispensers",
    "the cargo hold's magnetic crane operator booth overlooking shipping lanes",
    "the crew recreation center's ping pong table with tethered paddles",
    "the water treatment facility's membrane filter replacement chamber",
    "the workshop's metal fabrication forge with automated hammering arms",
    "the sleeping quarters' personal ventilation duct with adjustable airflow",
    "the bridge's backup navigation console with mechanical compass displays",
    "the botanical lab's pollination chamber with artificial bee drones",
    "the crew quarters' personal storage locker with biometric lock",
    "the reactor cooling system's heat exchanger monitoring station",
    "the mess hall's automated dishwashing unit with sanitization cycles",
    "the external repair bay's pressure suit testing chamber",
    "the crew fitness area's stationary bike with resistance magnetic wheels",
    "the laboratory's specimen freezer unit with temperature alarm systems",
    "the quarters' fold-down workspace with integrated computer terminal",
    "the docking bay's umbilical connection panel with fluid transfer gauges",
    "the atmospheric processor's humidity regulation chamber with mist nozzles",
    "the crew lounge's coffee brewing station with zero gravity dispensers",
    "the medical bay's x-ray imaging booth with lead-lined protective walls",
    "the storage area's automated retrieval system with conveyor belt mechanisms",
    "the observatory's spectrometer calibration bench with precision optical equipment",
    "the crew quarters' personal bathroom pod with vacuum waste systems",
    "the power distribution room's circuit breaker panels with status indicators",
    "the recreation area's chess board table with magnetized game pieces",
    "the laboratory's gas chromatography station with sample injection ports",
    "the crew dining area's food rehydration unit with steam vents",
    "the maintenance tunnel's pipe junction box with valve control wheels",
    "the medical facility's pharmacy storage cabinet with dose measurement scales",
    "the quarters' personal exercise corner with resistance band anchor points",
    "the communications room's message encryption terminal with security protocols",
    "the botanical section's seed germination chamber with growth monitoring sensors",
    "the crew workspace's document scanner with digital archive upload",
    "the atmospheric control room's pressure regulation valve assembly",
    "the recreation deck's musical instrument storage with acoustic dampening",
    "the laboratory's protein crystallization chamber with temperature gradient controls",
    "the crew quarters' personal reading lamp with adjustable beam focus",
    "the waste management facility's compactor chamber with hydraulic compression rams",
    "the external sensor array's calibration booth with signal amplification equipment",
  ],
};

export function pickSceneCluster(locationName: string | undefined): string | null {
  if (!locationName) return null;
  const pool = SCENE_CLUSTERS[locationName.toLowerCase()];
  if (!pool || pool.length === 0) return null;
  return pool[Math.floor(Math.random() * pool.length)];
}
