/**
 * Auto-generated by scripts/generate-scene-pools.js
 * 150 entries — do not edit manually, regenerate instead.
 */

type Entry = {
  text: string;
  weight: number;
  tags?: string[];
  rarity?: 'safe' | 'bold' | 'chaotic';
};

export const SETTINGS: Entry[] = [
  {
    text: 'Marble library floating among clouds with spiral staircases descending into endless sky',
    weight: 5,
    tags: ['sky', 'fantasy', 'surreal'],
  },
  {
    text: 'Crystalline ice cave illuminated by bioluminescent fungi growing through frozen waterfall walls',
    weight: 5,
    tags: ['underground', 'surreal', 'fantasy'],
  },
  {
    text: 'Crystalline cathedral carved entirely from translucent salt in a desert basin',
    weight: 5,
    tags: ['desert', 'fantasy', 'interior'],
  },
  {
    text: 'Venetian palazzo ballroom flooded waist-deep with still black water reflecting cracked frescoed ceiling',
    weight: 5,
    tags: ['interior', 'surreal', 'gothic'],
  },
  {
    text: 'Suspended glass bridges connecting crumbling skyscrapers above an endless cloud sea below',
    weight: 5,
    tags: ['urban', 'sky', 'surreal'],
  },
  {
    text: 'Terraced rice paddies carved into mountainside cascading toward misty valley below',
    weight: 5,
    tags: ['mountain', 'nature'],
  },
  {
    text: 'Gothic cathedral interior with fractured stained glass casting prismatic light on stone floors',
    weight: 5,
    tags: ['gothic', 'interior', 'surreal'],
  },
  {
    text: 'Bamboo scaffolding maze stretching across skyscraper rooftops beneath heavy fog',
    weight: 5,
    tags: ['urban'],
  },
  {
    text: 'Copper observatory dome cracked open revealing swirling nebula directly above',
    weight: 5,
    tags: ['space', 'surreal'],
  },
  {
    text: 'Abandoned greenhouse overgrown with wild vines piercing through shattered glass panels',
    weight: 5,
    tags: ['nature', 'interior', 'abandoned'],
  },
  {
    text: 'Submerged subway station with murky water and flickering fluorescent lights overhead',
    weight: 5,
    tags: ['underground', 'urban', 'surreal'],
  },
  {
    text: 'Marble quarry filled with turquoise water and carved white stone pillars',
    weight: 5,
    tags: ['underground', 'surreal', 'coastal'],
  },
  {
    text: 'Copper-domed bathhouse with steam rising through circular skylights and mosaic tile pools',
    weight: 5,
    tags: ['interior', 'cozy'],
  },
  {
    text: 'Suspension bridge made of rope and wooden planks crossing a foggy canyon',
    weight: 5,
    tags: ['mountain', 'fantasy', 'space'],
  },
  {
    text: 'Deteriorating space station interior with torn metal panels and exposed wiring drifting weightless',
    weight: 5,
    tags: ['interior', 'space', 'epic'],
  },
  {
    text: 'Venetian canal district submerged deeper with gondolas floating between second-story marble balconies',
    weight: 5,
    tags: ['urban', 'fantasy', 'surreal'],
  },
  {
    text: 'Lighthouse perched on jagged sea cliffs during a storm with crashing waves',
    weight: 5,
    tags: ['coastal', 'epic', 'rain'],
  },
  {
    text: 'Wheat field stretching endlessly beneath massive rotating storm clouds at golden hour',
    weight: 5,
    tags: ['nature', 'epic', 'surreal'],
  },
  {
    text: 'Sandstone monastery carved into red canyon walls with rope bridges connecting chambers',
    weight: 5,
    tags: ['desert', 'epic', 'interior'],
  },
  {
    text: 'Abandoned subway station overgrown with vines cascading through broken tile ceiling',
    weight: 5,
    tags: ['underground', 'nature', 'urban'],
  },
  {
    text: 'Sequoia forest floor carpeted in ferns with shafts of golden sunlight',
    weight: 5,
    tags: ['forest', 'nature'],
  },
  {
    text: 'Massive geode cavern with amethyst walls and a glowing mineral spring',
    weight: 5,
    tags: ['underground', 'fantasy', 'surreal'],
  },
  {
    text: 'Blackened redwood grove with ember-glowing trees after a contained forest fire',
    weight: 5,
    tags: ['forest', 'fire', 'nature'],
  },
  {
    text: 'Abandoned cinema with velvet seats and projector light cutting through dust',
    weight: 5,
    tags: ['interior', 'urban', 'cozy'],
  },
  {
    text: 'Tidal flats of black sand with skeletal driftwood and distant lighthouse beam',
    weight: 5,
    tags: ['coastal', 'surreal'],
  },
  {
    text: 'Abandoned shopping mall with shattered skylights and moonlight illuminating overgrown vegetation',
    weight: 5,
    tags: ['interior', 'urban', 'nature'],
  },
  {
    text: 'Lighthouse perched on black volcanic rock surrounded by churning white foam',
    weight: 5,
    tags: ['coastal', 'epic'],
  },
  {
    text: 'Lantern-lit rice paddies cascading down terraced hillsides at dusk',
    weight: 5,
    tags: ['nature', 'cozy'],
  },
  {
    text: 'Submerged cathedral with crumbling stone pillars and swimming jellyfish illuminated by shafts',
    weight: 5,
    tags: ['underwater', 'gothic', 'surreal'],
  },
  {
    text: 'Moonlit salt flats stretching endlessly with crystallized hexagonal patterns and distant mountains',
    weight: 5,
    tags: ['desert', 'mountain', 'surreal'],
  },
  {
    text: 'Decaying opera house with velvet curtains and ornate gilded balconies crumbling inward',
    weight: 5,
    tags: ['interior', 'gothic', 'cozy'],
  },
  {
    text: 'Submarine hangar carved into granite cliffs with rusted metal doors hanging open',
    weight: 5,
    tags: ['underground', 'coastal', 'interior'],
  },
  {
    text: 'Gravity-deficient junkyard with rusted satellites orbiting through debris clouds and broken machinery',
    weight: 5,
    tags: ['space', 'surreal', 'epic'],
  },
  {
    text: 'Suspension bridge swaying over a gorge filled with dense white fog below',
    weight: 5,
    tags: ['mountain', 'nature', 'surreal'],
  },
  {
    text: 'Sandstone labyrinth carved into cliffs with narrow sunlit passageways overhead',
    weight: 5,
    tags: ['desert', 'underground', 'epic'],
  },
  {
    text: 'Snow-buried train station with icicles hanging from iron girders and frosted platforms',
    weight: 5,
    tags: ['snow', 'urban', 'cozy'],
  },
  {
    text: 'Suspended glass greenhouse gardens built between skyscraper peaks with waterfalls spilling downward',
    weight: 5,
    tags: ['urban', 'nature', 'surreal'],
  },
  {
    text: 'Abandoned subway tunnel lined with ceramic tiles and flooded ankle-deep with water',
    weight: 5,
    tags: ['underground', 'urban', 'interior'],
  },
  {
    text: 'Lighthouse perched on jagged black rocks amid churning phosphorescent tide pools',
    weight: 5,
    tags: ['coastal', 'surreal'],
  },
  {
    text: 'Abandoned lunar colony with domed craters and Earth rising beyond dusty horizon',
    weight: 5,
    tags: ['space', 'underground', 'epic'],
  },
  {
    text: 'Abandoned dam interior with concrete spillways and shafts of dusty sunlight',
    weight: 5,
    tags: ['interior', 'underground', 'urban'],
  },
  {
    text: 'Petrified forest with towering stone tree trunks beneath purple twilight sky',
    weight: 5,
    tags: ['forest', 'fantasy', 'surreal'],
  },
  {
    text: 'Abandoned silk factory with torn fabric draping from rusted machinery and dusty sunbeams',
    weight: 5,
    tags: ['interior', 'urban', 'cozy'],
  },
  {
    text: 'Bamboo tea house on stilts above mist-covered rice paddies at dawn',
    weight: 5,
    tags: ['nature', 'cozy', 'mountain'],
  },
  {
    text: 'Abandoned grain silo interior with shafts of golden dust-filled sunlight streaming down',
    weight: 5,
    tags: ['interior', 'urban', 'cozy'],
  },
  {
    text: 'Mangrove swamp with twisted roots and fireflies drifting through humid darkness',
    weight: 5,
    tags: ['nature', 'tropical', 'swamp'],
  },
  {
    text: 'Abandoned paper mill with towering machinery draped in cobwebs and peeling paint',
    weight: 5,
    tags: ['interior', 'urban', 'gothic'],
  },
  {
    text: 'Abandoned train depot with graffitied locomotives and pigeons circling through broken skylights',
    weight: 5,
    tags: ['urban', 'interior'],
  },
  {
    text: 'Suspension bridge spanning fog-filled chasm between two snowy mountain peaks with fraying cables',
    weight: 5,
    tags: ['mountain', 'snow', 'epic'],
  },
  {
    text: 'Tilted skyscraper interior with furniture sliding toward shattered floor-to-ceiling windows',
    weight: 5,
    tags: ['interior', 'urban', 'surreal'],
  },
  {
    text: 'Glacier crevasse with cobalt ice walls and suspended frozen waterfall droplets',
    weight: 5,
    tags: ['snow', 'mountain', 'nature'],
  },
  {
    text: 'Abandoned conservatory with cracked Victorian ironwork and overgrown vines choking glass panels',
    weight: 5,
    tags: ['interior', 'nature', 'gothic'],
  },
  {
    text: 'Sunken subway tunnel with bioluminescent algae coating the ceramic walls and flooded tracks',
    weight: 5,
    tags: ['underground', 'urban', 'surreal'],
  },
  {
    text: 'Sandstone slot canyon with carved spiral patterns and crimson layered walls',
    weight: 5,
    tags: ['desert', 'nature', 'underground'],
  },
  {
    text: 'Bamboo forest with golden lanterns suspended between jade-green stalks at twilight',
    weight: 5,
    tags: ['forest', 'nature', 'cozy'],
  },
  {
    text: 'Suspension bridge swaying over misty gorge with sheer moss-covered limestone walls',
    weight: 5,
    tags: ['nature', 'mountain', 'forest'],
  },
  {
    text: 'Decrepit carnival pier extending over black ocean water with flickering bulbs',
    weight: 5,
    tags: ['gothic', 'coastal', 'surreal'],
  },
  {
    text: 'Abandoned grain silo interior with shafts of wheat dust suspended in light beams',
    weight: 5,
    tags: ['interior', 'urban'],
  },
  {
    text: 'Limestone cavern with waterfalls plunging through holes in the vaulted ceiling',
    weight: 5,
    tags: ['underground', 'nature', 'water'],
  },
  {
    text: 'Decrepit lighthouse perched on black rocks with crashing storm surf below',
    weight: 5,
    tags: ['coastal', 'gothic', 'epic'],
  },
  {
    text: 'Abandoned hotel swimming pool with cracked art deco tiles and moonlight streaming through skylights',
    weight: 5,
    tags: ['interior', 'underwater', 'cozy'],
  },
  {
    text: 'Abandoned sanatorium hallway with peeling wallpaper and tilted wheelchairs in moonlight',
    weight: 5,
    tags: ['interior', 'gothic'],
  },
  {
    text: 'Suspended glass greenhouse above a foggy alpine valley at dawn',
    weight: 5,
    tags: ['mountain', 'nature', 'surreal'],
  },
  {
    text: 'Salt mine cathedral carved entirely from pink himalayan rock walls',
    weight: 5,
    tags: ['underground', 'interior', 'epic'],
  },
  {
    text: 'Sandstone monastery carved into desert cliffs with wind-carved archways and shadows',
    weight: 5,
    tags: ['desert', 'gothic', 'epic'],
  },
  {
    text: 'Limestone karst peaks rising from emerald rice paddies shrouded in morning fog',
    weight: 5,
    tags: ['nature', 'mountain', 'tropical'],
  },
  {
    text: 'Sakura grove with fallen petals floating on still black water pools',
    weight: 5,
    tags: ['nature', 'surreal'],
  },
  {
    text: 'Suspension bridge spanning a chasm with fraying rope and missing wooden planks below',
    weight: 5,
    tags: ['epic', 'surreal', 'mountain'],
  },
  {
    text: 'Abandoned power plant with rusting turbines and rain pouring through collapsed roof',
    weight: 5,
    tags: ['urban', 'rain', 'interior'],
  },
  {
    text: 'Abandoned aquarium with cracked tanks leaking and skeletal whale bones suspended overhead',
    weight: 5,
    tags: ['underwater', 'interior', 'gothic'],
  },
  {
    text: 'Tidal palace half-submerged in black sand with waves crashing through arches',
    weight: 5,
    tags: ['underwater', 'gothic', 'coastal'],
  },
  {
    text: 'Abandoned soap factory with rusted cauldrons and shafts of amber light',
    weight: 5,
    tags: ['interior', 'urban', 'cozy'],
  },
  {
    text: 'Glacial crevasse with ice walls carved into spiraling chambers and cobalt shadows',
    weight: 5,
    tags: ['snow', 'underground', 'surreal'],
  },
  {
    text: 'Crumbling dam with reservoir draining through massive fractures at golden hour',
    weight: 5,
    tags: ['epic', 'water', 'surreal'],
  },
  {
    text: 'Sandstone amphitheater carved into canyon walls with natural arch opening overhead',
    weight: 5,
    tags: ['desert', 'epic'],
  },
  {
    text: 'Abandoned grain silo interior with spiraling metal catwalks and dust motes swirling',
    weight: 5,
    tags: ['interior', 'underground', 'abandoned'],
  },
  {
    text: 'Subway train graveyard with tracks disappearing into overgrown tunnels and rusted carriages',
    weight: 5,
    tags: ['underground', 'urban', 'nature'],
  },
  {
    text: 'Marble quarry with sapphire pools reflecting sheer alabaster walls and fallen columns',
    weight: 5,
    tags: ['underground', 'surreal', 'cozy'],
  },
  {
    text: 'Kelp forest with sunlight filtering through towering bronze-colored fronds above sandy floor',
    weight: 5,
    tags: ['underwater', 'nature', 'forest'],
  },
  {
    text: 'Abandoned train tunnel overgrown with hanging wisteria and scattered wildflowers throughout',
    weight: 5,
    tags: ['underground', 'nature', 'cozy'],
  },
  {
    text: 'Blackened iron drawbridge suspended over a molten lava river with ember sparks rising',
    weight: 5,
    tags: ['fire', 'epic', 'underground'],
  },
  {
    text: 'Sandstone monastery carved into cliffsides with wooden prayer wheels spinning in wind',
    weight: 5,
    tags: ['mountain', 'desert', 'cozy'],
  },
  {
    text: 'Abandoned subway car suspended vertically in a sinkhole with cascading roots',
    weight: 5,
    tags: ['underground', 'urban', 'surreal'],
  },
  {
    text: 'Abandoned grain silo interior with spiraling wooden chutes and golden dust motes',
    weight: 5,
    tags: ['interior', 'underground', 'cozy'],
  },
  {
    text: 'Abandoned conservatory with shattered dome revealing stars and frost-covered exotic plants below',
    weight: 5,
    tags: ['gothic', 'nature', 'interior'],
  },
  {
    text: "Abandoned lighthouse keeper's quarters with peeling wallpaper and fog pressing against cracked windows",
    weight: 5,
    tags: ['interior', 'coastal', 'gothic'],
  },
  {
    text: 'Abandoned train terminal with pigeons roosting on iron beams and dusty light.',
    weight: 5,
    tags: ['urban', 'interior'],
  },
  {
    text: 'Glacial palace carved from blue ice with crystalline columns and frozen chandeliers',
    weight: 5,
    tags: ['snow', 'fantasy', 'interior'],
  },
  {
    text: 'Suspension bridge spanning chasm between crimson sandstone towers in morning fog',
    weight: 5,
    tags: ['desert', 'mountain', 'surreal'],
  },
  {
    text: 'Tidal cave entrance with barnacle-encrusted walls and retreating seawater revealing tide pools',
    weight: 5,
    tags: ['coastal', 'underground', 'nature'],
  },
  {
    text: 'Suspension bridge spanning a ravine with frayed cables and missing wooden planks',
    weight: 5,
    tags: ['urban', 'epic', 'surreal'],
  },
  {
    text: 'Abandoned power plant with turbines choked by flowering vines and broken skylights',
    weight: 5,
    tags: ['interior', 'nature', 'urban'],
  },
  {
    text: 'Abandoned power plant cooling towers overgrown with flowering vines and pooling rainwater',
    weight: 5,
    tags: ['nature', 'rain', 'urban'],
  },
  {
    text: 'Abandoned subway platform submerged in clear water with bioluminescent jellyfish drifting through cars',
    weight: 5,
    tags: ['underground', 'underwater', 'surreal'],
  },
  {
    text: 'Abandoned train cemetery with rusted locomotives buried in deep snowdrifts',
    weight: 5,
    tags: ['snow', 'urban', 'surreal'],
  },
  {
    text: 'Abandoned power plant cooling towers with hanging gardens and cascading ivy walls',
    weight: 5,
    tags: ['urban', 'nature', 'interior'],
  },
  {
    text: 'Sawmill interior with massive rusted circular blades and fractured timber beams',
    weight: 5,
    tags: ['interior', 'underground', 'gothic'],
  },
  {
    text: 'Skeletal radio telescope array abandoned in red dust desert landscape',
    weight: 5,
    tags: ['desert', 'surreal'],
  },
  {
    text: 'Marble quarry lake with submerged columns and abandoned drilling equipment rusting underwater',
    weight: 5,
    tags: ['underwater', 'surreal', 'abandoned'],
  },
  {
    text: 'Treehouse village connected by suspension bridges across a misty rainforest canopy at dawn',
    weight: 5,
    tags: ['jungle', 'nature', 'cozy'],
  },
  {
    text: 'Subway platform abandoned mid-construction with exposed rebar and pooling rainwater reflections',
    weight: 5,
    tags: ['urban', 'underground', 'rain'],
  },
  {
    text: 'Abandoned paper factory with massive rusted printing presses and torn newsprint drifts',
    weight: 5,
    tags: ['interior', 'urban', 'cozy'],
  },
  {
    text: 'Sandstone monastery carved into canyon walls with prayer flags fluttering wildly',
    weight: 5,
    tags: ['desert', 'epic', 'mountain'],
  },
  {
    text: 'Glacial plateau with ice spires reflecting purple twilight and distant mountains',
    weight: 5,
    tags: ['snow', 'mountain', 'epic'],
  },
  {
    text: 'Sunken cathedral with stained glass casting colored light through deep water',
    weight: 5,
    tags: ['underwater', 'gothic', 'fantasy'],
  },
  {
    text: 'Abandoned pharmaceutical factory with pill capsules scattered across flooded white tile floors',
    weight: 5,
    tags: ['interior', 'urban', 'surreal'],
  },
  {
    text: 'Abandoned planetarium dome with constellations painted on crumbling plaster and exposed steel framework',
    weight: 5,
    tags: ['interior', 'urban', 'surreal'],
  },
  {
    text: 'Petrified lighthouse perched on volcanic rock columns jutting from churning sea',
    weight: 5,
    tags: ['coastal', 'epic', 'surreal'],
  },
  {
    text: 'Submerged temple complex with jade pillars and swirling koi fish overhead',
    weight: 5,
    tags: ['underwater', 'fantasy', 'surreal'],
  },
  {
    text: 'Abandoned power plant cooling towers with circling starlings and golden sunset light',
    weight: 5,
    tags: ['urban', 'nature', 'epic'],
  },
  {
    text: 'Abandoned sanatorium corridor with peeling mint-green paint and wheeled gurneys',
    weight: 5,
    tags: ['interior', 'gothic', 'urban'],
  },
  {
    text: 'Abandoned power plant cooling towers overgrown with cascading wisteria and ivy',
    weight: 5,
    tags: ['underground', 'nature', 'urban'],
  },
  {
    text: 'Abandoned train tunnel with chandeliers hanging from arched brick ceiling dripping water',
    weight: 5,
    tags: ['underground', 'interior', 'cozy'],
  },
  {
    text: 'Sandstone palace half-buried in windswept dunes under crimson sunset sky',
    weight: 5,
    tags: ['desert', 'epic', 'fantasy'],
  },
  {
    text: 'Abandoned tannery with leather scraps hanging from chains above copper vats',
    weight: 5,
    tags: ['underground', 'interior', 'gothic'],
  },
  {
    text: 'Abandoned suspension bridge spanning a misty gorge with snapped steel cables dangling',
    weight: 5,
    tags: ['mountain', 'surreal', 'fog'],
  },
  {
    text: 'Abandoned oil rig platform rising from fog-shrouded ocean with rusted derricks',
    weight: 5,
    tags: ['coastal', 'surreal', 'gothic'],
  },
  {
    text: 'Sanatorium balcony overlooking pine forest with rusted iron railings and peeling mint paint',
    weight: 5,
    tags: ['interior', 'forest', 'nature'],
  },
  {
    text: 'Tidal power station half-submerged with turbines churning through emerald seawater',
    weight: 5,
    tags: ['underwater', 'coastal'],
  },
  {
    text: 'Abandoned windmill interior with wooden gears and wheat dust suspended in sunlight beams',
    weight: 5,
    tags: ['interior', 'cozy'],
  },
  {
    text: 'Suspension bridge spanning a misty gorge with fraying steel cables overhead',
    weight: 5,
    tags: ['mountain', 'nature', 'surreal'],
  },
  {
    text: 'Abandoned paper factory interior with massive rolling drums and torn ribbons floating midair.',
    weight: 5,
    tags: ['interior', 'urban', 'surreal'],
  },
  {
    text: 'Abandoned terrarium dome with cracked glass panels and overgrown tropical vines cascading inward',
    weight: 5,
    tags: ['interior', 'tropical', 'nature'],
  },
  {
    text: 'Sakura grove with pink petals carpeting a mirror-still lake surface',
    weight: 5,
    tags: ['nature', 'fantasy', 'surreal'],
  },
  {
    text: 'Abandoned paper lantern factory with torn silk glowing in moonlight shafts',
    weight: 5,
    tags: ['interior', 'urban', 'cozy'],
  },
  {
    text: 'Abandoned ski lodge with snow-drifted furniture and cracked panoramic windows overlooking frozen peaks.',
    weight: 5,
    tags: ['snow', 'mountain', 'interior'],
  },
  {
    text: 'Sunken cathedral with baroque organ pipes wrapped in kelp and anemones',
    weight: 5,
    tags: ['underwater', 'gothic', 'fantasy'],
  },
  {
    text: 'Suspension bridge swaying over a misty jungle ravine with tangled rope railings',
    weight: 5,
    tags: ['jungle', 'nature'],
  },
  {
    text: 'Grain elevator interior with wooden chutes and golden wheat dust floating',
    weight: 5,
    tags: ['interior', 'cozy'],
  },
  {
    text: 'Sandstone amphitheater carved into cliffsides with swallow nests dotting the walls',
    weight: 5,
    tags: ['desert', 'epic'],
  },
  {
    text: 'Abandoned power plant cooling tower interior with spiraling rust stains and puddles',
    weight: 5,
    tags: ['interior', 'urban', 'cozy'],
  },
  {
    text: 'Sandstone monastery carved into canyon walls with wooden prayer balconies suspended overhead',
    weight: 5,
    tags: ['desert', 'epic', 'interior'],
  },
  {
    text: 'Abandoned metro platform with Byzantine mosaics and cascading tree roots breaking through arches',
    weight: 5,
    tags: ['underground', 'nature', 'interior'],
  },
  {
    text: 'Abandoned art museum with skylight pouring rain onto oil paintings below',
    weight: 5,
    tags: ['interior', 'rain', 'urban'],
  },
  {
    text: 'Tidal pool basin with mirror-black water reflecting chalk-white coastal cliffs above',
    weight: 5,
    tags: ['coastal', 'nature'],
  },
  {
    text: 'Sakura grove with moss-covered stone lanterns and koi pond reflections beneath pink canopy',
    weight: 5,
    tags: ['nature', 'fantasy', 'cozy'],
  },
  {
    text: 'Abandoned power plant cooling tower interior with spiral staircase and sky opening above.',
    weight: 5,
    tags: ['interior', 'urban', 'sky'],
  },
  {
    text: 'Submerged subway car overgrown with red coral and circling barracuda schools',
    weight: 5,
    tags: ['underwater', 'urban', 'surreal'],
  },
  {
    text: 'Abandoned terrarium greenhouse with cracked geodesic dome and fog rolling through shattered panes.',
    weight: 5,
    tags: ['interior', 'nature', 'cozy'],
  },
  {
    text: 'Abandoned power plant cooling towers with spiral staircases and rust-streaked concrete walls',
    weight: 5,
    tags: ['urban', 'interior', 'underground'],
  },
  {
    text: 'Limestone quarry filled with terraced pools of milky turquoise water at dusk',
    weight: 5,
    tags: ['underground', 'surreal', 'coastal'],
  },
  {
    text: 'Abandoned grain silo interior with wheat dust suspended in golden light shafts',
    weight: 5,
    tags: ['interior', 'cozy'],
  },
  {
    text: 'Windswept plateau covered in thousands of fluttering crimson prayer flags under twilight sky',
    weight: 5,
    tags: ['mountain', 'sky', 'epic'],
  },
  {
    text: 'Petrified whale skeleton half-buried in black volcanic sand dunes at twilight',
    weight: 5,
    tags: ['desert', 'surreal', 'coastal'],
  },
  {
    text: 'Domed train station with cracked skylights casting fractured sunlight across marble floors',
    weight: 5,
    tags: ['interior', 'urban'],
  },
  {
    text: 'Tannery ruins with leather strips hanging from rusted hooks and stone vats',
    weight: 5,
    tags: ['urban', 'gothic', 'interior'],
  },
];
