/**
 * Single character action pool — typed.
 *
 * Two pools picked 50/50 at random:
 *   1. CANDID — real moments captured (climbing, leaning, mid-laugh, mid-bite)
 *   2. PORTRAIT — posed for camera. Mix of stand-and-pose (hands in pockets,
 *      peace sign, shaka) and scene-interactive (sitting on rock, perched in tree,
 *      halfway up ladder). When picked, `needsEpicBackdrop` flags the brief to
 *      push for striking scenery — the background is the reason for the photo.
 */

export interface SingleAction {
  pose: string;
  needsEpicBackdrop: boolean;
}

export const CANDID_ACTIONS: string[] = [
  'stretching arms wide in the morning sun with head tilted back, expression peaceful',
  "crouched examining something tiny with magnifying glass held out at arm's length",
  'holding an oversized sandwich down at chest level with both hands gripping it tightly',
  'sitting on stone steps with one foot propped up, forearm draped over the raised knee',
  'brushing fingertips along a textured wall while walking slowly past it',
  'perched on a boulder with legs crossed, hands clasped around one ankle',
  'kneeling to pet an unseen animal with gentle outstretched hand, smiling softly',
  'wading through tall grass with both hands trailing through the stalks',
  'sitting cross-legged on the ground, leaning forward with forearms resting on the knees',
  'mid-step climbing wooden stairs with hand sliding along the rail',
  'standing in doorway with one hand on the frame, body leaning inward',
  'walking backward down a path with arms out for balance, grinning widely',
  'sitting on a swing with feet barely touching ground, hands gripping chains',
  'mid-reach toward a high shelf with other hand braced against wall',
  'kneeling on one knee tying a shoelace with focused concentration',
  'standing ankle-deep in sand with toes buried, hands brushing off palms',
  'pretending to conduct an orchestra with dramatic arm movements and serious expression',
  'balancing a book on head while walking with exaggerated careful steps',
  'fake-wrestling with an enormous teddy bear, arms wrapped around its middle',
  'wearing mismatched socks as mittens while pretending to box invisible opponent',
  'wearing a cape made from towel while striking superhero landing pose',
  'balancing on one foot while juggling three oranges with intense concentration',
  'pretending to be blown away by fan, leaning back with hair flying',
  'holding giant lollipop out like a microphone at chest level while belting a song',
  'pretending to be trapped with palms flat against air, pressing and sliding hands as if miming a wall',
  'wearing pot as helmet while saluting with wooden spoon like sword',
  'fake-surfing on ironing board with arms out catching imaginary waves',
  'hopping from foot to foot on hot pavement with pained expression',
  'scrambling up steep rocky incline with both hands finding holds above',
  'mid-vault over low fence with hands planted and legs swinging over',
  'rappelling down cliff face with rope in hands and focused expression',
  'scaling ladder rungs with alternating hand-over-hand climbing motion',
  'army-crawling under fallen log with elbows pulling body forward',
  'tiptoeing across narrow beam with arms spread for careful balance',
  'leaping between rooftops with arms windmilling and legs stretched wide',
  'somersaulting down grassy hill with body tucked and rolling freely',
  'bounding up sand dune with high knee steps and pumping arms',
  'side-stepping down steep slope with hands out for balance control',
  'cartwheeling across open field with legs and arms making perfect wheel',
  'pirouetting with arms gracefully curved and one leg extended behind',
  'crouching behind large mushroom with one hand braced on the cap, conspiratorial grin',
  'perched on picnic table with feet on bench and sandwich halfway eaten',
  'sitting backwards on chair with arms folded over backrest casually',
  'standing with one hand on hip peering into bright distance curiously',
  'crouched collecting shells in cupped palms along sandy shoreline',
  'sitting on dock with legs swinging over water and fishing line cast',
  'leaning over bridge railing dropping leaves into current below playfully',
  'standing with arms akimbo surveying garden beds with satisfied expression',
  'sitting cross-legged sorting through collection of interesting rocks and minerals',
  'standing on ladder picking apples with basket hooked over one arm',
  'crouched building small cairn of balanced stones with patient precision',
  'sitting on blanket unpacking picnic basket with items spread around',
  'standing in wheat field with hands running through grain stalks thoughtfully',
  'crouched photographing butterfly with camera held steady and body perfectly still',
  'standing at easel with palette in one hand and brush poised',
  'standing with arms full of firewood walking toward cabin with steady pace',
  'sitting on rock sorting through backpack contents spread on ground systematically',
  'standing at cliff edge with journal open writing with wind ruffling pages',
  'sitting in hammock with drink in hand and book balanced on stomach',
  'sitting on porch swing with feet tucked up and mug steaming',
  'standing with arms spread feeling ocean breeze with peaceful expression',
  'sitting on tailgate with guitar across lap and fingers finding chords',
  'sitting on museum steps with guidebook open and finger tracing map',
  'standing at overlook with camera raised capturing panoramic mountain view',
  'kneeling beside tide examining seaweed specimens with scientific curiosity',
  'sitting in café chair with pastry held on a plate in the lap and surprised delight',
  'standing at fruit stand selecting perfect peaches with gentle testing squeezes',
  'crouched beside fountain tossing coin with eyes closed making silent wish',
  'standing with easel outdoors painting landscape with brush loaded with color',
  'sitting on bleachers with scorecard and pencil tracking game progress',
  'sitting on library steps with stack of books and reading one intently',
  'standing at street cart ordering food with animated hand gestures',
  'sitting on deck chair with feet propped up and drink sweating condensation',
  'standing at telescope adjusting focus knobs to see distant celestial objects',
  'crouched beside herb garden pinching basil leaves and inhaling fresh scent',
  'sitting on a stump with a harmonica resting in one hand, relaxed and content',
  'kneeling beside flower pressing petals into book with careful gentle pressure',
  'sitting on diving board with legs swinging over pool water below',
  'sitting on porch rocker with cat purring in lap and hand stroking',
  'standing at grape arbor reaching up to test ripeness of hanging clusters',
  'sitting on tree swing with rope wound around wrist and feet barely touching',
  'sitting on tractor seat with hands on steering wheel surveying planted fields',
  'sitting on front porch with wool in lap spinning fiber into yarn',
  'sitting on chopping block with axe across knees taking break from splitting',
  'standing at outdoor oven with long paddle retrieving fresh baked bread loaves',
  'standing at fence line with wire stretchers repairing winter damage efficiently',
  'sitting on wagon tongue with harness in hands preparing horses for field',
  'standing at weather station checking instruments and recording daily atmospheric conditions',
  'standing at outdoor market with scales weighing produce for customer purchase transactions',
  'sitting on wagon bench with market goods loaded for weekly town selling',
  'standing with hands tucked in pockets, weight on one hip, easy smile toward the camera',
  'leaning back against a wall, arms loosely crossed, chin slightly lifted with a relaxed gaze',
  'walking toward the camera with hands in pockets, casual smile and confident stride',
  'sitting on a ledge with one knee up, arms resting casually, looking directly ahead',
  'standing with one hand running through hair, the other at their side, warm expression',
  'leaning sideways against a post, one ankle crossed over the other, soft smile',
  'turning to glance back over their shoulder, hand lightly touching their collar, gentle smile',
  'standing with thumbs hooked in belt loops, shoulders relaxed, easy laugh toward the camera',
  'sitting on steps with arms draped over knees, leaning forward slightly, engaged expression',
  'walking away then looking back mid-step, one hand in pocket, inviting smile',
  'standing with arms at sides, head tilted slightly, genuine smile and open posture',
  'leaning forward with forearms resting on a railing, relaxed shoulders, calm expression',
  'standing with one hand adjusting their cuff, the other relaxed, confident demeanor',
  'sitting with legs crossed, hands resting in lap, turned slightly toward the camera smiling',
  'standing in mid-stride, arms swinging naturally, candid laugh captured while moving forward',
  'leaning one shoulder against a surface, hands in pockets, thoughtful gaze toward the camera',
  'standing with weight shifted to one leg, hand resting on hip, playful smile',
  'turning at the waist to face the camera, one arm hanging loose, warm inviting expression',
  'sitting on a low wall with hands beside hips, leaning back slightly, relaxed smile',
  'standing with one hand in pocket, the other loosely gesturing, mid-conversation energy',
  'walking with arms loose at sides, captured mid-step with a natural easy smile',
  'leaning back on hands while sitting, legs extended, face tilted up with bright expression',
  'standing with jacket collar being adjusted with one hand, casual confident look',
  'sitting sideways with one arm draped over a backrest, looking over shoulder toward camera',
  'standing with hands clasped loosely in front, shoulders back, serene smile',
  'leaning against a railing with arms spread wide, gripping the edge, genuine laugh',
  'standing with one hand touching their neck, the other at their side, soft smile',
  'walking slowly with hands clasped behind back, peaceful expression facing the camera',
  'sitting with one leg folded over the other, hand resting on ankle, relaxed demeanor',
  'standing with both hands running through hair, elbows out, carefree joyful expression',
  'turning while standing with arms beginning to cross, caught mid-motion with a smile',
  'leaning to one side with hand resting on a surface, other arm hanging free, easy grin',
  'standing with one hand in pocket, other adjusting sleeve, looking slightly off-camera smiling',
  'sitting on edge of a surface with both feet on ground, hands on knees, forward lean',
  'standing with arms hanging naturally, mid-laugh with head tilted back slightly',
  'walking toward camera with one hand brushing hair back, confident stride and smile',
  'leaning forward on a ledge with weight on forearms, chin up, direct warm gaze',
  'standing with hands loosely in back pockets, chest open, relaxed genuine smile',
  'sitting casually with one arm extended along a surface, body angled toward the camera',
  'standing mid-turn with one hand reaching across to opposite shoulder, easy expression',
  'walking with thumbs in pockets, shoulders loose, captured looking toward the camera smiling',
  'standing with one foot resting on a low surface, arms crossed gently, calm look',
  'sitting upright with hands resting on either side, face turned three-quarters with a smile',
  'standing with one hand adjusting collar, other resting at waist, confident relaxed energy',
  'leaning casually with one elbow propped on a surface, other hand in pocket, genuine smile',
  'Standing with weight on one hip, hand resting in pocket, slight smile',
  'Walking slowly forward with both hands tucked into pockets, relaxed shoulders',
  'Leaning against a surface with arms loosely crossed, looking off to the side',
  'Mid-laugh with one hand brushing hair back, head tilted slightly',
  'Turning to glance back over shoulder, one hand at side, gentle expression',
  'Standing with thumbs hooked in pockets, chin slightly down, easy smile',
  'Adjusting sleeve with one hand while standing casually, weight shifted',
  'Sitting with one ankle crossed over knee, arm draped along surface edge',
  'Walking with hand running through hair, other arm swinging naturally at side',
  'Leaning sideways against surface, one hand in pocket, looking toward camera',
  'Standing with arms crossed loosely at waist, head turned in candid moment',
  'Mid-turn with hand sliding into pocket, relaxed shoulders, natural movement',
  'Sitting forward with elbows on knees, hands loosely clasped, attentive expression',
  'Standing with one hand adjusting collar, other hand resting at side casually',
  'Walking toward camera with slight smile, hands both in pockets, confident stride',
  'Leaning with shoulder against surface, one hand through hair, looking away',
  'Standing with hand resting on hip, other arm relaxed, weight on one leg',
  'Turning mid-step with hand leaving pocket, caught in natural motion, smiling',
  'Sitting back with one arm stretched along surface, relaxed posture, easy expression',
  'Standing with one hand touching neck briefly, other in pocket, thoughtful look',
  'Walking at angle with hands in pockets, head turned slightly, candid moment',
  'Leaning forward slightly while sitting, forearms resting on knees, engaged expression',
  'Standing with fingers hooked in belt loops, shoulders relaxed, subtle smile',
  'Mid-stride turning back with hand lifting toward hair, natural caught moment',
  'Sitting sideways with one arm along surface back, looking over shoulder casually',
  'Standing with one hand adjusting watch, other at side, moment of distraction',
  'Walking forward laughing with one hand coming out of pocket, genuine joy',
  'Leaning with back against surface, ankles crossed, both hands in pockets',
  'Standing in three-quarter turn, hand brushing through hair, relaxed authentic moment',
  'Sitting with legs stretched out, one hand on thigh, easy comfortable posture',
];

export const PORTRAIT_ACTIONS: string[] = [
  'standing with arms crossed loosely, head tilted slightly, warm smile toward camera',
  'sitting on steps leaning back on hands, legs stretched out, relaxed smile',
  'sitting cross-legged with hands resting on knees, gentle smile toward camera',
  'hands clasped in front, weight shifted to one leg, easy smile',
  'leaning against wall with shoulder, arms folded, slight smirk toward camera',
  'holding coffee cup up in cheers gesture, other hand on hip, warm smile',
  'sitting on bench with hands on either side, leaning forward slightly, bright smile',
  'one hand resting on the shoulder, other in pocket, casual smile toward camera',
  'standing with thumbs in front pockets, relaxed shoulders, friendly expression',
  'sitting backwards on chair with arms draped over back, smile toward camera',
  'rolling up sleeves while smiling, casual posed moment toward camera',
  'sitting on ledge with one leg up, arm wrapped around knee, peaceful smile',
  'leaning forward slightly with hands on thighs, engaging smile toward camera',
  'standing with one foot up on step, hands on raised knee, confident smile',
  'sitting with legs dangling, hands gripping edge of seat, carefree smile',
  'arms spread wide in welcome gesture, big genuine smile toward camera',
  'one hand on the hip, the other arm gesturing outward, amused smile',
  'sitting indian style with hands resting on ankles, serene smile toward camera',
  'leaning on one elbow against surface, other hand gesturing, conversational smile',
  'standing with hands interlocked behind back, gentle head tilt, soft smile',
  'sitting sideways on step with legs to one side, smile over shoulder',
  'one hand in jacket pocket, other holding small object up, pleased expression',
  'arms akimbo with confident stance, head held high, satisfied smile',
  'sitting with one ankle crossed over opposite knee, hands relaxed, comfortable smile',
  'leaning back against railing with elbows propped, relaxed smile toward camera',
  'standing with one hand on fence post, weight shifted, contemplative smile',
  'sitting on ground with knees up, arms wrapped around legs, cozy smile',
  'holding sunglasses in one hand, other hand on hip, cool smile',
  'standing with jacket slung over shoulder, free hand in pocket, casual smile',
  'sitting on tailgate with feet swinging, hands gripping edge, playful expression',
  'one hand pointing upward, other on chest, inspired smile toward camera',
  'leaning forward with forearms on knees while seated, attentive smile',
  'sitting with legs stretched out, leaning back on straight arms, relaxed smile',
  'standing with weight on back foot, front toe pointed, graceful smile',
  'holding small flower or leaf out at chest level, gentle contemplative smile',
  'sitting cross-legged with hands pressed together in front, peaceful expression',
  'one hand adjusting collar, other relaxed at side, polished smile',
  'leaning against doorframe with one shoulder, arms loosely crossed, inviting smile',
  'sitting on edge with both hands planted behind for support, carefree smile',
  'standing with one hand on lower back stretch, content relieved smile',
  'sitting with forearms resting on knees, hands loosely clasped, thoughtful smile',
  'holding beverage bottle up in toast gesture, celebratory smile toward camera',
  'one arm raised in a playful flourish, other on hip, mock serious grin',
  'standing with jacket pulled tight against wind, cozy bundled smile',
  'sitting with one leg folded under, hands on raised knee, comfortable expression',
  'making a finger frame out to one side with both hands, creative playful smile',
  'leaning with one hand flat against tree trunk, other thumb hooked in belt loop, easy smile',
  'sitting on picnic table with feet on bench, hands gripping table edge, bright grin',
  'standing with messenger bag strap across chest, one hand adjusting strap, traveler smile',
  'sitting backwards straddling bench, arms folded on backrest, mischievous smile toward camera',
  'holding a map rolled up like a telescope at the ready, other hand on the hip, explorer grin',
  'standing with hoodie strings being pulled, scrunched up shoulder shrug, cute smile',
  'sitting on curb with elbows on knees, fingers interlaced, street casual smile',
  'making prayer hands at chest level, slight bow of head, respectful gentle smile',
  'standing with one hand in back pocket, other holding keys up, ready smile',
  'sitting on swing with chains in hands, feet planted, nostalgic happy expression',
  'holding ticket stub up like trophy, other hand celebrating fist pump, victorious grin',
  'standing with arms behind back, rocking on heels, innocent whistling expression',
  'sitting on concrete barrier with legs to one side, hand touching ground, balanced smile',
  'standing with windbreaker unzipped, hands on zipper pulls, breezy casual smile',
  'sitting criss-cross with hands making meditation circle, zen peaceful expression toward camera',
  'holding postcard out at chest level, other hand waving, tourist excitement smile',
  'one hand brushing off shoulder, other on hip, confident dismissive smile',
  'standing with backpack straps in both hands, ready for adventure expression',
  'sitting on steps with one hand supporting behind, legs angled, relaxed portrait smile',
  'making double thumbs down ironically, tongue out slightly, sarcastic fun expression',
  'standing with one foot on skateboard, arms out for balance, cool steady smile',
  'sitting on hood of car with hands flat beside hips, rebel casual grin',
  'holding phone horizontally like filming, other hand directing, behind scenes smile',
  'one hand making stop gesture, other on chest, dramatic pause expression',
  'standing with jacket collar popped, hands smoothing lapels, suave confident smile',
  'sitting on fountain edge trailing fingers in water, dreamy content expression',
  'standing with one hand on fence rail, looking over property, contemplative smile',
  'sitting with legs in pretzel position, hands on ankles, flexible comfortable grin',
  'holding small shell or stone up to light, other hand cupped, discovery smile',
  'one hand making hang loose sign, other in front pocket, chill relaxed expression',
  'standing with arms crossed but hands visible on biceps, strong gentle smile',
  'sitting on log with hands pressed into bark beside hips, nature connection smile',
  'one hand gesturing out to the side, other hand on the hip, conversation smile',
  'standing with one hand on bike handlebars, other adjusting helmet, cyclist smile',
  'sitting on tailgate with one leg hanging, other folded, hands on shin, cozy smile',
  'sitting on a moss-covered rock with legs tucked under, hand on ankle, serene smile',
  'perched on a garden fence with arms draped over the top rail, cheerful grin',
  'leaning against a brick chimney with crossed ankles, hand on hip, relaxed smile',
  'standing on a tree stump with arms balanced out, playful expression toward camera',
  'sitting on concrete steps with elbows on different levels, casual smile',
  'perched on a picnic table with feet on the bench, hands behind, content smile',
  'leaning out a barn door with forearm on the frame, easy grin',
  'sitting on a low stone wall with one leg folded, hand on thigh, warm smile',
  'standing in a creek on smooth stones, arms loose at sides, peaceful expression',
  'perched on a hay bale with knees drawn up, arms wrapped around the shins, thoughtful smile',
  'leaning against a lamppost with shoulder, hands in pockets, sly grin',
  'sitting on a tire swing with rope in one hand, gentle smile',
  'standing on a wooden dock with toe pointed over edge, confident expression',
  'perched on a split-rail fence with legs on either side, hands gripping wood, bright smile',
  'leaning against a tree with back, arms folded loose, contemplative smile toward camera',
  'sitting on a park bench with ankle on opposite knee, arm draped over back',
  'standing on a low bridge with hand trailing the railing, soft smile',
  'perched on a concrete planter with feet tucked, hands on edge, cheerful expression',
  'leaning in a stone archway with elbow high on wall, relaxed grin',
  'sitting on a wooden crate with legs crossed at ankles, hands clasped, easy smile',
  'standing on a fallen tree trunk with arms out for balance, joyful expression',
  'perched on a weathered post with one foot dangling, hand on knee, content smile',
  'leaning against a wooden gate with hip, arms folded, friendly smile toward camera',
  'sitting on a marble step with hands flat beside hips, bright welcoming smile',
  'standing on a small hill with weight shifted back, arms relaxed, peaceful expression',
  'perched on a stone ledge with legs swinging freely, hands gripping sides, playful grin',
  'leaning out of a dutch door with arms crossed on lower half, warm smile',
  'sitting on a canvas chair with feet planted wide, hands on armrests, confident expression',
  'standing in shallow water on rocks with careful balance, serene smile toward camera',
  'perched on a wagon tailgate with legs crossed, hand on ankle, casual grin',
  'leaning against a shed wall with one foot up behind, relaxed smile',
  'sitting on a wooden bench with one leg tucked under, elbow on back',
  'standing on a small footbridge with hand skimming the side rail, gentle expression',
  'perched on a low garden wall with feet flat on ground, hands on stone',
  'leaning in a window frame with both forearms resting inside, cheerful smile',
  'sitting on a tree root with knees slightly apart, hands between legs, peaceful expression',
  'standing on a stepping stone with careful foot placement, arms slightly out, calm smile',
  'perched on a wooden barrel with feet hooked on metal bands, hands on rim',
  'leaning against a stone pillar with full back contact, arms at sides, content smile',
  'sitting on a porch railing with legs inside the posts, hands gripping rail, bright grin',
  'standing on a low retaining wall with toes near edge, confident relaxed expression',
  'perched on a wooden sawhorse with legs on either side, hands flat on top',
  'leaning out a loft opening with forearms on the sill, easy welcoming smile',
  'sitting on a large tree stump with feet flat on ground, hands on knees',
  'standing in a doorway threshold with shoulder against frame, gentle smile toward camera',
  'perched on a stone fountain edge with one hand near the water, peaceful expression',
  'leaning against a wooden post with shoulder, one foot crossed behind, relaxed smile',
  'sitting on a metal bench with back straight, hands beside hips, friendly grin',
  'standing on a narrow beam with arms slightly raised for balance, focused smile',
  'perched on a brick wall with legs hanging over, hands flat beside hips, cheerful expression',
  'leaning into a wooden fence with forearms on top rail, content smile toward camera',
  'sitting on a concrete barrier with legs stretched to one side, hand supporting weight',
  'standing on a large flat rock with solid stance, arms naturally positioned, peaceful smile',
  'perched on a wooden platform with knees drawn up slightly, arms around shins, serene expression',
  'leaning against a metal railing with back, hands gripping bar behind, relaxed grin',
  'sitting on a stone bench with one foot tucked under opposite leg, warm smile',
  'standing on a dock pier with weight evenly distributed, arms loose, gentle expression',
  'perched on a fence corner post with careful balance, hands steadying, bright smile',
  'leaning out a cabin window with both forearms resting on the sill, easy grin',
  'sitting on a wooden step with both feet on lower level, hands on upper step',
  'standing with one hand on the hip, the other at the collarbone, chin lifted with a warm smile',
  'leaning against a surface with arms crossed loosely, weight on one leg, face toward the camera',
  'sitting upright with hands resting gently on the knee, shoulders back, eyes engaging the camera warmly',
  'standing with both hands clasped low in front, weight shifted to one leg, smiling softly',
  'positioned with one hand adjusting a collar, the other relaxed at the side, expression confident',
  'leaning sideways against a surface with one hand resting near the waist, gentle smile showing',
  'standing with arms crossed softly at the waist, head tilted slightly, warm inviting expression',
  'sitting on a surface with one hand on the edge, the other in lap, face forward',
  'standing with one hand lightly touching the hair, the other at the hip, relaxed posture',
  'leaning back against a surface with hands resting on either side, shoulders relaxed and smiling',
  'standing with one hand adjusting a cuff, weight on one leg, confident friendly expression',
  'positioned with both hands resting at the waist, torso turned slightly, face toward the camera',
  'sitting with one arm resting along a surface behind, the other in lap, warm smile',
  'standing with one hand at the collarbone, the other hanging naturally, chin slightly raised',
  'leaning on one elbow against a surface, other hand at the waist, engaging the camera',
  'standing with fingers laced together low in front, posture tall, expression welcoming and kind',
  'sitting forward with both hands resting on the knees, attentive gaze and gentle smile',
  'standing with one hand smoothing hair back, the other relaxed at the side, confident expression',
  'positioned with one hand resting on a railing, the other at the hip, warm demeanor',
  'leaning against a surface with one hand near the shoulder, the other at the side, smiling',
  'standing with both hands adjusting a lapel, weight shifted to one leg, friendly expression',
  'sitting with one hand resting on a thigh, the other beside, shoulders back and smiling',
  'standing with arms loosely crossed below the chest, head straight, eyes warm and inviting',
  'leaning with one shoulder against a surface, both hands relaxed low, gentle confident smile',
  'standing with one hand touching the neck softly, the other at the waist, poised expression',
  'positioned with one hand resting on a ledge, the other adjusting a sleeve, face forward',
  'sitting on steps with hands resting on either knee, upright posture, warm engaging smile',
  'standing with one hand gently holding the opposite wrist low, weight on one leg, smiling',
  'leaning against a low wall with one hand on the hip, the other hanging, confident look',
  'standing with both hands resting lightly at the sides, shoulders relaxed, warm friendly expression',
  'sitting sideways on a surface with torso turned toward the camera, hands in lap, smiling',
  'standing with one hand adjusting a neckline, the other at the side, gentle expression',
  'positioned with one hand resting on a surface beside, the other at the waist, engaging',
  'leaning with one hand on a railing, the other touching the hair lightly, warm smile',
  'standing with arms crossed gently at the ribs, weight shifted, confident inviting expression',
  'sitting with one hand draped over a knee, the other resting beside, relaxed and smiling',
  'standing with one hand at the side of the neck, the other at the hip, poised',
  'leaning against a surface with both hands resting on it beside the body, warm demeanor',
  'standing with one hand adjusting a watch or bracelet, the other relaxed, friendly expression',
  'positioned with one hand resting on the opposite elbow low, the other hanging, gentle smile',
  'sitting on a surface edge with hands clasped together in lap, shoulders back, warm gaze',
  'standing with one hand lightly touching the collarbone, the other at the waist, confident smile',
];

// DYNAMIC pool — cinematic, powerful, energetic SOLO stances for hero-grade
// renders. Face stays forward for the swap; body language ONLY, prop-free and
// scene-neutral so the wardrobe + setting carry the theme. Always paired with an
// epic backdrop (needsEpicBackdrop = true) — the pose and the scenery both sell
// the moment. This is the pool that kills the "posed for a costume photo" look.
// (2026-08-25, Kevin)
export const DYNAMIC_ACTIONS: string[] = [
  'standing in a wide, grounded power stance with arms crossed and chin raised, squared to the camera, radiating quiet command',
  'one boot planted up on a rock with a forearm resting across the knee, leaning toward the camera with an easy confident grin',
  'arms flung wide in triumph, chin lifted in a mid-shout of victory, face toward the camera',
  'windswept and leaning into a strong gust, cloak and hair streaming to one side, jaw set and eyes forward',
  'standing tall with fists loosely clenched at the sides and shoulders squared, chest out, owning the frame',
  'a single fist raised high in triumph, the other hand on the hip, fierce grin to the camera',
  'mid-turn toward the camera as if just called, weight on the back foot, coat swinging',
  'arms spread wide and open as if taking in a vast view, chest lifted, face to the camera',
  'one hand raised in a bold hail to the camera, feet planted wide, commanding presence',
  'standing with weight cocked to one hip and a confident half-smirk, thumbs hooked in the belt',
  'both arms flexed in a triumphant strongman pose with a broad grin to the camera',
  'flinging an arm skyward in a rallying cry, chest out, fierce and forward',
  'crouched in a low athletic ready stance with a hand braced on the knee, chin up and eyes locked to the camera',
  'leaning forward with fists set on a ledge, glaring boldly ahead at the camera',
  'arms folded high across the chest with a slight swagger, jaw set, unshakeable',
  'one arm thrown wide presenting the scene with a showman flourish, proud stance',
  'standing broad and still like a carved hero, arms crossed and gaze steady to the camera',
  'raising open hands toward the sky as if calling down the storm, chest lifted, face forward',
  'hands on hips with elbows out and boots planted wide, a triumphant grin to the camera',
  'mid-laugh with chin up and hands on the hips, open and joyful and radiant, face toward the camera',
  'striding forward toward the camera with a confident purposeful gait, arms swinging',
  'pressing a fist into an open palm at the chest, resolute and squared to the camera',
  'a hand pressed to the chest and the other arm sweeping out in an inspired heroic flourish',
  'weight low and knees bent bracing as if against motion, arms out, eyes blazing forward',
  'chin lifted and arms crossed, a slow confident smile spreading, utterly self-assured',
  'one fist raised to the sky and the other planted on the hip, a champion victory stance',
  'leaning a shoulder back in a cocky half-turn to the camera, hands loose and ready',
  'arms raised wide and triumphant with fists clenched, head high in exultation',
  'standing tall at the edge of a height with the wind pulling at the clothes, arms folded, gaze to the camera',
  'one hand raised palm-out in a bold command to the camera, feet set wide, unflinching',
];

export interface SingleActionPools {
  candid: string[];
  portrait: string[];
  dynamic: string[];
}

export function pickSingleAction(
  forcePool?: 'portrait' | 'candid' | 'dynamic',
  // DB-loadable arrays; default = code arrays. needsEpicBackdrop stays derived
  // from POOL membership — never a DB column. Default nightly roll: 40% dynamic
  // + 30% portrait + 30% candid, so solo cast dreams read hero-grade while the
  // (chore-pruned) classic pools keep real presence.
  pools: SingleActionPools = {
    candid: CANDID_ACTIONS,
    portrait: PORTRAIT_ACTIONS,
    dynamic: DYNAMIC_ACTIONS,
  }
): SingleAction {
  const pick = (arr: string[]) => arr[Math.floor(Math.random() * arr.length)];
  if (forcePool === 'dynamic') return { pose: pick(pools.dynamic), needsEpicBackdrop: true };
  if (forcePool === 'portrait') return { pose: pick(pools.portrait), needsEpicBackdrop: true };
  if (forcePool === 'candid') return { pose: pick(pools.candid), needsEpicBackdrop: false };

  const r = Math.random();
  if (r < 0.4) return { pose: pick(pools.dynamic), needsEpicBackdrop: true }; // 40% hero-grade
  if (r < 0.7) return { pose: pick(pools.portrait), needsEpicBackdrop: true }; // 30% portrait
  return { pose: pick(pools.candid), needsEpicBackdrop: false }; // 30% candid (pruned of chores)
}
