/**
 * Single character action pool — typed.
 *
 * Two pools picked 50/50 at random:
 *   1. CANDID — real moments captured (climbing, leaning, mid-laugh, mid-bite)
 *   2. PORTRAIT — posed for camera. Mix of stand-and-pose (hands in pockets,
 *      peace sign, shaka) and scene-interactive (sitting on rock, perched in tree,
 *      halfway up ladder). When picked, `needsEpicBackdrop` flags the brief to
 *      push for striking scenery — the background is the reason for the photo.
 */

export interface SingleAction {
  pose: string;
  needsEpicBackdrop: boolean;
}

export const CANDID_ACTIONS: string[] = [
  'stretching arms wide in the morning sun with head tilted back, expression peaceful',
  'crouched examining something tiny with magnifying glass held close to eye',
  'mid-chomp of an oversized sandwich with both hands gripping it tightly',
  'sitting on stone steps with one foot propped up, chin resting on knee',
  'brushing fingertips along a textured wall while walking slowly past it',
  'perched on a boulder with legs crossed, hands clasped around one ankle',
  'reaching up to pluck fruit from an overhead branch, standing on tiptoes',
  'hunched over a map spread on knees, finger tracing a route intently',
  'mid-stretch with one arm overhead and torso bent to the side gracefully',
  'kneeling to pet an unseen animal with gentle outstretched hand, smiling softly',
  'wading through tall grass with both hands trailing through the stalks',
  'sitting cross-legged on ground with elbows on knees, chin in palms',
  'mid-step climbing wooden stairs with hand sliding along the rail',
  'crouched beside a tide pool with finger almost touching the water surface',
  'standing in doorway with one hand on the frame, body leaning inward',
  'walking backward down a path with arms out for balance, grinning widely',
  'sitting on a swing with feet barely touching ground, hands gripping chains',
  'mid-reach toward a high shelf with other hand braced against wall',
  'kneeling on one knee tying a shoelace with focused concentration',
  'standing ankle-deep in sand with toes buried, hands brushing off palms',
  'pretending to conduct an orchestra with dramatic arm movements and serious expression',
  'balancing a book on head while walking with exaggerated careful steps',
  'fake-wrestling with an enormous teddy bear, arms wrapped around its middle',
  'wearing mismatched socks as mittens while pretending to box invisible opponent',
  "holding a rubber duck like hamlet's skull with overly dramatic contemplative pose",
  'pretending to lasso something with jump rope spinning overhead in wide circle',
  'wearing a cape made from towel while striking superhero landing pose',
  'balancing on one foot while juggling three oranges with intense concentration',
  'pretending to be blown away by fan, leaning back with hair flying',
  'fake-tiptoeing past sleeping giant with exaggerated sneaky hunched posture',
  'holding giant lollipop like microphone while pretending to sing into it',
  'pretending to be trapped behind invisible wall with palms flat against air',
  'wearing pot as helmet while saluting with wooden spoon like sword',
  'fake-surfing on ironing board with arms out catching imaginary waves',
  'pretending to pull enormous invisible fish from water with fishing rod',
  'hopping from foot to foot on hot pavement with pained expression',
  'scrambling up steep rocky incline with both hands finding holds above',
  'mid-vault over low fence with hands planted and legs swinging over',
  'stepping carefully across stream on slippery stones with arms extended',
  'rappelling down cliff face with rope in hands and focused expression',
  'scaling ladder rungs with alternating hand-over-hand climbing motion',
  'duck-walking under low hanging branch with knees bent and head down',
  'army-crawling under fallen log with elbows pulling body forward',
  'tiptoeing across narrow beam with arms spread for careful balance',
  'leaping between rooftops with arms windmilling and legs stretched wide',
  'somersaulting down grassy hill with body tucked and rolling freely',
  'swinging from tree branch with both hands gripped tight overhead',
  'bounding up sand dune with high knee steps and pumping arms',
  'side-stepping down steep slope with hands out for balance control',
  'cartwheeling across open field with legs and arms making perfect wheel',
  'pirouetting with arms gracefully curved and one leg extended behind',
  'crouching behind large mushroom with finger pressed to lips conspiratorially',
  'sitting in field braiding flower stems with tongue poking out concentratedly',
  'perched on picnic table with feet on bench and sandwich halfway eaten',
  'standing in shallow creek with pants cuffed and hands cupped catching water',
  'lying on stomach reading book propped on elbows in grass',
  'sitting backwards on chair with arms folded over backrest casually',
  'squatting beside campfire poking logs with long stick and careful attention',
  'standing with hand shading eyes peering into bright distance curiously',
  'crouched collecting shells in cupped palms along sandy shoreline',
  'sitting on dock with legs swinging over water and fishing line cast',
  'leaning over bridge railing dropping leaves into current below playfully',
  'standing with arms akimbo surveying garden beds with satisfied expression',
  'kneeling transplanting seedlings with dirt-covered hands working gently in soil',
  'hunched over sketchbook with pencil moving quickly across page in concentration',
  'sitting cross-legged sorting through collection of interesting rocks and minerals',
  'standing on ladder picking apples with basket hooked over one arm',
  'crouched building small cairn of balanced stones with patient precision',
  'sitting on blanket unpacking picnic basket with items spread around',
  'leaning against barn door with straw hat pushed back and relaxed posture',
  'standing in wheat field with hands running through grain stalks thoughtfully',
  'crouched photographing butterfly with camera held steady and body perfectly still',
  'sitting on hay bale with legs dangling and hands gripping edge',
  'kneeling beside garden bed pulling weeds with sleeves rolled up determinedly',
  'sitting on porch step shelling peas into bowl with methodical movements',
  'standing at easel with palette in one hand and brush poised',
  'crouched beside tide pool with net ready to catch small creatures',
  'sitting on fallen tree whittling stick with pocket knife and careful strokes',
  'standing with arms full of firewood walking toward cabin with steady pace',
  'kneeling beside stream filling water bottle with clear mountain water',
  'sitting on rock sorting through backpack contents spread on ground systematically',
  'standing at cliff edge with journal open writing with wind ruffling pages',
  'crouched building sandcastle with bucket and shovel working on turret details',
  'sitting in hammock with drink in hand and book balanced on stomach',
  'standing with metal detector sweeping sand in methodical search pattern',
  'kneeling beside vegetable garden harvesting tomatoes into wicker basket carefully',
  'sitting on porch swing with feet tucked up and mug steaming',
  'standing with arms spread feeling ocean breeze with peaceful expression',
  'crouched beside pond feeding ducks with bread crumbs scattered from hand',
  'sitting on tailgate with guitar across lap and fingers finding chords',
  'kneeling beside flower bed deadheading roses with small scissors precisely',
  'sitting on bench with crossword puzzle and pen tapping against chin',
  'crouched beside creek skipping stones with careful sidearm throwing motion',
  'sitting on museum steps with guidebook open and finger tracing map',
  'standing at overlook with camera raised capturing panoramic mountain view',
  'kneeling beside tide examining seaweed specimens with scientific curiosity',
  'sitting in café chair with pastry halfway to mouth and surprised delight',
  'standing at fruit stand selecting perfect peaches with gentle testing squeezes',
  'crouched beside fountain tossing coin with eyes closed making silent wish',
  'sitting on park bench feeding pigeons with breadcrumbs scattered around feet',
  'standing with easel outdoors painting landscape with brush loaded with color',
  'kneeling beside stream washing face with cupped hands full of cold water',
  'sitting on bleachers with scorecard and pencil tracking game progress',
  'standing at fish market pointing at display while vendor explains options',
  'sitting on library steps with stack of books and reading one intently',
  'standing at street cart ordering food with animated hand gestures',
  'kneeling beside campfire roasting marshmallow on long stick with patient attention',
  'sitting on deck chair with feet propped up and drink sweating condensation',
  'standing at telescope adjusting focus knobs to see distant celestial objects',
  'crouched beside herb garden pinching basil leaves and inhaling fresh scent',
  'sitting on stump with harmonica pressed to lips and cheeks puffed',
  'standing at loom working threads with shuttle moving in rhythmic pattern',
  'kneeling beside flower pressing petals into book with careful gentle pressure',
  'sitting on diving board with legs swinging over pool water below',
  'standing at pottery wheel shaping clay with hands covered in slip',
  'sitting on porch rocker with cat purring in lap and hand stroking',
  'standing at grape arbor reaching up to test ripeness of hanging clusters',
  'kneeling beside strawberry patch selecting perfect berries for small basket',
  'sitting on dock with crab net ready to scoop creatures from water',
  'standing at beehive wearing protective gear and holding smoker carefully',
  'crouched beside fossil embedded in rock using small brush cleaning sediment',
  'sitting on tree swing with rope wound around wrist and feet barely touching',
  'standing at blacksmith anvil with hammer raised ready to shape glowing metal',
  'kneeling beside injured bird with gentle hands offering water from cupped palm',
  'sitting on porch with corn ears in lap removing kernels methodically',
  'standing at river with fly fishing rod casting line in graceful arc',
  'crouched beside mushroom patch identifying edible varieties with field guide reference',
  'sitting on milk stool with bucket positioned for morning dairy cow routine',
  'standing at spinning wheel with fiber feeding through fingers into growing thread',
  'kneeling beside newly planted tree watering roots with old watering can',
  'standing at honey extractor turning handle while golden liquid flows into jars',
  'crouched beside rabbit hutch offering fresh lettuce leaves through wire mesh',
  'sitting on boat dock with crab trap rope in hands checking morning catch',
  'standing at cider press turning wheel to extract juice from crushed apples',
  'kneeling beside chicken coop collecting warm eggs in basket lined with cloth',
  'sitting on hay wagon with reins in hands guiding gentle draft horses',
  'standing at maple tree with tap and bucket collecting sweet sap',
  'crouched beside compost pile turning decomposing materials with pitchfork efficiently',
  'sitting on porch with butter churn between knees working cream into solid',
  'standing at sheep pen with shears ready for annual wool harvest',
  'kneeling beside bee box with smoker calming hive before honey collection',
  'sitting on tractor seat with hands on steering wheel surveying planted fields',
  'standing at grain silo operating auger to move harvested wheat into storage',
  'crouched beside duck pond collecting eggs hidden in tall grass around edges',
  'sitting on barn beam with rope and pulley system raising hay bales',
  'standing at outdoor kitchen with cast iron pot stirring hearty stew',
  'kneeling beside herb spiral harvesting sage and rosemary for evening meal',
  'sitting on milk house steps with separator parts cleaning before next use',
  'standing at root cellar organizing preserved vegetables in wooden crates systematically',
  'crouched beside cold frame checking winter vegetables for readiness and quality',
  'sitting on front porch with wool in lap spinning fiber into yarn',
  'standing at smokehouse checking ham and bacon curing in aromatic cedar smoke',
  'kneeling beside rain barrel positioning downspout to catch precious roof water',
  'sitting on chopping block with axe across knees taking break from splitting',
  'standing at outdoor oven with long paddle retrieving fresh baked bread loaves',
  'crouched beside medicinal herb garden harvesting echinacea flowers for winter tea',
  'sitting on well cover with bucket and rope drawing cold water up',
  'standing at fence line with wire stretchers repairing winter damage efficiently',
  'kneeling beside fruit trees grafting new varieties onto established root stock',
  'sitting on wagon tongue with harness in hands preparing horses for field',
  'standing at granary with scoop measuring grain portions for animal feed',
  'crouched beside maple syrup boiler tending fire to maintain proper cooking temperature',
  'sitting on milking stool with warm bucket positioned collecting morning dairy production',
  'standing at tool shed with whetstone sharpening blades for upcoming harvest season',
  'kneeling beside seed bed transplanting tender seedlings with careful root protection',
  'sitting on porch step with account ledger recording farm expenses and income',
  'standing at weather station checking instruments and recording daily atmospheric conditions',
  'crouched beside irrigation ditch adjusting water flow to different field sections',
  'sitting on combine seat with controls ready to begin harvesting mature grain',
  'standing at produce stand arranging fresh vegetables in attractive display baskets',
  'kneeling beside grape vines pruning excess growth to concentrate fruit development',
  'sitting on hay mower with reins guiding horses through tall grass meadow',
  'standing at sausage grinder with meat mixture ready for casing and preservation',
  'crouched beside fish pond checking water quality and feeding ornamental carp',
  'sitting on dairy truck with clipboard recording delivery quantities and customer orders',
  'standing at canning station with jars and lids preparing seasonal vegetable preservation',
  'kneeling beside flower beds collecting seed pods for next year planting season',
  'sitting on threshing floor with flail separating grain kernels from wheat stalks',
  'standing at cream separator with handle turning to divide milk into components',
  'crouched beside rabbit warren checking breeding pairs and counting new baby rabbits',
  'sitting on hay rake with horses pulling equipment across recently cut grass',
  'standing at outdoor market with scales weighing produce for customer purchase transactions',
  'kneeling beside fruit trees with ladder positioned for efficient apple and pear',
  'sitting on wagon bench with market goods loaded for weekly town selling',
  'standing at grain elevator with conveyor belt moving harvested crops to storage',
  'crouched beside beehives with veil and gloves checking colony health and production',
  'sitting on tractor with cultivator attached preparing soil for spring planting season',
  'standing at farmers market with cash box making change for satisfied customers',
  'kneeling beside greenhouse benches transplanting seedlings into larger growing containers systematically',
];

export const PORTRAIT_ACTIONS: string[] = [
  'standing with arms crossed loosely, head tilted slightly, warm smile toward camera',
  'flashing double peace signs with both hands up, cheerful grin',
  'sitting on steps leaning back on hands, legs stretched out, relaxed smile',
  'one hand on hip, the other giving thumbs up, confident expression',
  'mid-wave with fingers wiggling, other hand tucked in back pocket, friendly smile',
  'pointing at camera with both index fingers, playful grin',
  'sitting cross-legged with chin resting on hand, gentle smile toward camera',
  'hands clasped in front, weight shifted to one leg, easy smile',
  'throwing up an ok sign with one hand, relaxed stance, content expression',
  'leaning against wall with shoulder, arms folded, slight smirk toward camera',
  'holding coffee cup up in cheers gesture, other hand on hip, warm smile',
  'sitting on bench with hands on either side, leaning forward slightly, bright smile',
  'one hand adjusting hat brim, other in pocket, casual smile toward camera',
  'standing with thumbs in front pockets, relaxed shoulders, friendly expression',
  'sitting backwards on chair with arms draped over back, smile toward camera',
  'rolling up sleeves while smiling, casual posed moment toward camera',
  'hands behind head in relaxed stretch pose, content smile',
  'sitting on ledge with one leg up, arm wrapped around knee, peaceful smile',
  'giving single thumbs up with dominant hand, other hand relaxed, cheerful expression',
  'leaning forward slightly with hands on thighs, engaging smile toward camera',
  'standing with one foot up on step, hands on raised knee, confident smile',
  'finger gun with one hand, other hand running through hair, sly grin',
  'sitting with legs dangling, hands gripping edge of seat, carefree smile',
  'arms spread wide in welcome gesture, big genuine smile toward camera',
  'holding phone in selfie position, free hand making peace sign, happy expression',
  'one hand shading eyes playfully, other on hip, amused smile',
  'sitting indian style with hands resting on ankles, serene smile toward camera',
  'leaning on one elbow against surface, other hand gesturing, conversational smile',
  'standing with hands interlocked behind back, gentle head tilt, soft smile',
  'giving shaka with both hands, relaxed island vibe, easy grin',
  'sitting sideways on step with legs to one side, smile over shoulder',
  'one hand in jacket pocket, other holding small object up, pleased expression',
  'arms akimbo with confident stance, head held high, satisfied smile',
  'sitting with one ankle crossed over opposite knee, hands relaxed, comfortable smile',
  'making heart shape with both hands above head, joyful expression',
  'leaning back against railing with elbows propped, relaxed smile toward camera',
  'standing with one hand on fence post, weight shifted, contemplative smile',
  'sitting on ground with knees up, arms wrapped around legs, cozy smile',
  'holding sunglasses in one hand, other hand on hip, cool smile',
  'standing with jacket slung over shoulder, free hand in pocket, casual smile',
  'sitting on tailgate with feet swinging, hands gripping edge, playful expression',
  'one hand pointing upward, other on chest, inspired smile toward camera',
  'leaning forward with forearms on knees while seated, attentive smile',
  'standing with arms stretched overhead in victory pose, triumphant grin',
  'sitting with legs stretched out, leaning back on straight arms, relaxed smile',
  'one hand making call me gesture, other hand on hip, cheeky grin',
  'standing with weight on back foot, front toe pointed, graceful smile',
  'holding small flower or leaf up near face, gentle contemplative smile',
  'sitting cross-legged with hands pressed together in front, peaceful expression',
  'one hand adjusting collar, other relaxed at side, polished smile',
  'leaning against doorframe with one shoulder, arms loosely crossed, inviting smile',
  'sitting on edge with both hands planted behind for support, carefree smile',
  'making rock horns with one hand, other thumb up, energetic grin',
  'standing with one hand on lower back stretch, content relieved smile',
  'sitting with chin propped on both fists, elbows on knees, thoughtful smile',
  'holding beverage bottle up in toast gesture, celebratory smile toward camera',
  'one hand saluting playfully, other on hip, mock serious grin',
  'standing with jacket pulled tight against wind, cozy bundled smile',
  'sitting with one leg folded under, hands on raised knee, comfortable expression',
  'making finger frame around face with both hands, creative playful smile',
  'leaning with one hand flat against tree trunk, other thumb hooked in belt loop, easy smile',
  'sitting on picnic table with feet on bench, hands gripping table edge, bright grin',
  'making jazz hands with both arms extended, theatrical excited expression toward camera',
  'standing with messenger bag strap across chest, one hand adjusting strap, traveler smile',
  'sitting backwards straddling bench, arms folded on backrest, mischievous smile toward camera',
  'holding map rolled up like telescope, other hand shielding forehead, explorer grin',
  'one hand doing finger guns, other making peace sign, mixed signal playful expression',
  'standing with hoodie strings being pulled, scrunched up shoulder shrug, cute smile',
  'sitting on curb with elbows on knees, fingers interlaced, street casual smile',
  'making prayer hands at chest level, slight bow of head, respectful gentle smile',
  'standing with one hand in back pocket, other holding keys up, ready smile',
  'sitting on swing with chains in hands, feet planted, nostalgic happy expression',
  'holding ticket stub up like trophy, other hand celebrating fist pump, victorious grin',
  'one hand on baseball cap brim, other giving casual salute, sporty smile',
  'standing with arms behind back, rocking on heels, innocent whistling expression',
  'sitting on concrete barrier with legs to one side, hand touching ground, balanced smile',
  'making ok sign with one hand, other pointing finger gun, combo gesture grin',
  'standing with windbreaker unzipped, hands on zipper pulls, breezy casual smile',
  'sitting criss-cross with hands making meditation circle, zen peaceful expression toward camera',
  'holding postcard up next to cheek, other hand waving, tourist excitement smile',
  'one hand brushing off shoulder, other on hip, confident dismissive smile',
  'standing with backpack straps in both hands, ready for adventure expression',
  'sitting on steps with one hand supporting behind, legs angled, relaxed portrait smile',
  'making double thumbs down ironically, tongue out slightly, sarcastic fun expression',
  'standing with one foot on skateboard, arms out for balance, cool steady smile',
  'sitting on hood of car with hands flat beside hips, rebel casual grin',
  'holding phone horizontally like filming, other hand directing, behind scenes smile',
  'one hand making stop gesture, other on chest, dramatic pause expression',
  'standing with jacket collar popped, hands smoothing lapels, suave confident smile',
  'sitting on fountain edge trailing fingers in water, dreamy content expression',
  'making air quotes with both hands raised, skeptical amused smile toward camera',
  'standing with one hand on fence rail, looking over property, contemplative smile',
  'sitting with legs in pretzel position, hands on ankles, flexible comfortable grin',
  'holding small shell or stone up to light, other hand cupped, discovery smile',
  'one hand making hang loose sign, other in front pocket, chill relaxed expression',
  'standing with arms crossed but hands visible on biceps, strong gentle smile',
  'sitting on log with hands pressed into bark beside hips, nature connection smile',
  'making telephone gesture with hand to ear, other hand gesturing, conversation smile',
  'standing with one hand on bike handlebars, other adjusting helmet, cyclist smile',
  'sitting on tailgate with one leg hanging, other folded, hands on shin, cozy smile',
  'sitting on a moss-covered rock with legs tucked under, hand on ankle, serene smile',
  'perched on a garden fence with arms draped over the top rail, cheerful grin',
  'leaning against a brick chimney with crossed ankles, hand on hip, relaxed smile',
  'standing on a tree stump with arms balanced out, playful expression toward camera',
  'sitting on concrete steps with elbows on different levels, casual smile',
  'perched on a picnic table with feet on the bench, hands behind, content smile',
  'leaning out a barn door with forearm on the frame, easy grin',
  'sitting on a low stone wall with one leg folded, hand on thigh, warm smile',
  'standing in a creek on smooth stones, arms loose at sides, peaceful expression',
  'perched on a hay bale with knees drawn up, chin on hand, thoughtful smile',
  'leaning against a lamppost with shoulder, hands in pockets, sly grin',
  'sitting on a tire swing with rope in one hand, gentle smile',
  'standing on a wooden dock with toe pointed over edge, confident expression',
  'perched on a split-rail fence with legs on either side, hands gripping wood, bright smile',
  'leaning against a tree with back, arms folded loose, contemplative smile toward camera',
  'sitting on a park bench with ankle on opposite knee, arm draped over back',
  'standing on a low bridge with hand trailing the railing, soft smile',
  'perched on a concrete planter with feet tucked, hands on edge, cheerful expression',
  'leaning in a stone archway with elbow high on wall, relaxed grin',
  'sitting on a wooden crate with legs crossed at ankles, hands clasped, easy smile',
  'standing on a fallen tree trunk with arms out for balance, joyful expression',
  'perched on a weathered post with one foot dangling, hand on knee, content smile',
  'leaning against a wooden gate with hip, arms folded, friendly smile toward camera',
  'sitting on a marble step with hands flat beside hips, bright welcoming smile',
  'standing on a small hill with weight shifted back, arms relaxed, peaceful expression',
  'perched on a stone ledge with legs swinging freely, hands gripping sides, playful grin',
  'leaning out of a dutch door with arms crossed on lower half, warm smile',
  'sitting on a canvas chair with feet planted wide, hands on armrests, confident expression',
  'standing in shallow water on rocks with careful balance, serene smile toward camera',
  'perched on a wagon tailgate with legs crossed, hand on ankle, casual grin',
  'leaning against a shed wall with one foot up behind, relaxed smile',
  'sitting on a wooden bench with one leg tucked under, elbow on back',
  'standing on a small footbridge with hand skimming the side rail, gentle expression',
  'perched on a low garden wall with feet flat on ground, hands on stone',
  'leaning in a window frame with both forearms resting inside, cheerful smile',
  'sitting on a tree root with knees slightly apart, hands between legs, peaceful expression',
  'standing on a stepping stone with careful foot placement, arms slightly out, calm smile',
  'perched on a wooden barrel with feet hooked on metal bands, hands on rim',
  'leaning against a stone pillar with full back contact, arms at sides, content smile',
  'sitting on a porch railing with legs inside the posts, hands gripping rail, bright grin',
  'standing on a low retaining wall with toes near edge, confident relaxed expression',
  'perched on a wooden sawhorse with legs on either side, hands flat on top',
  'leaning out a loft opening with forearms on the sill, easy welcoming smile',
  'sitting on a large tree stump with feet flat on ground, hands on knees',
  'standing in a doorway threshold with shoulder against frame, gentle smile toward camera',
  'perched on a stone fountain edge with one hand near the water, peaceful expression',
  'leaning against a wooden post with shoulder, one foot crossed behind, relaxed smile',
  'sitting on a metal bench with back straight, hands beside hips, friendly grin',
  'standing on a narrow beam with arms slightly raised for balance, focused smile',
  'perched on a brick wall with legs hanging over, hands flat beside hips, cheerful expression',
  'leaning into a wooden fence with forearms on top rail, content smile toward camera',
  'sitting on a concrete barrier with legs stretched to one side, hand supporting weight',
  'standing on a large flat rock with solid stance, arms naturally positioned, peaceful smile',
  'perched on a wooden platform with knees drawn up slightly, arms around shins, serene expression',
  'leaning against a metal railing with back, hands gripping bar behind, relaxed grin',
  'sitting on a stone bench with one foot tucked under opposite leg, warm smile',
  'standing on a dock pier with weight evenly distributed, arms loose, gentle expression',
  'perched on a fence corner post with careful balance, hands steadying, bright smile',
  'leaning out a cabin window with chin in one hand, elbow on sill, easy grin',
  'sitting on a wooden step with both feet on lower level, hands on upper step',
];

export function pickSingleAction(forcePool?: 'portrait' | 'candid'): SingleAction {
  const isPortrait = forcePool ? forcePool === 'portrait' : Math.random() < 0.5;
  if (isPortrait) {
    return {
      pose: PORTRAIT_ACTIONS[Math.floor(Math.random() * PORTRAIT_ACTIONS.length)],
      needsEpicBackdrop: true,
    };
  }
  return {
    pose: CANDID_ACTIONS[Math.floor(Math.random() * CANDID_ACTIONS.length)],
    needsEpicBackdrop: false,
  };
}
