/**
 * Universal entropy axes — 3 pools picked independently per render.
 *
 *   1. SCENE_ANGLES   — compositional framing approaches
 *   2. MOOD_TWISTS    — atmospheric/temporal beats (weather, time, light)
 *   3. NARRATOR_HINTS — storytelling perspective on the moment
 */

export const SCENE_ANGLES: string[] = [
  'shot from ground level with towering vertical elements stretching upward',
  'framed through overlapping transparent layers creating visual depth and complexity',
  'extreme close-up composition with only partial subject visible in frame',
  'subject positioned at intersection of diagonal architectural lines converging inward',
  'wide panoramic framing with subject as tiny element in vast space',
  'captured through mesh or fence creating geometric overlay patterns',
  'angled from corner perspective with two walls creating triangular composition',
  'subject reflected multiple times in series of parallel surfaces',
  'framed by circular opening with subject centered in the round aperture',
  'shot between foreground pillars or posts creating natural frame borders',
  'extreme macro perspective with subject filling entire frame edge to edge',
  'captured from inside looking outward through window or opening',
  'subject positioned against strong horizontal lines cutting through composition',
  'angled upward from below with dramatic perspective distortion of proportions',
  'framed by hanging elements creating organic curtain-like borders around subject',
  'shot across water surface with subject mirrored in still reflection',
  'captured through steam or vapor creating soft diffused foreground texture',
  'subject seen between dense vertical elements like trees or poles',
  'extreme telephoto compression flattening background elements into layered planes',
  'framed by shadow patterns cast across the scene from overhead',
  'captured from behind translucent screen with subject visible through material',
  'shot with extreme tilt creating diagonal horizon line across frame',
  'subject positioned where multiple perspective lines intersect and converge',
  'framed by elaborate decorative border elements in foreground',
  'captured through prismatic surface creating rainbow light scatter effects',
  'shot from elevated position looking down through layered horizontal planes',
  'subject silhouetted against geometric pattern or textural background surface',
  'framed by curved architectural elements creating flowing compositional lines',
  'captured with subject positioned at vanishing point of linear perspective',
  'shot through dense foliage creating dappled light and shadow patterns',
  'subject reflected in curved metallic surface distorting proportions and angles',
  'framed by repetitive structural elements creating rhythmic visual pattern',
  'captured from low angle with subject breaking above horizon line',
  'shot with multiple exposure creating ghostly overlapping transparent layers',
  'subject positioned against spiral or circular architectural background elements',
  'framed through narrow vertical slot creating compressed aspect ratio view',
  'captured with extreme wide angle creating fisheye perspective distortion',
  'shot from inside cave or tunnel looking toward bright opening',
  'subject positioned where diagonal and horizontal compositional lines cross',
  'framed by organic hole or opening in natural surface',
  'captured through rippled glass creating abstract distortion of background',
  'shot from directly above with subject against patterned floor surface',
  'subject positioned in negative space between solid foreground elements',
  'framed by interlacing branches or structural elements overhead',
  'captured through multiple layered transparent materials creating depth',
  'shot with subject emerging from or disappearing into geometric void',
  'framed by strong vertical elements on left and right edges',
  "captured from worm's eye view with subject against sky backdrop",
  'subject positioned at focal point of radial compositional lines',
  'framed by dense crowd or collection of similar objects',
  'captured with subject breaking through or emerging from surface plane',
  'shot from behind subject showing their view of scene ahead',
  'framed by elaborate geometric floor pattern extending into distance',
  'captured through rain-covered glass creating streaked visual texture',
  'shot with subject positioned against strong diagonal architectural slope',
  'framed by mechanical or industrial elements creating technical composition',
  'shot with multiple mirrors creating infinite recursive reflections',
  'subject positioned at center of concentric circular or square patterns',
  'framed by flowing fabric or flexible material creating organic borders',
  'captured through heat shimmer or mirage effect distorting background',
  'shot from extreme distance with subject barely visible speck',
  'framed by elaborate carved or textured surface creating ornate border',
  'captured with subject positioned against radiating linear pattern background',
  'shot through smoke or fog with subject partially obscured',
  'framed by water droplets on transparent surface in foreground',
  'shot with subject reflected in calm water creating perfect mirror',
  'framed by dense collection of hanging objects creating curtain effect',
  'captured through venetian blinds creating horizontal stripe light patterns',
  'shot from behind partial obstruction with subject visible in gaps',
  'framed by elaborate mosaic or tiled surface creating complex background',
  'framed by collection of vertical poles creating prison bar effect',
  'captured from extremely high vantage point showing miniature landscape below',
  'shot with subject positioned in bright spotlight against dark surround',
  'framed by organic growth patterns like coral or crystalline structures',
  'captured through chain link creating diamond grid overlay pattern',
  'shot with subject breaking surface tension of water or liquid',
  'framed by elaborate stonework or masonry creating architectural border',
  'captured through multiple soap bubbles creating spherical lens effects',
];

export const MOOD_TWISTS: string[] = [
  'winter twilight with snow still falling in fat flakes',
  'desert night with stars so bright they cast shadows',
  'thick humidity before dawn with dew forming on everything',
  'candlelight flickering through windows as darkness settles outside',
  'first thaw dripping steadily from every roof and branch',
  'pre-storm darkness with green-tinged clouds rolling overhead',
  'salt air heavy with ocean spray and seaweed scent',
  'mountain morning with frost melting into tiny streams',
  'sweltering noon with heat waves rising from pavement',
  'gentle rain pattering on leaves with rich earth smell',
  'arctic wind cutting through everything with crystalline clarity',
  'bonfire smoke drifting sideways through crisp autumn air',
  'lightning illuminating everything in stark white flashes',
  'summer storm approaching with rumbling thunder in distance',
  'fresh powder snow sparkling under bright winter sun',
  'coastal fog rolling in thick and silent',
  'cherry blossom petals falling like snow on warm breeze',
  'monsoon downpour drumming on metal roofs',
  'northern lights dancing green across star-filled sky',
  'harvest moon hanging low and orange through thin clouds',
  'ice storm coating every surface in crystal shell',
  'dust devil swirling across empty sun-baked ground',
  'morning frost retreating into shadow as sun climbs',
  'tropical humidity with air so thick it shimmers',
  'sleet tapping against windows in steady rhythm',
  'golden wheat field rippling under hot summer wind',
  'cave coolness with water echoing in darkness',
  'cathedral light streaming through ancient forest canopy',
  'midnight snow falling silent and thick',
  'spring thunderstorm with warm rain washing winter away',
  'frozen breath hanging in still mountain air',
  'campfire embers glowing as night deepens around them',
  'dawn breaking pink across snow-covered peaks',
  'humid greenhouse atmosphere thick with plant life',
  'sandstorm approaching like a wall of brown fury',
  'gentle snowfall beginning as gray clouds gather',
  'summer lightning dancing between distant hills',
  'morning dew heavy enough to soak through clothes',
  'bitter cold with snow crunching sharp underfoot',
  'warm rain on hot asphalt sending up steam',
  'firefly light blinking through humid summer darkness',
  'arctic aurora painting the ice fields green',
  'fresh cut grass scent mixing with approaching rain',
  'desert dawn with purple shadows stretching long',
  'heavy snow muffling all sound to whispers',
  'ocean storm spray flying over rocky coastline',
  'autumn wind stripping last leaves from bare branches',
  'afternoon heat building toward evening thunderstorm',
  'morning mist rising from sun-warmed water',
  'winter moonlight turning snow fields silver blue',
  'spring mud season with everything melting and flowing',
  'hot concrete radiating stored heat into night air',
  'alpine wind carrying pine scent down mountainside',
  "thick morning fog hiding everything beyond arm's reach",
  'summer drought with dust hanging in motionless air',
  'freezing rain coating tree branches in clear ice',
  'warm evening breeze carrying jasmine through open windows',
  'dawn chorus of birds as darkness fades to gray',
  'blizzard wind howling through bare winter branches',
  'humid basement coolness during scorching summer day',
  'campfire sparks rising into star-filled darkness',
  'morning sun burning through valley fog',
  'tropical storm wind bending palm trees horizontal',
  'afternoon hail drumming on car roofs and awnings',
  'warm spring rain bringing green scent of new growth',
  'moonless night so dark shapes disappear completely',
  'frozen pond reflecting winter sky like black mirror',
  'morning coffee steam mixing with cold outdoor air',
  'hurricane wind driving rain sideways through everything',
  'crisp fall air carrying wood smoke from distant chimneys',
  'midnight fog so thick streetlights become dim halos',
  'gentle afternoon shower pattering on tin roof overhead',
  'arctic wind sculpting snow into sharp crystalline drifts',
  'warm evening air heavy with honeysuckle and cut grass',
  'winter sunrise painting fresh snow pink and gold',
  'spring flood rushing brown and loud between bare trees',
  'scorching noon sun beating down without single cloud',
  'night rain drumming steady rhythm on canvas tent',
  'morning ice fog rising from still lake surface',
  'summer storm passing with dramatic light breaking through',
  'bitter wind driving snow horizontal across open ground',
  'humid evening air thick enough to swim through',
];

export const NARRATOR_HINTS: string[] = [
  'the instant of deciding to trust something new',
  'a breath held while waiting for permission',
  'the moment between hearing and understanding',
  'caught in the act of remembering someone fondly',
  'the pause after a question nobody expected',
  'recognition flickering before full understanding arrives',
  'the beat when pretending becomes unnecessary',
  'a private victory too small to celebrate aloud',
  'the second after realizing you were wrong',
  'caught between wanting to stay and needing to go',
  'the moment of choosing which truth to tell',
  'a pause to gather courage for what comes next',
  'the instant when a stranger becomes familiar',
  'caught mid-adjustment to unexpected news',
  'the beat after setting something fragile down safely',
  'a moment of gratitude arriving uninvited',
  'the pause between impulse and action',
  'caught measuring the distance to somewhere else',
  'the second when muscle memory takes over',
  'a beat of wondering if anyone else notices',
  'the moment of accepting an uncomfortable truth',
  'caught checking if the feeling is still there',
  'the pause between hoping and knowing',
  'the instant of remembering why this matters',
  'a beat of adjusting to changed circumstances',
  'the moment between flinching and recovering',
  'caught calculating whether to interrupt or wait',
  'the pause after delivering difficult news',
  'the second of choosing which mask to wear',
  'a beat of missing something you never had',
  'the moment when patience finally pays off',
  'caught between versions of the same story',
  'the pause before admitting you need help',
  'the instant of realizing the pattern was always there',
  'a beat of preparing for an inevitable goodbye',
  'the moment between asking and receiving an answer',
  'caught rehearsing words that might never be spoken',
  'the pause after a door closes somewhere nearby',
  'the second of understanding the weight of waiting',
  'a beat between giving up and trying differently',
  'the moment of noticing your own breathing',
  'caught adjusting expectations downward quietly',
  'the pause between seeing and being seen',
  'the instant when confusion crystallizes into clarity',
  'a beat of steadying before the next attempt',
  'the moment between reaching and touching',
  'caught measuring silence for signs of judgment',
  'the pause after admitting something true',
  'the second of choosing vulnerability over safety',
  'a beat between remembering and forgetting on purpose',
  'caught translating feelings into acceptable language',
  'the pause between wanting and allowing yourself',
  'the instant of recognizing your own reflection differently',
  'a beat of honoring something that almost happened',
  'the moment between knowing better and doing anyway',
  'caught mid-negotiation with your own conscience',
  'the pause after the echo of footsteps fades',
  'the second when gentle pressure becomes enough',
  'a beat of measuring how much truth to reveal',
  'the moment between holding on and letting settle',
  'caught calculating the cost of complete honesty',
  'the pause after muscle memory fails unexpectedly',
  'the instant when old advice suddenly makes sense',
  'a beat of choosing which worry deserves attention',
  'the moment between rehearsal and actual performance',
  'caught mid-translation between what happened and what it meant',
  'the pause after recognizing someone from a dream',
  'the second of adjusting to a world slightly different',
  'a beat between defending and simply explaining',
  'the moment when careful planning meets pure chance',
  'caught measuring the space between intention and result',
  'the pause after something precious breaks quietly',
  "the instant of discovering mercy you didn't expect",
  'a beat of letting consequences catch up slowly',
  'the moment between naming something and claiming it',
  'caught mid-adjustment to gravity working differently',
  'the second when borrowed courage becomes your own',
  'a beat of making peace with imperfect timing',
  'the moment between seeing clearly and speaking truthfully',
];

export function pickSceneAngle(): string {
  return SCENE_ANGLES[Math.floor(Math.random() * SCENE_ANGLES.length)];
}
export function pickMoodTwist(): string {
  return MOOD_TWISTS[Math.floor(Math.random() * MOOD_TWISTS.length)];
}
export function pickNarratorHint(): string {
  return NARRATOR_HINTS[Math.floor(Math.random() * NARRATOR_HINTS.length)];
}
